### PR TITLE
CHANGELOG.md: Fixed typos in 7.0.0.0 section

### PR DESCRIPTION
**Pull request by johlju**
**Pull Request (PR) description**
Fixed typos in CHANGELOG.md before release.

**This Pull Request (PR) fixes the following issues:**
n/a

**Task list:**
- [x] Change details added to Unreleased section of CHANGELOG.md?
- [ ] Added/updated documentation, comment-based help and descriptions in .schema.mof files where appropriate?
- [ ] Examples appropriately updated?
- [ ] New/changed code adheres to [Style Guidelines](https://github.com/PowerShell/DscResources/blob/master/StyleGuidelines.md)?
- [ ] [Unit and (optional) Integration tests](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md) created/updated where possible?

---
This change is [Reviewable](https://reviewable.io/reviews/powershell/xsqlserver/515)

### CODE REVIEW

**Comment by johlju** [comment]
:LGTM:

**Comment by johlju** [comment]
:lgtm: 

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xsqlserver/515#-:-Ki6nQo3eMZTVSRDX56e:bg7igkv)*

**Comment by johlju** [comment]
@kwirkykat I thought I was gonna be quick enough to get some typos fixed in the CHANGELOG.md. But was to late ;)
I will fix them later.

**Comment by kwirkykat** [comment]
@johlju Release PR isn't through yet. I can hold it if you'd like to get this in still

**Comment by johlju** [comment]
Yes it would be nice to get it in

**Comment by johlju** [comment]
:LGTM:

Again. 

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xsqlserver/515#-:-Ki6rGDeG_kGVHtlo-Gh:b-tzyvpb)*

**Comment by johlju** [comment]
@kwirkykat Did a rebase. So just waiting for the tests to pass again, then we I can merge it.

**Comment by johlju** [comment]
@kwirkykat Merged!

**Pull request merged**
