### PR TITLE
xSQLServerRSConfig: Fix the virtual directory creation for SQL 2016

### LINKED ISSUE #202: PowerShell DSC resource MSFT_xSQLServerRSConfig  failed to execute Set-TargetResource
Here is the config in question.

> xSQLServerRSConfig SQLServerRSConfig
> 		{
> 			DependsOn = "[xSqlServerSetup]SQLServerRSSetup", "[xCredSSP]Client", "[xCredSSP]Server"
> 			InstanceName       = $Node.InstanceName
> 			RSSQLServer        = $Node.RSSQLServer
> 			RSSQLInstanceName  = $Node.RSSQLInstanceName
> 			SQLAdminCredential = Get-Credential $Node.SQLAdminCredential
> 		} 
> 

This results in the following error.

> VERBOSE: [SSRS01]: LCM:  [ End    Set      ]  [[xSQLServerRSConfig]SQLServerRSConfig]  in 20.7200 seconds.
> PowerShell DSC resource MSFT_xSQLServerRSConfig  failed to execute Set-TargetResource functionality with error
> message: Test-TargetResource returned false after calling set.
>     + CategoryInfo          : InvalidOperation: (:) [], CimException
>     + FullyQualifiedErrorId : ProviderOperationExecutionFailure
>     + PSComputerName        : SSRS01
> 
> VERBOSE: [SSRS01]: LCM:  [ End    Set      ]
> The SendConfigurationApply function did not succeed.
>     + CategoryInfo          : NotSpecified: (root/Microsoft/...gurationManager:String) [], CimException
>     + FullyQualifiedErrorId : MI RESULT 1
>     + PSComputerName        : SSRS01

I have looked at the Microsoft --> Windows --> Desired State Configuration --> Operational event logs and see the following.

> Job {C475915E-AD3A-11E6-A943-000D3A72D03D} : 
> Message Test-TargetResource returned false after calling set. 
> HResult -2146233087 
> StackTrack    at System.Management.Automation.Runspaces.PipelineBase.Invoke(IEnumerable input)
>    at System.Management.Automation.PowerShell.Worker.ConstructPipelineAndDoWork(Runspace rs, Boolean performSyncInvoke)
>    at System.Management.Automation.PowerShell.Worker.CreateRunspaceIfNeededAndDoWork(Runspace rsToUse, Boolean isSync)
>    at System.Management.Automation.PowerShell.CoreInvokeHelper[TInput,TOutput](PSDataCollection`1 input, PSDataCollection`1 output, PSInvocationSettings settings)
>    at System.Management.Automation.PowerShell.CoreInvoke[TInput,TOutput](PSDataCollection`1 input, PSDataCollection`1 output, PSInvocationSettings settings)
>    at System.Management.Automation.PowerShell.Invoke(IEnumerable input, PSInvocationSettings settings)
>    at Microsoft.PowerShell.DesiredStateConfiguration.Internal.ResourceProviderAdapter.ExecuteCommand(PowerShell powerShell, ResourceModuleInfo resInfo, String operationCmd, List`1 acceptedProperties, CimInstance nonResourcePropeties, CimInstance resourceConfiguration, LCMDebugMode debugMode, PSInvocationSettings pSInvocationSettings, UInt32& resultStatusHandle, Collection`1& result, ErrorRecord& errorRecord, PSModuleInfo localRunSpaceModuleInfo)
> 

> Job {C475915E-AD3A-11E6-A943-000D3A72D03D} : 
> This event indicates that failure happens when LCM is processing the configuration. Error Id is 0x1. Error Detail is The SendConfigurationApply function did not succeed.. Resource Id is [xSQLServerRSConfig]SQLServerRSConfig and Source Info is C:\DSC_BuildDrop\reportingServer.ps1::66::3::xSQLServerRSConfig. Error Message is PowerShell DSC resource MSFT_xSQLServerRSConfig  failed to execute Set-TargetResource functionality with error message: Test-TargetResource returned false after calling set. .
> 

> Job {C475915E-AD3A-11E6-A943-000D3A72D03D} : 
> MIResult: 1
> Error Message: PowerShell DSC resource MSFT_xSQLServerRSConfig  failed to execute Set-TargetResource functionality with error message: Test-TargetResource returned false after calling set. 
> Message ID: ProviderOperationExecutionFailure
> Error Category: 7
> Error Code: 1
> Error Type: MI

What steps can I take to troubleshoot this further?

### PR DESCRIPTION
**Pull request by claudiospizzi**
Fix the virtual directory creation for SQL 2016 because of the introduced breaking change:
https://msdn.microsoft.com/en-us/library/ms143380.aspx?f=255&MSPPError=-2147217396

This Pull Request fixes the following issues:
Fixes #202

- [X] Change details added to Unreleased section of CHANGELOG.md?
- [ ] Added/updated documentation, comment-based help and descriptions in .schema.mof files where appropriate?
- [ ] Examples appropriately updated?
- [X] New/changed code adheres to [Style Guidelines]?(https://github.com/PowerShell/DscResources/blob/master/StyleGuidelines.md)?
- [ ] [Unit and (optional) Integration tests](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md) created/updated where possible?

---
This change is [Reviewable](https://reviewable.io/reviews/powershell/xsqlserver/220)

### CODE REVIEW

**Comment by johlju** [comment]
Since this resource is older and has yet to gone thru the style guideline clean up, nor has it any unit tests. Would you be up to do fix that? I would comment on any style changes that should be done.  It can be some undertaking, but you can ask for help at any time. And hopefully it will be a fun experience. 😄

**Comment by claudiospizzi** [comment]
@johlju Okay, I can do that.

But there is a second issue with this resource regarding SQL 2016. The resource depends on a local installed sqlcmd.exe. It's used to execute two sql files for setting up the SQL database.

Any idea how to properly replace that and remove this dependency?

**Comment by johlju** [comment]
My first thought is might be able to use `Invoke-Sqlcmd`. You think that would work?
https://msdn.microsoft.com/en-us/library/cc281720.aspx

There is a helper function `Import-SQLPSModule` that you can use to import SQLPS module. See xSQLServerSetup resource for example how to load the [helper module](https://github.com/PowerShell/xSQLServer/blob/dev/xSQLServerHelper.psm1)

I also saw that the code uses Invoke-Command with CredSSP. Would be nice to see if we could remove that too. :) Or at least add a comment why it is necessary to use Invoke-Command with CredSSP :)

I will start the review tomorrow. No hurry. Just solve this at your own pace. Let us know if you need help. You can just commit and push new changes to this working branch `fixrsconfig` in your fork and GitHub will update this PR automatically.

**Comment by claudiospizzi** [comment]
The Invoke-Command with CredSSP is related to the sqlcmd.exe issue. CredSSP is needed to invoke the sqlcmd.exe with the SQL admin credentials and then do a remote connection over the network to the SQL database engine.

I will add a comment and I will add a meaningful error message, if someone forgets to enable CredSSP.

**Comment by johlju** [comment]
Okay, I understand. So could the cmdlet `Invoke-Sqlcmd` replace all that then, if we can execute the SQL script directly (read them with `Get-Content` and execute them with `Invoke-Sqlcmd`)? Thinking if we can replace Invoke-Command and sqlcmd.exe then there is no need for a comment. :)

**Comment by johlju** [comment]
Ah, no need to use `Get-Content` to get the script from file. The code already has it in a string after it calls the 'Generate...' method. So could we execute that with `Invoke-Sqlcmd`?

**Comment by claudiospizzi** [comment]
Yes you are right, the `Invoke-SqlCmd` should be able to replace the sqlcmd.exe command. But when I see it right, this cmdlet is part of the SQL Database Engine installation - which is normally not installed on a reporting server when the ReportServer database is on a remote host.

Or is it possible to just install or run the cmdlet/module without the SQL database engine itself?

**Comment by johlju** [comment]
I will continue the review once these comments are fixed and all the tests are passing :smile: 

---

Reviewed 2 of 7 files at r2.
Review status: 2 of 7 files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[DSCResource.Tests, line 1 at r2](https://reviewable.io:443/reviews/powershell/xsqlserver/220#-KXMABfU__sUPgf4tAhl:-KXMABfU__sUPgf4tAhm:b6aalxs) ([raw file](https://github.com/powershell/xsqlserver/blob/c57d25f6c8f57d9c4a5a5f717c62828ff2746871/DSCResource.Tests#L1)):*
> ```
> Subproject commit 987ae8c9dc3f1449a0be8dab7f77d04b097c2da3
> ```

Please remove this from you working branch. It is created automatically when you run tests but should not be commited to the PR.
1. Remove this folder from your branch
2. Commit and push the change as normal
3. Add a .gitignore file. See https://github.com/PowerShell/DscResources/blob/master/GettingStartedWithGitHub.md#using-gitignore-to-exclude-files-andor-folders

---

*[README.md, line 195 at r2](https://reviewable.io:443/reviews/powershell/xsqlserver/220#-KXMB8l5vHKsg8Gia6GH:-KXMB8l5vHKsg8Gia6GI:brl9xdh) ([raw file](https://github.com/powershell/xsqlserver/blob/c57d25f6c8f57d9c4a5a5f717c62828ff2746871/README.md#L195)):*
> ```Markdown
> * **RSSQLInstanceName**: (Required) Name of the SQL Server instance to host the Reporting Service database.
> * **SQLAdminCredential**: (Required) Credential to be used to perform the configuration.
> * **IsInitialized**: (Output) Boolean if the Reporting Services instance is initialized.
> ```

Change `(OutPut)` to `(Read)` on this and those below.

---

*[DSCResources/MSFT_xSQLServerRSConfig/MSFT_xSQLServerRSConfig.psm1, line 13 at r2](https://reviewable.io:443/reviews/powershell/xsqlserver/220#-KXMBrxb5-Pz_Kcw5b1V:-KXMBrxb5-Pz_Kcw5b1W:b9qikc2) ([raw file](https://github.com/powershell/xsqlserver/blob/c57d25f6c8f57d9c4a5a5f717c62828ff2746871/DSCResources/MSFT_xSQLServerRSConfig/MSFT_xSQLServerRSConfig.psm1#L13)):*
> ```PowerShell
>     [CmdletBinding()]
>     [OutputType([System.Collections.Hashtable])]
>     [Diagnostics.CodeAnalysis.SuppressMessageAttribute('PSAvoidUsingComputerNameHardcoded', '')]
> ```

Please remove these in all places. The tests will not go thru with these because they are not allow to be overridden (suppressed).

---

*[DSCResources/MSFT_xSQLServerRSConfig/MSFT_xSQLServerRSConfig.psm1, line 49 at r2](https://reviewable.io:443/reviews/powershell/xsqlserver/220#-KXMCDwFeXQ4YRQajFvN:-KXMCDwFeXQ4YRQajFvO:bx3qs2d) ([raw file](https://github.com/powershell/xsqlserver/blob/c57d25f6c8f57d9c4a5a5f717c62828ff2746871/DSCResources/MSFT_xSQLServerRSConfig/MSFT_xSQLServerRSConfig.psm1#L49)):*
> ```PowerShell
> 
>     # Invoke the WMI query with the SQL admin credentials by using local PowerShell Remoting
>     $rsConfig = Invoke-Command -ComputerName 'localhost' -Credential $SQLAdminCredential -ArgumentList $sqlVersion, $InstanceName -ScriptBlock {
> ```

Instead of `'localhost'` try using $env:computername

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xsqlserver/220#-:-KXMCNfFqYufJTgWNskq:btbsckf)*

**Comment by johlju** [comment]
Reviewed 1 of 7 files at r2.
Review status: 3 of 7 files reviewed at latest revision, 10 unresolved discussions, some commit checks failed.

---

*[README.md, line 189 at r2](https://reviewable.io:443/reviews/powershell/xsqlserver/220#-KXMf7FUCGvFSRscnoy5:-KXMf7FUCGvFSRscnoy6:bktb11w) ([raw file](https://github.com/powershell/xsqlserver/blob/c57d25f6c8f57d9c4a5a5f717c62828ff2746871/README.md#L189)):*
> ```Markdown
> * **ISFileSystemFolder**: File system folder for Integration Services.
> 
> ### xSQLServerRSConfig
> ```

Please add a description saying this is dependent on the SQLPS module. And that the SQLPS module can be deploy using components in the feature pack. You could also refer to the example.

---

*[DSCResources/MSFT_xSQLServerRSConfig/MSFT_xSQLServerRSConfig.psm1, line 173 at r2](https://reviewable.io:443/reviews/powershell/xsqlserver/220#-KXMgLAlBRS_r62wifRH:-KXMgLAlBRS_r62wifRI:b-pp1wht) ([raw file](https://github.com/powershell/xsqlserver/blob/c57d25f6c8f57d9c4a5a5f717c62828ff2746871/DSCResources/MSFT_xSQLServerRSConfig/MSFT_xSQLServerRSConfig.psm1#L173)):*
> ```PowerShell
>     Write-Verbose 'Create the database for the SQL Reporting Service' 
> 
>     Invoke-Command -ComputerName 'localhost' -Credential $SQLAdminCredential -Authentication Credssp -ArgumentList $sqlVersion, $InstanceName, $desiredConfig.DatabaseName, $language, $rsConnection, $helperModulePath -ScriptBlock {
> ```

You should not be needing this `Invoke-Command` nor using CredSSP when using `Invoke-SqlCmd`.  Have you tested without it? Or do you need Invoke-Command for something else?

---

*[Examples/SQLServerReportingServices.ps1, line 31 at r2](https://reviewable.io:443/reviews/powershell/xsqlserver/220#-KXMeubrXSyuyOg0yKEK:-KXMeubrXSyuyOg0yKEL:b-d75f2j) ([raw file](https://github.com/powershell/xsqlserver/blob/c57d25f6c8f57d9c4a5a5f717c62828ff2746871/Examples/SQLServerReportingServices.ps1#L31)):*
> ```PowerShell
>         }
> 
>         # The xSQLServerRSConfig resource depends on te SQLPS module. Download
> ```

typo 'te' instead of 'the'

Could you also add how it depends on the SQLPS module.

---

*[Examples/SQLServerReportingServices.ps1, line 34 at r2](https://reviewable.io:443/reviews/powershell/xsqlserver/220#-KXMeNlkKI7k8uvQu_4V:-KXMeNlkKI7k8uvQu_4W:bpkdznk) ([raw file](https://github.com/powershell/xsqlserver/blob/c57d25f6c8f57d9c4a5a5f717c62828ff2746871/Examples/SQLServerReportingServices.ps1#L34)):*
> ```PowerShell
>         # the required tools from the Microsoft Download Center, e.g. SQL 2016:
>         # https://www.microsoft.com/en-us/download/details.aspx?id=52676
>         Package SQLSysClrTypesPackage
> ```

This one should not be necessary to get SQLPS module? 

---

*[Examples/SQLServerReportingServices.ps1, line 45 at r2](https://reviewable.io:443/reviews/powershell/xsqlserver/220#-KXMflpk2U-i5Kr4X8Fn:-KXMflpk2U-i5Kr4X8Fo:bbuo10u) ([raw file](https://github.com/powershell/xsqlserver/blob/c57d25f6c8f57d9c4a5a5f717c62828ff2746871/Examples/SQLServerReportingServices.ps1#L45)):*
> ```PowerShell
>             Ensure    = 'Present'
>             Path      = 'C:\Setup\Tools\SharedManagementObjects.msi'
>             Name      = 'Microsoft SQL Server 2016 Management Objects  (x64)'
> ```

Is this extra space after 'Objects' actually typo in the package name as the one below? Then please add a comment saying that. See next comment also.

---

*[Examples/SQLServerReportingServices.ps1, line 56 at r2](https://reviewable.io:443/reviews/powershell/xsqlserver/220#-KXMfPBnylWmHcDbWgxO:-KXMfPBnylWmHcDbWgxP:b-izt5f9) ([raw file](https://github.com/powershell/xsqlserver/blob/c57d25f6c8f57d9c4a5a5f717c62828ff2746871/Examples/SQLServerReportingServices.ps1#L56)):*
> ```PowerShell
>             Ensure    = 'Present'
>             Path      = 'C:\Setup\Tools\PowerShellTools.msi'
>             Name      = 'PowerShell Extensions for SQL Server 2016 '
> ```

Please add a comment saying that the extra space at the end of the string is not a typo `'...Server 2016 '`. Name Name in the package has a typo so you need to match that. Right?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xsqlserver/220)*

**Comment by Zuldan** [comment]
@claudiospizzi thank you so much for all these contributions. Great work. I have a feeling they are going to resolve https://github.com/PowerShell/xSQLServer/issues/202 and https://github.com/PowerShell/xSQLServer/issues/148.

Since you are re-working a large portion of this resource I'm wondering if you are able to add in a small feature? The ability to define the reporting database name. Default is "ReportServer" as you. The problem is if we want to install multiple reporting server databases on a single instance, it's not currently possible. By simple being able to define the Report Services database name, the issue is eliminated. See https://github.com/PowerShell/xSQLServer/issues/149

**Comment by johlju** [comment]
Review status: 3 of 7 files reviewed at latest revision, 10 unresolved discussions, some commit checks failed.

---

*[Examples/SQLServerReportingServices.ps1, line 34 at r2](https://reviewable.io:443/reviews/powershell/xsqlserver/220#-KXMeNlkKI7k8uvQu_4V:-KXUvkfBUFN57zyAiReW:b-glgdz2) ([raw file](https://github.com/powershell/xsqlserver/blob/c57d25f6c8f57d9c4a5a5f717c62828ff2746871/Examples/SQLServerReportingServices.ps1#L34)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary>
> This one should not be necessary to get SQLPS module? 
</details>
This one is indeed needed to install 'Shared Management Objects' . Please add a comment saying that.

---

*[Examples/SQLServerReportingServices.ps1, line 45 at r2](https://reviewable.io:443/reviews/powershell/xsqlserver/220#-KXMflpk2U-i5Kr4X8Fn:-KXUvzam23KkGW3ijPpF:b-vlz358) ([raw file](https://github.com/powershell/xsqlserver/blob/c57d25f6c8f57d9c4a5a5f717c62828ff2746871/Examples/SQLServerReportingServices.ps1#L45)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary>
> Is this extra space after 'Objects' actually typo in the package name as the one below? Then please add a comment saying that. See next comment also.
</details>
And this extra space is also needed. Please add a comment saying why there is an extra space so next contributor don't think it is a typo.

Also, please add a comment saying that this is a dependency on 'PowerShell Tools' to install.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xsqlserver/220)*

**Comment by johlju** [comment]
@claudiospizzi are you still working on this PR? Let me know if you need any help or if you don't have time to continue the work on this PR, let me know.

**Comment by claudiospizzi** [comment]
Hi. Yes I'm still working on it, sorry for the delay. I tried to rebase my branch with the latest dev - guess I made an error because all commits now showing up in this PR?

**Comment by johlju** [comment]
Yes, I think you made an error somewhere. They should not show up.

The steps should have been:

```
# 'origin' is the remote name to PowerShell/xSQLServer
# 'my' is the remote name to claudiospizzi/xSQLServer
git checkout dev
git fetch origin dev
git rebase origin/dev
git push my dev --force

git checkout fixrsconfig
git rebase my/dev

# Resolve any merge conflicts and continue with 'git rebase --continue' if needed.

git push my fixrsconfig --force
```

**Comment by johlju** [comment]
@claudiospizzi Did you have a chance to try the rebase again?

**Comment by reicher001** [comment]
Any updates on getting this merged in?

**Comment by johlju** [comment]
@reicher001 I'm waiting for @claudiospizzi to rebase and resolve the review comments. 

@claudiospizzi Do you need any help with this one? Or do you want someone to take over? Just let us know.

**Comment by bozho** [comment]
Hi all,

I was looking at adding options to configure RS reserved URLs using xSQLServerRSConfig and ended up looking at this pull request.

I have one general question: why is $SQLAdminCredential a required parameter? Is it only required for executing sqlcmd?

I'm asking because I currently have a fairly similar code to configure RS in a function - the only major difference is that it uses Invoke-Sqlcmd to run the config scripts. For a quick test, I dumped the code in a custom xScript resource and it ran fine under DSC's default credentials (system account)

Unless I'm missing something, I think we can make $SQLAdminCredential an optional argument, as it's really only needed for executing SQL. 

On the subject of this pull request, it feels bit overly complicated, as it's not only solving the one thing it's supposed to solve - virtual directories for SQL Server 2016 (and onwards, presumably)

I suggest we create separate pull requests for the following issues to minimise code disruption:

- replace sqlcmd.exe with Invoke-Sqlcmd calls (with appropriate checks)
- make $SQLAdminCredential an optional argument (unless I'm missing something :)
- fix virtual directory creation for SQL Server 2016
- and my endgame: configurable URL reservations :)

Kind regards,
Marko

**Comment by reicher001** [comment]
@johlju and @claudiospizzi do you have any thoughts on the post from @bozho?

**Comment by johlju** [comment]
@bozho I apologize, I totally missed your comment. 😞  @reicher001 thanks for letting me know I had not answered 😄 

@bozho I'm all for your suggestion. Could you create issues for each of the steps you mention? Also mention in the issue which resolves issue #220 (if any). And please, if you want to run with any or all, then comment on them saying so, and I will label the issues as 'in progress'.
As soon as "fix virtual directory creation" has been sent into a new PR and merged, I will close this PR.
And regarding $SQLAdminCredential being required, there is no need to have that required if it is not necessary, see it as more of a technical debt and change it appropriately.

Again, apologize for not responding sooner. I'm glad you reminded me! 🙇

**Comment by bozho** [comment]
Hi @johlju. No worries, I'm quite busy myself and tend to miss these things :-)

I'll create the issues and start working on them - again, I'll need a bit of help with the tests (I promise I'll start to learn :-)

**Comment by johlju** [comment]
There are few read only properties that would be good to get into the resource before closing this one. 
I'm adding an issue for this.

```
    [Read, Description("The Windows service name.")] String ServiceName;
    [Read, Description("The SQL database name")] String DatabaseName;
    [Read, Description("Virtual directory name for the report manager.")] String VirtualDirectoryReportManager;
    [Read, Description("Virtual directory name for the report server.")] String VirtualDirectoryReportServer;
```

**Comment by bozho** [comment]
@johlju I'm not sure I understand...

You'd like to add read-only `VirtualDirectoryReportManager` and `VirtualDirectoryReportServer` in addition to the optional write parameters `ReportServerVirtualDir` and `ReportsVirtualDir`?

Also, what it `ServiceName`? RS service name?

What is `DatabaseName`? RS uses two databases, ReportServer and ReportServerTempDB.

**Comment by johlju** [comment]
@bozho Let's continue the discussion over at issue #626

**Comment by johlju** [comment]
Closing this PR since the main part was merged in #575. The rest is added to an issue #626 for evaluation. If something has been forgotten in this PR (hard to see, because the rebase went wrong) then please comment on this PR or raise another issue. Thanks!

**Pull request closed without merging**
