### PR TITLE
xSQLServerSetup: Updated xSQLServerSetup module Get-Resource method to detect DQ, DQC, BOL, SDK features.

### LINKED ISSUE #490: xSQLServerSetup: Not supporting feature DQ and DQC
**Details of the scenario you try and problem that is occurring:**
xSQLServerSetup should support feature DQ and DQC.

**The DSC configuration that is using the resource (as detailed as possible):**
Configuration from issue #484 

```
xSQLServerSetup ($Node.NodeName)
{
    Action  = "InstallFailoverCluster"
    InstanceName  = "MSSQLSERVER"
    SetupCredential = $Credential
    SourcePath  = "c:\users\public\downloads\sql2016\source\" 
    Features  = "SQLENGINE, REPLICATION, FULLTEXT, DQ"
    InstanceID  = "MSSQLSERVER"
    UpdateEnabled  = "True"
    UpdateSource  = "MU"
    InstallSharedDir  = "c:\Program Files\Microsoft SQL Server\"
    InstallSharedWOWDir  = "c:\Program Files (x86)\Microsoft SQL Server\"
    InstanceDir  = "C:\Program Files\Microsoft SQL Server\"
    SQLSvcAccount  = $SQLSvcAccount
    AgtSvcAccount  = $AgtSvcAccount
    SQLCollation  = "SQL_Latin1_General_CP1_CI_AS"
    SQLSysAdminAccounts   = "$SQLAdmin"
    SecurityMode  = "SQL"
    SAPwd  = $SACreds
    InstallSQLDataDir  = "W:\sql\binaries"
    SQLUserDBDir = "W:\SQL\Data\COMMON"
    SQLUserDBLogDir = "W:\SQL\Logs\LG_COMMON"
    SQLTempDBDir = "H:\SQL\Data" # Local disk
    SQLTempDBLogDir  = "H:\SQL\Logs" # Local disk
    FailoverClusterGroupName  = "$FailoverClusterGroupName"
    FailoverClusterIPAddress  = "$FailoverClusterIPAddress"
    FailoverClusterNetworkName  = "$FailoverClusterNetworkName"
    PsDscRunAsCredential = $Credential

}
```

**Version of the Operating System, SQL Server and PowerShell the DSC Target Node is running:**
All

**Version of the DSC module you're using, or 'dev' if you're using current dev branch:**
Dev

### LINKED ISSUE #516: xSQLServerSetup: Get-Resource does not detect following features: BOL, DQ, DQC, SDK, SNAC_SDK
Get-Resource does not detect following features: BOL, DQ, DQC, SDK, SNAC_SDK.
Error Message: Test-TargetResource returned false after calling set. 

xSQLServerSetup Instance
{
	Action = "Install"
	InstanceName = $SqlInstanceName
	SetupCredential = $DeployServiceAccount
	SourcePath = "C:\Media"
	Features = "FULLTEXT,BC,**DQ**,**BOL**,SSMS,**DQC**,ADV_SSMS,AS,**SDK**,**SNAC_SDK**,SQLENGINE,CONN,RS"
	ProductKey = $ProductKey
}

Plan to fix this by implementing additional Get-Resource method checks for each of these features.

- Operating System: Windows Server 2012 R2
- SQL Server: 2014
- PowerShell: 5
- Module: xSQLServerSetup
- Version: 6.0.0.0

### PR DESCRIPTION
**Pull request by GoelPooja**
**Pull Request (PR) description**
 Updated xSQLServerSetup module Get-Resource method to detect DQ, DQC, BOL, SDK features.

**Tested with following DSC:**
```
xSQLServerSetup Instance
{
Action = "Install"
InstanceName = $SqlInstanceName
SetupCredential = $DeployServiceAccount
SourcePath = "C:\Media"
Features = "FULLTEXT,BC,DQ,BOL,SSMS,DQC,ADV_SSMS,AS,SDK,SQLENGINE,CONN,RS"
ProductKey = $ProductKey
}
```

**This Pull Request (PR) fixes the following issues:**
Fixes #516 
Fixes #490 

**Task list:**
- [x] Change details added to Unreleased section of CHANGELOG.md?
- [x] Added/updated documentation, comment-based help and descriptions in .schema.mof files where appropriate?
- [ ] Examples appropriately updated?
- [x] New/changed code adheres to [Style Guidelines](https://github.com/PowerShell/DscResources/blob/master/StyleGuidelines.md)?
- [x] [Unit and (optional) Integration tests](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md) created/updated where possible?

---
This change is [Reviewable](https://reviewable.io/reviews/powershell/xsqlserver/521)

### CODE REVIEW

**Comment by johlju** [comment]
First, thanks for sending this in! Thanks for contributing! 😄 

It seems you are missing a mock, so the tests fail
https://ci.appveyor.com/project/PowerShell/xsqlserver/build/5.0.1106.0#L3095

Do you have an opportunity to resolve that?

**Comment by johlju** [comment]
@GoelPooja I thought you had written test for this since it said +19 hits in the Codecov Report. Seems some of the rows was tested by another mock (a mock which might have the wrong parameter filter maybe). 
Could you add tests for these changes please? Let me know if you need any help.

**Comment by GoelPooja** [comment]
@johlju: I have added updated tests for detecting SDK, BOL, DQ, DQC features and all tests are passing now except I am not able to fix markdown error in changelog.md.
So just one test is failing for Markdownerror.

**Comment by johlju** [comment]
Review status: 0 of 3 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[CHANGELOG.md, line 120 at r3](https://reviewable.io:443/reviews/powershell/xsqlserver/521#-Kijmbk_Og_hCFXteA5C:-Kijmbka1IqabbAJMP8M:bsa96bn) ([raw file](https://github.com/powershell/xsqlserver/blob/81708c1020ba109a8c0cbe9caaf7a1f900a0a677/CHANGELOG.md#L120)):*
> ```Markdown
> - Changes to xSQLServerScript
>   - Updated tests for this resource, because they failed when Import-SQLPSModule was updated.
>   
> ```

You have blank spaces on this row that probably is causing two of the markdown lint errors.

---

*[CHANGELOG.md, line 121 at r3](https://reviewable.io:443/reviews/powershell/xsqlserver/521#-Kijli0S_dLqjJwPzxvJ:-Kijli0S_dLqjJwPzxvK:b-jb8nrj) ([raw file](https://github.com/powershell/xsqlserver/blob/81708c1020ba109a8c0cbe9caaf7a1f900a0a677/CHANGELOG.md#L121)):*
> ```Markdown
>   - Updated tests for this resource, because they failed when Import-SQLPSModule was updated.
>   
>  - Changes to xSQLServerSetup
> ```

Please rebase your working branch against dev (do not merge or pull). Please see here how to do this. https://github.com/PowerShell/DscResources/blob/master/GettingStartedWithGitHub.md#1-rebase-the-local-dev-branch-from-the-base-dev-branch

When that is done, please move this to the end of the Unreleased section.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xsqlserver/521)*

**Comment by johlju** [comment]
@GoelPooja Let's rebase this (see review comment) and move the change log entries to the Unreleased section and then ww can see where we are at with the last lint errors failing.  😄

**Comment by GoelPooja** [comment]
@johlju: Able to fix the markdown errors now. Build is green now.
I have rebased also as per the instructions and it says my branch is up-to-date.

**Comment by johlju** [comment]
The code logic changes looks great! Awesome work on the tests! 

The rebase did go as it should. :/ You are still missing entries in the CHANGELOG.md. If you compare to the one in the dev branch and compare it to the dev branch in your fork, your fork is missing entries under the unreleased section.

If your run these it should fix it. :)

origin = chnage to the remote name that points to PowerShell/xSQLServer
my = change to the remote name that points to GoelPooja\xSQLServer
You can list remotes with `git remote -v`

```
git checkout dev
git fetch origin dev
git rebase origin/dev
```

Fix any merge conflicts, and stage the files with `git add` (or preferably use VS Code and stage the change) and then run `git rebase --continue`. Do this until all conflicts are resolved.

At the end run this
```
git push my dev --force
```

---

Reviewed 2 of 3 files at r3, 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 10 unresolved discussions.

---

*[CHANGELOG.md, line 77 at r4](https://reviewable.io:443/reviews/powershell/xsqlserver/521#-Kit6AVhhkhgd75M7pTm:-Kit6AVhhkhgd75M7pTn:b-3kq8of) ([raw file](https://github.com/powershell/xsqlserver/blob/776a7c7cae447c9dbb75c26dee685d1830a2ccea/CHANGELOG.md#L77)):*
> ```Markdown
>   - Now it ignores parameters that are not allowed for action Addnode (issue #441).
>   - Added support for vNext CTP 1.4 (issue #472).
>   - Updated xSQLServerSetup Module Get-Resource method to fix (issue #516 and #490).
> ```

Move these change log entries to the unreleased section (line 3). V7.0.0.0 is what is already released to the PowerShell Gallery. 

---

*[Tests/Unit/MSFT_xSQLServerSetup.Tests.ps1, line 404 at r4](https://reviewable.io:443/reviews/powershell/xsqlserver/521#-Kit9au51k8iWPRLXf6G:-Kit9au51k8iWPRLXf6H:b4mr0vs) ([raw file](https://github.com/powershell/xsqlserver/blob/776a7c7cae447c9dbb75c26dee685d1830a2ccea/Tests/Unit/MSFT_xSQLServerSetup.Tests.ps1#L404)):*
> ```PowerShell
>             )
>         }
>         
> ```

What editor are you using? It seem to have added 8 spaces on each blank row :/ 
But only for the test file for some reason. Could you look at that? I'm getting a change on a lot of rows now.
Suggestion is to use VS Code and add the setting  `"files.trimTrailingWhitespace": true`.
Thanks!

---

*[Tests/Unit/MSFT_xSQLServerSetup.Tests.ps1, line 665 at r4](https://reviewable.io:443/reviews/powershell/xsqlserver/521#-KitHi9ouRBfc328XE2Y:-KitHi9ouRBfc328XE2Z:b-54x7ue) ([raw file](https://github.com/powershell/xsqlserver/blob/776a7c7cae447c9dbb75c26dee685d1830a2ccea/Tests/Unit/MSFT_xSQLServerSetup.Tests.ps1#L665)):*
> ```PowerShell
>                 (
>                     New-Object Microsoft.Management.Infrastructure.CimInstance 'MSCluster_ClusterSharedVolume', 'root/MSCluster' |
>                     Add-Member -MemberType NoteProperty -Name 'Name' -Value $mockCSVClusterDiskMap['SysData'].Path -PassThru -Force
> ```

All Add-Member has been indented back 4 spaces. This also gives changes on _a lot_ of rows. Could you fix this too please?

---

*[Tests/Unit/MSFT_xSQLServerSetup.Tests.ps1, line 891 at r4](https://reviewable.io:443/reviews/powershell/xsqlserver/521#-Kit8hKkdSBqpMn_l_tO:-Kit8hKkdSBqpMn_l_tP:b-54hw9l) ([raw file](https://github.com/powershell/xsqlserver/blob/776a7c7cae447c9dbb75c26dee685d1830a2ccea/Tests/Unit/MSFT_xSQLServerSetup.Tests.ps1#L891)):*
> 'SQLENGINE,REPLICATION,DQC,DQ,BOL,CONN,BC,SDK,FULLTEXT,RS,AS,IS,SSMS,ADV_SSMS'

Please change these to both upper-case and lower-case letters. That is used for regression testing since we had a bug before where we did not support features written in lower-case

So please change it to 
`'SQLEngine,Replication,Dqc,Dq,Bol,Conn,Bc,Sdk,FullText,Rs,As,Is,Ssms,Adv_Ssms'`

---

*[Tests/Unit/MSFT_xSQLServerSetup.Tests.ps1, line 893 at r4](https://reviewable.io:443/reviews/powershell/xsqlserver/521#-KitAjpPMjIhLv2POOuW:-KitAjpPMjIhLv2POOuX:b70bjga) ([raw file](https://github.com/powershell/xsqlserver/blob/776a7c7cae447c9dbb75c26dee685d1830a2ccea/Tests/Unit/MSFT_xSQLServerSetup.Tests.ps1#L893)):*
> ```PowerShell
>             Features = 'SQLENGINE,REPLICATION,DQC,DQ,BOL,CONN,BC,SDK,FULLTEXT,RS,AS,IS,SSMS,ADV_SSMS'
>         }
>         $featuresForSqlServer2016 = ''
> ```

Please add a blank line before this one.

---

*[Tests/Unit/MSFT_xSQLServerSetup.Tests.ps1, line 1319 at r4](https://reviewable.io:443/reviews/powershell/xsqlserver/521#-KitGU4680LVzbzcDz28:-KitGU4680LVzbzcDz29:b3ktpwq) ([raw file](https://github.com/powershell/xsqlserver/blob/776a7c7cae447c9dbb75c26dee685d1830a2ccea/Tests/Unit/MSFT_xSQLServerSetup.Tests.ps1#L1319)):*
> ```PowerShell
>                         if ($mockSqlMajorVersion -in (13, 14))
>                         {
>                             $result.Features | Should Be 'SQLENGINE,REPLICATION,DQC,DQ,BOL,FULLTEXT,RS,AS,IS'
> ```

Was expecting feature SDK in as well.

---

*[Tests/Unit/MSFT_xSQLServerSetup.Tests.ps1, line 1323 at r4](https://reviewable.io:443/reviews/powershell/xsqlserver/521#-KitG_Z21pKn-J4t_irf:-KitG_Z21pKn-J4t_irg:b3ktpwq) ([raw file](https://github.com/powershell/xsqlserver/blob/776a7c7cae447c9dbb75c26dee685d1830a2ccea/Tests/Unit/MSFT_xSQLServerSetup.Tests.ps1#L1323)):*
> ```PowerShell
>                         else
>                         {
>                             $result.Features | Should Be 'SQLENGINE,REPLICATION,DQC,DQ,BOL,FULLTEXT,RS,AS,IS,SSMS,ADV_SSMS'
> ```

Was expecting feature SDK in as well.

---

*[Tests/Unit/MSFT_xSQLServerSetup.Tests.ps1, line 3799 at r4](https://reviewable.io:443/reviews/powershell/xsqlserver/521#-KitG-m85Aqm0euYlz1p:-KitG-m85Aqm0euYlz1q:b-kuxt6k) ([raw file](https://github.com/powershell/xsqlserver/blob/776a7c7cae447c9dbb75c26dee685d1830a2ccea/Tests/Unit/MSFT_xSQLServerSetup.Tests.ps1#L3799)):*
> ```PowerShell
>                         $setTargetResourceParameters.Remove('SQLTempDbLogDir')
>                         $setTargetResourceParameters.Remove('SQLBackupDir')
>                         { Set-TargetResource @setTargetResourceParameters } | Should Not Throw
> ```

Blank line before this one.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xsqlserver/521#-:-Kit3UZFHid77vXhcQvv:b5rnh6q)*

**Comment by GoelPooja** [comment]
@johlju: 

- Rebased as per instructions.
- Moved changes in Changelog.md to unreleased section.
- Changed casing for featureslist, fixed whitespace issues and added new lines as per review comments.
- For feature SDK I have updated mockGetItemProperty_ClientComponentsFull_FeatureList parameter. Line 1219  is a negative test for CONN and BC feature from mockGetItemProperty_ClientComponentsFull_FeatureList so I cannot add SDK to the list at line 1319 and 1323. Therefore updated the context at line 1219 to do a negative test for SDK feature as well.

**Comment by johlju** [comment]
@GoelPooja Could you please go into Reviewable (big purple button at the top) and write (or press) 'Done' in each comment and the press the big green Publish at the top of the page in reviewable (which will send the comments back to GitHub). If you do that I can acknowledge (resolve) the comments.

@GoelPooja My bad on the negative test, didn't read the test as carefully as I should have done. Good that you added SDK to the negative test. 😄

**Comment by GoelPooja** [comment]
Review status: 1 of 3 files reviewed at latest revision, 10 unresolved discussions.

---

*[CHANGELOG.md, line 120 at r3](https://reviewable.io:443/reviews/powershell/xsqlserver/521#-Kijmbk_Og_hCFXteA5C:-Kj24WIc1qpm_HffXRdl:b-896fix) ([raw file](https://github.com/powershell/xsqlserver/blob/81708c1020ba109a8c0cbe9caaf7a1f900a0a677/CHANGELOG.md#L120)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

You have blank spaces on this row that probably is causing two of the markdown lint errors.
</blockquote></details>

Done.

---

*[CHANGELOG.md, line 121 at r3](https://reviewable.io:443/reviews/powershell/xsqlserver/521#-Kijli0S_dLqjJwPzxvJ:-Kj24VRgxUIwdHjggW0B:b-896fix) ([raw file](https://github.com/powershell/xsqlserver/blob/81708c1020ba109a8c0cbe9caaf7a1f900a0a677/CHANGELOG.md#L121)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

Please rebase your working branch against dev (do not merge or pull). Please see here how to do this. https://github.com/PowerShell/DscResources/blob/master/GettingStartedWithGitHub.md#1-rebase-the-local-dev-branch-from-the-base-dev-branch

When that is done, please move this to the end of the Unreleased section.
</blockquote></details>

Done.

---

*[CHANGELOG.md, line 77 at r4](https://reviewable.io:443/reviews/powershell/xsqlserver/521#-Kit6AVhhkhgd75M7pTm:-Kj24QARV7dq_Y96b6mA:b-896fix) ([raw file](https://github.com/powershell/xsqlserver/blob/776a7c7cae447c9dbb75c26dee685d1830a2ccea/CHANGELOG.md#L77)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

Move these change log entries to the unreleased section (line 3). V7.0.0.0 is what is already released to the PowerShell Gallery. 
</blockquote></details>

Done.

---

*[Tests/Unit/MSFT_xSQLServerSetup.Tests.ps1, line 404 at r4](https://reviewable.io:443/reviews/powershell/xsqlserver/521#-Kit9au51k8iWPRLXf6G:-Kj24cPT6Fd6N1MT7NsN:b-896fix) ([raw file](https://github.com/powershell/xsqlserver/blob/776a7c7cae447c9dbb75c26dee685d1830a2ccea/Tests/Unit/MSFT_xSQLServerSetup.Tests.ps1#L404)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

What editor are you using? It seem to have added 8 spaces on each blank row :/ 
But only for the test file for some reason. Could you look at that? I'm getting a change on a lot of rows now.
Suggestion is to use VS Code and add the setting  `"files.trimTrailingWhitespace": true`.
Thanks!
</blockquote></details>

Done.

---

*[Tests/Unit/MSFT_xSQLServerSetup.Tests.ps1, line 665 at r4](https://reviewable.io:443/reviews/powershell/xsqlserver/521#-KitHi9ouRBfc328XE2Y:-Kj24dLJJ5fdMMd-vXBO:b-896fix) ([raw file](https://github.com/powershell/xsqlserver/blob/776a7c7cae447c9dbb75c26dee685d1830a2ccea/Tests/Unit/MSFT_xSQLServerSetup.Tests.ps1#L665)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

All Add-Member has been indented back 4 spaces. This also gives changes on _a lot_ of rows. Could you fix this too please?
</blockquote></details>

Done.

---

*[Tests/Unit/MSFT_xSQLServerSetup.Tests.ps1, line 891 at r4](https://reviewable.io:443/reviews/powershell/xsqlserver/521#-Kit8hKkdSBqpMn_l_tO:-Kj24e3KnUGRqKChzDHG:b-896fix) ([raw file](https://github.com/powershell/xsqlserver/blob/776a7c7cae447c9dbb75c26dee685d1830a2ccea/Tests/Unit/MSFT_xSQLServerSetup.Tests.ps1#L891)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

> 'SQLENGINE,REPLICATION,DQC,DQ,BOL,CONN,BC,SDK,FULLTEXT,RS,AS,IS,SSMS,ADV_SSMS'

Please change these to both upper-case and lower-case letters. That is used for regression testing since we had a bug before where we did not support features written in lower-case

So please change it to 
`'SQLEngine,Replication,Dqc,Dq,Bol,Conn,Bc,Sdk,FullText,Rs,As,Is,Ssms,Adv_Ssms'`
</blockquote></details>

Done.

---

*[Tests/Unit/MSFT_xSQLServerSetup.Tests.ps1, line 893 at r4](https://reviewable.io:443/reviews/powershell/xsqlserver/521#-KitAjpPMjIhLv2POOuW:-Kj24ev_He4xRjzL8aCE:b-896fix) ([raw file](https://github.com/powershell/xsqlserver/blob/776a7c7cae447c9dbb75c26dee685d1830a2ccea/Tests/Unit/MSFT_xSQLServerSetup.Tests.ps1#L893)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

Please add a blank line before this one.
</blockquote></details>

Done.

---

*[Tests/Unit/MSFT_xSQLServerSetup.Tests.ps1, line 1319 at r4](https://reviewable.io:443/reviews/powershell/xsqlserver/521#-KitGU4680LVzbzcDz28:-Kj24fg_WVsjDUptvf8M:b-896fix) ([raw file](https://github.com/powershell/xsqlserver/blob/776a7c7cae447c9dbb75c26dee685d1830a2ccea/Tests/Unit/MSFT_xSQLServerSetup.Tests.ps1#L1319)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

Was expecting feature SDK in as well.
</blockquote></details>

Done.

---

*[Tests/Unit/MSFT_xSQLServerSetup.Tests.ps1, line 1323 at r4](https://reviewable.io:443/reviews/powershell/xsqlserver/521#-KitG_Z21pKn-J4t_irf:-Kj24gNHwQPLNjwN4cpO:b-896fix) ([raw file](https://github.com/powershell/xsqlserver/blob/776a7c7cae447c9dbb75c26dee685d1830a2ccea/Tests/Unit/MSFT_xSQLServerSetup.Tests.ps1#L1323)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

Was expecting feature SDK in as well.
</blockquote></details>

Done.

---

*[Tests/Unit/MSFT_xSQLServerSetup.Tests.ps1, line 3799 at r4](https://reviewable.io:443/reviews/powershell/xsqlserver/521#-KitG-m85Aqm0euYlz1p:-Kj24hLSaa9UrXH4FCC1:b-896fix) ([raw file](https://github.com/powershell/xsqlserver/blob/776a7c7cae447c9dbb75c26dee685d1830a2ccea/Tests/Unit/MSFT_xSQLServerSetup.Tests.ps1#L3799)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

Blank line before this one.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xsqlserver/521)*

**Comment by GoelPooja** [comment]
@johlju Published the reviewable comments.

**Comment by johlju** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r6.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xsqlserver/521#-:-Kj3TNRqXhY2L-wzl_o2:bnfp4nl)*

**Comment by johlju** [comment]
Awesome work on this! Big thanks!

**Comment by GoelPooja** [comment]
@johlju Thanks for accepting the changes,
When will these changes available in master branch ?

**Comment by johlju** [comment]
It will be release to master and PowerShell Gallery when the PowerShell team is releasing the next version, which they usually does 1-2 month apart. Version 7 of xSQLServer was release a couple of weeks ago so it's gonna be some weeks until next release unfortunately.

**Pull request merged**
