### PR TITLE
xSQLServerDatabaseDefaultLocations: New Resource

### LINKED ISSUE #656: xSQLServerDatabaseDefaultLocation: New Resource
**Details of the scenario you tried and the problem that is occurring:**
I propose a new resource called **xSQLServerDatabaseDefaultLocation** be created in order to manage the default data, log, and backup locations of an instance. Here is the proposed schema:

```
[ClassVersion("1.0.0.0"), FriendlyName("xSQLServerDatabaseDefaultLocation")]
class MSFT_xSQLServerDatabaseDefaultLocation : OMI_BaseResource
{
    [Key, Description("The host name of the SQL Server to be configured.")] String SQLServer;
    [Key, Description("The name of the SQL instance to be configured.")] String SQLInstanceName;
    [Key, Description("The default location to set. Valid values are 'Data','Log', and 'Backup'."), ValueMap{"Data","Log","Backup"}, Values{"Data","Log","Backup"}] String Location;
    [Key, Description("The full path to the desired default location.")] String Path;
};
```

**The DSC configuration that is using the resource (as detailed as possible):**
N/A
**Version of the Operating System, SQL Server and PowerShell the DSC Target Node is running:**
N/A
**What module (SqlServer or SQLPS) and which version of the module the DSC Target Node is running:**
N/A
**Version of the DSC module you're using, or 'dev' if you're using current dev branch:**
dev

### PR DESCRIPTION
**Pull request by PaulFeaser**
**Pull Request (PR) description**
Created new resource for setting Database Default Locations (Data/Log/Backup) for SQL Server

**This Pull Request (PR) fixes the following issues:**
Fixes #656 

**Task list:**
- [X] Change details added to Unreleased section of CHANGELOG.md?
- [X] Added/updated documentation, comment-based help and descriptions in .schema.mof files where appropriate?
- [X] Examples appropriately updated?
- [X] New/changed code adheres to [Style Guidelines](https://github.com/PowerShell/DscResources/blob/master/StyleGuidelines.md)?
- [X] [Unit and (optional) Integration tests](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md) created/updated where possible?

---
This change is [Reviewable](https://reviewable.io/reviews/powershell/xsqlserver/854)

### CODE REVIEW

**Comment by PaulFeaser** [comment]
@msftclas I'm full-time Microsoft employee, not sure why it is asking for a signed CLA.

**Comment by johlju** [comment]
@PaulFeaser Contact @mbreakey3 or @kwirkykat and make sure you are in the Microsoft organisation in GitHub (think that's the problem).

**Comment by johlju** [comment]
@PaulFeaser Could you please rename the resource to 'xSQLServerDatabaseDefaultLocation' (singular). Throughout the files.

**Comment by PaulFeaser** [comment]
I would be happy to rename it.  However, I made it plural because that matches exactly how it is in SQL Server Management Studio.

**Comment by johlju** [comment]
All other resources are singular and in PowerShell the norm is to use singular in all Cmdlets. So I rather see this as singular too.

**Comment by PaulFeaser** [comment]
Sounds good, I will rename it.

**Pull request closed without merging**
