### PR TITLE
xSQLServerDatabaseRecoveryModel: Increase code coverage

### PR DESCRIPTION
**Pull request by luigilink**
xSQLServerDatabaseRecoveryModel: Increase code coverage

- [x] Change details added to Unreleased section of CHANGELOG.md?
- [x] Added/updated documentation, comment-based help and descriptions in .schema.mof files where appropriate?
- [x] Examples appropriately updated?
- [x] New/changed code adheres to [Style Guidelines](https://github.com/PowerShell/DscResources/blob/master/StyleGuidelines.md)?
- [x] [Unit and (optional) Integration tests](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md) created/updated where possible?

---
This change is [Reviewable](https://reviewable.io/reviews/powershell/xsqlserver/428)

### CODE REVIEW

**Comment by johlju** [comment]
:lgtm:

---

Reviewed 3 of 4 files at r1, 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xsqlserver/428#-:-KfRM2MzNYb6p0DcoiWf:bnfp4nl)*

**Comment by johlju** [comment]
@luigilink Could you rebase this one, I can't resolve the conflicts thru GitHub on this one, must be to big of a difference.

Also, have you run this code in a lab to verify that is sets the correct RecoveryModel? If not, I will do that before merging.

**Comment by luigilink** [comment]
@johlju I have 100 % codecov on this branch but 69% on project 😭

**Comment by johlju** [comment]
@luigilink I think that is a false negative since code was removed. I'm ignoring that :) As long as the code is fully tested I'm happy :smile:

**Comment by luigilink** [comment]
Test is OK in my lab:

- Windows Version: Windows Server 2012 R2
- PowerShell Version: 5.0.10586.117
- SQL Version: 11.0.6020

DSC Configuration:

```
        xSQLServerDatabase TEST_SqlDatabase
        {
            DependsOn = '[xSqlServerSetup]MIDDLEWARE_SqlMSSQLSERVER'
            Ensure ='Present'
            Name = 'AdventureWorks'
            SQLServer = $Node.NodeName
            SQLInstanceName = $ConfigurationData.NonNodeData.SQLServer.Instances.Common.Instance
            PsDscRunAsCredential = $FFP
        }
        xSQLServerDatabaseRecoveryModel TEST_SqlDatabase_RecoveryModel
        {
            Name = 'AdventureWorks'
            RecoveryModel = 'Simple'
            DependsOn = '[xSQLServerDatabase]TEST_SqlDatabase'
            PsDscRunAsCredential = $FFP
            SQLServer = $Node.NodeName
            SQLInstanceName = $ConfigurationData.NonNodeData.SQLServer.Instances.Common.Instance
        }
```

Result from Update-DscConfiguration -Wait -Verbose

```
VERBOSE: [SPS15DEV]: LCM:  [ Start  Resource ]  [[xSQLServerDatabase]TEST_SqlDatabase]
VERBOSE: [SPS15DEV]: LCM:  [ Start  Test     ]  [[xSQLServerDatabase]TEST_SqlDatabase]
VERBOSE: [SPS15DEV]:                            [[xSQLServerDatabase]TEST_SqlDatabase] Importing the module
MSFT_xSQLServerDatabase in force mode.
VERBOSE: [SPS15DEV]:                            [[xSQLServerDatabase]TEST_SqlDatabase] Importing the module
MSFT_xSQLServerDatabase in force mode.
VERBOSE: [SPS15DEV]:                            [[xSQLServerDatabase]TEST_SqlDatabase] Checking if database named
AdventureWorks is present or absent
VERBOSE: [SPS15DEV]:                            [[xSQLServerDatabase]TEST_SqlDatabase] 2017-03-19_15-52-34: Connected
to SQL SPS15DEV\ZUDA0
VERBOSE: [SPS15DEV]:                            [[xSQLServerDatabase]TEST_SqlDatabase] Getting SQL Databases
VERBOSE: [SPS15DEV]:                            [[xSQLServerDatabase]TEST_SqlDatabase] SQL Database name AdventureWorks
 is present
VERBOSE: [SPS15DEV]: LCM:  [ End    Test     ]  [[xSQLServerDatabase]TEST_SqlDatabase]  in 1.6410 seconds.
VERBOSE: [SPS15DEV]: LCM:  [ Skip   Set      ]  [[xSQLServerDatabase]TEST_SqlDatabase]
VERBOSE: [SPS15DEV]: LCM:  [ End    Resource ]  [[xSQLServerDatabase]TEST_SqlDatabase]
VERBOSE: [SPS15DEV]: LCM:  [ Start  Resource ]  [[xSQLServerDatabaseRecoveryModel]TEST_SqlDatabase_RecoveryModel]
VERBOSE: [SPS15DEV]: LCM:  [ Start  Test     ]  [[xSQLServerDatabaseRecoveryModel]TEST_SqlDatabase_RecoveryModel]
VERBOSE: [SPS15DEV]:                            [[xSQLServerDatabaseRecoveryModel]TEST_SqlDatabase_RecoveryModel]
Importing the module MSFT_xSQLServerDatabaseRecoveryModel in force mode.
VERBOSE: [SPS15DEV]:                            [[xSQLServerDatabaseRecoveryModel]TEST_SqlDatabase_RecoveryModel]
Importing the module MSFT_xSQLServerDatabaseRecoveryModel in force mode.
VERBOSE: [SPS15DEV]:                            [[xSQLServerDatabaseRecoveryModel]TEST_SqlDatabase_RecoveryModel]
Testing RecoveryModel of database 'AdventureWorks'
VERBOSE: [SPS15DEV]:                            [[xSQLServerDatabaseRecoveryModel]TEST_SqlDatabase_RecoveryModel]
2017-03-19_15-52-35: Connected to SQL SPS15DEV\ZUDA0
VERBOSE: [SPS15DEV]:                            [[xSQLServerDatabaseRecoveryModel]TEST_SqlDatabase_RecoveryModel]
Getting RecoveryModel of SQL database 'AdventureWorks'
VERBOSE: [SPS15DEV]:                            [[xSQLServerDatabaseRecoveryModel]TEST_SqlDatabase_RecoveryModel]
2017-03-19_15-52-35: The current recovery model used by database AdventureWorks is 'Simple'
VERBOSE: [SPS15DEV]: LCM:  [ End    Test     ]  [[xSQLServerDatabaseRecoveryModel]TEST_SqlDatabase_RecoveryModel]  in
0.5630 seconds.
VERBOSE: [SPS15DEV]: LCM:  [ Skip   Set      ]  [[xSQLServerDatabaseRecoveryModel]TEST_SqlDatabase_RecoveryModel]
VERBOSE: [SPS15DEV]: LCM:  [ End    Resource ]  [[xSQLServerDatabaseRecoveryModel]TEST_SqlDatabase_RecoveryModel]
```

**Comment by johlju** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xsqlserver/428#-:-Kg4vsSmiU4U5Yc8UksK:bnfp4nl)*

**Comment by johlju** [comment]
@luigilink Can you rebase this one again? I tried to do it for you but got permission denied, so I guess you did not check 'Allow edits from maintainers'. It was worth a shot 😄

**Comment by luigilink** [comment]
@johlju Rebase is done, but how can I give you this 'Allow edits from maintainers' setting for the future PR.

**Comment by johlju** [comment]
Yes, there it is. Also you have the check-box on the page where you submit a PR. 😄 I submitted a request to GitHub for that check-box to show for a PR you are not the author of as well. Hope GitHub can get that in eventually. Makes life easier to see it as a maintainer. Then I know directly if there is a point to try to submit fixes/resolve conflicts to a contributors working branch. :)

**Comment by johlju** [comment]
:lgtm:

---

Reviewed 3 of 3 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xsqlserver/428#-:-KgFGE1xVeRRWpoT5Gqw:bnfp4nl)*

**Pull request merged**
