### PR TITLE
xSQLServerSetup: Move checking for Tools features to not depend on SQLEngine - Fixes #591

### LINKED ISSUE #591: xSqlServerSetup: Conn, BC etc features only detected if SQLENGINE also installed
**Details of the scenario you tried and the problem that is occurring:**

When installing some of the tools features, in this case Conn and BC, but not installing SQLENGINE the Get-TargetResource is not returning them as installed features. Looking at the code the check for these features is within a check for a service named after the instance name. 

**The DSC configuration that is using the resource (as detailed as possible):**

```
xSqlServerSetup SqlInstall {
                DependsOn = '[xComputer]DomainJoin'
                Action = 'Install'
                InstanceName = 'MSSQLSERVER'
                SourcePath = $Node.SqlSourcePath
                SetupCredential = $LocalAdminCredential
                Features = 'Conn,BC,IS,SSMS,ADV_SSMS'
                ProductKey = '<stuff here>'
                UpdateEnabled = 'False'
                INSTALLSHAREDDIR="C:\Program Files\Microsoft SQL Server"
                INSTALLSHAREDWOWDIR="C:\Program Files (x86)\Microsoft SQL Server"
                INSTANCEDIR="C:\Program Files\Microsoft SQL Server"
                SQLSvcAccount = $SQLServerUAT
                AgtSvcAccount = $SQLServerAgentUAT
                SQLCollation = "Latin1_General_CI_AS"
                SecurityMode = 'SQL'
                SAPwd = $SAPWD
                ASCOLLATION = "Latin1_General_CI_AS"
                ASDATADIR = "Data"
                ASBACKUPDIR = "Backup"
                ASTEMPDIR = "Temp"
                ASCONFIGDIR = "Config"
                SQLSYSADMINACCOUNTS = "$DomainNetBiosName\Database Admins"
                SQLUSERDBDIR = (Join-Path -Path $DataDrive -ChildPath "Data\SQL")
                SQLUSERDBLOGDIR = (Join-Path -Path $DataDrive -ChildPath "Data\SQL")
                BROWSERSVCSTARTUPTYPE = "Disabled"
            }
```
**Version of the Operating System, SQL Server and PowerShell the DSC Target Node is running:**

Server 2012R2, running SQL 2012, PSv5.1 and v7.0.0.0 of xSqlServer

The fix for this is reasonably simple, just moving the various checks which detect the tools features outside the current If block would work. I will have a look at putting in a PR for this at some point in the next few days.

### PR DESCRIPTION
**Pull request by ChrisLGardner**
**Pull Request (PR) description**
Get-TargetResource was only checking for Conn, BC and other features if the SQL service was found, There are use cases for installing these tools without installing SQL Engine. This moves them outside that scope and updates the tests to reflect this change. 

**This Pull Request (PR) fixes the following issues:**
Fixes #591 

**Task list:**
- [X] Change details added to Unreleased section of CHANGELOG.md?
- [ ] Added/updated documentation, comment-based help and descriptions in .schema.mof files where appropriate?
- [ ] Examples appropriately updated?
- [X] New/changed code adheres to [Style Guidelines](https://github.com/PowerShell/DscResources/blob/master/StyleGuidelines.md)?
- [X] [Unit and (optional) Integration tests](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md) created/updated where possible?

---
This change is [Reviewable](https://reviewable.io/reviews/powershell/xsqlserver/595)

### CODE REVIEW

**Comment by johlju** [comment]
Reviewed 2 of 3 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[CHANGELOG.md, line 43 at r2](https://reviewable.io:443/reviews/powershell/xsqlserver/595#-KleJHhpdg4LwT5e4y1V:-KleJHhpdg4LwT5e4y1W:b1wjefo) ([raw file](https://github.com/powershell/xsqlserver/blob/8bbcfc462473f24dd89d74c1b377cd22aa23bd90/CHANGELOG.md#L43)):*
> ```Markdown
>   - Updated xSQLServerSetup Module Get-Resource method to fix (issue #516 and #490).
>   - Added change to detect DQ, DQC, BOL, SDK features. Now the function Test-TargetResource returns true after calling set for DQ, DQC, BOL, SDK features (issue #516 and #490).
>   - Updated Get-TargetResource to correctly detect BOL, Conn, BC and other tools when they are installed withouth SQLENGINE (issue #591).
> ```

PR need to be rebased after release.

---

*[DSCResources/MSFT_xSQLServerSetup/MSFT_xSQLServerSetup.psm1, line 374 at r2](https://reviewable.io:443/reviews/powershell/xsqlserver/595#-KleJ1XapfL7SfKBtAiR:-KleJ1Xb1a1k5X0JeA7b:b-jr8r0c) ([raw file](https://github.com/powershell/xsqlserver/blob/8bbcfc462473f24dd89d74c1b377cd22aa23bd90/DSCResources/MSFT_xSQLServerSetup/MSFT_xSQLServerSetup.psm1#L374)):*
> ```PowerShell
> 
>     $features = $features.Trim(',')
>     if (-not ([string]::IsNullOrWhiteSpace($Features)))
> ```

Shouldn't this have sufficed with `if ($features)`?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xsqlserver/595)*

**Comment by johlju** [comment]
Could you rebase this PR please? Also, please make sure the change log entries goes back under the unreleased section. It's always a problem when rebasing after a new release. 😄

**Comment by johlju** [comment]
And here is a linnk for information on how to rebase and resolve merge conflicts.
https://github.com/PowerShell/DscResources/blob/master/GettingStartedWithGitHub.md#resolve-merge-conflicts

**Comment by ChrisLGardner** [comment]
Review status: 1 of 3 files reviewed at latest revision, 2 unresolved discussions.

---

*[CHANGELOG.md, line 43 at r2](https://reviewable.io:443/reviews/powershell/xsqlserver/595#-KleJHhpdg4LwT5e4y1V:-KlmTVgkMn5cZA6d0Pyq:b-9h2nu6) ([raw file](https://github.com/powershell/xsqlserver/blob/8bbcfc462473f24dd89d74c1b377cd22aa23bd90/CHANGELOG.md#L43)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

PR need to be rebased after release.
</blockquote></details>

That should be done now.

---

*[DSCResources/MSFT_xSQLServerSetup/MSFT_xSQLServerSetup.psm1, line 374 at r2](https://reviewable.io:443/reviews/powershell/xsqlserver/595#-KleJ1XapfL7SfKBtAiR:-KlmTad87NVLmAr_yywj:bqqcmx0) ([raw file](https://github.com/powershell/xsqlserver/blob/8bbcfc462473f24dd89d74c1b377cd22aa23bd90/DSCResources/MSFT_xSQLServerSetup/MSFT_xSQLServerSetup.psm1#L374)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

Shouldn't this have sufficed with `if ($features)`?
</blockquote></details>

Yes it should have been. I was trying to be too clever with it when I didn't need to be.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xsqlserver/595)*

**Comment by johlju** [comment]
Reviewed 2 of 2 files at r4.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[DSCResources/MSFT_xSQLServerSetup/MSFT_xSQLServerSetup.psm1, line 374 at r2](https://reviewable.io:443/reviews/powershell/xsqlserver/595#-KleJ1XapfL7SfKBtAiR:-KlnuJARs1aiAgIPuy0g:btcy8fa) ([raw file](https://github.com/powershell/xsqlserver/blob/8bbcfc462473f24dd89d74c1b377cd22aa23bd90/DSCResources/MSFT_xSQLServerSetup/MSFT_xSQLServerSetup.psm1#L374)):*
<details><summary><i>Previously, ChrisLGardner wrote…</i></summary><blockquote>

Yes it should have been. I was trying to be too clever with it when I didn't need to be.
</blockquote></details>

Thanks for fixing that, but could you please change it to `$features` (lower 'f')?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xsqlserver/595)*

**Comment by ChrisLGardner** [comment]
Review status: 1 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[DSCResources/MSFT_xSQLServerSetup/MSFT_xSQLServerSetup.psm1, line 374 at r2](https://reviewable.io:443/reviews/powershell/xsqlserver/595#-KleJ1XapfL7SfKBtAiR:-KloGFt8hVogt7te0x0W:b-896fix) ([raw file](https://github.com/powershell/xsqlserver/blob/8bbcfc462473f24dd89d74c1b377cd22aa23bd90/DSCResources/MSFT_xSQLServerSetup/MSFT_xSQLServerSetup.psm1#L374)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

Thanks for fixing that, but could you please change it to `$features` (lower 'f')?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xsqlserver/595)*

**Comment by johlju** [comment]
Reviewed 2 of 2 files at r5.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[CHANGELOG.md, line 5 at r5](https://reviewable.io:443/reviews/powershell/xsqlserver/595#-KloIXOv8kT3liG3wfw-:-KloIXOwcQ3T92eyv16Y:b7rqfqx) ([raw file](https://github.com/powershell/xsqlserver/blob/2c4cf34c0de2ef2786a94badb05b83fd14915af1/CHANGELOG.md#L5)):*
> ```Markdown
> ## Unreleased
> 
> <<<<<<< HEAD
> ```

I think when you did the rebase you didn't fix the conflicts. They went in into the PR. Could you please clean up the Unreleased section?
Just push a new commit fixing this. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xsqlserver/595)*

**Comment by johlju** [comment]
Let me know if you need any help :smile:

**Comment by ChrisLGardner** [comment]
Review status: 2 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[CHANGELOG.md, line 5 at r5](https://reviewable.io:443/reviews/powershell/xsqlserver/595#-KloIXOv8kT3liG3wfw-:-KlrFJZYUQUvr-4aQoVG:bjtjbsd) ([raw file](https://github.com/powershell/xsqlserver/blob/2c4cf34c0de2ef2786a94badb05b83fd14915af1/CHANGELOG.md#L5)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

I think when you did the rebase you didn't fix the conflicts. They went in into the PR. Could you please clean up the Unreleased section?
Just push a new commit fixing this. 
</blockquote></details>

Fixed I think. That's what I get for trying to work on a train with a bad internet connection.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xsqlserver/595)*

**Comment by johlju** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r6.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xsqlserver/595#-:-Klt54iB-qZaA5eT81nA:bnfp4nl)*

**Comment by johlju** [comment]
@ChrisLGardner Awesome work! Thanks for this! Merged. 😄

**Pull request merged**
