### PR TITLE
MSFT_xSQLServerRole, MSFT_xSQLServerRoleMembership

### LINKED ISSUE #30: Server roles
Is it possible to grant server roles to users? It would be great if you could grant them using xSQLServerLogin resource.

### PR DESCRIPTION
**Pull request by rakkhin**
Added following resources
- **MSFT_xSQLServerRole** used to create/drop server roles
- **MSFT_xSQLServerRoleMembership** used to add/remove server role membership

Fixes #30

---

This change is [Reviewable](https://reviewable.io/reviews/powershell/xsqlserver/74)

### CODE REVIEW

**Comment by mbreakey3** [comment]
Reviewed 5 of 6 files at r1.
Review status: 5 of 6 files reviewed at latest revision, 2 unresolved discussions.

---

*[DSCResources/MSFT_xSQLServerRole/MSFT_xSQLServerRole.psm1, line 1 \[r2\]](https://reviewable.io:443/reviews/powershell/xsqlserver/74#-KNddRa6jo5g8_IDTLfM:-KNddRa6jo5g8_IDTLfN:1281121038) ([raw file](https://github.com/powershell/xsqlserver/blob/19c66b9d22fa82a11f13a3db75ed30254e2c652a/DSCResources/MSFT_xSQLServerRole/MSFT_xSQLServerRole.psm1#L1)):*
> ```PowerShell
> $currentPath = Split-Path -Parent $MyInvocation.MyCommand.Path
> ```

$script:currentPath

---

*[DSCResources/MSFT_xSQLServerRoleMembership/MSFT_xSQLServerRoleMembership.psm1, line 1 \[r2\]](https://reviewable.io:443/reviews/powershell/xsqlserver/74#-KNde2mVG6uyJdhvOi5Z:-KNde2mVG6uyJdhvOi5_:1281121038) ([raw file](https://github.com/powershell/xsqlserver/blob/19c66b9d22fa82a11f13a3db75ed30254e2c652a/DSCResources/MSFT_xSQLServerRoleMembership/MSFT_xSQLServerRoleMembership.psm1#L1)):*
> ```PowerShell
> $currentPath = Split-Path -Parent $MyInvocation.MyCommand.Path
> ```

$script:currentPath

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xsqlserver/74)*

**Comment by mbreakey3** [comment]
Also, we're requiring all new resources to have adequate test-coverage - specifically unit test coverage. So can you create a unit-test file in the new unit tests folder in this module? Here's a link to the template for writing DSC unit tests: [Unit tests Template](https://github.com/PowerShell/DscResources/blob/master/Tests.Template/unit_template.ps1)

**Comment by luigilink** [comment]
This PR can be closed, the resource MSFT_xSQLServerRole already exist in release 2.0.0.0

**Comment by johlju** [comment]
Do you think it should be closed? I does exist already, but doesn't this PR contain another resource as well. If so xSQLServerRole should be removed from this PR. 
I will look at this also and get back shortly.

**Comment by johlju** [comment]
@luigilink I think this PR should _not_ be closed. Rather I think we need to do some actions to solve this conflict. I submit an issue with my findings to track this.

**Comment by johlju** [comment]
@rakkhin Are you up to make some changes to this PR to make in align with the conflicting resource? Let us know if you have time to help out with this.

**Comment by johlju** [comment]
Review status: 5 of 6 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[README.md, line 289 at r2](https://reviewable.io:443/reviews/powershell/xsqlserver/74#-KX9ybhtWwYru8gQKOFY:-KX9ybhtWwYru8gQKOFZ:b3i54kl) ([raw file](https://github.com/powershell/xsqlserver/blob/19c66b9d22fa82a11f13a3db75ed30254e2c652a/README.md#L289)):*
> ```Markdown
> ### Unreleased
> * Converted appveyor.yml to install Pester from PSGallery instead of from Chocolatey.
> * Resources Added
> ```

The Unreleased section has been moved to the CHANGELOG.md. Please move your entries to the Unreleased section in the new CHANGELOG.md when you do `git rebase`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xsqlserver/74)*

**Comment by johlju** [comment]
Changes here has been proposed in the PR #414. When PR #414 is merged this can be closed. I keep it open until then for reference.

**Comment by johlju** [comment]
This one is obsolete since PR #414 was merged. Thanks to @luigilink for fixing the new resource that does both creating a role and manages memberships!

Closing this one.

**Pull request closed without merging**
