### PR TITLE
xSQLServer: Update Pester syntax to v4

### LINKED ISSUE #863: xSQLServer: Migrate Pester Test Syntax from v3 -> v4
**Details of the scenario you tried and the problem that is occurring:**
As of Pester v4 the syntax of the Should cmdlet has changed from Should Be to Should -Be.

There is a helpful script that can be used to easily perform the conversion:
https://gist.github.com/indented-automation/aeb14825e39dd8849beee44f681fbab3

This script should be used to correct the Pester syntax.

**The DSC configuration that is using the resource (as detailed as possible):**
n/a

**Version of the Operating System, SQL Server and PowerShell the DSC Target Node is running:**
n/a

**What module (SqlServer or SQLPS) and which version of the module the DSC Target Node is running:**
n/a

**Version of the DSC module you're using, or 'dev' if you're using current dev branch:**
Dev

### PR DESCRIPTION
**Pull request by mnewswanger**
**Pull Request (PR) description**
Update Pester flag syntax to v4

**This Pull Request (PR) fixes the following issues:**
Resolves #863

**Task list:**
- [X] Change details added to Unreleased section of CHANGELOG.md?
- [X] Added/updated documentation, comment-based help and descriptions in .schema.mof files where appropriate?
- [X] Examples appropriately updated?
- [X] New/changed code adheres to [Style Guidelines](https://github.com/PowerShell/DscResources/blob/master/StyleGuidelines.md)?
- [X] [Unit and (optional) Integration tests](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md) created/updated where possible?

---
This change is [Reviewable](https://reviewable.io/reviews/powershell/xsqlserver/888)

### CODE REVIEW

**Comment by johlju** [comment]
@mnewswanger There are some failing tests in the AppVeyor run. Please see https://ci.appveyor.com/project/PowerShell/xsqlserver/build/6.0.1685.0#L3098

Not sure what the problem is. But one issue could be that it looks like that the string is formatted wrong and this new Pester syntax handles this correctly (by throwing). This has nothing to do with your change, but we need to solve this for me to be able to merge your changes.

See line 131:
```
'Got unexpected result from Get-TargetResource. No change is made. InnerException: Endpoint 'DefaultEndpointMirror' does not exist'
```
maybe see if escaping the single quotes around `'DefaultEndpointMirror'` will solve the problem?

```
'Got unexpected result from Get-TargetResource. No change is made. InnerException: Endpoint ''DefaultEndpointMirror'' does not exist'
```

Let me know if you need any help with this one.

**Comment by johlju** [comment]
@mnewswanger Btw awesome work fixing all of these! Thanks a lot! 😄

**Comment by mnewswanger** [comment]
These are resolved with proper variable escapes

**Comment by johlju** [comment]
@mnewswanger Awesome that you solved it. Thanks! Will review!

**Comment by johlju** [comment]
Some review comments of old typos (in existing code). Sorry for repeating the same comment. But it's just for me to be able to find it again :)

---

Reviewed 31 of 34 files at r1, 3 of 3 files at r2.
Review status: all files reviewed at latest revision, 16 unresolved discussions.

---

*[Tests/Unit/MSFT_xSQLServerAlwaysOnService.Tests.ps1, line 223 at r2](https://reviewable.io:443/reviews/powershell/xsqlserver/888#-KwjbeGdSoOx1atYr3mP:-KwjbeGdSoOx1atYr3mQ:b9io8dg) ([raw file](https://github.com/powershell/xsqlserver/blob/6a62ec4987b28f2452e604d83045da3e5ce93ef6/Tests/Unit/MSFT_xSQLServerAlwaysOnService.Tests.ps1#L223)):*
> -be

Could you please change this to `-Be`.

---

*[Tests/Unit/MSFT_xSQLServerAlwaysOnService.Tests.ps1, line 235 at r2](https://reviewable.io:443/reviews/powershell/xsqlserver/888#-KwjbjuyVs9TgnqZ1sMR:-KwjbjuyVs9TgnqZ1sMS:b9io8dg) ([raw file](https://github.com/powershell/xsqlserver/blob/6a62ec4987b28f2452e604d83045da3e5ce93ef6/Tests/Unit/MSFT_xSQLServerAlwaysOnService.Tests.ps1#L235)):*
> -be

Could you please change this to `-Be`.

---

*[Tests/Unit/MSFT_xSQLServerConfiguration.Tests.ps1, line 199 at r2](https://reviewable.io:443/reviews/powershell/xsqlserver/888#-KwjbzEHjZdCG6vAHJEc:-KwjbzEHjZdCG6vAHJEd:b9io8dg) ([raw file](https://github.com/powershell/xsqlserver/blob/6a62ec4987b28f2452e604d83045da3e5ce93ef6/Tests/Unit/MSFT_xSQLServerConfiguration.Tests.ps1#L199)):*
> -be

Could you please change this to `-Be`.

---

*[Tests/Unit/MSFT_xSQLServerConfiguration.Tests.ps1, line 203 at r2](https://reviewable.io:443/reviews/powershell/xsqlserver/888#-Kwjbzho4QJxTG_2CmJL:-Kwjbzho4QJxTG_2CmJM:b9io8dg) ([raw file](https://github.com/powershell/xsqlserver/blob/6a62ec4987b28f2452e604d83045da3e5ce93ef6/Tests/Unit/MSFT_xSQLServerConfiguration.Tests.ps1#L203)):*
> -be

Could you please change this to `-Be`.

---

*[Tests/Unit/MSFT_xSQLServerReplication.Tests.ps1, line 41 at r2](https://reviewable.io:443/reviews/powershell/xsqlserver/888#-KwjdhUYwogkbjiys_5x:-KwjdhUYwogkbjiys_5y:b9io8dg) ([raw file](https://github.com/powershell/xsqlserver/blob/6a62ec4987b28f2452e604d83045da3e5ce93ef6/Tests/Unit/MSFT_xSQLServerReplication.Tests.ps1#L41)):*
> -be

Could you please change this to `-Be`.

---

*[Tests/Unit/MSFT_xSQLServerReplication.Tests.ps1, line 57 at r2](https://reviewable.io:443/reviews/powershell/xsqlserver/888#-KwjdjCr8spEbUQ4hv1F:-KwjdjCr8spEbUQ4hv1G:b9io8dg) ([raw file](https://github.com/powershell/xsqlserver/blob/6a62ec4987b28f2452e604d83045da3e5ce93ef6/Tests/Unit/MSFT_xSQLServerReplication.Tests.ps1#L57)):*
> -be

Could you please change this to `-Be`.

---

*[Tests/Unit/MSFT_xSQLServerReplication.Tests.ps1, line 61 at r2](https://reviewable.io:443/reviews/powershell/xsqlserver/888#-KwjdjkH_o9pWgOubnKb:-KwjdjkH_o9pWgOubnKc:b9io8dg) ([raw file](https://github.com/powershell/xsqlserver/blob/6a62ec4987b28f2452e604d83045da3e5ce93ef6/Tests/Unit/MSFT_xSQLServerReplication.Tests.ps1#L61)):*
> -be

Could you please change this to `-Be`.

---

*[Tests/Unit/MSFT_xSQLServerReplication.Tests.ps1, line 157 at r2](https://reviewable.io:443/reviews/powershell/xsqlserver/888#-KwjdlqiTjRFMX4mxTan:-KwjdlqiTjRFMX4mxTao:b9io8dg) ([raw file](https://github.com/powershell/xsqlserver/blob/6a62ec4987b28f2452e604d83045da3e5ce93ef6/Tests/Unit/MSFT_xSQLServerReplication.Tests.ps1#L157)):*
> -be

Could you please change this to `-Be`.

---

*[Tests/Unit/MSFT_xSQLServerReplication.Tests.ps1, line 288 at r2](https://reviewable.io:443/reviews/powershell/xsqlserver/888#-KwjdnGnaDjInsw9fpFd:-KwjdnGnaDjInsw9fpFe:b9io8dg) ([raw file](https://github.com/powershell/xsqlserver/blob/6a62ec4987b28f2452e604d83045da3e5ce93ef6/Tests/Unit/MSFT_xSQLServerReplication.Tests.ps1#L288)):*
> -be

Could you please change this to `-Be`.

---

*[Tests/Unit/MSFT_xSQLServerReplication.Tests.ps1, line 421 at r2](https://reviewable.io:443/reviews/powershell/xsqlserver/888#-KwjdoNkurgOXnAJZ4Hp:-KwjdoNkurgOXnAJZ4Hq:b9io8dg) ([raw file](https://github.com/powershell/xsqlserver/blob/6a62ec4987b28f2452e604d83045da3e5ce93ef6/Tests/Unit/MSFT_xSQLServerReplication.Tests.ps1#L421)):*
> -be

Could you please change this to `-Be`.

---

*[Tests/Unit/MSFT_xSQLServerReplication.Tests.ps1, line 549 at r2](https://reviewable.io:443/reviews/powershell/xsqlserver/888#-KwjdplcSrTWpcIQy-Gh:-KwjdplcSrTWpcIQy-Gi:b9io8dg) ([raw file](https://github.com/powershell/xsqlserver/blob/6a62ec4987b28f2452e604d83045da3e5ce93ef6/Tests/Unit/MSFT_xSQLServerReplication.Tests.ps1#L549)):*
> -be

Could you please change this to `-Be`.

---

*[Tests/Unit/MSFT_xSQLServerReplication.Tests.ps1, line 676 at r2](https://reviewable.io:443/reviews/powershell/xsqlserver/888#-Kwjdr0ddNB0BK7hbpHB:-Kwjdr0eN3pVkg-8EWep:b9io8dg) ([raw file](https://github.com/powershell/xsqlserver/blob/6a62ec4987b28f2452e604d83045da3e5ce93ef6/Tests/Unit/MSFT_xSQLServerReplication.Tests.ps1#L676)):*
> -be

Could you please change this to `-Be`.

---

*[Tests/Unit/MSFT_xSQLServerReplication.Tests.ps1, line 806 at r2](https://reviewable.io:443/reviews/powershell/xsqlserver/888#-KwjdrgjNm52KCRpNhA4:-KwjdrgjNm52KCRpNhA5:b9io8dg) ([raw file](https://github.com/powershell/xsqlserver/blob/6a62ec4987b28f2452e604d83045da3e5ce93ef6/Tests/Unit/MSFT_xSQLServerReplication.Tests.ps1#L806)):*
> -be

Could you please change this to `-Be`.

---

*[Tests/Unit/MSFT_xSQLServerReplication.Tests.ps1, line 934 at r2](https://reviewable.io:443/reviews/powershell/xsqlserver/888#-KwjdslNWxFu3Tr0TdHL:-KwjdslNWxFu3Tr0TdHM:b9io8dg) ([raw file](https://github.com/powershell/xsqlserver/blob/6a62ec4987b28f2452e604d83045da3e5ce93ef6/Tests/Unit/MSFT_xSQLServerReplication.Tests.ps1#L934)):*
> -be

Could you please change this to `-Be`.

---

*[Tests/Unit/xSQLServerHelper.Tests.ps1, line 1507 at r2](https://reviewable.io:443/reviews/powershell/xsqlserver/888#-KwjfLlLbVPr9sl3WpdI:-KwjfLlLbVPr9sl3WpdJ:b-r2v9h2) ([raw file](https://github.com/powershell/xsqlserver/blob/6a62ec4987b28f2452e604d83045da3e5ce93ef6/Tests/Unit/xSQLServerHelper.Tests.ps1#L1507)):*
> -throw

Could you please change this to `-Throw`.

---

*[Tests/Unit/xSQLServerHelper.Tests.ps1, line 1511 at r2](https://reviewable.io:443/reviews/powershell/xsqlserver/888#-KwjfOwse6FswGkaXf8g:-KwjfOwse6FswGkaXf8h:b-r2v9h2) ([raw file](https://github.com/powershell/xsqlserver/blob/6a62ec4987b28f2452e604d83045da3e5ce93ef6/Tests/Unit/xSQLServerHelper.Tests.ps1#L1511)):*
> -throw

Could you please change this to `-Throw`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xsqlserver/888#-:-Kwjdukz20ihroSSBltE:bvkeum)*

**Comment by mnewswanger** [comment]
Review status: 29 of 34 files reviewed at latest revision, 16 unresolved discussions.

---

*[Tests/Unit/MSFT_xSQLServerAlwaysOnService.Tests.ps1, line 223 at r2](https://reviewable.io:443/reviews/powershell/xsqlserver/888#-KwjbeGdSoOx1atYr3mP:-KwjpP2RcINOXl8LcnvZ:b-896fix) ([raw file](https://github.com/powershell/xsqlserver/blob/6a62ec4987b28f2452e604d83045da3e5ce93ef6/Tests/Unit/MSFT_xSQLServerAlwaysOnService.Tests.ps1#L223)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

> -be

Could you please change this to `-Be`.
</blockquote></details>

Done.

---

*[Tests/Unit/MSFT_xSQLServerAlwaysOnService.Tests.ps1, line 235 at r2](https://reviewable.io:443/reviews/powershell/xsqlserver/888#-KwjbjuyVs9TgnqZ1sMR:-KwjpPuNp4aCVz2oXw_U:b-896fix) ([raw file](https://github.com/powershell/xsqlserver/blob/6a62ec4987b28f2452e604d83045da3e5ce93ef6/Tests/Unit/MSFT_xSQLServerAlwaysOnService.Tests.ps1#L235)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

> -be

Could you please change this to `-Be`.
</blockquote></details>

Done.

---

*[Tests/Unit/MSFT_xSQLServerConfiguration.Tests.ps1, line 199 at r2](https://reviewable.io:443/reviews/powershell/xsqlserver/888#-KwjbzEHjZdCG6vAHJEc:-KwjpR8OEnA8WWGjRu5k:b-896fix) ([raw file](https://github.com/powershell/xsqlserver/blob/6a62ec4987b28f2452e604d83045da3e5ce93ef6/Tests/Unit/MSFT_xSQLServerConfiguration.Tests.ps1#L199)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

> -be

Could you please change this to `-Be`.
</blockquote></details>

Done.

---

*[Tests/Unit/MSFT_xSQLServerConfiguration.Tests.ps1, line 203 at r2](https://reviewable.io:443/reviews/powershell/xsqlserver/888#-Kwjbzho4QJxTG_2CmJL:-KwjpRcfMjEyJyxag-aT:b-896fix) ([raw file](https://github.com/powershell/xsqlserver/blob/6a62ec4987b28f2452e604d83045da3e5ce93ef6/Tests/Unit/MSFT_xSQLServerConfiguration.Tests.ps1#L203)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

> -be

Could you please change this to `-Be`.
</blockquote></details>

Done.

---

*[Tests/Unit/MSFT_xSQLServerReplication.Tests.ps1, line 41 at r2](https://reviewable.io:443/reviews/powershell/xsqlserver/888#-KwjdhUYwogkbjiys_5x:-KwjpT3nj7MB5JlD_FbO:b-896fix) ([raw file](https://github.com/powershell/xsqlserver/blob/6a62ec4987b28f2452e604d83045da3e5ce93ef6/Tests/Unit/MSFT_xSQLServerReplication.Tests.ps1#L41)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

> -be

Could you please change this to `-Be`.
</blockquote></details>

Done.

---

*[Tests/Unit/MSFT_xSQLServerReplication.Tests.ps1, line 57 at r2](https://reviewable.io:443/reviews/powershell/xsqlserver/888#-KwjdjCr8spEbUQ4hv1F:-KwjpTb_Rk1VN1qhrtAu:b-896fix) ([raw file](https://github.com/powershell/xsqlserver/blob/6a62ec4987b28f2452e604d83045da3e5ce93ef6/Tests/Unit/MSFT_xSQLServerReplication.Tests.ps1#L57)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

> -be

Could you please change this to `-Be`.
</blockquote></details>

Done.

---

*[Tests/Unit/MSFT_xSQLServerReplication.Tests.ps1, line 61 at r2](https://reviewable.io:443/reviews/powershell/xsqlserver/888#-KwjdjkH_o9pWgOubnKb:-KwjpUVrFgO_BR309maX:b-896fix) ([raw file](https://github.com/powershell/xsqlserver/blob/6a62ec4987b28f2452e604d83045da3e5ce93ef6/Tests/Unit/MSFT_xSQLServerReplication.Tests.ps1#L61)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

> -be

Could you please change this to `-Be`.
</blockquote></details>

Done.

---

*[Tests/Unit/MSFT_xSQLServerReplication.Tests.ps1, line 157 at r2](https://reviewable.io:443/reviews/powershell/xsqlserver/888#-KwjdlqiTjRFMX4mxTan:-KwjpUzOKyVS4egAfdgD:b-896fix) ([raw file](https://github.com/powershell/xsqlserver/blob/6a62ec4987b28f2452e604d83045da3e5ce93ef6/Tests/Unit/MSFT_xSQLServerReplication.Tests.ps1#L157)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

> -be

Could you please change this to `-Be`.
</blockquote></details>

Done.

---

*[Tests/Unit/MSFT_xSQLServerReplication.Tests.ps1, line 288 at r2](https://reviewable.io:443/reviews/powershell/xsqlserver/888#-KwjdnGnaDjInsw9fpFd:-KwjpVV3X7ZuJhK7QDav:b-896fix) ([raw file](https://github.com/powershell/xsqlserver/blob/6a62ec4987b28f2452e604d83045da3e5ce93ef6/Tests/Unit/MSFT_xSQLServerReplication.Tests.ps1#L288)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

> -be

Could you please change this to `-Be`.
</blockquote></details>

Done.

---

*[Tests/Unit/MSFT_xSQLServerReplication.Tests.ps1, line 421 at r2](https://reviewable.io:443/reviews/powershell/xsqlserver/888#-KwjdoNkurgOXnAJZ4Hp:-KwjpVubdug__8LvMC_Y:b-896fix) ([raw file](https://github.com/powershell/xsqlserver/blob/6a62ec4987b28f2452e604d83045da3e5ce93ef6/Tests/Unit/MSFT_xSQLServerReplication.Tests.ps1#L421)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

> -be

Could you please change this to `-Be`.
</blockquote></details>

Done.

---

*[Tests/Unit/MSFT_xSQLServerReplication.Tests.ps1, line 549 at r2](https://reviewable.io:443/reviews/powershell/xsqlserver/888#-KwjdplcSrTWpcIQy-Gh:-KwjpWMWTqKvurHpmmcJ:b-896fix) ([raw file](https://github.com/powershell/xsqlserver/blob/6a62ec4987b28f2452e604d83045da3e5ce93ef6/Tests/Unit/MSFT_xSQLServerReplication.Tests.ps1#L549)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

> -be

Could you please change this to `-Be`.
</blockquote></details>

Done.

---

*[Tests/Unit/MSFT_xSQLServerReplication.Tests.ps1, line 676 at r2](https://reviewable.io:443/reviews/powershell/xsqlserver/888#-Kwjdr0ddNB0BK7hbpHB:-KwjpWql7CcgxceHXOPG:b-896fix) ([raw file](https://github.com/powershell/xsqlserver/blob/6a62ec4987b28f2452e604d83045da3e5ce93ef6/Tests/Unit/MSFT_xSQLServerReplication.Tests.ps1#L676)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

> -be

Could you please change this to `-Be`.
</blockquote></details>

Done.

---

*[Tests/Unit/MSFT_xSQLServerReplication.Tests.ps1, line 806 at r2](https://reviewable.io:443/reviews/powershell/xsqlserver/888#-KwjdrgjNm52KCRpNhA4:-KwjpXUS5_EJ-CEiaBeA:b-896fix) ([raw file](https://github.com/powershell/xsqlserver/blob/6a62ec4987b28f2452e604d83045da3e5ce93ef6/Tests/Unit/MSFT_xSQLServerReplication.Tests.ps1#L806)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

> -be

Could you please change this to `-Be`.
</blockquote></details>

Done.

---

*[Tests/Unit/MSFT_xSQLServerReplication.Tests.ps1, line 934 at r2](https://reviewable.io:443/reviews/powershell/xsqlserver/888#-KwjdslNWxFu3Tr0TdHL:-KwjpY9C7idrFJDfdvB0:b-896fix) ([raw file](https://github.com/powershell/xsqlserver/blob/6a62ec4987b28f2452e604d83045da3e5ce93ef6/Tests/Unit/MSFT_xSQLServerReplication.Tests.ps1#L934)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

> -be

Could you please change this to `-Be`.
</blockquote></details>

Done.

---

*[Tests/Unit/xSQLServerHelper.Tests.ps1, line 1507 at r2](https://reviewable.io:443/reviews/powershell/xsqlserver/888#-KwjfLlLbVPr9sl3WpdI:-Kwjp_UPVOU254Xu07sd:b-896fix) ([raw file](https://github.com/powershell/xsqlserver/blob/6a62ec4987b28f2452e604d83045da3e5ce93ef6/Tests/Unit/xSQLServerHelper.Tests.ps1#L1507)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

> -throw

Could you please change this to `-Throw`.
</blockquote></details>

Done.

---

*[Tests/Unit/xSQLServerHelper.Tests.ps1, line 1511 at r2](https://reviewable.io:443/reviews/powershell/xsqlserver/888#-KwjfOwse6FswGkaXf8g:-KwjpaAud-hPPibVWtI_:b-896fix) ([raw file](https://github.com/powershell/xsqlserver/blob/6a62ec4987b28f2452e604d83045da3e5ce93ef6/Tests/Unit/xSQLServerHelper.Tests.ps1#L1511)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

> -throw

Could you please change this to `-Throw`.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xsqlserver/888)*

**Comment by johlju** [comment]
:lgtm:

---

Reviewed 5 of 5 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xsqlserver/888#-:-KwjzOdbzh46VuGDK4dn:bnfp4nl)*

**Comment by johlju** [comment]
Ah, was to quick there. Just one more comment, then we are done. Saw it when I was about to merge. 

---

Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[CHANGELOG.md, line 6 at r3](https://reviewable.io:443/reviews/powershell/xsqlserver/888#-KwjzmTlcgT72Qp1c7k5:-KwjzmTlcgT72Qp1c7k6:bkgvfdr) ([raw file](https://github.com/powershell/xsqlserver/blob/5f2035cdffcd37e77ab7f8f148c2706a3e160e40/CHANGELOG.md#L6)):*
> ```Markdown
> 
> - Changes to xSQLServer
>   - Updated Pester command flags to v4
> ```

I missed this one. :/ 
Could we change this to `Update Pester syntax to v4.` as well (as you did in the xFailOverCluster  module).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xsqlserver/888#-:-KwjzyvcnD66dHY0k25U:bsgxw2m)*

**Comment by mnewswanger** [comment]
Review status: 33 of 34 files reviewed at latest revision, 1 unresolved discussion.

---

*[CHANGELOG.md, line 6 at r3](https://reviewable.io:443/reviews/powershell/xsqlserver/888#-KwjzmTlcgT72Qp1c7k5:-Kwk6nmpJKmNbfPUKfSf:b-896fix) ([raw file](https://github.com/powershell/xsqlserver/blob/5f2035cdffcd37e77ab7f8f148c2706a3e160e40/CHANGELOG.md#L6)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

I missed this one. :/ 
Could we change this to `Update Pester syntax to v4.` as well (as you did in the xFailOverCluster  module).
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xsqlserver/888)*

**Comment by johlju** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xsqlserver/888#-:-Kwk8iHDoei-y-VTA-u2:bnfp4nl)*

**Pull request merged**
