### PR TITLE
xSQLServerSetup: Adds a simple integration test

### LINKED ISSUE #709: xSQLServerSetup: Add a simple integration test
**Details of the scenario you tried and the problem that is occurring:**
To start off somewhere, with integration tests, I'm working on a simple integration test for this resource. I call it simple, because this resource has a lot of aspects when looking at integration tests, and some are limited to what we can do in AppVeyor. But the more complex integration test scenarios should be able to run locally on multiple servers. 
But let's create separate issues per integration test scenario, and keep this first one to a simple local single server install.

**The DSC configuration that is using the resource (as detailed as possible):**
n/a

**Version of the Operating System, SQL Server and PowerShell the DSC Target Node is running:**
n/a

**What module (SqlServer or SQLPS) and which version of the module the DSC Target Node is running:**
n/a

**Version of the DSC module you're using, or 'dev' if you're using current dev branch:**
Dev

### PR DESCRIPTION
**Pull request by johlju**
**Pull Request (PR) description**
- Changes to xSQLServerSetup
  - Added a simple integration test (issue #709).

**This Pull Request (PR) fixes the following issues:**
Fixes #709 

**Task list:**

- [x] Change details added to Unreleased section of CHANGELOG.md?
- [ ] Added/updated documentation, comment-based help and descriptions in .schema.mof files where appropriate?
- [ ] Examples appropriately updated?
- [x] New/changed code adheres to [Style Guidelines](https://github.com/PowerShell/DscResources/blob/master/StyleGuidelines.md)?
- [x] [Unit and (optional) Integration tests](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md) created/updated where possible?

---
This change is [Reviewable](https://reviewable.io/reviews/powershell/xsqlserver/710)

### CODE REVIEW

**Comment by johlju** [comment]
@PlagueHO would you mind review this one? This is the first integration test I make, so would be nice to have your eyes on it, to see if there is anything that can be improved. 😄

**Comment by johlju** [comment]
@PlagueHO is it possible to control the order the integration tests are run? If possible I would like this integration to run first, and after that i will run other integration tests that is dependent on that SQL Server is installed. If it is not possible to control the order these are run, then one way is to use this tests config file as the base for all config files, so the SQL Server is always installed if it has not been installed in a test prior to this test. But then I lose logic that this test uses to help determine what went wrong during install (outputing the summary log), since there is a chance this was not run as the first integration test.

**Comment by johlju** [comment]
@PlagueHO do you think you have a chance to look this over? You don't need to do a full review (if you don't want to). I'm mostly looking if I made a mistake or something can be improved. First time doing this for me 😄

**Comment by PlagueHO** [comment]
Just some minor style tweaks. Awesome you got integration tests going in xSQLServer - that is very awesome! How long does the ISO take to download? Hope AppVeyor provides some sort of file caching service :grin:

---

Reviewed 1 of 3 files at r1, 1 of 2 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 12 unresolved discussions.

---

*[Tests/Integration/MSFT_xSQLServerSetup.config.ps1, line 48 at r3](https://reviewable.io:443/reviews/powershell/xsqlserver/710#-KrKy6l4xCUCJhISPje_:-KrKy6l4xCUCJhISPjea:b-pimhxg) ([raw file](https://github.com/powershell/xsqlserver/blob/17f4206d7d15a678b46e8bd23c043777d4685ad6/Tests/Integration/MSFT_xSQLServerSetup.config.ps1#L48)):*
> ```PowerShell
>         {
>             Ensure   = 'Present'
>             UserName = Split-Path $mockSqlServiceCredential.UserName -Leaf
> ```

Should be a named `-path` parameter

---

*[Tests/Integration/MSFT_xSQLServerSetup.config.ps1, line 55 at r3](https://reviewable.io:443/reviews/powershell/xsqlserver/710#-KrKyEKqbAY1iXzVbI45:-KrKyEKqbAY1iXzVbI46:b-pimhxg) ([raw file](https://github.com/powershell/xsqlserver/blob/17f4206d7d15a678b46e8bd23c043777d4685ad6/Tests/Integration/MSFT_xSQLServerSetup.config.ps1#L55)):*
> ```PowerShell
>         {
>             Ensure   = 'Present'
>             UserName = Split-Path $SqlAgentServiceCredential.UserName -Leaf
> ```

Should be a named `-path` parameter

---

*[Tests/Integration/MSFT_xSQLServerSetup.config.ps1, line 62 at r3](https://reviewable.io:443/reviews/powershell/xsqlserver/710#-KrKyEgsI2ITt0StaqpN:-KrKyEgsI2ITt0StaqpO:b-pimhxg) ([raw file](https://github.com/powershell/xsqlserver/blob/17f4206d7d15a678b46e8bd23c043777d4685ad6/Tests/Integration/MSFT_xSQLServerSetup.config.ps1#L62)):*
> ```PowerShell
>         {
>             Ensure   = 'Present'
>             UserName = Split-Path $SqlInstallCredential.UserName -Leaf
> ```

Should be a named `-path` parameter

---

*[Tests/Integration/MSFT_xSQLServerSetup.config.ps1, line 69 at r3](https://reviewable.io:443/reviews/powershell/xsqlserver/710#-KrKyFBjH_ncsnuH4dwT:-KrKyFBjH_ncsnuH4dwU:b-pimhxg) ([raw file](https://github.com/powershell/xsqlserver/blob/17f4206d7d15a678b46e8bd23c043777d4685ad6/Tests/Integration/MSFT_xSQLServerSetup.config.ps1#L69)):*
> ```PowerShell
>         {
>             Ensure   = 'Present'
>             UserName = Split-Path $SqlAdministratorCredential.UserName -Leaf
> ```

Should be a named `-path` parameter

---

*[Tests/Integration/MSFT_xSQLServerSetup.Integration.Tests.ps1, line 43 at r3](https://reviewable.io:443/reviews/powershell/xsqlserver/710#-KrKyXyyoVP9aqY0Yjux:-KrKyXyyoVP9aqY0Yjuy:b-4vt2qu) ([raw file](https://github.com/powershell/xsqlserver/blob/17f4206d7d15a678b46e8bd23c043777d4685ad6/Tests/Integration/MSFT_xSQLServerSetup.Integration.Tests.ps1#L43)):*
> ```PowerShell
> $mockIsoMediaDriveLetter = [char](([int][char]$mockLastDrive) + 1)
> 
> $mockSqlInstallAccountPassword = ConvertTo-SecureString 'P@ssw0rd1' -AsPlainText -Force
> ```

Positional parameter should be named parameter.

---

*[Tests/Integration/MSFT_xSQLServerSetup.Integration.Tests.ps1, line 47 at r3](https://reviewable.io:443/reviews/powershell/xsqlserver/710#-KrKy_zRJzs4aEkXuLKH:-KrKy_zS7OevOIyF4ybf:b-4vt2qu) ([raw file](https://github.com/powershell/xsqlserver/blob/17f4206d7d15a678b46e8bd23c043777d4685ad6/Tests/Integration/MSFT_xSQLServerSetup.Integration.Tests.ps1#L47)):*
> ```PowerShell
> $mockSqlInstallCredential = New-Object -TypeName System.Management.Automation.PSCredential -ArgumentList $mockSqlInstallAccountUserName, $mockSqlInstallAccountPassword
> 
> $mockSqlAdminAccountPassword = ConvertTo-SecureString 'P@ssw0rd1' -AsPlainText -Force
> ```

Positional parameter should be named parameter.

---

*[Tests/Integration/MSFT_xSQLServerSetup.Integration.Tests.ps1, line 51 at r3](https://reviewable.io:443/reviews/powershell/xsqlserver/710#-KrKyaW_ew2oVWlWZcYR:-KrKyaW_ew2oVWlWZcYS:b-4vt2qu) ([raw file](https://github.com/powershell/xsqlserver/blob/17f4206d7d15a678b46e8bd23c043777d4685ad6/Tests/Integration/MSFT_xSQLServerSetup.Integration.Tests.ps1#L51)):*
> ```PowerShell
> $mockSqlAdminCredential = New-Object -TypeName System.Management.Automation.PSCredential -ArgumentList $mockSqlAdminAccountUserName, $mockSqlAdminAccountPassword
> 
> $mockSqlServiceAccountPassword = ConvertTo-SecureString 'yig-C^Equ3' -AsPlainText -Force
> ```

Positional parameter should be named parameter.

---

*[Tests/Integration/MSFT_xSQLServerSetup.Integration.Tests.ps1, line 55 at r3](https://reviewable.io:443/reviews/powershell/xsqlserver/710#-KrKybFkYlLGgSSjv_Jf:-KrKybFkYlLGgSSjv_Jg:b-4vt2qu) ([raw file](https://github.com/powershell/xsqlserver/blob/17f4206d7d15a678b46e8bd23c043777d4685ad6/Tests/Integration/MSFT_xSQLServerSetup.Integration.Tests.ps1#L55)):*
> ```PowerShell
> $mockSqlServiceCredential = New-Object -TypeName System.Management.Automation.PSCredential -ArgumentList $mockSqlServiceAccountUserName, $mockSqlServiceAccountPassword
> 
> $mockSqlAgentServiceAccountPassword = ConvertTo-SecureString 'yig-C^Equ3' -AsPlainText -Force
> ```

Positional parameter should be named parameter.

---

*[Tests/Integration/MSFT_xSQLServerSetup.Integration.Tests.ps1, line 62 at r3](https://reviewable.io:443/reviews/powershell/xsqlserver/710#-KrKysZAwWm9RhYl-ReU:-KrKysZAwWm9RhYl-ReV:b-4vt2qu) ([raw file](https://github.com/powershell/xsqlserver/blob/17f4206d7d15a678b46e8bd23c043777d4685ad6/Tests/Integration/MSFT_xSQLServerSetup.Integration.Tests.ps1#L62)):*
> ```PowerShell
> if (-not (Test-Path -Path $mockIsoMediaFilePath))
> {
>     Write-Verbose "Start downloading the SQL Server media iso at $(Get-Date -Format 'yyyy-MM-dd hh:mm:ss')" -Verbose
> ```

Positional parameter should be named parameter.

---

*[Tests/Integration/MSFT_xSQLServerSetup.Integration.Tests.ps1, line 64 at r3](https://reviewable.io:443/reviews/powershell/xsqlserver/710#-KrKyssE1kq0KwgqFpKi:-KrKyssE1kq0KwgqFpKj:b-4vt2qu) ([raw file](https://github.com/powershell/xsqlserver/blob/17f4206d7d15a678b46e8bd23c043777d4685ad6/Tests/Integration/MSFT_xSQLServerSetup.Integration.Tests.ps1#L64)):*
> ```PowerShell
>     Write-Verbose "Start downloading the SQL Server media iso at $(Get-Date -Format 'yyyy-MM-dd hh:mm:ss')" -Verbose
> 
>     Invoke-WebRequest $mockSourceMediaUrl -OutFile $mockIsoMediaFilePath
> ```

Positional parameter should be named parameter.

---

*[Tests/Integration/MSFT_xSQLServerSetup.Integration.Tests.ps1, line 74 at r3](https://reviewable.io:443/reviews/powershell/xsqlserver/710#-KrKyqhVro1XSAJfJcej:-KrKyqhVro1XSAJfJcek:b-4vt2qu) ([raw file](https://github.com/powershell/xsqlserver/blob/17f4206d7d15a678b46e8bd23c043777d4685ad6/Tests/Integration/MSFT_xSQLServerSetup.Integration.Tests.ps1#L74)):*
> ```PowerShell
>     else
>     {
>         Write-Verbose "Finished downloading the SQL Server media iso at $(Get-Date -Format 'yyyy-MM-dd hh:mm:ss')" -Verbose
> ```

Positional parameter should be named parameter.

---

*[Tests/Integration/MSFT_xSQLServerSetup.Integration.Tests.ps1, line 79 at r3](https://reviewable.io:443/reviews/powershell/xsqlserver/710#-KrKypZUrUdqWooSRSi9:-KrKypZUrUdqWooSRSiA:b-4vt2qu) ([raw file](https://github.com/powershell/xsqlserver/blob/17f4206d7d15a678b46e8bd23c043777d4685ad6/Tests/Integration/MSFT_xSQLServerSetup.Integration.Tests.ps1#L79)):*
> ```PowerShell
> else
> {
>     Write-Verbose 'SQL Server media is already downloaded' -Verbose
> ```

Positional parameter should be named parameter.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xsqlserver/710#-:-KrKzRu2V4kECfcgcsOi:b-xtqhhq)*

**Comment by johlju** [comment]
File download speed was the first thing I tested. If this was even possible. When I got a download in ~40 seconds I thought something went wrong. But no. It actually downloaded so fast. Either cached or there is a CDN in the same same datacenter. :smile: I still log the time to see if this change over time. But at most I got 2 minutes to download the iso.
Impressive! :heart_eyes: 

Strange that I used a lot of positional parameters in this one. :laughing: 

---

Review status: 1 of 3 files reviewed at latest revision, 12 unresolved discussions.

---

*[Tests/Integration/MSFT_xSQLServerSetup.config.ps1, line 48 at r3](https://reviewable.io:443/reviews/powershell/xsqlserver/710#-KrKy6l4xCUCJhISPje_:-KrL28V4eHDVgk2eIwlV:b-896fix) ([raw file](https://github.com/powershell/xsqlserver/blob/17f4206d7d15a678b46e8bd23c043777d4685ad6/Tests/Integration/MSFT_xSQLServerSetup.config.ps1#L48)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

Should be a named `-path` parameter
</blockquote></details>

Done.

---

*[Tests/Integration/MSFT_xSQLServerSetup.config.ps1, line 55 at r3](https://reviewable.io:443/reviews/powershell/xsqlserver/710#-KrKyEKqbAY1iXzVbI45:-KrL281UzPvvVB5YCQX4:b-896fix) ([raw file](https://github.com/powershell/xsqlserver/blob/17f4206d7d15a678b46e8bd23c043777d4685ad6/Tests/Integration/MSFT_xSQLServerSetup.config.ps1#L55)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

Should be a named `-path` parameter
</blockquote></details>

Done.

---

*[Tests/Integration/MSFT_xSQLServerSetup.config.ps1, line 62 at r3](https://reviewable.io:443/reviews/powershell/xsqlserver/710#-KrKyEgsI2ITt0StaqpN:-KrL29Hnk3zeNjIbiK_n:b-896fix) ([raw file](https://github.com/powershell/xsqlserver/blob/17f4206d7d15a678b46e8bd23c043777d4685ad6/Tests/Integration/MSFT_xSQLServerSetup.config.ps1#L62)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

Should be a named `-path` parameter
</blockquote></details>

Done.

---

*[Tests/Integration/MSFT_xSQLServerSetup.config.ps1, line 69 at r3](https://reviewable.io:443/reviews/powershell/xsqlserver/710#-KrKyFBjH_ncsnuH4dwT:-KrL29oy-fUIdRR410ud:b-896fix) ([raw file](https://github.com/powershell/xsqlserver/blob/17f4206d7d15a678b46e8bd23c043777d4685ad6/Tests/Integration/MSFT_xSQLServerSetup.config.ps1#L69)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

Should be a named `-path` parameter
</blockquote></details>

Done.

---

*[Tests/Integration/MSFT_xSQLServerSetup.Integration.Tests.ps1, line 43 at r3](https://reviewable.io:443/reviews/powershell/xsqlserver/710#-KrKyXyyoVP9aqY0Yjux:-KrL2ArSRsR_5SuYe2AO:b-896fix) ([raw file](https://github.com/powershell/xsqlserver/blob/17f4206d7d15a678b46e8bd23c043777d4685ad6/Tests/Integration/MSFT_xSQLServerSetup.Integration.Tests.ps1#L43)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

Positional parameter should be named parameter.
</blockquote></details>

Done.

---

*[Tests/Integration/MSFT_xSQLServerSetup.Integration.Tests.ps1, line 47 at r3](https://reviewable.io:443/reviews/powershell/xsqlserver/710#-KrKy_zRJzs4aEkXuLKH:-KrL2Bj7grF0FLfI2En6:b-896fix) ([raw file](https://github.com/powershell/xsqlserver/blob/17f4206d7d15a678b46e8bd23c043777d4685ad6/Tests/Integration/MSFT_xSQLServerSetup.Integration.Tests.ps1#L47)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

Positional parameter should be named parameter.
</blockquote></details>

Done.

---

*[Tests/Integration/MSFT_xSQLServerSetup.Integration.Tests.ps1, line 51 at r3](https://reviewable.io:443/reviews/powershell/xsqlserver/710#-KrKyaW_ew2oVWlWZcYR:-KrL2C83jeG-SHpA7Iky:b-896fix) ([raw file](https://github.com/powershell/xsqlserver/blob/17f4206d7d15a678b46e8bd23c043777d4685ad6/Tests/Integration/MSFT_xSQLServerSetup.Integration.Tests.ps1#L51)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

Positional parameter should be named parameter.
</blockquote></details>

Done.

---

*[Tests/Integration/MSFT_xSQLServerSetup.Integration.Tests.ps1, line 55 at r3](https://reviewable.io:443/reviews/powershell/xsqlserver/710#-KrKybFkYlLGgSSjv_Jf:-KrL2CdUXxMEyni52VCR:b-896fix) ([raw file](https://github.com/powershell/xsqlserver/blob/17f4206d7d15a678b46e8bd23c043777d4685ad6/Tests/Integration/MSFT_xSQLServerSetup.Integration.Tests.ps1#L55)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

Positional parameter should be named parameter.
</blockquote></details>

Done.

---

*[Tests/Integration/MSFT_xSQLServerSetup.Integration.Tests.ps1, line 62 at r3](https://reviewable.io:443/reviews/powershell/xsqlserver/710#-KrKysZAwWm9RhYl-ReU:-KrL2DKi-WfC5oNJvZeB:b-896fix) ([raw file](https://github.com/powershell/xsqlserver/blob/17f4206d7d15a678b46e8bd23c043777d4685ad6/Tests/Integration/MSFT_xSQLServerSetup.Integration.Tests.ps1#L62)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

Positional parameter should be named parameter.
</blockquote></details>

Done.

---

*[Tests/Integration/MSFT_xSQLServerSetup.Integration.Tests.ps1, line 64 at r3](https://reviewable.io:443/reviews/powershell/xsqlserver/710#-KrKyssE1kq0KwgqFpKi:-KrL2E2jDGAEsXpPAX89:b-896fix) ([raw file](https://github.com/powershell/xsqlserver/blob/17f4206d7d15a678b46e8bd23c043777d4685ad6/Tests/Integration/MSFT_xSQLServerSetup.Integration.Tests.ps1#L64)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

Positional parameter should be named parameter.
</blockquote></details>

Done.

---

*[Tests/Integration/MSFT_xSQLServerSetup.Integration.Tests.ps1, line 74 at r3](https://reviewable.io:443/reviews/powershell/xsqlserver/710#-KrKyqhVro1XSAJfJcej:-KrL2EbByf0_tPf-3ohJ:b-896fix) ([raw file](https://github.com/powershell/xsqlserver/blob/17f4206d7d15a678b46e8bd23c043777d4685ad6/Tests/Integration/MSFT_xSQLServerSetup.Integration.Tests.ps1#L74)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

Positional parameter should be named parameter.
</blockquote></details>

Done.

---

*[Tests/Integration/MSFT_xSQLServerSetup.Integration.Tests.ps1, line 79 at r3](https://reviewable.io:443/reviews/powershell/xsqlserver/710#-KrKypZUrUdqWooSRSi9:-KrL2FWHcvGsZnzu_KFF:b-896fix) ([raw file](https://github.com/powershell/xsqlserver/blob/17f4206d7d15a678b46e8bd23c043777d4685ad6/Tests/Integration/MSFT_xSQLServerSetup.Integration.Tests.ps1#L79)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

Positional parameter should be named parameter.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xsqlserver/710#-:-KrL0lBomkQXOY69B_1A:bppruq6)*

**Comment by PlagueHO** [comment]
:lgtm:

Awesome about the speed! AppVeyor does provide a build cache service too that might help - but it only caches 1GB of files in free version: https://www.appveyor.com/docs/build-cache/

---

Reviewed 2 of 2 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xsqlserver/710#-:-KrL5gmEujj44qNYAGO-:bgkvtkg)*

**Pull request merged**
