### PR TITLE
Split README.md so the change log is in a new Changelog.md file (Fixes #189)

### LINKED ISSUE #189: FeedBack - Split ReadMe and ChangeLog in two separate files
What do you think of the splitting of readme and changelog in two .md files ?
We can also put the detail of resources in a new file ?

Suggested PR #190

### PR DESCRIPTION
**Pull request by luigilink**
Fixes #189 

Add Changelog.md file

- [x] Change details added to Unreleased section of changelog.md?
- [x] Added/updated documentation and descriptions in .schema.mof files where appropriate?
- [x] Examples appropriately updated?
- [x] New/changed code adheres to [Style Guidelines]?(https://github.com/PowerShell/DscResources/blob/master/StyleGuidelines.md)?
- [x] [Unit and Integration tests](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md) created/updated where possible?

---
This change is [Reviewable](https://reviewable.io/reviews/powershell/xsqlserver/190)

### CODE REVIEW

**Comment by johlju** [comment]
@luigilink I'm waiting for a word from @kwirkykat in issue #189 that this will just work when she does releases, or if they she has to change something in her end as well.

_I do think we have touch this subject before, several months back, but I can't find where though._

**Comment by johlju** [comment]
Unless I hear something different from @kwirkykat by Tuesday I will review and merge this.

**Comment by johlju** [comment]
Reviewed 1 of 2 files at r1.
Review status: 1 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[README.md, line 372 at r1](https://reviewable.io:443/reviews/powershell/xsqlserver/190#-KX1HCwqgpUSG9GkV4Bh:-KX1HCwqgpUSG9GkV4Bi:bo1hyg9) ([raw file](https://github.com/powershell/xsqlserver/blob/624004b53ba9bc91e3fc818e8358bae1726e568d/README.md#L372)):*
> ```Markdown
> ## Examples
> 
> Examples for use of this resource can be found with the System Center resources, such as **xSCVMM**, **xSCSMA**, and **xSCOM**.
> ```

This is and old text and is no longer correct.
I think we should replace this to something that say that the examples can be found in the Examples folder. What do you say? 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xsqlserver/190)*

**Comment by luigilink** [comment]
Reviewed 1 of 2 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[README.md, line 372 at r1](https://reviewable.io:443/reviews/powershell/xsqlserver/190#-KX1HCwqgpUSG9GkV4Bh:-KX2Mq2eWRj8-CG6tJ7K:b-896fix) ([raw file](https://github.com/powershell/xsqlserver/blob/624004b53ba9bc91e3fc818e8358bae1726e568d/README.md#L372)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary>
> This is and old text and is no longer correct.
> I think we should replace this to something that say that the examples can be found in the Examples folder. What do you say? 
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xsqlserver/190)*

**Comment by luigilink** [comment]
Reviewed 2 of 2 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xsqlserver/190)*

**Comment by johlju** [comment]
Could you rebase this one, at least by tomorrow?

I will review and merge this tomorrow evening.

**Comment by luigilink** [comment]
When you can my friend :smile_cat: 

---

Reviewed 2 of 2 files at r4.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[README.md, line 372 at r1](https://reviewable.io:443/reviews/powershell/xsqlserver/190#-KX1HCwqgpUSG9GkV4Bh:-KX7OsmTGwPys6GLc4PY:b-896fix) ([raw file](https://github.com/powershell/xsqlserver/blob/624004b53ba9bc91e3fc818e8358bae1726e568d/README.md#L372)):*
<details><summary><i>Previously, luigilink (Jean-Cyril Drouhin) wrote…</i></summary>
> Done.
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xsqlserver/190#-:-KX7OgrstdyOj0jcklDw:b2u51d7)*

**Comment by johlju** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r4.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xsqlserver/190#-:-KX9snJnO9FfigLxFrrv:bnfp4nl)*

**Pull request merged**
