### PR TITLE
new resource xSqlServerReplication

### PR DESCRIPTION
**Pull request by Arturas-K**
Created new resource to manage replication configuration.
Supports local and remote distribution.
Supports removing replication configuration.

---
This change is [Reviewable](https://reviewable.io/reviews/powershell/xsqlserver/66)

### CODE REVIEW

**Comment by Arturas-K** [comment]
Hi,

I would appreciate any review feedback on this pull request.

**Comment by Arturas-K** [comment]
@PowerShellTeam can someone have a look at this PR.

**Comment by mbreakey3** [comment]
Reviewed 3 of 8 files at r1.
Review status: 3 of 8 files reviewed at latest revision, 6 unresolved discussions.

---

*[DSCResources/xSQLServerReplication/xSQLServerReplication.psm1, line 3 \[r1\]](https://reviewable.io:443/reviews/powershell/xsqlserver/66#-KNdb58XRn6avjTd0oQ2:-KNdb58XRn6avjTd0oQ3:-846594310) ([raw file](https://github.com/powershell/xsqlserver/blob/c3f9066d44f8d0cb980b1e09f8bb1b999122b768/DSCResources/xSQLServerReplication/xSQLServerReplication.psm1#L3)):*
> ```PowerShell
> $dom = [AppDomain]::CreateDomain('xSQLServerReplication')
> 
> Function Get-TargetResource
> ```

lowercase: 'function'

---

*[DSCResources/xSQLServerReplication/xSQLServerReplication.psm1, line 86 \[r1\]](https://reviewable.io:443/reviews/powershell/xsqlserver/66#-KNdbXNJTVEHrwe6AXka:-KNdbXNKwd65O8cXyecK:-725568547) ([raw file](https://github.com/powershell/xsqlserver/blob/c3f9066d44f8d0cb980b1e09f8bb1b999122b768/DSCResources/xSQLServerReplication/xSQLServerReplication.psm1#L86)):*
> ```PowerShell
> }
> 
> Function Set-TargetResource
> ```

function

---

*[DSCResources/xSQLServerReplication/xSQLServerReplication.psm1, line 124 \[r1\]](https://reviewable.io:443/reviews/powershell/xsqlserver/66#-KNdbeDr8GidMn5e9RuP:-KNdbeDr8GidMn5e9RuQ:1363082592) ([raw file](https://github.com/powershell/xsqlserver/blob/c3f9066d44f8d0cb980b1e09f8bb1b999122b768/DSCResources/xSQLServerReplication/xSQLServerReplication.psm1#L124)):*
> ```PowerShell
>     )
> 
>     if($DistributorMode -eq 'Remote' -and !$RemoteDistributor)
> ```

space after pipe: '-and | $RemoteDistributor'

---

*[DSCResources/xSQLServerReplication/xSQLServerReplication.psm1, line 185 \[r1\]](https://reviewable.io:443/reviews/powershell/xsqlserver/66#-KNdbvHqNe-5lOSNiSj-:-KNdbvHqNe-5lOSNiSj0:-725568547) ([raw file](https://github.com/powershell/xsqlserver/blob/c3f9066d44f8d0cb980b1e09f8bb1b999122b768/DSCResources/xSQLServerReplication/xSQLServerReplication.psm1#L185)):*
> ```PowerShell
> }
> 
> Function Test-TargetResource
> ```

function

---

*[DSCResources/xSQLServerReplication/xSQLServerReplication.psm1, line 240 \[r1\]](https://reviewable.io:443/reviews/powershell/xsqlserver/66#-KNdc4ya9uWuI0ngkRvG:-KNdc4ya9uWuI0ngkRvH:-725568547) ([raw file](https://github.com/powershell/xsqlserver/blob/c3f9066d44f8d0cb980b1e09f8bb1b999122b768/DSCResources/xSQLServerReplication/xSQLServerReplication.psm1#L240)):*
> ```PowerShell
> 
> #region helper functions
> Function Get-SqlServerMajorVersion
> ```

function

---

*[DSCResources/xSQLServerReplication/xSQLServerReplication.psm1, line 260 \[r1\]](https://reviewable.io:443/reviews/powershell/xsqlserver/66#-KNdc6RWXWXDADP-xw7y:-KNdc6RWXWXDADP-xw7z:-725568547) ([raw file](https://github.com/powershell/xsqlserver/blob/c3f9066d44f8d0cb980b1e09f8bb1b999122b768/DSCResources/xSQLServerReplication/xSQLServerReplication.psm1#L260)):*
> ```PowerShell
> }
> 
> Function Get-SqlLocalServerName
> ```

function

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xsqlserver/66)*

**Comment by Arturas-K** [comment]
Review status: 3 of 8 files reviewed at latest revision, 6 unresolved discussions.

---

*[DSCResources/xSQLServerReplication/xSQLServerReplication.psm1, line 3 \[r1\]](https://reviewable.io:443/reviews/powershell/xsqlserver/66#-KNdb58XRn6avjTd0oQ2:-KNhtYPEGBUHdht7jzEs:-499146009) ([raw file](https://github.com/powershell/xsqlserver/blob/c3f9066d44f8d0cb980b1e09f8bb1b999122b768/DSCResources/xSQLServerReplication/xSQLServerReplication.psm1#L3)):*
<details><summary><i>Previously, mbreakey3 (Mariah) wrote…</i></summary>
> lowercase: 'function'
</details>
Done.

---

*[DSCResources/xSQLServerReplication/xSQLServerReplication.psm1, line 86 \[r1\]](https://reviewable.io:443/reviews/powershell/xsqlserver/66#-KNdbXNJTVEHrwe6AXka:-KNhtZjOu__uZwcp4R3-:-499146009) ([raw file](https://github.com/powershell/xsqlserver/blob/c3f9066d44f8d0cb980b1e09f8bb1b999122b768/DSCResources/xSQLServerReplication/xSQLServerReplication.psm1#L86)):*
<details><summary><i>Previously, mbreakey3 (Mariah) wrote…</i></summary>
> function
</details>
Done.

---

*[DSCResources/xSQLServerReplication/xSQLServerReplication.psm1, line 124 \[r1\]](https://reviewable.io:443/reviews/powershell/xsqlserver/66#-KNdbeDr8GidMn5e9RuP:-KNhtiuX59Y0nwUNRzkF:-1916455384) ([raw file](https://github.com/powershell/xsqlserver/blob/c3f9066d44f8d0cb980b1e09f8bb1b999122b768/DSCResources/xSQLServerReplication/xSQLServerReplication.psm1#L124)):*
<details><summary><i>Previously, mbreakey3 (Mariah) wrote…</i></summary>
> space after pipe: '-and | $RemoteDistributor'
</details>
This was exclamation sign, but i see that reviewable is using font that is hard to distinguish.
So i have change to -not literal instead so it is obvious and more readable.

---

*[DSCResources/xSQLServerReplication/xSQLServerReplication.psm1, line 185 \[r1\]](https://reviewable.io:443/reviews/powershell/xsqlserver/66#-KNdbvHqNe-5lOSNiSj-:-KNhu756bWjVIb4XRQ9Q:-499146009) ([raw file](https://github.com/powershell/xsqlserver/blob/c3f9066d44f8d0cb980b1e09f8bb1b999122b768/DSCResources/xSQLServerReplication/xSQLServerReplication.psm1#L185)):*
<details><summary><i>Previously, mbreakey3 (Mariah) wrote…</i></summary>
> function
</details>
Done.

---

*[DSCResources/xSQLServerReplication/xSQLServerReplication.psm1, line 240 \[r1\]](https://reviewable.io:443/reviews/powershell/xsqlserver/66#-KNdc4ya9uWuI0ngkRvG:-KNhu7uVO1GO5KebF_zG:-499146009) ([raw file](https://github.com/powershell/xsqlserver/blob/c3f9066d44f8d0cb980b1e09f8bb1b999122b768/DSCResources/xSQLServerReplication/xSQLServerReplication.psm1#L240)):*
<details><summary><i>Previously, mbreakey3 (Mariah) wrote…</i></summary>
> function
</details>
Done.

---

*[DSCResources/xSQLServerReplication/xSQLServerReplication.psm1, line 260 \[r1\]](https://reviewable.io:443/reviews/powershell/xsqlserver/66#-KNdc6RWXWXDADP-xw7y:-KNhu8TX537CQJqsUtpT:-499146009) ([raw file](https://github.com/powershell/xsqlserver/blob/c3f9066d44f8d0cb980b1e09f8bb1b999122b768/DSCResources/xSQLServerReplication/xSQLServerReplication.psm1#L260)):*
<details><summary><i>Previously, mbreakey3 (Mariah) wrote…</i></summary>
> function
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xsqlserver/66)*

**Comment by Arturas-K** [comment]
@mbreakey3 thank you for your review.
I have made changes to resolve all comments, please have a look.

**Comment by mbreakey3** [comment]
Reviewed 4 of 8 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xsqlserver/66)*

**Comment by mbreakey3** [comment]
@TravisEz13 would you mind taking a quick look at this PR before I merge?

**Comment by mbreakey3** [comment]
Also, we're requiring all new resources to have adequate test-coverage - specifically unit test coverage. So can you create a unit-test file in the new unit tests folder in this module? Here's a link to the template for writing DSC unit tests: [Unit tests Template](https://github.com/PowerShell/DscResources/blob/master/Tests.Template/unit_template.ps1)

**Comment by Arturas-K** [comment]
@mbreakey3 i'll have a go at unit tests.
Not sure how to deal with external libraries, in my case i use SMO and RMO libraries to configure replication role.
I'll dig through examples in other resources.
Any guidance/tips appreciated ...

**Comment by mbreakey3** [comment]
@Arturas-K - Great, thank you! We had to deal with mocking out commands from a windows feature on a server on [xWebAdministration](https://github.com/PowerShell/xWebAdministration/tree/dev/Tests) and we ended up generating a stub file for all of those functions there. [SharePointDSC](https://github.com/PowerShell/SharePointDsc/tree/dev/Tests/Unit) also did something similar. You can also take a look at . [Contribution Guidelines -Adding test coverage for DSC resources.](https://github.com/PowerShell/DscResources/blob/master/CONTRIBUTING.md#adding-test-coverage-for-dsc-resources)

**Comment by mbreakey3** [comment]
Feel free to let me know if you run into any issues as well :)

**Comment by TravisEz13** [comment]
The only major issue I see is the lack of tests.  What is the plan to add coverage for this if we take it without tests?

**Comment by aultt** [comment]
@TravisEz13 I added an issue that all existing resources need to have pester tests.

**Comment by TravisEz13** [comment]
merge
Please resolve all merge conflicts.  For more information see [GitHowTo - 30. Resolving Conflicts](http://githowto.com/resolving_conflicts )
[Instructions to setup BC4, my favorite merge tool](http://www.scootersoftware.com/support.php?zz=kb_vcs#gitwindows)

**Comment by Arturas-K** [comment]
Hi,

I have added my stab at unit test.
To be able to test i had to refactor heavily all of the code that uses SMO or RMO assemblies.
So far i have covered to states:
 * Local distribution not in sync
 * Remote distribution not in sync

Please review test and give feedback so i can add additional states with revised approach if needed.

States to be added in future commits:
 * Local distribution in sync
 * Remote distribution in sync
 * Distribution should be absent and not in sync
 * Distribution should be absent and in sync

Any feedback appreciated.
Thanks.

**Comment by Arturas-K** [comment]
@mbreakey3 would appreciate feedback on my unit test approach, thanks

**Comment by Arturas-K** [comment]
@mbreakey3 @TravisEz13 

I have added my stab at unit test.
To be able to test i had to refactor heavily all of the code that uses SMO or RMO assemblies.
I have added all the states that i wanted to support with this resource:
 * Local distribution not in sync
 * Remote distribution not in sync
 * Local distribution in sync
 * Remote distribution in sync
 * Distribution should be absent, but system is in Local distribution mode
 * Distribution should be absent, but system is in Remote distribution mode
 * Distribution should be absent and distribution is not configured

Please review and let me know if i need to make any further changes.
All feedback is welcome.

Thanks.

**Comment by mbreakey3** [comment]
Reviewed 1 of 2 files at r3, 1 of 2 files at r4.
Review status: 7 of 9 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xsqlserver/66)*

**Comment by mbreakey3** [comment]
Reviewed 1 of 1 files at r5, 1 of 1 files at r6.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xsqlserver/66)*

**Pull request merged**
