### PR TITLE
xSQLServerDatabasePermission: Fix PSSA issues

### LINKED ISSUE #725: xSQLServerDatabasePermission: PSScriptAnalyzer errors need to be fixed
**Details of the scenario you tried and the problem that is occurring:**
The following PSScriptAnalyzer errors need to be fixed:
MSFT_xSQLServerDatabasePermission.psm1 (Line 55): Mandatory Parameter 'SQLServer' is initialized in the Param block. To fix a violation of this rule, please leave it unintialized.
MSFT_xSQLServerDatabasePermission.psm1 (Line 60): Mandatory Parameter 'SQLInstanceName' is initialized in the Param block. To fix a violation of this rule, please leave it unintialized.

**The DSC configuration that is using the resource (as detailed as possible):**
n/a

**Version of the Operating System, SQL Server and PowerShell the DSC Target Node is running:**
n/a

**What module (SqlServer or SQLPS) and which version of the module the DSC Target Node is running:**
n/a

**Version of the DSC module you're using, or 'dev' if you're using current dev branch:**
Dev

### PR DESCRIPTION
**Pull request by ChrisLGardner**
**Pull Request (PR) description**
As raised in #725 there are PSSA errors due to Mandatory parameters having values specified for them in the param block. This removes that and fixes the error.

**This Pull Request (PR) fixes the following issues:**
Fixes #725 

**Task list:**
- [x] Change details added to Unreleased section of CHANGELOG.md?
- [ ] Added/updated documentation, comment-based help and descriptions in .schema.mof files where appropriate?
- [ ] Examples appropriately updated?
- [ ] New/changed code adheres to [Style Guidelines](https://github.com/PowerShell/DscResources/blob/master/StyleGuidelines.md)?
- [ ] [Unit and (optional) Integration tests](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md) created/updated where possible?

---
This change is [Reviewable](https://reviewable.io/reviews/powershell/xsqlserver/766)

### CODE REVIEW

**Comment by johlju** [comment]
@ChrisLGardner Please add this change to the CHANGELOG.md.

**Comment by johlju** [comment]
@ChrisLGardner Next time you send in a PR, please use and fill-in the PR template that is pre-populated in the description/comment field when sending in a PR 😄

**Comment by ChrisLGardner** [comment]
Done. Sorry about not using the template, I'll make sure I do in future.

**Comment by johlju** [comment]
Sounds good. I will review these 😄

**Comment by johlju** [comment]
@ChrisLGardner Please rebase this PR. Please use git rebase (not git merge or git pull).
Help is here; https://github.com/PowerShell/DscResources/blob/master/GettingStartedWithGitHub.md#resolve-merge-conflicts

**Comment by ChrisLGardner** [comment]
Rebased as requested. I might need to rebase one of these again once it's merged.

**Comment by johlju** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r1, 1 of 1 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xsqlserver/766#-:-KrgLOdZT8dLM8FaHdeB:bnfp4nl)*

**Pull request merged**
