### PR TITLE
xSqlServerSetup: Remove trailing slash from 'UpdateSource' Property

### LINKED ISSUE #720: xSQLServerSetup: Trailing Slash in UpdatePath
**Details of the scenario you tried and the problem that is occurring:**
I had specified an UpdateSource that contained a trailing slash e.g. "C:\SQL\Updates\\".

I then received the error "The /IAcceptSQLServerLicenseTerms command line parameter is missing or has not been set to true."

From what I can tell the xSQLServerSetup is sanitizing all paths in terms of trailing slashes EXCEPT UpdateSource. Should be an easy fix by adding ,'UpdateSource' at line 853 in the resource.
**The DSC configuration that is using the resource (as detailed as possible):**
UpdatePath = "C:\SQL\Updates\\"
**Version of the Operating System, SQL Server and PowerShell the DSC Target Node is running:**
Win2012R2
SQL2014Dev
WMF5.1
**What module (SqlServer or SQLPS) and which version of the module the DSC Target Node is running:**
xSqlServer 8.0.0.0
**Version of the DSC module you're using, or 'dev' if you're using current dev branch:**
Main / PSGET

Would be glad to make the contribution

### PR DESCRIPTION
**Pull request by aboersch**
**Pull Request (PR) description**
Remove trailing slash from 'UpdateSource' property to avoid errors being thrown by setup invocation.

**This Pull Request (PR) fixes the following issues:**
Fixes #720 

**Task list:**
- [X] Change details added to Unreleased section of CHANGELOG.md?
- [NA] Added/updated documentation, comment-based help and descriptions in .schema.mof files where appropriate?
- [NA] Examples appropriately updated?
- [X] New/changed code adheres to [Style Guidelines](https://github.com/PowerShell/DscResources/blob/master/StyleGuidelines.md)?
- [x] [Unit and (optional) Integration tests](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md) created/updated where possible?

---
This change is [Reviewable](https://reviewable.io/reviews/powershell/xsqlserver/723)

### CODE REVIEW

**Comment by johlju** [comment]
Could you test this change as well?  I think is should be easy enough.

If you add below to the hash table at [line 3058](https://github.com/PowerShell/xSQLServer/blob/dev/Tests/Unit/MSFT_xSQLServerSetup.Tests.ps1#L3058).

```powershell
UpdateEnabled = 'True'
UpdateSource = 'C:\Updates\' # Regression test for issue #720
```
And add the following to the hash table at [line 3076](https://github.com/PowerShell/xSQLServer/blob/dev/Tests/Unit/MSFT_xSQLServerSetup.Tests.ps1#L3076).

```powershell
UpdateEnabled = 'True'
UpdateSource = 'C:\Updates'
```

I haven't tested it, but it hope it will work. Test it by running `Invoke-Pester 'MSFT_xSQLServerSetup.Tests.ps1'`

**Comment by johlju** [comment]
@aboersch Do you have time to create a test for this? If you feel that you don't have time, or feel unsure on how to do it, then I could help you if you tick the box "Allow edit from maintainers" to the right here around "Notifications".

**Comment by aboersch** [comment]
@johlju should be done

**Comment by johlju** [comment]
:lgtm:

---

Reviewed 2 of 3 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xsqlserver/723#-:-KtClk9GeEtO0_BQep2e:bnfp4nl)*

**Comment by johlju** [comment]
@aboersch Thanks for this! Great work! 😄

**Pull request merged**
