### PR TITLE
Fixing issues with tests (fixes #201)

### LINKED ISSUE #201: Currently we have issues with tests failing in AppVeyor
These resource pass tests locally, but not in AppVeyor.
https://ci.appveyor.com/project/PowerShell/xsqlserver/build/3.0.464.0

* Resources failing
  - MSFT_xSQLServerDatabase
  - MSFT_xSQLServerLogin
  - MSFT_xSQLServerPermission
* PSScríptAnalyzer
  - There is a _lot_ of failing PSSA rules.

### PR DESCRIPTION
**Pull request by johlju**
This fixes #201

* Removed old test templates for unit and integration tests
* Renamed schema file for xSQLServerScript

---
This change is [Reviewable](https://reviewable.io/reviews/powershell/xsqlserver/200)

### CODE REVIEW

**Comment by johlju** [comment]
Thanks to @kwirkykat I got the first errors solved quickly. :) Now we need to fix the rest :)

**Comment by kwirkykat** [comment]
@johlju Not sure why so many of the unit tests are failing now if they weren't before. The only effect the common test changes could have had had on these tests is that the PSModulePath is now properly cleaned up in Restore-TestEnvironment after each test. I'm not sure it was actually cleaning up that path before. That really shouldn't have affected unit tests though.

Those problems don't look like they are coming from the common tests. Sorry

**Comment by johlju** [comment]
I'm testing if there is a new version om build server that has SQL Server classes loaded. I experimenting on my end in my AppVeyor to see if I it is using or mocks. Rule that out first I think.

**Comment by johlju** [comment]
@kwirkykat Seems like our stubs are no longer being used :/

I added this code to the test
```
$dummyDatabase = New-Object Microsoft.SqlServer.Management.Smo.Database -ArgumentList @( $null, 'AdventureWorks')
Write-Host $dummyDatabase.Dummy()
```

And the stub looks like this
```
	// TypeName: Microsoft.SqlServer.Management.Smo.Database
    // BaseType: Microsoft.SqlServer.Management.Smo.ScriptNameObjectBase
    // Used by: 
    //  MSFT_xSQLServerDatabase
	public class Database
	{
        public Database( Server server, string name ) {
            this.Name = name;
        } 

        public Database( Object server, string name ) {
            this.Name = name;
        } 
            
        public string Name;
        		
		public void Create()
        {
        }
		
		public void Drop()
        {
        }

		public string Dummy()
        {
            return "THIS IS THE MOCK STUB CLASS!";
        }
}
```

The error:
https://ci.appveyor.com/project/johlju/xsqlserver/build/3.0.17.0#L512
```
 [-] Error occurred in test script 'C:\projects\xsqlserver\Tests\Unit\MSFT_xSQLServerDatabase.Tests.ps1' 207ms
   ArgumentNullException: Value cannot be null.
   Parameter name: newParent
   FailedOperationException: SetParent failed for Database 'AdventureWorks'. 
   MethodInvocationException: Exception calling ".ctor" with "2" argument(s): "SetParent failed for Database 'AdventureWorks'. "
   at <ScriptBlock>, C:\projects\xsqlserver\Tests\Unit\MSFT_xSQLServerDatabase.Tests.ps1: line 39
   at <ScriptBlock>, C:\Program Files\WindowsPowerShell\Modules\Pester\3.4.3\Pester.psm1: line 451
   at Invoke-Pester, C:\Program Files\WindowsPowerShell\Modules\Pester\3.4.3\Pester.psm1: line 464
   at <ScriptBlock>, <No file>: line 2
Describing MSFT_xSQLServerDatabaseOwner\Get-TargetResource
   Context When the system is not in the desired state
    [+] Should return the name as null f
```

**Comment by johlju** [comment]
Locally the test looks like this:
```
PS V:\Source\xSqlServer\Tests\Unit> Invoke-Pester *database*
THIS IS THE MOCK STUB CLASS!
Describing MSFT_xSQLServerDatabase\Get-TargetResource
   Context When the system is not in the desired state
    [+] Should return the state as absent 1.57s
    [+] Should return the same values as passed as parameters 122ms
    [+] Should call the mock function Connect-SQL 82ms
   Context When the system is in the desired state for a database
    [+] Should return the state as present 109ms
    [+] Should return the same values as passed as parameters 17ms
    [+] Should call the mock function Connect-SQL 21ms
Describing MSFT_xSQLServerDatabase\Test-TargetResource
   Context When the system is not in the desired state
    [+] Should return the state as absent when desired database does not exist 4.35s
    [+] Should return the state as present when desired database exist 31ms
   Context When the system is in the desired state
    [+] Should return the state as present when desired database exist 5.93s
    [+] Should return the state as absent when desired database does not exist 31ms
Describing MSFT_xSQLServerDatabase\Set-TargetResource
   Context When the system is not in the desired state
VERBOSE: 2016-11-17_19-14-03: Created Database NewDatabase
    [+] Should call the function New-SqlDatabase when desired database should be present 7.95s
   Context When the system is not in the desired state
VERBOSE: 2016-11-17_19-14-07: Dropped Database AdventureWorks
    [+] Should call the function Remove-SqlDatabase when desired database should be absent 4.02s
Describing MSFT_xSQLServerDatabaseOwner\Get-TargetResource
   Context When the system is not in the desired state
    [+] Should return the name as null from the get method 1.01s
    [+] Should return the same values as passed as parameters 22ms
    [+] Should call the mock functions Connect-SQL and Get-SqlDatabaseOwner 24ms
   Context When the specified database does not exist
    [+] Should return the name as null from the get method 63ms
    [+] Should return the same values as passed as parameters 18ms
    [+] Should call the mock functions Connect-SQL and Get-SqlDatabaseOwner 31ms
   Context When the system is in the desired state
    [+] Should return the name of the owner from the get method 80ms
    [+] Should return the same values as passed as parameters 25ms
    [+] Should call the mock functions Connect-SQL and Get-SqlDatabaseOwner 27ms
Describing MSFT_xSQLServerDatabaseOwner\Test-TargetResource
   Context When the system is not in the desired state
VERBOSE: String value for property Name does not match. Current state is '' and Desired state is 'CONTOSO\SqlServiceAcct'
    [+] Should return the state as false when desired login is not the database owner 165ms
   Context When the system is in the desired state
    [+] Should return the state as true when desired login is the database owner 72ms
Describing MSFT_xSQLServerDatabaseOwner\Set-TargetResource
   Context When the system is not in the desired state
    [+] Should call the function Set-SqlDatabaseOwner when desired login is not the database owner 149ms
    [+] Should throw an error when desired database does not exist 238ms
   Context When the system is in the desired state
    [+] Should not call the function Set-SqlDatabaseOwner when desired login is the database owner 80ms
```

**Comment by johlju** [comment]
Yep. SMO is loaded... :/ 
Printed all assemblies: https://ci.appveyor.com/project/johlju/xsqlserver/build/3.0.18.0

@kwirkykat Do you have any pointers how do we could solve this? Can we get a clean PowerShell somehow?

**Comment by johlju** [comment]
Only way I see to solve this is 

* Get a clean build worker
* Get a clean session to test in
* Remove SMO stubs and change to wrappers for all of those calls, and using `System.Object` in Parameters.

I preferably want a clean session. :)

@luigilink If you have any clues let me know. 😄

**Comment by johlju** [comment]
Currently looking at `Start-Job` to try to get a clean environment.

**Comment by johlju** [comment]
Okay, so `Start-Job` seems to do the trick. Shall verify I can get a clean build with this approach. Dirty workaround though.

**Comment by johlju** [comment]
Got a build to pass by using `Start-Job` as a workaround: https://ci.appveyor.com/project/johlju/xsqlserver/build/3.0.20.0

 I think I sleep on this before doing this change. If anybody has a better solution, let me know.

**Comment by kwirkykat** [comment]
@johlju No idea why those assemblies are getting added before your tests run. We don't add any assemblies in the common tests. Maybe it's in a test that's suddenly running before all these other tests now?

This [new New-MockObject function](https://github.com/pester/Pester/wiki/New-MockObject) that Pester just added would probably solve all these problems... This version is not out on the PowerShell Gallery yet though :cry: so the AppVeyor machine won't be able to pick it up yet.

You could just add the workaround fix for now until Pester releases version 3.4.4 to the PSGallery.

**Comment by johlju** [comment]
@kwirkykat The build worker has all SQL Server major versions installed (the Express edition), but with the windows services disabled. SQL Server 2016 SP1 was release on the 16:th so they (AppVeyor) might have done something with the build worker to change this behavior. I really would like it if we could have a clean build worker with just WMF5 installed. I tried changing to the VMF5 build worker image in appveyor.yml. But that did not work either.

Regarding if a test is doing this. I thought about that too last night. If a test is not mocking `Connect-SQL` correctly which in turn loads the assembly. But I don't think so, because there were so many SQL assemblies loaded. But I will verify this today to make sure.

The new `New-MockObject` will work if it can also set values. Right now, in the first implementation, it just returns an empty object which you cannot do anything with. I saw that the Pester team are working on an approach to make it able to "set values" by setting the underlying variable for the property to a value. If that works, we need to set mocked values in the mocked object, then we definitely will go over to using `New-MockObject`. I'm keeping an eye on that progress.

**Comment by johlju** [comment]
Another thing about `New-MockObject`. It expects the type to be present to be able to 'mock' it. We don't expect the SMO assemblies to be on the node we run unit test on. Because of this we need the mock stubs of the SMO classes, and also because we cant use the original SMO classes because they actually change something.

**Comment by luigilink** [comment]
👍 Congrats !!
You find a solution, nice work !
Hope this PR will be quickly merged 😄

**Comment by johlju** [comment]
Reviewed 5 of 5 files at r1, 1 of 9 files at r2, 9 of 9 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[Tests/Unit/MSFT_xSQLAOGroupEnsure.Tests.ps1, line 15 at r3](https://reviewable.io:443/reviews/powershell/xsqlserver/200#-KWsNyhEuBbgbtUl1GDw:-KWsNyhEuBbgbtUl1GDx:b-dpkvdy) ([raw file](https://github.com/powershell/xsqlserver/blob/f20e651e6827074b550be2183659d0fe6811a248/Tests/Unit/MSFT_xSQLAOGroupEnsure.Tests.ps1#L15)):*
> ```PowerShell
>     )
>     $script:DSCModuleName      = 'xSQLServer' 
>     $script:DSCResourceName    = 'MSFT_xSQLAOGroupEnsure' 
> ```

This test does not output correctly with the workaround. Investigating. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xsqlserver/200)*

**Comment by johlju** [comment]
Now days I have the power to merge. So we can get this in today. :smile: 

---

Review status: all files reviewed at latest revision, all discussions resolved.

---

*[Tests/Unit/MSFT_xSQLAOGroupEnsure.Tests.ps1, line 15 at r3](https://reviewable.io:443/reviews/powershell/xsqlserver/200#-KWsNyhEuBbgbtUl1GDw:-KWsVfFol7w3O1H4aWBV:b-gqi9ha) ([raw file](https://github.com/powershell/xsqlserver/blob/f20e651e6827074b550be2183659d0fe6811a248/Tests/Unit/MSFT_xSQLAOGroupEnsure.Tests.ps1#L15)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary>
> This test does not output correctly with the workaround. Investigating. 
</details>
My bad. It was there. The test was so small, and did not have the resource name in it so was hard to find. But all good!

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xsqlserver/200#-:-KWsVjLvWdwwxo3x2ZU3:b-qjzp0w)*

**Comment by johlju** [comment]
:lgtm: 

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xsqlserver/200#-:-KWsWIlxkzdW2cWFKN-g:bg7igkv)*

**Pull request merged**
