### PR TITLE
Adding specific contributing guidelines (resolves #158)

### LINKED ISSUE #158: Adding specific guidelines for contributing to xSQLServer
I think we need to add some guidelines that are specific to xSQLServer. So far I have found the following specific guidelines that would help new contributors.
- Resource name should be prefixed with 'MSFT_xSQLServer'.
- Throwing an error should be done using `New-TerminatingError` (for localization).
- Writing verbose messages should be done using `New-VerboseMessage` (for localization).
- (soon, in PR) Writing warning should be done using `New-WarningMessage` (for localization).

I bet there are more we could add, this was just top of my head. If you know anything else that should be added, please comment.

Either we do a CONTRIBUTING.md in this module, or we start a wiki like @BrianFarnhill did in SharePointDsc.
https://github.com/PowerShell/SharePointDsc/wiki/Contributing%20to%20SharePointDsc

I am happy to take this on, if we agree this should be done.

@mbreakey3 @kwirkykat If we go the wiki way, is it okay to start a wiki? Are contributors (all users) allowed to edit wiki pages?
Seems there is not a (easy) way to PR into a wiki. Seems GitHub Pages is the way to got to be able to PR in changes. Have you looked at that yet?

### PR DESCRIPTION
**Pull request by johlju**
Adding specific guidelines for contributing to xSQLServer resource (resolves #158)

This is a proposal of how the specific guideline could look like and what it could contain. Please review and make comments and suggestions.

---

This change is [Reviewable](https://reviewable.io/reviews/powershell/xsqlserver/164)

### CODE REVIEW

**Comment by johlju** [comment]
It might be easier to read the CONTRIBUTION.md in my cloned repo while reviewing https://github.com/johlju/xSQLServer/blob/contributing-guidelines/CONTRIBUTING.md

Also added a row under 'Contribution' here:
https://github.com/johlju/xSQLServer/blob/contributing-guidelines/README.md

**Comment by johlju** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[CONTRIBUTING.md, line 79 at r2](https://reviewable.io:443/reviews/powershell/xsqlserver/164#-KWqUOQ-4SKScxh-YxNA:-KWqUOQ-4SKScxh-YxNB:b-ekby7h) ([raw file](https://github.com/powershell/xsqlserver/blob/eb87765b2a3ffd7237d142bbd16f493e742e2c69/CONTRIBUTING.md#L79)):*
> ```Markdown
> one resource, then the functions can also be placed in the common [xSQLServerHelper.psm1](https://github.com/PowerShell/xSQLServer/blob/dev/xSQLServerHelper.psm1) module file.
> 
> To import the helper function, add this code block to the beginning of your resource module.
> ```

This section can be removed, it will be obsolete with PR #198

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xsqlserver/164)*

**Comment by johlju** [comment]
Reviewed 1 of 1 files at r3.
Review status: 1 of 2 files reviewed at latest revision, all discussions resolved.

---

*[CONTRIBUTING.md, line 79 at r2](https://reviewable.io:443/reviews/powershell/xsqlserver/164#-KWqUOQ-4SKScxh-YxNA:-KX0XoeuPMutL6FFK000:bb6un1j) ([raw file](https://github.com/powershell/xsqlserver/blob/38146dadb5626c613f6fe336090557c1a96f3cbd/CONTRIBUTING.md#L79)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary>
> This section can be removed, it will be obsolete with PR #198
</details>
Done

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xsqlserver/164)*

**Comment by johlju** [comment]
@frokensonja If you have time, could you proof read this for me? You see the link to the page in an easier read form than the markdown language in Reviewable. 
If you have any comments, click the purple review button on top of this page to get to Reviewable. Write your comment(s) on the line in question. 
After you added all your comments throughout the file, click the big green Publish button at the top of the Reviewable site. Click Publish will send your comments back to GitHub and this PR.
If by chance all is good (you wrote no comments) please leave a 'LGTM' as your only comment in the "top" comments and click Publish.

**Comment by FrokenSonja** [comment]
Reviewed 1 of 2 files at r1, 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[CONTRIBUTING.md, line 13 at r4](https://reviewable.io:443/reviews/powershell/xsqlserver/164#-KX0ejSSyY3JeqQmL53L:-KX0ejSSyY3JeqQmL53M:bygxs7a) ([raw file](https://github.com/powershell/xsqlserver/blob/9f0caa996e30003a1e620e45e7b3bb5d1f496d7b/CONTRIBUTING.md#L13)):*
> ```Markdown
> ### SQL Server products supported by resources
> 
> Any resource should be able to target at least all SQL Server versions that is currently supported by Microsoft (also those in extended support).
> ```

that are currently

---

*[CONTRIBUTING.md, line 65 at r4](https://reviewable.io:443/reviews/powershell/xsqlserver/164#-KX0f7fg56w3-0Hdc2oy:-KX0f7fheA3hUq3hQyfp:b-j79h37) ([raw file](https://github.com/powershell/xsqlserver/blob/9f0caa996e30003a1e620e45e7b3bb5d1f496d7b/CONTRIBUTING.md#L65)):*
> ```Markdown
> |Function|Short description|
> ---|---|---
> |`New-TerminatingError`| Throws a localized error message using `Throw`. The parameter `ErrorType` take the message type for which it will get the localized message string. |
> ```

Error Rype takes the message

---

*[CONTRIBUTING.md, line 66 at r4](https://reviewable.io:443/reviews/powershell/xsqlserver/164#-KX0fIU9rWZFhFj2tiq1:-KX0fIU9rWZFhFj2tiq2:b-j79h37) ([raw file](https://github.com/powershell/xsqlserver/blob/9f0caa996e30003a1e620e45e7b3bb5d1f496d7b/CONTRIBUTING.md#L66)):*
> ```Markdown
> ---|---|---
> |`New-TerminatingError`| Throws a localized error message using `Throw`. The parameter `ErrorType` take the message type for which it will get the localized message string. |
> |`New-VerboseMessage`| Writes a localized verbose message using `Write-Verbose`. The parameter `ErrorType` take the message type for which it will get the localized message string. |
> ```

Error Rype takes the message

---

*[CONTRIBUTING.md, line 67 at r4](https://reviewable.io:443/reviews/powershell/xsqlserver/164#-KX0fJ6L36yvoJeZbTk_:-KX0fJ6L36yvoJeZbTka:b-j79h37) ([raw file](https://github.com/powershell/xsqlserver/blob/9f0caa996e30003a1e620e45e7b3bb5d1f496d7b/CONTRIBUTING.md#L67)):*
> ```Markdown
> |`New-TerminatingError`| Throws a localized error message using `Throw`. The parameter `ErrorType` take the message type for which it will get the localized message string. |
> |`New-VerboseMessage`| Writes a localized verbose message using `Write-Verbose`. The parameter `ErrorType` take the message type for which it will get the localized message string. |
> |`New-WarningMessage`| Writes a localized warning message using `Write-Warning`. The parameter `ErrorType` take the message type for which it will get the localized message string. |
> ```

Error Rype takes the message

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xsqlserver/164)*

**Comment by johlju** [comment]
Reviewed 2 of 2 files at r5.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[CONTRIBUTING.md, line 13 at r4](https://reviewable.io:443/reviews/powershell/xsqlserver/164#-KX0ejSSyY3JeqQmL53L:-KXPGjbj1fPbSpqA15tV:b-896fix) ([raw file](https://github.com/powershell/xsqlserver/blob/9f0caa996e30003a1e620e45e7b3bb5d1f496d7b/CONTRIBUTING.md#L13)):*
<details><summary><i>Previously, FrokenSonja wrote…</i></summary>
> that are currently
</details>
Done.

---

*[CONTRIBUTING.md, line 65 at r4](https://reviewable.io:443/reviews/powershell/xsqlserver/164#-KX0f7fg56w3-0Hdc2oy:-KXPGlWfSwmu6Rr-8kj1:b-896fix) ([raw file](https://github.com/powershell/xsqlserver/blob/9f0caa996e30003a1e620e45e7b3bb5d1f496d7b/CONTRIBUTING.md#L65)):*
<details><summary><i>Previously, FrokenSonja wrote…</i></summary>
> Error Rype takes the message
</details>
Done.

---

*[CONTRIBUTING.md, line 66 at r4](https://reviewable.io:443/reviews/powershell/xsqlserver/164#-KX0fIU9rWZFhFj2tiq1:-KXPGm2A9pbbra4bhmFw:b-896fix) ([raw file](https://github.com/powershell/xsqlserver/blob/9f0caa996e30003a1e620e45e7b3bb5d1f496d7b/CONTRIBUTING.md#L66)):*
<details><summary><i>Previously, FrokenSonja wrote…</i></summary>
> Error Rype takes the message
</details>
Done.

---

*[CONTRIBUTING.md, line 67 at r4](https://reviewable.io:443/reviews/powershell/xsqlserver/164#-KX0fJ6L36yvoJeZbTk_:-KXPGmfiUoSDGcJoPdSr:b-896fix) ([raw file](https://github.com/powershell/xsqlserver/blob/9f0caa996e30003a1e620e45e7b3bb5d1f496d7b/CONTRIBUTING.md#L67)):*
<details><summary><i>Previously, FrokenSonja wrote…</i></summary>
> Error Rype takes the message
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xsqlserver/164)*

**Comment by johlju** [comment]
:lgtm: 

---

Review status: all files reviewed at latest revision, 4 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xsqlserver/164#-:-KXPGxEYXa5p739DYObW:bg7igkv)*

**Pull request merged**
