### PR TITLE
xSQLServerSetup: Fix PSSA Rules

### LINKED ISSUE #729: xSQLServerSetup: PSScriptAnalyzer errors need to be fixed
**Details of the scenario you tried and the problem that is occurring:**
The following PSScriptAnalyzer errors need to be fixed:
MSFT_xSQLServerSetup.psm1 (Line 1808): Mandatory parameters must use the correct format [Parameter(Mandatory = $true)] for the mandatory attribute. See https://github.com/PowerShell/DscResources/blob/master/StyleGuidelines.md#correct-format-for-parameter-block
MSFT_xSQLServerSetup.psm1 (Line 1828): Mandatory parameters must use the correct format [Parameter(Mandatory = $true)] for the mandatory attribute. See https://github.com/PowerShell/DscResources/blob/master/StyleGuidelines.md#correct-format-for-parameter-block

**The DSC configuration that is using the resource (as detailed as possible):**
n/a

**Version of the Operating System, SQL Server and PowerShell the DSC Target Node is running:**
n/a

**What module (SqlServer or SQLPS) and which version of the module the DSC Target Node is running:**
n/a

**Version of the DSC module you're using, or 'dev' if you're using current dev branch:**
Dev

### PR DESCRIPTION
**Pull request by ChrisLGardner**
**Pull Request (PR) description**
Adds the whitespace needed for the rules to pass on xSqlServerSetup.

**This Pull Request (PR) fixes the following issues:**
Fixes #729 

**Task list:**
- [x] Change details added to Unreleased section of CHANGELOG.md?
- [ ] Added/updated documentation, comment-based help and descriptions in .schema.mof files where appropriate?
- [ ] Examples appropriately updated?
- [ ] New/changed code adheres to [Style Guidelines](https://github.com/PowerShell/DscResources/blob/master/StyleGuidelines.md)?
- [ ] [Unit and (optional) Integration tests](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md) created/updated where possible?

---
This change is [Reviewable](https://reviewable.io/reviews/powershell/xsqlserver/762)

### CODE REVIEW

**Comment by johlju** [comment]
@ChrisLGardner Thanks for fixing this! Please add this change to the CHANGELOG.md.

**Comment by ChrisLGardner** [comment]
Done.

**Comment by johlju** [comment]
Reviewed 1 of 1 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[CHANGELOG.md, line 60 at r2](https://reviewable.io:443/reviews/powershell/xsqlserver/762#-KrdwPsjUWf87pO35akw:-KrdwPsjUWf87pO35akx:b-r6z3uo) ([raw file](https://github.com/powershell/xsqlserver/blob/5bc5f46c33d01acfd82d1df238b5e9b8aba78649/CHANGELOG.md#L60)):*
> Analyser

Please change to 'Analyzer' (let's use american english)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xsqlserver/762)*

**Comment by johlju** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[CHANGELOG.md, line 60 at r3](https://reviewable.io:443/reviews/powershell/xsqlserver/762#-KrdzbKoXxThBs_Fjhz2:-KrdzbKoXxThBs_Fjhz3:b-2hjcxl) ([raw file](https://github.com/powershell/xsqlserver/blob/41397ba1d2f010f12479f72ca7a23f70c1ef091f/CHANGELOG.md#L60)):*
> ```Markdown
>     administrator (issue #691).
>   - Added a simple integration test ([issue #709](https://github.com/PowerShell/xSQLServer/issues/709)).
>   - Fixed PS Script Analyzer errors ([Issue #729](https://github.com/PowerShell/xSQLServer/issues/729))
> ```

Please change to lower-case 'i' on 'issue'. Here and the other PR's.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xsqlserver/762)*

**Comment by ChrisLGardner** [comment]
Review status: 1 of 2 files reviewed at latest revision, 2 unresolved discussions.

---

*[CHANGELOG.md, line 60 at r2](https://reviewable.io:443/reviews/powershell/xsqlserver/762#-KrdwPsjUWf87pO35akw:-Kre-Jd4osCjrxXEOGBb:b-896fix) ([raw file](https://github.com/powershell/xsqlserver/blob/5bc5f46c33d01acfd82d1df238b5e9b8aba78649/CHANGELOG.md#L60)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

> Analyser

Please change to 'Analyzer' (let's use american english)
</blockquote></details>

Done.

---

*[CHANGELOG.md, line 60 at r3](https://reviewable.io:443/reviews/powershell/xsqlserver/762#-KrdzbKoXxThBs_Fjhz2:-Kre-LAqCXIOpTPX7H81:b-896fix) ([raw file](https://github.com/powershell/xsqlserver/blob/41397ba1d2f010f12479f72ca7a23f70c1ef091f/CHANGELOG.md#L60)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

Please change to lower-case 'i' on 'issue'. Here and the other PR's.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xsqlserver/762)*

**Comment by johlju** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xsqlserver/762#-:-Kre-hWq7iaCfpFsJAyF:bnfp4nl)*

**Comment by johlju** [comment]
Thanks for fixing this! 😄

**Pull request merged**
