### PR TITLE
xSQLServerHelper: Connect-SQL: Throw on failed connection

### LINKED ISSUE #333: xSQLServerHelper: Function Connect-SQL returns successfull even when connection fails
**Details of the scenario you try and problem that is occurring:**

When running the following 
```
$sql = New-Object Microsoft.SqlServer.Management.Smo.Server 'sqltest\Default'
```

An empty object is returned. 

```
AuditLevel                  : 
BackupDirectory             : 
BrowserServiceAccount       : 
BrowserStartMode            : 
BuildClrVersionString       : 
BuildNumber                 : 
ClusterName                 : 
ClusterQuorumState          : 
ClusterQuorumType           : 
Collation                   : 
CollationID                 : 
ComparisonStyle             : 
ComputerNamePhysicalNetBIOS : 
DefaultFile                 : 
DefaultLog                  : 
Edition                     : 
ErrorLogPath                : 
FilestreamLevel             : 
FilestreamShareName         : 
HadrManagerStatus           : 
InstallDataDirectory        : 
InstallSharedDirectory      : 
InstanceName                : 
IsCaseSensitive             : 
IsClustered                 : 
IsFullTextInstalled         : 
IsHadrEnabled               : 
IsSingleUser                : 
Language                    : 
LoginMode                   : 
MailProfile                 : 
MasterDBLogPath             : 
MasterDBPath                : 
MaxPrecision                : 
NamedPipesEnabled           : 
NetName                     : 
NumberOfLogFiles            : 
OSVersion                   : 
PerfMonMode                 : 
PhysicalMemory              : 
PhysicalMemoryUsageInKB     : 
Platform                    : 
Processors                  : 
ProcessorUsage              : 
Product                     : 
ProductLevel                : 
ResourceLastUpdateDateTime  : 
ResourceVersionString       : 
RootDirectory               : 
ServerType                  : 
ServiceAccount              : 
ServiceInstanceId           : 
ServiceName                 : 
ServiceStartMode            : 
SqlCharSet                  : 
SqlCharSetName              : 
SqlDomainGroup              : 
SqlSortOrder                : 
SqlSortOrderName            : 
Status                      : 
TapeLoadWaitTime            : 
TcpEnabled                  : 
VersionMajor                : 
VersionMinor                : 
VersionString               : 
Name                        : sqltest\Default
Version                     : 
EngineEdition               : 
ResourceVersion             : 
BuildClrVersion             : 
DefaultTextMode             : True
Configuration               : Microsoft.SqlServer.Management.Smo.Configuration
AffinityInfo                : 
ProxyAccount                : 
Mail                        : 
Databases                   : 
Endpoints                   : 
Languages                   : 
SystemMessages              : 
UserDefinedMessages         : 
Credentials                 : 
CryptographicProviders      : 
Logins                      : 
Roles                       : 
LinkedServers               : 
SystemDataTypes             : 
JobServer                   : 
ResourceGovernor            : 
ServiceMasterKey            : 
Settings                    : Microsoft.SqlServer.Management.Smo.Settings
Information                 : Microsoft.SqlServer.Management.Smo.Information
UserOptions                 : Microsoft.SqlServer.Management.Smo.UserOptions
BackupDevices               : 
FullTextService             : 
ActiveDirectory             : 
Triggers                    : 
Audits                      : 
ServerAuditSpecifications   : 
AvailabilityGroups          : 
ConnectionContext           : Data Source=sqltest\Default;Integrated Security=True;MultipleActiveResultSets=False;Application Name="SQL Management"
Events                      : Microsoft.SqlServer.Management.Smo.ServerEvents
OleDbProviderSettings       : 
Urn                         : 
Properties                  : 
UserData                    : 
State                       : Existing
IsDesignMode                : False
DomainName                  : SMO
DomainInstanceName          : 
```

Instead of validating using the following, and throw an error is it is true.
```
if (!$sql)
```
Validation should use
```
if (-not $sql.Status -eq 'Online' )
```

**The DSC configuration that is using the resource (as detailed as possible):**
n/a

**Version of the Operating System, SQL Server and PowerShell the DSC Target Node is running:**
n/a

**Version of the DSC module you're using, or 'dev' if you're using current dev branch:**
Dev

### PR DESCRIPTION
**Pull request by randomnote1**
**Pull Request (PR) description**
Fixed Connect-SQL by ensuring the Status property returns 'Online' prior to returning the SQL Server object.

**This Pull Request (PR) fixes the following issues:**
Fixes #333 

**Task list:**
- [X] Change details added to Unreleased section of CHANGELOG.md?
- [ ] Added/updated documentation, comment-based help and descriptions in .schema.mof files where appropriate?
- [ ] Examples appropriately updated?
- [X] New/changed code adheres to [Style Guidelines](https://github.com/PowerShell/DscResources/blob/master/StyleGuidelines.md)?
- [X] [Unit and (optional) Integration tests](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md) created/updated where possible?

---
This change is [Reviewable](https://reviewable.io/reviews/powershell/xsqlserver/799)

### CODE REVIEW

**Comment by johlju** [comment]
@randomnote1 Please rebase this one.

**Comment by randomnote1** [comment]
Rebase is complete.

---

Review status: 0 of 3 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xsqlserver/799#-:-KtrUhxgaAhCaUA99XFY:b8jf69i)*

**Comment by johlju** [comment]
Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[xSQLServerHelper.psm1, line 65 at r1](https://reviewable.io:443/reviews/powershell/xsqlserver/799#-KtvbIXZ_VnL-e3hUuM3:-KtvbIXZ_VnL-e3hUuM4:bp6459u) ([raw file](https://github.com/powershell/xsqlserver/blob/da793d2f1700adb78ed715eb5bf6ebb5d350bf75/xSQLServerHelper.psm1#L65)):*
> ```PowerShell
>     }
> 
>     if ( $sql.Status -match '^Online$' )
> ```

Minor: Could you make this `-notmatch` and throw if true? Then we can have the `return` at the end outside the `if`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xsqlserver/799)*

**Comment by randomnote1** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[xSQLServerHelper.psm1, line 65 at r1](https://reviewable.io:443/reviews/powershell/xsqlserver/799#-KtvbIXZ_VnL-e3hUuM3:-KtvcCWg7Ggbj6a7_OYL:bxvf503) ([raw file](https://github.com/powershell/xsqlserver/blob/da793d2f1700adb78ed715eb5bf6ebb5d350bf75/xSQLServerHelper.psm1#L65)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

Minor: Could you make this `-notmatch` and throw if true? Then we can have the `return` at the end outside the `if`.
</blockquote></details>

I originally coded it like that, however I feel like this ended up be more readable. Plus this way it "defaults" to the error and only returns when confirmed good.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xsqlserver/799)*

**Comment by johlju** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xsqlserver/799#-:-KtzWvqhBB6y2USPa4CB:bnfp4nl)*

**Pull request merged**
