### PR TITLE
Add template for Issue and Pull Request (Fixes #197)

### LINKED ISSUE #197: Add template for New Issue and New Pull Request
Add template for Issue and Pull Request
Example for Issue Template:
**Details of the scenario you try and problem that is occurring:**

**The DSC configuration that is using the resource:**

**Version of the Operating System and PowerShell the DSC Target Node is running:**

**Version of the DSC module you're using:**

PR #191

### PR DESCRIPTION
**Pull request by luigilink**
Fixes #197 

Add template for Issue and Pull Request

- [x] Change details added to Unreleased section of readme.md?
- [x] Added/updated documentation and descriptions in .schema.mof files where appropriate?
- [x] Examples appropriately updated?
- [x] New/changed code adheres to [Style Guidelines]?(https://github.com/PowerShell/DscResources/blob/master/StyleGuidelines.md)?
- [x] [Unit and Integration tests](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md) created/updated where possible?

---
This change is [Reviewable](https://reviewable.io/reviews/powershell/xsqlserver/191)

### CODE REVIEW

**Comment by johlju** [comment]
@luigilink This has potential, would ease things. But could you please submit an issue describing how the process should be working with these templates?

**Comment by luigilink** [comment]
Issue submited, "Waiting for the author" can be removed

**Comment by johlju** [comment]
Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 7 unresolved discussions.

---

*[.github/CONTRIBUTING.md, line 1 at r1](https://reviewable.io:443/reviews/powershell/xsqlserver/191#-KX6tY3W3YrGyflSDELK:-KX6tY3W3YrGyflSDELL:bgy2ynl) ([raw file](https://github.com/powershell/xsqlserver/blob/c4353b0bfcadaef6708d6323f432f6cb2163bd75/.github/CONTRIBUTING.md#L1)):*
> ```Markdown
> If you'd like to contribute to this project, please review the [Contribution Guidelines](https://github.com/PowerShell/DscResources/blob/master/CONTRIBUTING.md).
> ```

Where/When does this text show up? :) 

---

*[.github/ISSUE_TEMPLATE.md, line 7 at r1](https://reviewable.io:443/reviews/powershell/xsqlserver/191#-KX6u-OdUQ0YIdm4BCsX:-KX6u-OdUQ0YIdm4BCsY:bx4bghr) ([raw file](https://github.com/powershell/xsqlserver/blob/c4353b0bfcadaef6708d6323f432f6cb2163bd75/.github/ISSUE_TEMPLATE.md#L7)):*
> **The DSC configuration that is using the resource:**

Would it be better to change to? **The DSC configuration that is using the resource (as detailed as possible):**

---

*[.github/ISSUE_TEMPLATE.md, line 9 at r1](https://reviewable.io:443/reviews/powershell/xsqlserver/191#-KX6vJ2frg76j4VlQkE_:-KX6vJ2frg76j4VlQkEa:bictuno) ([raw file](https://github.com/powershell/xsqlserver/blob/c4353b0bfcadaef6708d6323f432f6cb2163bd75/.github/ISSUE_TEMPLATE.md#L9)):*
> **Version of the Operating System and PowerShell the DSC Target Node is running:**

Would it be better to change to? **Version of the Operating System, SQL Server and PowerShell the DSC Target Node is running:**

---

*[.github/ISSUE_TEMPLATE.md, line 11 at r1](https://reviewable.io:443/reviews/powershell/xsqlserver/191#-KX6vn6_HIOEuAdlU42s:-KX6vn6_HIOEuAdlU42t:bgofvav) ([raw file](https://github.com/powershell/xsqlserver/blob/c4353b0bfcadaef6708d6323f432f6cb2163bd75/.github/ISSUE_TEMPLATE.md#L11)):*
> **Version of the DSC module you're using:**

Would it be better to change to? **Version of the DSC module you're using, or 'dev' if you're using current dev branch:**

---

*[.github/PULL_REQUEST_TEMPLATE.md, line 14 at r1](https://reviewable.io:443/reviews/powershell/xsqlserver/191#-KX6wlIn8uFBWKV4FWoN:-KX6wlIn8uFBWKV4FWoO:b6hjqms) ([raw file](https://github.com/powershell/xsqlserver/blob/c4353b0bfcadaef6708d6323f432f6cb2163bd75/.github/PULL_REQUEST_TEMPLATE.md#L14)):*
> ```Markdown
> [Replace this with a description of your pull request]
> 
> - [ ] Change details added to Unreleased section of changelog.md?
> ```

Change 'Changelog.md' to README.md for the time being.

---

*[.github/PULL_REQUEST_TEMPLATE.md, line 15 at r1](https://reviewable.io:443/reviews/powershell/xsqlserver/191#-KX6wbbMbUBc2piAi3OJ:-KX6wbbNpKoNesy6NphT:bt6jfi4) ([raw file](https://github.com/powershell/xsqlserver/blob/c4353b0bfcadaef6708d6323f432f6cb2163bd75/.github/PULL_REQUEST_TEMPLATE.md#L15)):*
> Added/updated documentation and descriptions 

Change to 'Added/updated documentation, comment-based help and descriptions in .schema.mof files where appropriate?'

---

*[.github/PULL_REQUEST_TEMPLATE.md, line 19 at r1](https://reviewable.io:443/reviews/powershell/xsqlserver/191#-KX6y4O97K7PGnaoDYPl:-KX6y4OA0lpfIZpl8hJC:bobu8fq) ([raw file](https://github.com/powershell/xsqlserver/blob/c4353b0bfcadaef6708d6323f432f6cb2163bd75/.github/PULL_REQUEST_TEMPLATE.md#L19)):*
> ```Markdown
> - [ ] New/changed code adheres to [Style Guidelines]?(https://github.com/PowerShell/DscResources/blob/master/StyleGuidelines.md)?
> - [ ] [Unit and Integration tests](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md) created/updated where possible?
> ```

Also add a section after the list that say something like the following. Is the below test understandable? 

This PR fixes the following issues (use format `Fixes #123`): 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xsqlserver/191)*

**Comment by johlju** [comment]
Review status: all files reviewed at latest revision, 7 unresolved discussions.

---

*[.github/PULL_REQUEST_TEMPLATE.md, line 14 at r1](https://reviewable.io:443/reviews/powershell/xsqlserver/191#-KX6wlIn8uFBWKV4FWoN:-KX7-M6mKBDOlEINfSy7:b-find72) ([raw file](https://github.com/powershell/xsqlserver/blob/c4353b0bfcadaef6708d6323f432f6cb2163bd75/.github/PULL_REQUEST_TEMPLATE.md#L14)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary>
> Change 'Changelog.md' to README.md for the time being.
</details>
Nevermind, just change it to Changelog.md (capital 'C')

I will make sure to merge the other PR before this one, so Changelog.md will be correct. :)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xsqlserver/191)*

**Comment by luigilink** [comment]
Review status: all files reviewed at latest revision, 7 unresolved discussions.

---

*[.github/CONTRIBUTING.md, line 1 at r1](https://reviewable.io:443/reviews/powershell/xsqlserver/191#-KX6tY3W3YrGyflSDELK:-KXALEuN8yv4dXCbNVXB:b-wsr3mx) ([raw file](https://github.com/powershell/xsqlserver/blob/31b2fdac94c81e0d4f8441b113fb1ca003df00c9/.github/CONTRIBUTING.md#L1)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary>
> Where/When does this text show up? :) 
</details>
It shows up when you add an issue or a pr, very useful.
https://help.github.com/articles/setting-guidelines-for-repository-contributors/

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xsqlserver/191)*

**Comment by luigilink** [comment]
Reviewed 3 of 3 files at r2.
Review status: all files reviewed at latest revision, 7 unresolved discussions.

---

*[.github/CONTRIBUTING.md, line 1 at r1](https://reviewable.io:443/reviews/powershell/xsqlserver/191#-KX6tY3W3YrGyflSDELK:-KXAQB2Hz4F4uVnvyJjt:b-896fix) ([raw file](https://github.com/powershell/xsqlserver/blob/31b2fdac94c81e0d4f8441b113fb1ca003df00c9/.github/CONTRIBUTING.md#L1)):*
<details><summary><i>Previously, luigilink (Jean-Cyril Drouhin) wrote…</i></summary>
> It shows up when you add an issue or a pr, very useful.
> https://help.github.com/articles/setting-guidelines-for-repository-contributors/
</details>
Done.

---

*[.github/ISSUE_TEMPLATE.md, line 7 at r1](https://reviewable.io:443/reviews/powershell/xsqlserver/191#-KX6u-OdUQ0YIdm4BCsX:-KXAQ96ZcywwX4djzisP:b-896fix) ([raw file](https://github.com/powershell/xsqlserver/blob/31b2fdac94c81e0d4f8441b113fb1ca003df00c9/.github/ISSUE_TEMPLATE.md#L7)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary>
> > **The DSC configuration that is using the resource:**
> 
> Would it be better to change to? **The DSC configuration that is using the resource (as detailed as possible):**
</details>
Done.

---

*[.github/ISSUE_TEMPLATE.md, line 9 at r1](https://reviewable.io:443/reviews/powershell/xsqlserver/191#-KX6vJ2frg76j4VlQkE_:-KXAQ9PoER19WBufDiQs:b-896fix) ([raw file](https://github.com/powershell/xsqlserver/blob/31b2fdac94c81e0d4f8441b113fb1ca003df00c9/.github/ISSUE_TEMPLATE.md#L9)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary>
> > **Version of the Operating System and PowerShell the DSC Target Node is running:**
> 
> Would it be better to change to? **Version of the Operating System, SQL Server and PowerShell the DSC Target Node is running:**
</details>
Done.

---

*[.github/ISSUE_TEMPLATE.md, line 11 at r1](https://reviewable.io:443/reviews/powershell/xsqlserver/191#-KX6vn6_HIOEuAdlU42s:-KXAQ9uHJ9OrV9EFODXG:b-896fix) ([raw file](https://github.com/powershell/xsqlserver/blob/31b2fdac94c81e0d4f8441b113fb1ca003df00c9/.github/ISSUE_TEMPLATE.md#L11)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary>
> > **Version of the DSC module you're using:**
> 
> Would it be better to change to? **Version of the DSC module you're using, or 'dev' if you're using current dev branch:**
</details>
Done.

---

*[.github/PULL_REQUEST_TEMPLATE.md, line 14 at r1](https://reviewable.io:443/reviews/powershell/xsqlserver/191#-KX6wlIn8uFBWKV4FWoN:-KXAQ72qn9RzbYasux-o:b-896fix) ([raw file](https://github.com/powershell/xsqlserver/blob/31b2fdac94c81e0d4f8441b113fb1ca003df00c9/.github/PULL_REQUEST_TEMPLATE.md#L14)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary>
> Nevermind, just change it to Changelog.md (capital 'C')
> 
> I will make sure to merge the other PR before this one, so Changelog.md will be correct. :)
</details>
Done.

---

*[.github/PULL_REQUEST_TEMPLATE.md, line 15 at r1](https://reviewable.io:443/reviews/powershell/xsqlserver/191#-KX6wbbMbUBc2piAi3OJ:-KXAQ7ZlE0p9tM7Ai2GG:b-896fix) ([raw file](https://github.com/powershell/xsqlserver/blob/31b2fdac94c81e0d4f8441b113fb1ca003df00c9/.github/PULL_REQUEST_TEMPLATE.md#L15)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary>
> > Added/updated documentation and descriptions 
> 
> Change to 'Added/updated documentation, comment-based help and descriptions in .schema.mof files where appropriate?'
</details>
Done.

---

*[.github/PULL_REQUEST_TEMPLATE.md, line 19 at r1](https://reviewable.io:443/reviews/powershell/xsqlserver/191#-KX6y4O97K7PGnaoDYPl:-KXAQ8J8rswtCyTfFiKz:b-896fix) ([raw file](https://github.com/powershell/xsqlserver/blob/31b2fdac94c81e0d4f8441b113fb1ca003df00c9/.github/PULL_REQUEST_TEMPLATE.md#L19)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary>
> Also add a section after the list that say something like the following. Is the below test understandable? 
> 
> This PR fixes the following issues (use format `Fixes #123`): 
> 
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xsqlserver/191)*

**Comment by johlju** [comment]
So awesome you though of adding these.  This will really help a lot!  :smiley: 
I did not know about this functionality. 

Just a few more tweaks.

---

Review status: all files reviewed at latest revision, 9 unresolved discussions.

---

*[.github/PULL_REQUEST_TEMPLATE.md, line 14 at r1](https://reviewable.io:443/reviews/powershell/xsqlserver/191#-KX6wlIn8uFBWKV4FWoN:-KXBoUA5i5mCeaQt_Rzk:b-dgiwtc) ([raw file](https://github.com/powershell/xsqlserver/blob/31b2fdac94c81e0d4f8441b113fb1ca003df00c9/.github/PULL_REQUEST_TEMPLATE.md#L14)):*
<details><summary><i>Previously, luigilink (Jean-Cyril Drouhin) wrote…</i></summary>
> Done.
</details>
Actually, I saw now that the file is called CHANGELOG.md with all capital letter, so please change to that. :)

---

*[.github/PULL_REQUEST_TEMPLATE.md, line 15 at r2](https://reviewable.io:443/reviews/powershell/xsqlserver/191#-KXBoDNbZzY-JYd_t7mD:-KXBoDNbZzY-JYd_t7mE:b-oq9cq5) ([raw file](https://github.com/powershell/xsqlserver/blob/fd08020c1060868eeee6f0d9ee7d1adeb9e8540c/.github/PULL_REQUEST_TEMPLATE.md#L15)):*
> [Replace this with the list of issues (use format Fixes #123)]

When I see this in context, maybe this would be better? 

[Replace this with the list of issues. Use format: Fixes #123]

---

*[.github/PULL_REQUEST_TEMPLATE.md, line 21 at r2](https://reviewable.io:443/reviews/powershell/xsqlserver/191#-KXBowbdykHOuY-CwMp2:-KXBowbdykHOuY-CwMp3:b3nxgj0) ([raw file](https://github.com/powershell/xsqlserver/blob/fd08020c1060868eeee6f0d9ee7d1adeb9e8540c/.github/PULL_REQUEST_TEMPLATE.md#L21)):*
> ```Markdown
> - [ ] Examples appropriately updated?
> - [ ] New/changed code adheres to [Style Guidelines]?(https://github.com/PowerShell/DscResources/blob/master/StyleGuidelines.md)?
> - [ ] [Unit and Integration tests](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md) created/updated where possible?
> ```

I feel we can't enforce Integration tests just yet, so until we do, maybe change `[Unit and Integration tests]` to `[Unit and (optional) Integration tests]`? 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xsqlserver/191#-:-KXBpdUq7BeOvMpcPfRM:b-kq06o0)*

**Comment by luigilink** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 9 unresolved discussions.

---

*[.github/CONTRIBUTING.md, line 1 at r1](https://reviewable.io:443/reviews/powershell/xsqlserver/191#-KX6tY3W3YrGyflSDELK:-KXCClb6SldrFClJ7dds:b-896fix) ([raw file](https://github.com/powershell/xsqlserver/blob/31b2fdac94c81e0d4f8441b113fb1ca003df00c9/.github/CONTRIBUTING.md#L1)):*
<details><summary><i>Previously, luigilink (Jean-Cyril Drouhin) wrote…</i></summary>
> Done.
</details>
Done.

---

*[.github/ISSUE_TEMPLATE.md, line 7 at r1](https://reviewable.io:443/reviews/powershell/xsqlserver/191#-KX6u-OdUQ0YIdm4BCsX:-KXCCm9FG9ikbxytpcjo:b-896fix) ([raw file](https://github.com/powershell/xsqlserver/blob/31b2fdac94c81e0d4f8441b113fb1ca003df00c9/.github/ISSUE_TEMPLATE.md#L7)):*
<details><summary><i>Previously, luigilink (Jean-Cyril Drouhin) wrote…</i></summary>
> Done.
</details>
Done.

---

*[.github/ISSUE_TEMPLATE.md, line 9 at r1](https://reviewable.io:443/reviews/powershell/xsqlserver/191#-KX6vJ2frg76j4VlQkE_:-KXCCmm5eiSrncdi6PCo:b-896fix) ([raw file](https://github.com/powershell/xsqlserver/blob/31b2fdac94c81e0d4f8441b113fb1ca003df00c9/.github/ISSUE_TEMPLATE.md#L9)):*
<details><summary><i>Previously, luigilink (Jean-Cyril Drouhin) wrote…</i></summary>
> Done.
</details>
Done.

---

*[.github/ISSUE_TEMPLATE.md, line 11 at r1](https://reviewable.io:443/reviews/powershell/xsqlserver/191#-KX6vn6_HIOEuAdlU42s:-KXCCgVJTqVawH-fUknc:b-896fix) ([raw file](https://github.com/powershell/xsqlserver/blob/31b2fdac94c81e0d4f8441b113fb1ca003df00c9/.github/ISSUE_TEMPLATE.md#L11)):*
<details><summary><i>Previously, luigilink (Jean-Cyril Drouhin) wrote…</i></summary>
> Done.
</details>
Done.

---

*[.github/PULL_REQUEST_TEMPLATE.md, line 14 at r1](https://reviewable.io:443/reviews/powershell/xsqlserver/191#-KX6wlIn8uFBWKV4FWoN:-KXCCiWDVK3aPgt3VvtS:b-896fix) ([raw file](https://github.com/powershell/xsqlserver/blob/31b2fdac94c81e0d4f8441b113fb1ca003df00c9/.github/PULL_REQUEST_TEMPLATE.md#L14)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary>
> Actually, I saw now that the file is called CHANGELOG.md with all capital letter, so please change to that. :)
</details>
Done.

---

*[.github/PULL_REQUEST_TEMPLATE.md, line 15 at r1](https://reviewable.io:443/reviews/powershell/xsqlserver/191#-KX6wbbMbUBc2piAi3OJ:-KXCCjBNXDTPhcBoiRCf:b-896fix) ([raw file](https://github.com/powershell/xsqlserver/blob/31b2fdac94c81e0d4f8441b113fb1ca003df00c9/.github/PULL_REQUEST_TEMPLATE.md#L15)):*
<details><summary><i>Previously, luigilink (Jean-Cyril Drouhin) wrote…</i></summary>
> Done.
</details>
Done.

---

*[.github/PULL_REQUEST_TEMPLATE.md, line 19 at r1](https://reviewable.io:443/reviews/powershell/xsqlserver/191#-KX6y4O97K7PGnaoDYPl:-KXCCkM4WSO6MXOwPC3-:b-896fix) ([raw file](https://github.com/powershell/xsqlserver/blob/31b2fdac94c81e0d4f8441b113fb1ca003df00c9/.github/PULL_REQUEST_TEMPLATE.md#L19)):*
<details><summary><i>Previously, luigilink (Jean-Cyril Drouhin) wrote…</i></summary>
> Done.
</details>
Done.

---

*[.github/PULL_REQUEST_TEMPLATE.md, line 15 at r2](https://reviewable.io:443/reviews/powershell/xsqlserver/191#-KXBoDNbZzY-JYd_t7mD:-KXCChu0B65Jicu624Dz:b-896fix) ([raw file](https://github.com/powershell/xsqlserver/blob/fd08020c1060868eeee6f0d9ee7d1adeb9e8540c/.github/PULL_REQUEST_TEMPLATE.md#L15)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary>
> > [Replace this with the list of issues (use format Fixes #123)]
> 
> When I see this in context, maybe this would be better? 
> 
> [Replace this with the list of issues. Use format: Fixes #123]
</details>
Done.

---

*[.github/PULL_REQUEST_TEMPLATE.md, line 21 at r2](https://reviewable.io:443/reviews/powershell/xsqlserver/191#-KXBowbdykHOuY-CwMp2:-KXCCjif7wutT9iJaL6l:b-896fix) ([raw file](https://github.com/powershell/xsqlserver/blob/fd08020c1060868eeee6f0d9ee7d1adeb9e8540c/.github/PULL_REQUEST_TEMPLATE.md#L21)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary>
> I feel we can't enforce Integration tests just yet, so until we do, maybe change `[Unit and Integration tests]` to `[Unit and (optional) Integration tests]`? 
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xsqlserver/191)*

**Comment by johlju** [comment]
:lgtm:

---

Reviewed 2 of 3 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 9 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xsqlserver/191#-:-KXCPLV0cZjlhRwZlZvv:bnfp4nl)*

**Pull request merged**
