### PR TITLE
BREAKING CHANGE: xSQLServerSetup: Rename parameter PID to ProductKey (fixes #332)

### LINKED ISSUE #332: xSQLServerSetup: should not use PID to store the Product Key
**Details of the scenario you try and problem that is occurring:**
XSQLServerSetup uses the parameter PID to store the product key for SQL Server. However, $PID is an automatic variable used internally by PowerShell to store the Process ID. This variable is read-only, although in DSC context it does get overwritten. This causes issues while debugging the resource, as the $PID variable no longer holds the Process ID of the process.

**The DSC configuration that is using the resource (as detailed as possible):**
All configurations using PID parameter to specify Product ID.

**Version of the Operating System, SQL Server and PowerShell the DSC Target Node is running:**
Any

**Version of the DSC module you're using, or 'dev' if you're using current dev branch:**
4.0.0.0

**Suggestion**
Rename PID to ProductKey, that way it will not collide with the automatic variable $PID

### PR DESCRIPTION
**Pull request by danielboth**
Rename parameter PID to ProductKey to avoid collision with automatic variable $PID.

This Pull Request (PR) fixes the following issues:
Fixes #332 

- [X] Change details added to Unreleased section of CHANGELOG.md?
- [X] Added/updated documentation, comment-based help and descriptions in .schema.mof files where appropriate?
- [N/A] Examples appropriately updated?
- [X] New/changed code adheres to [Style Guidelines](https://github.com/PowerShell/DscResources/blob/master/StyleGuidelines.md)?
- [X] [Unit and (optional) Integration tests](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md) created/updated where possible?

---
This change is [Reviewable](https://reviewable.io/reviews/powershell/xsqlserver/337)

### CODE REVIEW

**Comment by johlju** [comment]
@danielboth The test failed because you forgot to change the schema.mof. :)
https://ci.appveyor.com/project/PowerShell/xsqlserver/build/4.0.765.0#L270

Please change, and then make sure the tests passes.

**Comment by johlju** [comment]
@danielboth Could you please make sure this change is tested?

If you add `ProductKey` with a fake product key to this hash table
https://github.com/PowerShell/xSQLServer/blob/dev/Tests/Unit/MSFT_xSQLServerSetup.Tests.ps1#L2414

And then add PID with the fake product key to this hash table (so that we know PID is returned with the correct value).
https://github.com/PowerShell/xSQLServer/blob/dev/Tests/Unit/MSFT_xSQLServerSetup.Tests.ps1#L2440

That should work I think. 😄 

Thanks!

**Comment by danielboth** [comment]
@johlju Test is added. I had to add the parameter to the install of SMSS / ADV_SSMS as well, I'm assuming these will install fine when a product key is used in the commandline. I didn't actually test it yet though, do you know by any change?

**Comment by johlju** [comment]
@danielboth If PID is added as a setup argument (in the test) I feel comfortable that it will work. I will review this now!

**Comment by johlju** [comment]
Great work with this! Thanks for fixing the tests, and good that you added them to SSMS and ADV_SSMS too.

Just one small thing, then we can merge. 

---

Reviewed 3 of 3 files at r1, 1 of 1 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[CHANGELOG.md, line 38 at r3](https://reviewable.io:443/reviews/powershell/xsqlserver/337#-KbL_mXEtARc-_B3UfIo:-KbL_mXEtARc-_B3UfIp:b-9xbh3o) ([raw file](https://github.com/powershell/xsqlserver/blob/5f8342a9ec10927c64627132598542db5bd238fc/CHANGELOG.md#L38)):*
> ```Markdown
>       - Function `NetUse` has been replaced with `New-SmbMapping` and `Remove-SmbMapping`.
>   - Renamed function `GetSQLVersion` to `Get-SqlMajorVersion`.
>   - Renamed parameter PID to ProductKey to avoid collision with automatic variable $PID
> ```

Please add 'BREAKING CHANGE: ' to this change.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xsqlserver/337#-:-KbLaiy2kJALGZfZvqIk:bwclea1)*

**Comment by johlju** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xsqlserver/337#-:-KbLhHPRAPVMvtt1XX_N:bnfp4nl)*

**Pull request merged**
