### PR TITLE
xSQLServerScript: Fixing PSSA errors

### LINKED ISSUE #728: xSQLServerScript: PSScriptAnalyzer errors need to be fixed
**Details of the scenario you tried and the problem that is occurring:**
The following PSScriptAnalyzer errors need to be fixed:
MSFT_xSQLServerScript.psm1 (Line 68): Non-mandatory parameters must use the correct format [Parameter()] for the parameter attribute. See https://github.com/PowerShell/DscResources/blob/master/StyleGuidelines.md#correct-format-for-parameter-block
MSFT_xSQLServerScript.psm1 (Line 156): Non-mandatory parameters must use the correct format [Parameter()] for the parameter attribute. See https://github.com/PowerShell/DscResources/blob/master/StyleGuidelines.md#correct-format-for-parameter-block
MSFT_xSQLServerScript.psm1 (Line 231): Non-mandatory parameters must use the correct format [Parameter()] for the parameter attribute. See https://github.com/PowerShell/DscResources/blob/master/StyleGuidelines.md#correct-format-for-parameter-block
MSFT_xSQLServerScript.psm1 (Line 301): Non-mandatory parameters must use the correct format [Parameter()] for the parameter attribute. See https://github.com/PowerShell/DscResources/blob/master/StyleGuidelines.md#correct-format-for-parameter-block

**The DSC configuration that is using the resource (as detailed as possible):**
n/a

**Version of the Operating System, SQL Server and PowerShell the DSC Target Node is running:**
n/a

**What module (SqlServer or SQLPS) and which version of the module the DSC Target Node is running:**
n/a

**Version of the DSC module you're using, or 'dev' if you're using current dev branch:**
Dev

### PR DESCRIPTION
**Pull request by ChrisLGardner**
**Pull Request (PR) description**
As raised in #728 there are various ScriptAnalyzer errors from the parameters being marked as Mandatory = $false, this resolves those errors.

**This Pull Request (PR) fixes the following issues:**
Fixes #728 

**Task list:**
- [x] Change details added to Unreleased section of CHANGELOG.md?
- [ ] Added/updated documentation, comment-based help and descriptions in .schema.mof files where appropriate?
- [ ] Examples appropriately updated?
- [ ] New/changed code adheres to [Style Guidelines](https://github.com/PowerShell/DscResources/blob/master/StyleGuidelines.md)?
- [ ] [Unit and (optional) Integration tests](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md) created/updated where possible?

---
This change is [Reviewable](https://reviewable.io/reviews/powershell/xsqlserver/764)

### CODE REVIEW

**Comment by johlju** [comment]
@ChrisLGardner Thanks for fixing this and the others! Please add this change to the CHANGELOG.md.

**Comment by ChrisLGardner** [comment]
Done.

**Comment by johlju** [comment]
Reviewed 1 of 1 files at r1, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[CHANGELOG.md, line 55 at r3](https://reviewable.io:443/reviews/powershell/xsqlserver/764#-KrdyWe2MEk8-60iY-aR:-KrdyWe2MEk8-60iY-aS:b75z6uk) ([raw file](https://github.com/powershell/xsqlserver/blob/f5691db119e46a61d9b619d6dc0674fce58649c3/CHANGELOG.md#L55)):*
> [Issue #728]

Please use lower-case 'i' in issue to be consequent with the other entries.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xsqlserver/764)*

**Comment by johlju** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[CHANGELOG.md, line 55 at r3](https://reviewable.io:443/reviews/powershell/xsqlserver/764#-KrdywVD9L8jfktAmpb_:-KrdywVD9L8jfktAmpba:bd90byk) ([raw file](https://github.com/powershell/xsqlserver/blob/f5691db119e46a61d9b619d6dc0674fce58649c3/CHANGELOG.md#L55)):*
> - - 

Please remove on of the dashes here as well.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xsqlserver/764)*

**Comment by ChrisLGardner** [comment]
Review status: 1 of 2 files reviewed at latest revision, 2 unresolved discussions.

---

*[CHANGELOG.md, line 55 at r3](https://reviewable.io:443/reviews/powershell/xsqlserver/764#-KrdyWe2MEk8-60iY-aR:-Kre-OEokG3xnaULb8pC:b-896fix) ([raw file](https://github.com/powershell/xsqlserver/blob/f5691db119e46a61d9b619d6dc0674fce58649c3/CHANGELOG.md#L55)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

> [Issue #728]

Please use lower-case 'i' in issue to be consequent with the other entries.
</blockquote></details>

Done.

---

*[CHANGELOG.md, line 55 at r3](https://reviewable.io:443/reviews/powershell/xsqlserver/764#-KrdywVD9L8jfktAmpb_:-Kre-OXqL8nQ2T2RIyXQ:b-896fix) ([raw file](https://github.com/powershell/xsqlserver/blob/f5691db119e46a61d9b619d6dc0674fce58649c3/CHANGELOG.md#L55)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

> - - 

Please remove on of the dashes here as well.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xsqlserver/764)*

**Comment by johlju** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xsqlserver/764#-:-Kre71U97lznNvbiCNQd:bnfp4nl)*

**Pull request merged**
