### PR TITLE
BREAKING CHANGE: xSQLServerRSConfig: remove $SQLAdminCredential parameter

### PR DESCRIPTION
**Pull request by bozho**
**Pull Request (PR) description**
[Replace this with a description of your pull request]

**This Pull Request (PR) fixes the following issues:**
[Replace this with the list of issues or n/a. Use format: Fixes #123]

**Task list:**
- [x] Change details added to Unreleased section of CHANGELOG.md?
- [x] Added/updated documentation, comment-based help and descriptions in .schema.mof files where appropriate?
- [ ] Examples appropriately updated?
- [ ] New/changed code adheres to [Style Guidelines](https://github.com/PowerShell/DscResources/blob/master/StyleGuidelines.md)?
- [ ] [Unit and (optional) Integration tests](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md) created/updated where possible?

---
This change is [Reviewable](https://reviewable.io/reviews/powershell/xsqlserver/573)

### CODE REVIEW

**Comment by bozho** [comment]
I've mentioned the first question I have for this PR in #568  comments:

We still need to use CredSSP authentication when running Invoke-Sqlcmd with $SQLAdminCredential using Invoke-Command, even though we're running it on the same machine. I don't know how this behaves when run in a domain, but running it on a non-domain machine requires enabling/configuring CredSSP - I'm not sure if we should consider this to be within the remit of this resource, or just document the fact that CredSSP needs to be enabled and configured.

**Comment by bozho** [comment]
The second question I have is: do we actually need to use $SQLAdminCredential for anything other than executing RS SQL?

It looks like some of the WMI calls need CredSSP authentication if Invoke-Command is using different credentials, but I'm not sure what's the benefit over simply running everything under system account and optionally executing SQL under different credentials.

**Comment by johlju** [comment]
Regarding your first question. xSQLServerScript uses `Invoke-Sqlcmd`, and when I running that resource I don't need to use CredSSP (unless it is on default, which I think not?). I  have not run it on a non-domain joined machine.
So since that is a requirement for using this resource for a non-domain joined machine, could you add that requirement to the resource description in the README.md? 

Regarding the second question. If the resource works running as SYSTEM, and Invoke-Sqlcmd is using another credentials to run SQL, then I don't see a problem to do it that way. Invoke-Sqlcmd should only use  `$SQLAdminCredential` if it is set. Because if built-in `PsDscRunAsCredential` is set then the resource run in that user context and the all calls should be made in that context without impersonating using `$SQLAdminCredential`.

**Comment by johlju** [comment]
By the way, the WMI calls should be replaced by CIM, but that is a separate issue (issue #264). But if it would help in anyway for this.

**Comment by bozho** [comment]
I'll do a quick xSQLServerScript  test on my non-domain machine tomorrow.

If we can run any resource under a different set of credentials using ```PsDscRunAsCredential```, do we even need ```$SQLAdminCredential```? Would there ever be a scenario where you'd need to run this resource as one user and have the need to execute SSRS initialisation queries as another? I would expect you'd either use the system account (default DSC) or an admin-level account for everything. Introducing yet another set of credentials just complicates their management...

**Comment by johlju** [comment]
Likely the reason parameter SQLAdminCredential exist is because the resource needs with WMF 4.0 to be able to logon to SQL Server. Only WMF 5.0 and above supports PsDscRunAsCredential. And this resource has yet been updated to suppport PsDscRunAsCredential.
So on WMF 4.0 the resource can use SYSTEM for WMI (CIM) queries and SQLAdminCredential for SQL Server access (SYSTEM does not normally have that access). 
But on WMF 5.0 and above, same method as WMF 4.0 can be used, but here we should support  PsDscRunAsCredential for both WMI and SQL Server access.

I created an issue [Remove support for WMF 4.0 (PowerShell 4.0)](https://github.com/PowerShell/xSQLServer/issues/574) regarding PowerShell 4.0 support (for the module).

**Comment by johlju** [comment]
Great that you can run a test with xSQLServerScript!

**Comment by bozho** [comment]
Looking at xSQLServerScript examples, the one using SQL authentication uses the resource's ```Credential``` parameter. Looking at the xSQLServerScript code, ```Username``` and ```Password``` from the ```Credential``` parameter are passed in to ```Invoke-Sqlcmd``` as ```$Username``` and ```$Password``` parameters, which are used only for SQL authentication.

The example for Windows authentication uses PsDscRunAsCredential, so that can only be used in PS 5.x.

I'll try running xSQLServerRSConfig using PsDscRunAsCredential  with no CredSSP enabled to see what happens.

**Comment by johlju** [comment]
Most resources works only with WMF 5.x. Unless what they do works when running as the SYSTEM account.

Great that you test it without CredSSP. Depending on the result we might need to add an issue to change the description on that resource that CredSSP is needed for non-domain joined machines.

**Comment by bozho** [comment]
Ok, looks like ```PsDscRunAsCredential``` works fine on a non-domain box with no CredSSP configured.

Here's the scenario:
1. Prepare a configuration for the remote test machine that uses ```PsDscRunAsCredential```, pass in a test account
2. Publish and run the configuration on the remote machine with no test account created - ```xSQLServerRSConfig``` resource execution fails, as expected
3. Create the test account, but don't grant it access to SQL server. ```xSQLServerRSConfig``` runs, but barfs at SQL query execution, as expected
4. Grant sysadmin SQL Server access to the test account. ```xSQLServerRSConfig``` runs without errors. Yay!
5. Finally, if I remove all the ```Invoke-Command```s, it still works fine :)

In light of this, can we just remove ```$SQLAdminCredential``` and ```Invoke-Command``` usages?

**Comment by johlju** [comment]
@randomnote1 just said that when he sends in his class-based resource, that will make the module require WMF 5.0 (issue #574). So there is no need to keep WMF 4.0 support. 

So I agree that we can remove $SQLAdminCredential.

**Comment by johlju** [comment]
Also agree that we can remove `Invoke-Command`.

**Comment by johlju** [comment]
I labeled this a breaking change. Please change the title when you removed the parameter.

**Comment by bozho** [comment]
Changed title.

**Comment by johlju** [comment]
@bozho PR #571 is merged. Please rebase this one.

**Comment by bozho** [comment]
@johlju Rebased. Sorry for the delay, had a Bank holiday yesterday :)

**Comment by bozho** [comment]
Hi, are you ok with me rebasing this on top of current dev?

**Comment by bozho** [comment]
... or should we just merge stuff? I know the history will look ugly until the patch goes into dev, but with rebasing we're risking overwriting each other's work...

**Comment by johlju** [comment]
I will review this one and merge it. I just wanted to wait for the release of 7.1.0.0. I did not want to add a breaking change so close to release. 
I will review this tonight.

**Comment by johlju** [comment]
@bozho Sorry, my bad, this one must be rebase against dev. Then all the commits you have done in this working branch will be re-played on to of the dev-version.

Also, make sure the change notes goes back under the unreleased section, and not the 7.1.0.0 version number. It always a problem after a release.

**Comment by bozho** [comment]
Ok, I'll rebase everything carefully :)

**Comment by bozho** [comment]
Rebased. Phew!

**Comment by johlju** [comment]
@bozho Great work! I will review this one.

**Comment by johlju** [comment]
Just a few minor comments.

---

Reviewed 3 of 4 files at r3, 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[CHANGELOG.md, line 6 at r4](https://reviewable.io:443/reviews/powershell/xsqlserver/573#-Kle3rxCSbUA2vl97r8c:-Kle3rxCSbUA2vl97r8d:b-nbs6tj) ([raw file](https://github.com/powershell/xsqlserver/blob/78bcbdc129c3e6a87fff6ad735ff6225f6b14ea1/CHANGELOG.md#L6)):*
> ```Markdown
> 
> - Changes to xSQLServerRSConfig
>   - BREAKING CHANGE: removed $SQLAdminCredential parameter. Use common parameter PsDscRunAsCredential (WMF 5.0+) to run the resource under different credentials. PsDscRunAsCredential Windows account must be a sysadmin on SQL Server (issue #568).
> ```

Couyld you please add this requirement to the section requirements for the resource in the README.md?

And could you add in which SQL Server instance? The instance being configured, or the instance where the reporting services databases should be created?

---

*[CHANGELOG.md, line 6 at r4](https://reviewable.io:443/reviews/powershell/xsqlserver/573#-Kle4_F3UdmPuN5nUjUu:-Kle4_F3UdmPuN5nUjUv:bak87a6) ([raw file](https://github.com/powershell/xsqlserver/blob/78bcbdc129c3e6a87fff6ad735ff6225f6b14ea1/CHANGELOG.md#L6)):*
> removed $SQLAdminCredential parameter.

Could you change to 'Removed' , upper 'R'.
Could you also add something like 'it was removed since it was only used for WMF 4.0 support.'?

---

*[CHANGELOG.md, line 6 at r4](https://reviewable.io:443/reviews/powershell/xsqlserver/573#-Kle5GDFjQK6yGdFIq1U:-Kle5GDGHItBPLmuuGuE:b-3sry58) ([raw file](https://github.com/powershell/xsqlserver/blob/78bcbdc129c3e6a87fff6ad735ff6225f6b14ea1/CHANGELOG.md#L6)):*
> ```Markdown
> 
> - Changes to xSQLServerRSConfig
>   - BREAKING CHANGE: removed $SQLAdminCredential parameter. Use common parameter PsDscRunAsCredential (WMF 5.0+) to run the resource under different credentials. PsDscRunAsCredential Windows account must be a sysadmin on SQL Server (issue #568).
> ```

Please also add that the resource no longer uses Invoke-Command. And that Invoke-Command was only used to impersonate the user set in the parameter SQLAdminCredential and needed CredSSP to be configured to work.

Not I'm unsure about all of that above, so please correct me if I'm wrong.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xsqlserver/573#-:-Kle6BI3hqWzZaAwN-RJ:byqjw8p)*

**Comment by bozho** [comment]
Review status: 2 of 4 files reviewed at latest revision, 3 unresolved discussions.

---

*[CHANGELOG.md, line 6 at r4](https://reviewable.io:443/reviews/powershell/xsqlserver/573#-Kle3rxCSbUA2vl97r8c:-KlrZabYdqFqGnKjVDhA:b4t8ksk) ([raw file](https://github.com/powershell/xsqlserver/blob/78bcbdc129c3e6a87fff6ad735ff6225f6b14ea1/CHANGELOG.md#L6)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

Couyld you please add this requirement to the section requirements for the resource in the README.md?

And could you add in which SQL Server instance? The instance being configured, or the instance where the reporting services databases should be created?
</blockquote></details>

Hm, this comment got me thinking. `PsDscRunAsCredential` parameter refers to the user that will be used to execute the resource.

This is fine if you're deploying RS databases to a local SQL server, or to a remote server and your credential is a domain user with correct permissions on the remote SQL server.

However, if you need to deploy RS databases to a remote server without a domain user, you'll need to specify an SQL account for `Invoke-Sqlcmd` cmdlet. Should we actually keep `$SQLAdminCredential` parameter for that scenario? It would still be a breaking change, as we'd be changing the parameter's usage...

---

*[CHANGELOG.md, line 6 at r4](https://reviewable.io:443/reviews/powershell/xsqlserver/573#-Kle4_F3UdmPuN5nUjUu:-Klrc5a4kbCyFjLsoeDl:b-896fix) ([raw file](https://github.com/powershell/xsqlserver/blob/78bcbdc129c3e6a87fff6ad735ff6225f6b14ea1/CHANGELOG.md#L6)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

> removed $SQLAdminCredential parameter.

Could you change to 'Removed' , upper 'R'.
Could you also add something like 'it was removed since it was only used for WMF 4.0 support.'?
</blockquote></details>

Done.

---

*[CHANGELOG.md, line 6 at r4](https://reviewable.io:443/reviews/powershell/xsqlserver/573#-Kle5GDFjQK6yGdFIq1U:-Klre46VZR5QxLvFMSjY:b-uv6c0q) ([raw file](https://github.com/powershell/xsqlserver/blob/78bcbdc129c3e6a87fff6ad735ff6225f6b14ea1/CHANGELOG.md#L6)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

Please also add that the resource no longer uses Invoke-Command. And that Invoke-Command was only used to impersonate the user set in the parameter SQLAdminCredential and needed CredSSP to be configured to work.

Not I'm unsure about all of that above, so please correct me if I'm wrong.
</blockquote></details>

Done.

I've added a small paragraph about removing Invoke-Command and CredSSP under that bullet.

This also got me thinking that we should probably suggest a line length limit in .md files. Ordinary line breaks don't affect rendering, but make it easier to read the "source".

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xsqlserver/573)*

**Comment by johlju** [comment]
Reviewed 1 of 2 files at r5.
Review status: 3 of 4 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[CHANGELOG.md, line 6 at r4](https://reviewable.io:443/reviews/powershell/xsqlserver/573#-Kle5GDFjQK6yGdFIq1U:-Klsyj7EK8v__AFXYBUa:b-u2lwlr) ([raw file](https://github.com/powershell/xsqlserver/blob/78bcbdc129c3e6a87fff6ad735ff6225f6b14ea1/CHANGELOG.md#L6)):*
<details><summary><i>Previously, bozho (Marko Bozikovic) wrote…</i></summary><blockquote>

Done.

I've added a small paragraph about removing Invoke-Command and CredSSP under that bullet.

This also got me thinking that we should probably suggest a line length limit in .md files. Ordinary line breaks don't affect rendering, but make it easier to read the "source".
</blockquote></details>

OK. 

We have a common test for line length in the DscResource.Tests (which is run in AppVeyor). But it is not turned on for this resource yet since we still have some technical debt. See issue 98 over at DscResource.Tests repository.
We should absolutely enforce MD013 https://github.com/DavidAnson/markdownlint/blob/master/doc/Rules.md#md013 even now if we can

---

*[CHANGELOG.md, line 6 at r4](https://reviewable.io:443/reviews/powershell/xsqlserver/573#-Kle3rxCSbUA2vl97r8c:-Klt21gh04L2-6PuNQqh:b-mta737) ([raw file](https://github.com/powershell/xsqlserver/blob/78bcbdc129c3e6a87fff6ad735ff6225f6b14ea1/CHANGELOG.md#L6)):*
<details><summary><i>Previously, bozho (Marko Bozikovic) wrote…</i></summary><blockquote>

Hm, this comment got me thinking. `PsDscRunAsCredential` parameter refers to the user that will be used to execute the resource.

This is fine if you're deploying RS databases to a local SQL server, or to a remote server and your credential is a domain user with correct permissions on the remote SQL server.

However, if you need to deploy RS databases to a remote server without a domain user, you'll need to specify an SQL account for `Invoke-Sqlcmd` cmdlet. Should we actually keep `$SQLAdminCredential` parameter for that scenario? It would still be a breaking change, as we'd be changing the parameter's usage...
</blockquote></details>

Since xSQLServerSetup cannot install Reporting Services using SQL account, so you still need domain credentials (or a local user) to run the service, thus that account is used to logon to the database. So seems very odd to use a SQL account to configure the database, when the service will always need Windows athentication. 
Of course, there might be a scenario where the login to create the DB is a SQL account. So you are correct, for that occasion we would need a credential parameter. But I don't think it should be named SQLAdminCredential, but rather RSSQLCredential. But then RSSQLCredential must work with both SQL Auth and Windows Auth. So the user can specify a different login for the database instance, than set in PsDscRunAsCredential. 

If you want to add a new credential object for this scenario, I'm all for it. :smile: 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xsqlserver/573)*

**Comment by bozho** [comment]
Review status: 3 of 4 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[CHANGELOG.md, line 6 at r4](https://reviewable.io:443/reviews/powershell/xsqlserver/573#-Kle3rxCSbUA2vl97r8c:-Klt6KiqHYwsU0LiSbfk:b-hojaja) ([raw file](https://github.com/powershell/xsqlserver/blob/78bcbdc129c3e6a87fff6ad735ff6225f6b14ea1/CHANGELOG.md#L6)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

Since xSQLServerSetup cannot install Reporting Services using SQL account, so you still need domain credentials (or a local user) to run the service, thus that account is used to logon to the database. So seems very odd to use a SQL account to configure the database, when the service will always need Windows athentication. 
Of course, there might be a scenario where the login to create the DB is a SQL account. So you are correct, for that occasion we would need a credential parameter. But I don't think it should be named SQLAdminCredential, but rather RSSQLCredential. But then RSSQLCredential must work with both SQL Auth and Windows Auth. So the user can specify a different login for the database instance, than set in PsDscRunAsCredential. 

If you want to add a new credential object for this scenario, I'm all for it. :smile: 
</blockquote></details>

We can't make `RSSQLCredential` parameter work with both SQL and Windows authentications for Invoke-Sqlcmd, since it only provides `-Username` and `-Password` parameters, which are used to pass in SQL authentication parameters.

If we decide to add the `RSSQLCredential` parameter, we should make it clear in the documentation that it's only for SQL authentication against SQL server when initialising RS databases.

---

*[CHANGELOG.md, line 6 at r4](https://reviewable.io:443/reviews/powershell/xsqlserver/573#-Kle5GDFjQK6yGdFIq1U:-Klt7DMNrN2W3cEsOIGR:b-896fix) ([raw file](https://github.com/powershell/xsqlserver/blob/78bcbdc129c3e6a87fff6ad735ff6225f6b14ea1/CHANGELOG.md#L6)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

OK. 

We have a common test for line length in the DscResource.Tests (which is run in AppVeyor). But it is not turned on for this resource yet since we still have some technical debt. See issue 98 over at DscResource.Tests repository.
We should absolutely enforce MD013 https://github.com/DavidAnson/markdownlint/blob/master/doc/Rules.md#md013 even now if we can

</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xsqlserver/573)*

**Comment by johlju** [comment]
Reviewed 1 of 1 files at r6.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[CHANGELOG.md, line 6 at r4](https://reviewable.io:443/reviews/powershell/xsqlserver/573#-Kle3rxCSbUA2vl97r8c:-Klt7msSOXV79g5THPCf:blvz1ks) ([raw file](https://github.com/powershell/xsqlserver/blob/78bcbdc129c3e6a87fff6ad735ff6225f6b14ea1/CHANGELOG.md#L6)):*
<details><summary><i>Previously, bozho (Marko Bozikovic) wrote…</i></summary><blockquote>

We can't make `RSSQLCredential` parameter work with both SQL and Windows authentications for Invoke-Sqlcmd, since it only provides `-Username` and `-Password` parameters, which are used to pass in SQL authentication parameters.

If we decide to add the `RSSQLCredential` parameter, we should make it clear in the documentation that it's only for SQL authentication against SQL server when initialising RS databases.
</blockquote></details>

Ah, of course. Yes that sounds like a plan. 

Could you please create an issue for this, what was said here, for the RSSQLCredential parameter? I would be grateful.

Then it's up to you if you want to add it to this PR. Otherwise you, or someone else, can take it on at a later date in a different PR. I will let you decide. :smile: 

For the current implementation I think we should add to the documentation (requirements section for the resource) that PsDscRunAsCredential must have permission to connect and create the databases on the in SQL Instance specified in the RS* parameters. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xsqlserver/573)*

**Comment by bozho** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[CHANGELOG.md, line 6 at r4](https://reviewable.io:443/reviews/powershell/xsqlserver/573#-Kle3rxCSbUA2vl97r8c:-Klwc1hBYuNTGlAyu79i:bp062jg) ([raw file](https://github.com/powershell/xsqlserver/blob/78bcbdc129c3e6a87fff6ad735ff6225f6b14ea1/CHANGELOG.md#L6)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

Ah, of course. Yes that sounds like a plan. 

Could you please create an issue for this, what was said here, for the RSSQLCredential parameter? I would be grateful.

Then it's up to you if you want to add it to this PR. Otherwise you, or someone else, can take it on at a later date in a different PR. I will let you decide. :smile: 

For the current implementation I think we should add to the documentation (requirements section for the resource) that PsDscRunAsCredential must have permission to connect and create the databases on the in SQL Instance specified in the RS* parameters. 
</blockquote></details>

Ok, I'll add a separate issue and not add it to this PR. I'm being a bit selfish - I'd like this PR to go in as son as possible :)

I'll update the README with a PsDscRunAsCredential note.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xsqlserver/573)*

**Comment by bozho** [comment]
Review status: 3 of 4 files reviewed at latest revision, 1 unresolved discussion.

---

*[CHANGELOG.md, line 6 at r4](https://reviewable.io:443/reviews/powershell/xsqlserver/573#-Kle3rxCSbUA2vl97r8c:-KlwqwWNQ91uiJbjjn0c:b-896fix) ([raw file](https://github.com/powershell/xsqlserver/blob/78bcbdc129c3e6a87fff6ad735ff6225f6b14ea1/CHANGELOG.md#L6)):*
<details><summary><i>Previously, bozho (Marko Bozikovic) wrote…</i></summary><blockquote>

Ok, I'll add a separate issue and not add it to this PR. I'm being a bit selfish - I'd like this PR to go in as son as possible :)

I'll update the README with a PsDscRunAsCredential note.


</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xsqlserver/573)*

**Comment by johlju** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r7.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xsqlserver/573#-:-Klws6s0_B0GRdBO0t5T:bnfp4nl)*

**Pull request merged**
