### PR TITLE
xSQLServerAlwaysOnAvailabilityGroupDatabaseMembership: Refactored as a MOF based resource

### LINKED ISSUE #673: xSQLServerAlwaysOnAvailabilityGroupDatabaseMembership: Logic error in tests
**Details of the scenario you tried and the problem that is occurring:**
When trying to opt-in for common tests, the tests for xSQLServerAlwaysOnAvailabilityGroupDatabaseMembership started to fail..

See errors:
https://ci.appveyor.com/project/johlju/xsqlserver/build/6.0.700.0#L1717

```plaintext
System.InvalidOperationException: Neither PowerShell module SqlServer or SQLPS was found. Unable to run SQL Server cmdlets.
        at <ScriptBlock>, C:\projects\xsqlserver\DscResources\CommonResourceHelper.psm1: line 88
        88:     throw $errorRecordToThrow
```

I think it has to do with this row that loads Import-SQLPSModule in the construct on initialization.
```powershell
    # Load the SQLPS module when the class is initialized
    xSQLServerAlwaysOnAvailabilityGroupDatabaseMembership()
    {
        Import-SQLPSModule
    }
```

That means that this code in the tests fail, because the mocks are only active when the It-block is run, not when BeforeEach is run. 

```powershell
            BeforeEach {
                $databaseMembershipClass = [xSQLServerAlwaysOnAvailabilityGroupDatabaseMembership]::New()
                $databaseMembershipClass.DatabaseName = $mockDatabaseNameParameter.Clone()
                $databaseMembershipClass.SqlServer = 'Server1'
                $databaseMembershipClass.SQLInstanceName = 'MSSQLSERVER'
                $databaseMembershipClass.AvailabilityGroupName = 'AvailabilityGroup1'
            }
```

The downside of having that in the construct is that each call to initialize a new object will call Import-SQLPSModule regardless if it is needed or not.
```powershell
$currentConfiguration = New-Object xSQLServerAlwaysOnAvailabilityGroupDatabaseMembership 
```

But the above seems wrong to, because then the tests would work at all. But they do, unless I opt-in for the common tests. What that does is activate markdown checking and example compiling. And I think it is the last that changes this behavior in some way. 

BUT, I can repeat this error in the command line. When running the test in a new PowerShell window, the tests works, but if I run it a second time, the test fail with the same error as above. If I change the code, like just a white space, then the test runs fine on a third try, but when I then run a forth time it fails again, and so on. Which make me conclude that something fishy is going on with Pester and class-based resources.

**The DSC configuration that is using the resource (as detailed as possible):**
n/a

**Version of the Operating System, SQL Server and PowerShell the DSC Target Node is running:**
n/a

**What module (SqlServer or SQLPS) and which version of the module the DSC Target Node is running:**
n/a

**Version of the DSC module you're using, or 'dev' if you're using current dev branch:**
Dev

### PR DESCRIPTION
**Pull request by randomnote1**
**Pull Request (PR) description**
Refactored as a MOF based resource due to issues with testing in Pester on PowerShell 5.

**This Pull Request (PR) fixes the following issues:**
Fixes #673 

**Task list:**
- [X] Change details added to Unreleased section of CHANGELOG.md?
- [X] Added/updated documentation, comment-based help and descriptions in .schema.mof files where appropriate?
- [ ] Examples appropriately updated?
- [X] New/changed code adheres to [Style Guidelines](https://github.com/PowerShell/DscResources/blob/master/StyleGuidelines.md)?
- [X] [Unit and (optional) Integration tests](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md) created/updated where possible?

---
This change is [Reviewable](https://reviewable.io/reviews/powershell/xsqlserver/682)

### CODE REVIEW

**Comment by johlju** [comment]
Thank you so much for the work on his one! You don't know how much I appreciated you taking the time to help fix this!!! :smile: 

I will review this one tomorrow morning. Because it's very late now and I don't think I would do a good review job at this hour. :wink:

**Comment by randomnote1** [comment]
*[DSCResources/MSFT_xSQLServerAlwaysOnAvailabilityGroupDatabaseMembership/MSFT_xSQLServerAlwaysOnAvailabilityGroupDatabaseMembership.psm1, line 603 at r2](https://reviewable.io:443/reviews/powershell/xsqlserver/682#-Konh0uJWGiJtu72YQXP:-Konh0uJWGiJtu72YQXQ:b-9rpph3) ([raw file](https://github.com/powershell/xsqlserver/blob/b5e7dc9b5fe3e1b3b82bce1f8966e1e9bec67171/DSCResources/MSFT_xSQLServerAlwaysOnAvailabilityGroupDatabaseMembership/MSFT_xSQLServerAlwaysOnAvailabilityGroupDatabaseMembership.psm1#L603)):*
> ```PowerShell
> function Test-TargetResource
> {
>     [CmdletBinding()]
> ```

The common tests are stating:

 > Test-TargetResource should return a [boolean]. Prepend the param block with [OutputType([Boolean])].

When I put that in, Pester/PowerShell doesn't like it. Thoughts?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xsqlserver/682)*

**Comment by kwirkykat** [comment]
Review status: 0 of 5 files reviewed at latest revision, 2 unresolved discussions.

---

*[DSCResources/MSFT_xSQLServerAlwaysOnAvailabilityGroupDatabaseMembership/MSFT_xSQLServerAlwaysOnAvailabilityGroupDatabaseMembership.psm1, line 603 at r2](https://reviewable.io:443/reviews/powershell/xsqlserver/682#-Konh0uJWGiJtu72YQXP:-KonlS_mGNLaQHOcs4BK:b-2oy43r) ([raw file](https://github.com/powershell/xsqlserver/blob/b5e7dc9b5fe3e1b3b82bce1f8966e1e9bec67171/DSCResources/MSFT_xSQLServerAlwaysOnAvailabilityGroupDatabaseMembership/MSFT_xSQLServerAlwaysOnAvailabilityGroupDatabaseMembership.psm1#L603)):*
<details><summary><i>Previously, randomnote1 (Dan Reist) wrote…</i></summary><blockquote>

The common tests are stating:

 > Test-TargetResource should return a [boolean]. Prepend the param block with [OutputType([Boolean])].

When I put that in, Pester/PowerShell doesn't like it. Thoughts?
</blockquote></details>

What do you mean Pester/PowerShell doesn't like it?
Does it show an error? Or it doesn't run? What doesn't run? A Pester test? What test file?

---

*[DSCResources/MSFT_xSQLServerAlwaysOnAvailabilityGroupDatabaseMembership/MSFT_xSQLServerAlwaysOnAvailabilityGroupDatabaseMembership.psm1, line 936 at r2](https://reviewable.io:443/reviews/powershell/xsqlserver/682#-KonlpBrXCgLeivDbZ-T:-KonlpBrXCgLeivDbZ-U:b-9xilm5) ([raw file](https://github.com/powershell/xsqlserver/blob/b5e7dc9b5fe3e1b3b82bce1f8966e1e9bec67171/DSCResources/MSFT_xSQLServerAlwaysOnAvailabilityGroupDatabaseMembership/MSFT_xSQLServerAlwaysOnAvailabilityGroupDatabaseMembership.psm1#L936)):*
> ```PowerShell
> }
> 
> Export-ModuleMember -Function *-TargetResource
> ```

This line isn't needed

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xsqlserver/682)*

**Comment by johlju** [comment]
@randomnote1 Just want to double check. Have you done a manual integration tests with this resource? Have you tested so this refactored version works?  :smile: 

---

Reviewed 3 of 5 files at r1, 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[DSCResources/MSFT_xSQLServerAlwaysOnAvailabilityGroupDatabaseMembership/MSFT_xSQLServerAlwaysOnAvailabilityGroupDatabaseMembership.psm1, line 603 at r2](https://reviewable.io:443/reviews/powershell/xsqlserver/682#-Konh0uJWGiJtu72YQXP:-KoqC9ca_Aiw8-npZUeX:b-o8o4w8) ([raw file](https://github.com/powershell/xsqlserver/blob/b5e7dc9b5fe3e1b3b82bce1f8966e1e9bec67171/DSCResources/MSFT_xSQLServerAlwaysOnAvailabilityGroupDatabaseMembership/MSFT_xSQLServerAlwaysOnAvailabilityGroupDatabaseMembership.psm1#L603)):*
<details><summary><i>Previously, kwirkykat (Katie Keim) wrote…</i></summary><blockquote>

What do you mean Pester/PowerShell doesn't like it?
Does it show an error? Or it doesn't run? What doesn't run? A Pester test? What test file?
</blockquote></details>

This `[OutputType([Boolean])]` is set in all other resource, it should work. So add it back and point us to the error so we can solve it. :smile: 

---

*[DSCResources/MSFT_xSQLServerAlwaysOnAvailabilityGroupDatabaseMembership/MSFT_xSQLServerAlwaysOnAvailabilityGroupDatabaseMembership.psm1, line 649 at r2](https://reviewable.io:443/reviews/powershell/xsqlserver/682#-KoqEa9-rkZDc4duGmJF:-KoqEa9-rkZDc4duGmJG:b-ayv15h) ([raw file](https://github.com/powershell/xsqlserver/blob/b5e7dc9b5fe3e1b3b82bce1f8966e1e9bec67171/DSCResources/MSFT_xSQLServerAlwaysOnAvailabilityGroupDatabaseMembership/MSFT_xSQLServerAlwaysOnAvailabilityGroupDatabaseMembership.psm1#L649)):*
> ```PowerShell
>         BackupPath = $BackupPath
>     }
>     $currentConfiguration = Get-TargetResource @getTargetResourceParameters
> ```

Is this variable used anywhere? Can't find it.

---

*[DSCResources/MSFT_xSQLServerAlwaysOnAvailabilityGroupDatabaseMembership/MSFT_xSQLServerAlwaysOnAvailabilityGroupDatabaseMembership.psm1, line 936 at r2](https://reviewable.io:443/reviews/powershell/xsqlserver/682#-KonlpBrXCgLeivDbZ-T:-KoqDp9APR2_5zF5sWRb:b-4ehwgv) ([raw file](https://github.com/powershell/xsqlserver/blob/b5e7dc9b5fe3e1b3b82bce1f8966e1e9bec67171/DSCResources/MSFT_xSQLServerAlwaysOnAvailabilityGroupDatabaseMembership/MSFT_xSQLServerAlwaysOnAvailabilityGroupDatabaseMembership.psm1#L936)):*
<details><summary><i>Previously, kwirkykat (Katie Keim) wrote…</i></summary><blockquote>

This line isn't needed
</blockquote></details>

OH, I didn't know that. Good to know. That is in every mof resource. :smile: 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xsqlserver/682#-:-KoqE5OG4YwegXuqZ-WD:b-efv43j)*

**Comment by randomnote1** [comment]
Not yet. I ran out of time last night. I'm spinning up a fresh lab in Azure right now to give it a whirl.

---

Review status: 4 of 5 files reviewed at latest revision, 4 unresolved discussions.

---

*[DSCResources/MSFT_xSQLServerAlwaysOnAvailabilityGroupDatabaseMembership/MSFT_xSQLServerAlwaysOnAvailabilityGroupDatabaseMembership.psm1, line 603 at r2](https://reviewable.io:443/reviews/powershell/xsqlserver/682#-Konh0uJWGiJtu72YQXP:-KoqWSPC4jdQW3lBShSm:b5rpapz) ([raw file](https://github.com/powershell/xsqlserver/blob/b5e7dc9b5fe3e1b3b82bce1f8966e1e9bec67171/DSCResources/MSFT_xSQLServerAlwaysOnAvailabilityGroupDatabaseMembership/MSFT_xSQLServerAlwaysOnAvailabilityGroupDatabaseMembership.psm1#L603)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

This `[OutputType([Boolean])]` is set in all other resource, it should work. So add it back and point us to the error so we can solve it. :smile: 
</blockquote></details>

The error received is
`Property 'Boolean' cnnot be found for type 'System.Management.Automation.CmdletBindingAttribute'.`
I've added it, so we'll see what AppVeyor does with it.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xsqlserver/682#-:-KoqVlRdSbXK1vzbFR8I:b-b6bkiw)*

**Comment by johlju** [comment]
@randomnote1 I clone your branch, shall see what's going on with the output type.

**Comment by johlju** [comment]
Review status: 4 of 5 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[DSCResources/MSFT_xSQLServerAlwaysOnAvailabilityGroupDatabaseMembership/MSFT_xSQLServerAlwaysOnAvailabilityGroupDatabaseMembership.psm1, line 603 at r2](https://reviewable.io:443/reviews/powershell/xsqlserver/682#-Konh0uJWGiJtu72YQXP:-Koqbmiv8oCZyJWJdGch:b-p5k57v) ([raw file](https://github.com/powershell/xsqlserver/blob/b5e7dc9b5fe3e1b3b82bce1f8966e1e9bec67171/DSCResources/MSFT_xSQLServerAlwaysOnAvailabilityGroupDatabaseMembership/MSFT_xSQLServerAlwaysOnAvailabilityGroupDatabaseMembership.psm1#L603)):*
<details><summary><i>Previously, randomnote1 (Dan Reist) wrote…</i></summary><blockquote>

The error received is
`Property 'Boolean' cnnot be found for type 'System.Management.Automation.CmdletBindingAttribute'.`
I've added it, so we'll see what AppVeyor does with it.
</blockquote></details>

You missed [] around the type. I think you stared you blind on that one. :wink: 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xsqlserver/682)*

**Comment by johlju** [comment]
Review status: 4 of 5 files reviewed at latest revision, 6 unresolved discussions, some commit checks failed.

---

*[DSCResources/MSFT_xSQLServerAlwaysOnAvailabilityGroupDatabaseMembership/MSFT_xSQLServerAlwaysOnAvailabilityGroupDatabaseMembership.psm1, line 76 at r3](https://reviewable.io:443/reviews/powershell/xsqlserver/682#-KoqcZFGWiS-4nSZP-1U:-KoqcZFGWiS-4nSZP-1V:b-x14hpg) ([raw file](https://github.com/powershell/xsqlserver/blob/2178773b52af7679e6bdbba05493ef071cbedd79/DSCResources/MSFT_xSQLServerAlwaysOnAvailabilityGroupDatabaseMembership/MSFT_xSQLServerAlwaysOnAvailabilityGroupDatabaseMembership.psm1#L76)):*
> ```PowerShell
>     $serverObject = Connect-SQL -SQLServer $SQLServer -SQLInstanceName $SQLInstanceName
> 
>     # Get the availabilty group object
> ```

Typo 'Availability'

---

*[DSCResources/MSFT_xSQLServerAlwaysOnAvailabilityGroupDatabaseMembership/MSFT_xSQLServerAlwaysOnAvailabilityGroupDatabaseMembership.psm1, line 187 at r3](https://reviewable.io:443/reviews/powershell/xsqlserver/682#-Koqc_9BzUBDB5h3Dw-6:-Koqc_9BzUBDB5h3Dw-7:b-x14hpg) ([raw file](https://github.com/powershell/xsqlserver/blob/2178773b52af7679e6bdbba05493ef071cbedd79/DSCResources/MSFT_xSQLServerAlwaysOnAvailabilityGroupDatabaseMembership/MSFT_xSQLServerAlwaysOnAvailabilityGroupDatabaseMembership.psm1#L187)):*
> ```PowerShell
>     $serverObject = Connect-SQL -SQLServer $SQLServer -SQLInstanceName $SQLInstanceName
> 
>     # Get the Availabilty Group
> ```

Typo 'Availability'

---

*[DSCResources/MSFT_xSQLServerAlwaysOnAvailabilityGroupDatabaseMembership/MSFT_xSQLServerAlwaysOnAvailabilityGroupDatabaseMembership.psm1, line 655 at r3](https://reviewable.io:443/reviews/powershell/xsqlserver/682#-KoqcS-pRc4Tn9PMgBH_:-KoqcS-pRc4Tn9PMgBHa:b-x14hpg) ([raw file](https://github.com/powershell/xsqlserver/blob/2178773b52af7679e6bdbba05493ef071cbedd79/DSCResources/MSFT_xSQLServerAlwaysOnAvailabilityGroupDatabaseMembership/MSFT_xSQLServerAlwaysOnAvailabilityGroupDatabaseMembership.psm1#L655)):*
> ```PowerShell
>     $serverObject = Connect-SQL -SQLServer $SQLServer -SQLInstanceName $SQLInstanceName
> 
>     # Get the Availabilty Group if it exists
> ```

Typo 'Availability'

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xsqlserver/682)*

**Comment by randomnote1** [comment]
Review status: 3 of 5 files reviewed at latest revision, 6 unresolved discussions.

---

*[DSCResources/MSFT_xSQLServerAlwaysOnAvailabilityGroupDatabaseMembership/MSFT_xSQLServerAlwaysOnAvailabilityGroupDatabaseMembership.psm1, line 603 at r2](https://reviewable.io:443/reviews/powershell/xsqlserver/682#-Konh0uJWGiJtu72YQXP:-Koqd6v1d87iAdgstlH9:b-uzc6q4) ([raw file](https://github.com/powershell/xsqlserver/blob/b5e7dc9b5fe3e1b3b82bce1f8966e1e9bec67171/DSCResources/MSFT_xSQLServerAlwaysOnAvailabilityGroupDatabaseMembership/MSFT_xSQLServerAlwaysOnAvailabilityGroupDatabaseMembership.psm1#L603)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

You missed [] around the type. I think you stared you blind on that one. :wink: 
</blockquote></details>

Just figured that out! The worst part is I typed it incorrectly several times. :man_facepalming: 

Done.

---

*[DSCResources/MSFT_xSQLServerAlwaysOnAvailabilityGroupDatabaseMembership/MSFT_xSQLServerAlwaysOnAvailabilityGroupDatabaseMembership.psm1, line 649 at r2](https://reviewable.io:443/reviews/powershell/xsqlserver/682#-KoqEa9-rkZDc4duGmJF:-Koqcqh6WyhmYTT7olk4:bxr7q49) ([raw file](https://github.com/powershell/xsqlserver/blob/b5e7dc9b5fe3e1b3b82bce1f8966e1e9bec67171/DSCResources/MSFT_xSQLServerAlwaysOnAvailabilityGroupDatabaseMembership/MSFT_xSQLServerAlwaysOnAvailabilityGroupDatabaseMembership.psm1#L649)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

Is this variable used anywhere? Can't find it.
</blockquote></details>

Completely missed it.

Done.

---

*[DSCResources/MSFT_xSQLServerAlwaysOnAvailabilityGroupDatabaseMembership/MSFT_xSQLServerAlwaysOnAvailabilityGroupDatabaseMembership.psm1, line 936 at r2](https://reviewable.io:443/reviews/powershell/xsqlserver/682#-KonlpBrXCgLeivDbZ-T:-KoqX5llDO6-AJ7UCtGX:b-hq85ey) ([raw file](https://github.com/powershell/xsqlserver/blob/b5e7dc9b5fe3e1b3b82bce1f8966e1e9bec67171/DSCResources/MSFT_xSQLServerAlwaysOnAvailabilityGroupDatabaseMembership/MSFT_xSQLServerAlwaysOnAvailabilityGroupDatabaseMembership.psm1#L936)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

OH, I didn't know that. Good to know. That is in every mof resource. :smile: 
</blockquote></details>

Module members would only need to be exported if we wanted the functions to be available outside of DSC, correct?

Done.

---

*[DSCResources/MSFT_xSQLServerAlwaysOnAvailabilityGroupDatabaseMembership/MSFT_xSQLServerAlwaysOnAvailabilityGroupDatabaseMembership.psm1, line 76 at r3](https://reviewable.io:443/reviews/powershell/xsqlserver/682#-KoqcZFGWiS-4nSZP-1U:-Koqd4ClFbeeFCYUKx9N:b-896fix) ([raw file](https://github.com/powershell/xsqlserver/blob/2178773b52af7679e6bdbba05493ef071cbedd79/DSCResources/MSFT_xSQLServerAlwaysOnAvailabilityGroupDatabaseMembership/MSFT_xSQLServerAlwaysOnAvailabilityGroupDatabaseMembership.psm1#L76)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

Typo 'Availability'
</blockquote></details>

Done.

---

*[DSCResources/MSFT_xSQLServerAlwaysOnAvailabilityGroupDatabaseMembership/MSFT_xSQLServerAlwaysOnAvailabilityGroupDatabaseMembership.psm1, line 187 at r3](https://reviewable.io:443/reviews/powershell/xsqlserver/682#-Koqc_9BzUBDB5h3Dw-6:-Koqd4rs-dZY2c7DhkC-:b-896fix) ([raw file](https://github.com/powershell/xsqlserver/blob/2178773b52af7679e6bdbba05493ef071cbedd79/DSCResources/MSFT_xSQLServerAlwaysOnAvailabilityGroupDatabaseMembership/MSFT_xSQLServerAlwaysOnAvailabilityGroupDatabaseMembership.psm1#L187)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

Typo 'Availability'
</blockquote></details>

Done.

---

*[DSCResources/MSFT_xSQLServerAlwaysOnAvailabilityGroupDatabaseMembership/MSFT_xSQLServerAlwaysOnAvailabilityGroupDatabaseMembership.psm1, line 655 at r3](https://reviewable.io:443/reviews/powershell/xsqlserver/682#-KoqcS-pRc4Tn9PMgBH_:-Koqd2MikCOCOwXhCiOZ:b-896fix) ([raw file](https://github.com/powershell/xsqlserver/blob/2178773b52af7679e6bdbba05493ef071cbedd79/DSCResources/MSFT_xSQLServerAlwaysOnAvailabilityGroupDatabaseMembership/MSFT_xSQLServerAlwaysOnAvailabilityGroupDatabaseMembership.psm1#L655)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

Typo 'Availability'
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xsqlserver/682)*

**Comment by johlju** [comment]
:lgtm:

Just want confirmation that your manual tests are working. And the tests are passing. Then I merge.  

---

Reviewed 2 of 2 files at r4.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[DSCResources/MSFT_xSQLServerAlwaysOnAvailabilityGroupDatabaseMembership/MSFT_xSQLServerAlwaysOnAvailabilityGroupDatabaseMembership.psm1, line 603 at r2](https://reviewable.io:443/reviews/powershell/xsqlserver/682#-Konh0uJWGiJtu72YQXP:-Koqe5gJ1w7ZsadgZmdr:b4smwi3) ([raw file](https://github.com/powershell/xsqlserver/blob/b5e7dc9b5fe3e1b3b82bce1f8966e1e9bec67171/DSCResources/MSFT_xSQLServerAlwaysOnAvailabilityGroupDatabaseMembership/MSFT_xSQLServerAlwaysOnAvailabilityGroupDatabaseMembership.psm1#L603)):*
<details><summary><i>Previously, randomnote1 (Dan Reist) wrote…</i></summary><blockquote>

Just figured that out! The worst part is I typed it incorrectly several times. :man_facepalming: 

Done.
</blockquote></details>

I know the feeling. Done similar things. :wink: 

---

*[DSCResources/MSFT_xSQLServerAlwaysOnAvailabilityGroupDatabaseMembership/MSFT_xSQLServerAlwaysOnAvailabilityGroupDatabaseMembership.psm1, line 936 at r2](https://reviewable.io:443/reviews/powershell/xsqlserver/682#-KonlpBrXCgLeivDbZ-T:-Koqeb361yShAXFyPA_6:b-uww1xo) ([raw file](https://github.com/powershell/xsqlserver/blob/b5e7dc9b5fe3e1b3b82bce1f8966e1e9bec67171/DSCResources/MSFT_xSQLServerAlwaysOnAvailabilityGroupDatabaseMembership/MSFT_xSQLServerAlwaysOnAvailabilityGroupDatabaseMembership.psm1#L936)):*
<details><summary><i>Previously, randomnote1 (Dan Reist) wrote…</i></summary><blockquote>

Module members would only need to be exported if we wanted the functions to be available outside of DSC, correct?

Done.
</blockquote></details>

I guess so. Hope @kwirkykat has oppertunity to respond to that. If so I want to remove that from all resources eventually. :smile: 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xsqlserver/682#-:-KoqeuzGUf87J7DOfjRJ:b904jkw)*

**Comment by johlju** [comment]
See if I can ack the last two 

---

Reviewed 1 of 1 files at r5.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[DSCResources/MSFT_xSQLServerAlwaysOnAvailabilityGroupDatabaseMembership/MSFT_xSQLServerAlwaysOnAvailabilityGroupDatabaseMembership.psm1, line 603 at r2](https://reviewable.io:443/reviews/powershell/xsqlserver/682#-Konh0uJWGiJtu72YQXP:-KoqfUvp-TQD9QUEdvoN:b32w0x) ([raw file](https://github.com/powershell/xsqlserver/blob/b5e7dc9b5fe3e1b3b82bce1f8966e1e9bec67171/DSCResources/MSFT_xSQLServerAlwaysOnAvailabilityGroupDatabaseMembership/MSFT_xSQLServerAlwaysOnAvailabilityGroupDatabaseMembership.psm1#L603)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

I know the feeling. Done similar things. :wink: 
</blockquote></details>

OK

---

*[DSCResources/MSFT_xSQLServerAlwaysOnAvailabilityGroupDatabaseMembership/MSFT_xSQLServerAlwaysOnAvailabilityGroupDatabaseMembership.psm1, line 936 at r2](https://reviewable.io:443/reviews/powershell/xsqlserver/682#-KonlpBrXCgLeivDbZ-T:-KoqfUDSKh_bBo_OIdxb:b32w0x) ([raw file](https://github.com/powershell/xsqlserver/blob/b5e7dc9b5fe3e1b3b82bce1f8966e1e9bec67171/DSCResources/MSFT_xSQLServerAlwaysOnAvailabilityGroupDatabaseMembership/MSFT_xSQLServerAlwaysOnAvailabilityGroupDatabaseMembership.psm1#L936)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

I guess so. Hope @kwirkykat has oppertunity to respond to that. If so I want to remove that from all resources eventually. :smile: 
</blockquote></details>

OK

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xsqlserver/682#-:-Koqfb-pc3CagHLrj6nC:be6nlc0)*

**Comment by johlju** [comment]
@randomnote1 Great you fixed those PSSA rule warnings! I saw them before but forgot about them.

**Comment by johlju** [comment]
@kwirkykat tried to get the last to review comments to resolve without you needing to acknowledge, but seems that didn't work. 😄  I will just merge this anyway.

**Comment by johlju** [comment]
:lgtm:

Again. Just want confirmation that your manual tests are working. And the tests are passing. Then I merge.

---

Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xsqlserver/682#-:-KoqhCjm9l3UTbVpstTL:b7pqjg0)*

**Comment by johlju** [comment]
@randomnote1 Could you confirm that the refactored code works when you have had a chance to test it?

**Comment by randomnote1** [comment]
I just finished validation that this works. Let me know if you need anything else!

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xsqlserver/682#-:-KorClvv45n5vxRjVW7M:bo8echo)*

**Comment by johlju** [comment]
:lgtm:

---

Reviewed 5 of 5 files at r6.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xsqlserver/682#-:-KorEGbIZBq_4JCN9-t9:bnfp4nl)*

**Comment by johlju** [comment]
@randomnote1 Thanks for testing! The changes you did looks good to me now! I will merge as soon as the tests are passing.

If you are at Ignite (Orlando) in September look me up and I will buy you a beverage! 😄 🍺

**Comment by randomnote1** [comment]
Sure thing! Bummer, I'm not planning on attending :frowning_face: 

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xsqlserver/682#-:-KorFqvx2b3yztz90TZ2:b-arnajp)*

**Comment by johlju** [comment]
Hope our paths cross another time then :smile:

**Comment by TraGicCode** [comment]
@johlju @randomnote1 Thanks soo much for making this a non class based dsc resource.  This will be autopicked up on the next release and available for puppet users 👍

**Comment by johlju** [comment]
@TraGicCode Glad all puppet users will be able to use this!  😄 @randomnote1 deserves all credit! He did an awesome job with this. Coding this entire (almost) resource and testing it twice!!

**Pull request merged**
