### PR TITLE
Changes to xSQLServerLogin (Fixes #105, #31)

### LINKED ISSUE #105: Error when dropping a login using the resource xSqlServerLogin
When dropping a login by saying state should be 'Absent' the login will be removed, but an error will occur. This is because a validation occur after the drop. That validation does improperly validation on LoginType when state is absent.

### PR DESCRIPTION
**Pull request by johlju**
* Changes to xSQLServerLogin
   - Fixed an issue when dropping logins (issue #105).
   - Fixed an issue where it was not possible to add the same login to two instances on the same server (#31).
   - Added unit test for the resource.

---
This change is [Reviewable](https://reviewable.io/reviews/powershell/xsqlserver/106)

### CODE REVIEW

**Comment by mbreakey3** [comment]
Reviewed 3 of 5 files at r1, 1 of 2 files at r2.
Review status: 4 of 5 files reviewed at latest revision, 1 unresolved discussion.

---

*[Tests/Unit/MSFT_xSQLServerLogin.Tests.ps1, line 179 \[r2\]](https://reviewable.io:443/reviews/powershell/xsqlserver/106#-KPL3fkm8oRbzx6pkt9o:-KPL3fkm8oRbzx6pkt9p:b-y44x14) ([raw file](https://github.com/powershell/xsqlserver/blob/fd1d4d9b15baafa556ee2cc41e5d8fcd2f350b12/Tests/Unit/MSFT_xSQLServerLogin.Tests.ps1#L179)):*
> ```PowerShell
> 
>         Context 'When the system is not in the desired state' {
>             It 'Should return desired state as absent when desired windows user don''t exists' {
> ```

change this to 'user does not exist'

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xsqlserver/106)*

**Comment by mbreakey3** [comment]
Thank you so much for adding in all these tests!

**Comment by johlju** [comment]
@mbreakey3 It's fun coding these test, I learn a lot! :smile: 
And I'm looking forward to when all the tests are written. Then we can add new tests for new functionality and then do the code changes so you see the code you wrote did what was expected. :)

**Comment by mbreakey3** [comment]
Reviewed 2 of 2 files at r3.
Review status: 4 of 5 files reviewed at latest revision, 8 unresolved discussions.

---

*[Tests/Unit/MSFT_xSQLServerLogin.Tests.ps1, line 120 \[r3\]](https://reviewable.io:443/reviews/powershell/xsqlserver/106#-KPU-NDfbL7WTKU5UVQV:-KPU-NDfbL7WTKU5UVQW:b-jji2wm) ([raw file](https://github.com/powershell/xsqlserver/blob/0620a28979a3c9fe579670ead81f35a4ec9cfa28/Tests/Unit/MSFT_xSQLServerLogin.Tests.ps1#L120)):*
> ```PowerShell
>             $result = Get-TargetResource @testParameters
> 
>             It 'Should not return the state as present' {
> ```

should this be 'Should return the state as present'?

---

*[Tests/Unit/MSFT_xSQLServerLogin.Tests.ps1, line 144 \[r3\]](https://reviewable.io:443/reviews/powershell/xsqlserver/106#-KPU-YJ9jdfaLMmxqg9f:-KPU-YJARVqJ3habnVsI:b-85lotl) ([raw file](https://github.com/powershell/xsqlserver/blob/0620a28979a3c9fe579670ead81f35a4ec9cfa28/Tests/Unit/MSFT_xSQLServerLogin.Tests.ps1#L144)):*
> ```PowerShell
>             $result = Get-TargetResource @testParameters
> 
>             It 'Should not return the state as present' {
> ```

Again, should this be 'Should return...'?

---

*[Tests/Unit/MSFT_xSQLServerLogin.Tests.ps1, line 198 \[r3\]](https://reviewable.io:443/reviews/powershell/xsqlserver/106#-KPU2PJga2ybJrmGI1lx:-KPU2PJga2ybJrmGI1ly:b-zgmes7) ([raw file](https://github.com/powershell/xsqlserver/blob/0620a28979a3c9fe579670ead81f35a4ec9cfa28/Tests/Unit/MSFT_xSQLServerLogin.Tests.ps1#L198)):*
> ```PowerShell
>                 }
> 
>                 $result = Test-TargetResource @testParameters
> ```

You shouldn't be calling this function more than once in an It statement - divide it up into multiple It statements

---

*[Tests/Unit/MSFT_xSQLServerLogin.Tests.ps1, line 227 \[r3\]](https://reviewable.io:443/reviews/powershell/xsqlserver/106#-KPU2sfwL7gayNjKbx9x:-KPU2sfxS1hp1XjZBAP9:blnd92g) ([raw file](https://github.com/powershell/xsqlserver/blob/0620a28979a3c9fe579670ead81f35a4ec9cfa28/Tests/Unit/MSFT_xSQLServerLogin.Tests.ps1#L227)):*
> ```PowerShell
>             }
> 
>             It 'Should return that desired state as present when desired windows group exist' {
> ```

'group exists'

---

*[Tests/Unit/MSFT_xSQLServerLogin.Tests.ps1, line 240 \[r3\]](https://reviewable.io:443/reviews/powershell/xsqlserver/106#-KPU3-3DQwtjk5PZwOfc:-KPU3-3DQwtjk5PZwOfd:bcqtxav) ([raw file](https://github.com/powershell/xsqlserver/blob/0620a28979a3c9fe579670ead81f35a4ec9cfa28/Tests/Unit/MSFT_xSQLServerLogin.Tests.ps1#L240)):*
> ```PowerShell
>             }
> 
>             It 'Should return that desired state as present when desired sql login exist' {
> ```

should this be 'Should return the desired state as $true..' ?

---

*[Tests/Unit/MSFT_xSQLServerLogin.Tests.ps1, line 345 \[r3\]](https://reviewable.io:443/reviews/powershell/xsqlserver/106#-KPU4Aghy-LKKJpad3pb:-KPU4Aghy-LKKJpad3pc:b-r9vc7n) ([raw file](https://github.com/powershell/xsqlserver/blob/0620a28979a3c9fe579670ead81f35a4ec9cfa28/Tests/Unit/MSFT_xSQLServerLogin.Tests.ps1#L345)):*
> ```PowerShell
>             }
> 
>             It 'Should not throw an error when desired login should be absent but are present' {
> ```

rephrase this It statement

---

*[Tests/Unit/MSFT_xSQLServerLogin.Tests.ps1, line 428 \[r3\]](https://reviewable.io:443/reviews/powershell/xsqlserver/106#-KPU5Tq3Y-shoG_QFvt_:-KPU5Tq47uFxChrJYMVK:b-huefl5) ([raw file](https://github.com/powershell/xsqlserver/blob/0620a28979a3c9fe579670ead81f35a4ec9cfa28/Tests/Unit/MSFT_xSQLServerLogin.Tests.ps1#L428)):*
> ```PowerShell
>             }
> 
>             It 'Should not throw an error when desired login should be absent but are already absent' {
> ```

rephrase this 'It' statement

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xsqlserver/106)*

**Comment by johlju** [comment]
Reviewed 1 of 5 files at r1, 1 of 2 files at r3, 3 of 3 files at r4.
Review status: all files reviewed at latest revision, 8 unresolved discussions, some commit checks failed.

---

*[Tests/Unit/MSFT_xSQLServerLogin.Tests.ps1, line 179 \[r2\]](https://reviewable.io:443/reviews/powershell/xsqlserver/106#-KPL3fkm8oRbzx6pkt9o:-KPYuH3YSYBpLX11XmHp:bb6un1j) ([raw file](https://github.com/powershell/xsqlserver/blob/fd1d4d9b15baafa556ee2cc41e5d8fcd2f350b12/Tests/Unit/MSFT_xSQLServerLogin.Tests.ps1#L179)):*
<details><summary><i>Previously, mbreakey3 (Mariah) wrote…</i></summary>
> change this to 'user does not exist'
</details>
Done

---

*[Tests/Unit/MSFT_xSQLServerLogin.Tests.ps1, line 120 \[r3\]](https://reviewable.io:443/reviews/powershell/xsqlserver/106#-KPU-NDfbL7WTKU5UVQV:-KPYuALvITNbayLsegNK:b-acotng) ([raw file](https://github.com/powershell/xsqlserver/blob/0620a28979a3c9fe579670ead81f35a4ec9cfa28/Tests/Unit/MSFT_xSQLServerLogin.Tests.ps1#L120)):*
<details><summary><i>Previously, mbreakey3 (Mariah) wrote…</i></summary>
> should this be 'Should return the state as present'?
</details>
You are correct. Fixed.

---

*[Tests/Unit/MSFT_xSQLServerLogin.Tests.ps1, line 144 \[r3\]](https://reviewable.io:443/reviews/powershell/xsqlserver/106#-KPU-YJ9jdfaLMmxqg9f:-KPYuD1mAv86pAicYe-o:b-acotng) ([raw file](https://github.com/powershell/xsqlserver/blob/0620a28979a3c9fe579670ead81f35a4ec9cfa28/Tests/Unit/MSFT_xSQLServerLogin.Tests.ps1#L144)):*
<details><summary><i>Previously, mbreakey3 (Mariah) wrote…</i></summary>
> Again, should this be 'Should return...'?
</details>
You are correct. Fixed.

---

*[Tests/Unit/MSFT_xSQLServerLogin.Tests.ps1, line 198 \[r3\]](https://reviewable.io:443/reviews/powershell/xsqlserver/106#-KPU2PJga2ybJrmGI1lx:-KPYuL-aFl3ycINcp2Xm:bb6un1j) ([raw file](https://github.com/powershell/xsqlserver/blob/0620a28979a3c9fe579670ead81f35a4ec9cfa28/Tests/Unit/MSFT_xSQLServerLogin.Tests.ps1#L198)):*
<details><summary><i>Previously, mbreakey3 (Mariah) wrote…</i></summary>
> You shouldn't be calling this function more than once in an It statement - divide it up into multiple It statements
</details>
Done

---

*[Tests/Unit/MSFT_xSQLServerLogin.Tests.ps1, line 227 \[r3\]](https://reviewable.io:443/reviews/powershell/xsqlserver/106#-KPU2sfwL7gayNjKbx9x:-KPYweATPtjNOf9QktPb:bb6un1j) ([raw file](https://github.com/powershell/xsqlserver/blob/0620a28979a3c9fe579670ead81f35a4ec9cfa28/Tests/Unit/MSFT_xSQLServerLogin.Tests.ps1#L227)):*
<details><summary><i>Previously, mbreakey3 (Mariah) wrote…</i></summary>
> 'group exists'
</details>
Done

---

*[Tests/Unit/MSFT_xSQLServerLogin.Tests.ps1, line 240 \[r3\]](https://reviewable.io:443/reviews/powershell/xsqlserver/106#-KPU3-3DQwtjk5PZwOfc:-KPYvIMkIAo3FtVJXwxU:b-cv5rv9) ([raw file](https://github.com/powershell/xsqlserver/blob/0620a28979a3c9fe579670ead81f35a4ec9cfa28/Tests/Unit/MSFT_xSQLServerLogin.Tests.ps1#L240)):*
<details><summary><i>Previously, mbreakey3 (Mariah) wrote…</i></summary>
> should this be 'Should return the desired state as $true..' ?
</details>
I changed it a little, but did not change to $true, my thinking is that Test-method returns "$true" to say it is "Present". So I think it's more readable with "Present". But I can go with $true as well if you think it's better.

---

*[Tests/Unit/MSFT_xSQLServerLogin.Tests.ps1, line 345 \[r3\]](https://reviewable.io:443/reviews/powershell/xsqlserver/106#-KPU4Aghy-LKKJpad3pb:-KPYvviT91k6btC7N8AO:b89hra5) ([raw file](https://github.com/powershell/xsqlserver/blob/0620a28979a3c9fe579670ead81f35a4ec9cfa28/Tests/Unit/MSFT_xSQLServerLogin.Tests.ps1#L345)):*
<details><summary><i>Previously, mbreakey3 (Mariah) wrote…</i></summary>
> rephrase this It statement
</details>
So this one I had to rework totally. This one returned false positive because the code caught the error and never throw. I had to rework the resource, stub and mocking to make this test work.

---

*[Tests/Unit/MSFT_xSQLServerLogin.Tests.ps1, line 428 \[r3\]](https://reviewable.io:443/reviews/powershell/xsqlserver/106#-KPU5Tq3Y-shoG_QFvt_:-KPYwS0wcX_v8Rf625m3:b-gmlrl6) ([raw file](https://github.com/powershell/xsqlserver/blob/0620a28979a3c9fe579670ead81f35a4ec9cfa28/Tests/Unit/MSFT_xSQLServerLogin.Tests.ps1#L428)):*
<details><summary><i>Previously, mbreakey3 (Mariah) wrote…</i></summary>
> rephrase this 'It' statement
</details>
Same here. Reworked the test totally.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xsqlserver/106)*

**Comment by johlju** [comment]
@mbreakey3 Did I break AppVeyor with this commit? How can I see what's wrong?

**Comment by johlju** [comment]
@mbreakey3 Never mind, I missed that you merged in a PR. I resolved the conflict and now AppVeyor is happy again :smile:

**Comment by mbreakey3** [comment]
Reviewed 2 of 3 files at r4, 1 of 1 files at r5.
Review status: all files reviewed at latest revision, 7 unresolved discussions.

---

*[DSCResources/MSFT_xSQLServerLogin/MSFT_xSQLServerLogin.psm1, line 154 \[r5\]](https://reviewable.io:443/reviews/powershell/xsqlserver/106#-KPZ0OChHKAaUg5nEcCe:-KPZ0OChHKAaUg5nEcCf:b-ac3pk9) ([raw file](https://github.com/powershell/xsqlserver/blob/8ce229ea133926120aad0bf5e0cd7033e4d7908f/DSCResources/MSFT_xSQLServerLogin/MSFT_xSQLServerLogin.psm1#L154)):*
> ```PowerShell
>                     Write-Verbose "Deleting SQL login $Name"
> 
>                     $sqlLogin = $($sql.Logins[ $Name ])
> ```

you don't need to add the space within the brackets and parentheses. But there should be one after the 'if' before the '(' on the line below

---

*[DSCResources/MSFT_xSQLServerLogin/MSFT_xSQLServerLogin.psm1, line 235 \[r5\]](https://reviewable.io:443/reviews/powershell/xsqlserver/106#-KPZ0g5bKfdkgW38xGzp:-KPZ0g5bKfdkgW38xGzq:bpprq17) ([raw file](https://github.com/powershell/xsqlserver/blob/8ce229ea133926120aad0bf5e0cd7033e4d7908f/DSCResources/MSFT_xSQLServerLogin/MSFT_xSQLServerLogin.psm1#L235)):*
> ```PowerShell
>     )
> 
>     if( ( $PSCmdlet.ShouldProcess( $($sqlLogin.Name), "Remove login" ) ) ) {
> ```

Again, the spaces aren't needed within the parentheses, but there should be a space after the 'if'

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xsqlserver/106)*

**Comment by johlju** [comment]
Reviewed 1 of 1 files at r5, 1 of 1 files at r6.
Review status: all files reviewed at latest revision, 7 unresolved discussions.

---

*[DSCResources/MSFT_xSQLServerLogin/MSFT_xSQLServerLogin.psm1, line 154 \[r5\]](https://reviewable.io:443/reviews/powershell/xsqlserver/106#-KPZ0OChHKAaUg5nEcCe:-KPaUXRqSBDAu13wqbBd:b4b3gsj) ([raw file](https://github.com/powershell/xsqlserver/blob/8ce229ea133926120aad0bf5e0cd7033e4d7908f/DSCResources/MSFT_xSQLServerLogin/MSFT_xSQLServerLogin.psm1#L154)):*
<details><summary><i>Previously, mbreakey3 (Mariah) wrote…</i></summary>
> you don't need to add the space within the brackets and parentheses. But there should be one after the 'if' before the '(' on the line below
</details>
Done. I remembered this one wrong from the StyleGuide. No I have changed all the parentheses back and added a space where it suppose to be in the whole file. :) 

---

*[DSCResources/MSFT_xSQLServerLogin/MSFT_xSQLServerLogin.psm1, line 235 \[r5\]](https://reviewable.io:443/reviews/powershell/xsqlserver/106#-KPZ0g5bKfdkgW38xGzp:-KPaUsznYHFzsviar_G3:bb6un1j) ([raw file](https://github.com/powershell/xsqlserver/blob/8ce229ea133926120aad0bf5e0cd7033e4d7908f/DSCResources/MSFT_xSQLServerLogin/MSFT_xSQLServerLogin.psm1#L235)):*
<details><summary><i>Previously, mbreakey3 (Mariah) wrote…</i></summary>
> Again, the spaces aren't needed within the parentheses, but there should be a space after the 'if'
</details>
Done

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xsqlserver/106)*

**Comment by mbreakey3** [comment]
Reviewed 1 of 1 files at r6, 2 of 2 files at r7.
Review status: all files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xsqlserver/106)*

**Comment by mbreakey3** [comment]
Now there's just the merge conflicts....

**Comment by johlju** [comment]
@mbreakey3 Resolved the conflicts

**Comment by mbreakey3** [comment]
:lgtm:

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xsqlserver/106#-:-KPnN3dI6cLXfL1gqCxm:bnfp4nl)*

**Pull request merged**
