### PR TITLE
Renamed MSFT_xSQLServerScript.Test to MSFT_xSQLServerScript.Tests

### PR DESCRIPTION
**Pull request by dcrreynolds**
This change is [Reviewable](https://reviewable.io/reviews/powershell/xsqlserver/156)

### CODE REVIEW

**Comment by johlju** [comment]
Awesome that you are fixing this test! I have a few comments which would make it even greater I hope.
I will review it further after you changed this. Didn't have time to go thru all of the test this round.

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---

*[Tests/Unit/MSFT_xSQLServerScript.Tests.ps1, line 28 at r1](https://reviewable.io:443/reviews/powershell/xsqlserver/156#-KU18ip5_hLwCwv3AmmG:-KU18ip5_hLwCwv3AmmH:bi0lzij) ([raw file](https://github.com/powershell/xsqlserver/blob/766b75155509e0597c4778894b5e8b7417935b18/Tests/Unit/MSFT_xSQLServerScript.Tests.ps1#L28)):*
> ```PowerShell
> #endregion HEADER
> 
> Add-Type -ErrorAction SilentlyContinue -TypeDefinition @'
> ```

I think this class could come in handy for more resources in the future. What do you say about moving it into a seperate file? For example PowerShell.cs file in the stub folder (https://github.com/PowerShell/xSQLServer/tree/dev/Tests/Unit/Stubs), just like we did for the SMO classes (SMO.cs).

You load it by using
```
# Loading mocked classes
Add-Type -Path (Join-Path -Path $script:moduleRoot -ChildPath 'Tests\Unit\Stubs\PowerShell.cs')
```

---

*[Tests/Unit/MSFT_xSQLServerScript.Tests.ps1, line 44 at r1](https://reviewable.io:443/reviews/powershell/xsqlserver/156#-KU10CBf-qqQh-TBCOST:-KU10CBf-qqQh-TBCOSU:b79y80e) ([raw file](https://github.com/powershell/xsqlserver/blob/766b75155509e0597c4778894b5e8b7417935b18/Tests/Unit/MSFT_xSQLServerScript.Tests.ps1#L44)):*
> ```PowerShell
> {
>     #region Pester Test Initialization
>         Function Invoke-SqlScript {}
> ```

To get better code coverage you should Mock Invoke-SqlCmd. And you can add the stubs to get the stub for Invoke-SqlCmd instead of adding a function in the test. Please change to mock Invoke-SqlCmd instead throughout the test.

Example of importing stub:
https://github.com/PowerShell/xSQLServer/blob/dev/Tests/Unit/MSFT_xSQLServerEndpointState.Tests.ps1
Stubs:
https://github.com/PowerShell/xSQLServer/blob/dev/Tests/Unit/Stubs/SQLPSStub.psm1

---

*[Tests/Unit/MSFT_xSQLServerScript.Tests.ps1, line 48 at r1](https://reviewable.io:443/reviews/powershell/xsqlserver/156#-KU15tHNDzgMByJQ5CNr:-KU15tHNDzgMByJQ5CNs:bljavea) ([raw file](https://github.com/powershell/xsqlserver/blob/766b75155509e0597c4778894b5e8b7417935b18/Tests/Unit/MSFT_xSQLServerScript.Tests.ps1#L48)):*
> ```PowerShell
> 
>     #region Test Sql script throws an error
>     Describe 'Test Sql script throws an error' {
> ```

Could you add `$script:DSCResourceName` to each Describe-block so it is easier to see which resource it is testing, and also preferable add `Get-TargetResource`, `Set-TargetResource` or `Test-TargetResource` to the description to either the Describe block or to a Context block so it's clear which method it is testing.
Please see this test for examples: https://github.com/PowerShell/xSQLServer/blob/dev/Tests/Unit/MSFT_xSQLServerLogin.Tests.ps1

---

*[Tests/Unit/MSFT_xSQLServerScript.Tests.ps1, line 58 at r1](https://reviewable.io:443/reviews/powershell/xsqlserver/156#-KU16nL8q58a0X4LeGt4:-KU16nL8q58a0X4LeGt5:b1dsuku) ([raw file](https://github.com/powershell/xsqlserver/blob/766b75155509e0597c4778894b5e8b7417935b18/Tests/Unit/MSFT_xSQLServerScript.Tests.ps1#L58)):*
> ```PowerShell
>         }
> 
>         It 'Get method returns successfully' {         
> ```

Could you please change all It-blocks throughout the test so they start with `It 'Should...'`
See unit template: https://github.com/PowerShell/DscResources/blob/master/Tests.Template/unit_template.ps1

For example:
`It 'Should return the same values as passed as parameters'`
`It 'Should throw when calling Invoke-SqlCmd` 

Also see this test for examples: https://github.com/PowerShell/xSQLServer/blob/dev/Tests/Unit/MSFT_xSQLServerLogin.Tests.ps1

---

*[Tests/Unit/MSFT_xSQLServerScript.Tests.ps1, line 63 at r1](https://reviewable.io:443/reviews/powershell/xsqlserver/156#-KU19v_P1FvjXeaCuECC:-KU19v_Q0vgkbsZIjMFW:b6nilb1) ([raw file](https://github.com/powershell/xsqlserver/blob/766b75155509e0597c4778894b5e8b7417935b18/Tests/Unit/MSFT_xSQLServerScript.Tests.ps1#L63)):*
> ```PowerShell
>             $result = Get-TargetResource @testParameters
> 
>             $result.ServerInstance | should be $testParameters.ServerInstance
> ```

Please change all `should be` to `Should Be` (upper 'S' and upper 'B'). Do this throughout the test.

---

*[Tests/Unit/MSFT_xSQLServerScript.Tests.ps1, line 140 at r1](https://reviewable.io:443/reviews/powershell/xsqlserver/156#-KU1Dh1aRVtlKTzPowdk:-KU1Dh1aRVtlKTzPowdl:bltf8ck) ([raw file](https://github.com/powershell/xsqlserver/blob/766b75155509e0597c4778894b5e8b7417935b18/Tests/Unit/MSFT_xSQLServerScript.Tests.ps1#L140)):*
> ```PowerShell
> 
>     #region Set-TargetResource throws when Set Sql script throws
>     Describe 'Set-TargetResource throws when Set Sql script throws' {
> ```

Here you say you are testing Set-TargetResource, but you are actually testing all three methods. And the Test-TargetResource test is duplicated also. I think this will be clearer when you change the Describe/Context/It-blocks.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xsqlserver/156#-:-KU12omPn_Z6w0zSc_Oe:b-6xpwjt)*

**Comment by dcrreynolds** [comment]
Reviewable keeps showing me a sign in error. I believe I addressed all of the comments in the updated PR. Let me know what else you would like to see updated.

**Comment by johlju** [comment]
@dcrreynolds Could you please go into Reviewable and comment on those comments of mine that you are done with. You can just comment with 'Done' if nothing else. :)

You start Reviewable by clicking the big purple button at the top of this page. Then you go thru all comments and comment (it will auto save a draft as you type for each comment you make). After you have written all comments then you go to the top of the Revewable page and click the big green button Publish. This will send all your comments back to GitHub (as a comment on this page).

**Comment by dcrreynolds** [comment]
Now that I am no longer locked out of Reviewable, I am more then happy too.

---

Review status: 0 of 3 files reviewed at latest revision, 6 unresolved discussions.

---

*[Tests/Unit/MSFT_xSQLServerScript.Tests.ps1, line 28 at r1](https://reviewable.io:443/reviews/powershell/xsqlserver/156#-KU18ip5_hLwCwv3AmmG:-KWC46mGdQGq5XFzZvzp:b-896fix) ([raw file](https://github.com/powershell/xsqlserver/blob/766b75155509e0597c4778894b5e8b7417935b18/Tests/Unit/MSFT_xSQLServerScript.Tests.ps1#L28)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary>
> I think this class could come in handy for more resources in the future. What do you say about moving it into a seperate file? For example PowerShell.cs file in the stub folder (https://github.com/PowerShell/xSQLServer/tree/dev/Tests/Unit/Stubs), just like we did for the SMO classes (SMO.cs).
> 
> You load it by using
> ```
> # Loading mocked classes
> Add-Type -Path (Join-Path -Path $script:moduleRoot -ChildPath 'Tests\Unit\Stubs\PowerShell.cs')
> ```
</details>
Done.

---

*[Tests/Unit/MSFT_xSQLServerScript.Tests.ps1, line 44 at r1](https://reviewable.io:443/reviews/powershell/xsqlserver/156#-KU10CBf-qqQh-TBCOST:-KWC49q39r5cAtpetC1b:b-896fix) ([raw file](https://github.com/powershell/xsqlserver/blob/766b75155509e0597c4778894b5e8b7417935b18/Tests/Unit/MSFT_xSQLServerScript.Tests.ps1#L44)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary>
> To get better code coverage you should Mock Invoke-SqlCmd. And you can add the stubs to get the stub for Invoke-SqlCmd instead of adding a function in the test. Please change to mock Invoke-SqlCmd instead throughout the test.
> 
> Example of importing stub:
> https://github.com/PowerShell/xSQLServer/blob/dev/Tests/Unit/MSFT_xSQLServerEndpointState.Tests.ps1
> Stubs:
> https://github.com/PowerShell/xSQLServer/blob/dev/Tests/Unit/Stubs/SQLPSStub.psm1
> 
</details>
Done.

---

*[Tests/Unit/MSFT_xSQLServerScript.Tests.ps1, line 48 at r1](https://reviewable.io:443/reviews/powershell/xsqlserver/156#-KU15tHNDzgMByJQ5CNr:-KWC4QYIQ7k5gVSDjf4x:b-896fix) ([raw file](https://github.com/powershell/xsqlserver/blob/766b75155509e0597c4778894b5e8b7417935b18/Tests/Unit/MSFT_xSQLServerScript.Tests.ps1#L48)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary>
> Could you add `$script:DSCResourceName` to each Describe-block so it is easier to see which resource it is testing, and also preferable add `Get-TargetResource`, `Set-TargetResource` or `Test-TargetResource` to the description to either the Describe block or to a Context block so it's clear which method it is testing.
> Please see this test for examples: https://github.com/PowerShell/xSQLServer/blob/dev/Tests/Unit/MSFT_xSQLServerLogin.Tests.ps1
</details>
Done.

---

*[Tests/Unit/MSFT_xSQLServerScript.Tests.ps1, line 58 at r1](https://reviewable.io:443/reviews/powershell/xsqlserver/156#-KU16nL8q58a0X4LeGt4:-KWC4ek-PQZnCLlq5iDa:b-896fix) ([raw file](https://github.com/powershell/xsqlserver/blob/766b75155509e0597c4778894b5e8b7417935b18/Tests/Unit/MSFT_xSQLServerScript.Tests.ps1#L58)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary>
> Could you please change all It-blocks throughout the test so they start with `It 'Should...'`
> See unit template: https://github.com/PowerShell/DscResources/blob/master/Tests.Template/unit_template.ps1
> 
> For example:
> `It 'Should return the same values as passed as parameters'`
> `It 'Should throw when calling Invoke-SqlCmd` 
> 
> Also see this test for examples: https://github.com/PowerShell/xSQLServer/blob/dev/Tests/Unit/MSFT_xSQLServerLogin.Tests.ps1
> 
</details>
Done.

---

*[Tests/Unit/MSFT_xSQLServerScript.Tests.ps1, line 63 at r1](https://reviewable.io:443/reviews/powershell/xsqlserver/156#-KU19v_P1FvjXeaCuECC:-KWC50WYFbF6jZcmC8-k:b-896fix) ([raw file](https://github.com/powershell/xsqlserver/blob/766b75155509e0597c4778894b5e8b7417935b18/Tests/Unit/MSFT_xSQLServerScript.Tests.ps1#L63)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary>
> Please change all `should be` to `Should Be` (upper 'S' and upper 'B'). Do this throughout the test.
</details>
Done.

---

*[Tests/Unit/MSFT_xSQLServerScript.Tests.ps1, line 140 at r1](https://reviewable.io:443/reviews/powershell/xsqlserver/156#-KU1Dh1aRVtlKTzPowdk:-KWC52fR9OkrYR-uAYxb:b-896fix) ([raw file](https://github.com/powershell/xsqlserver/blob/766b75155509e0597c4778894b5e8b7417935b18/Tests/Unit/MSFT_xSQLServerScript.Tests.ps1#L140)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary>
> Here you say you are testing Set-TargetResource, but you are actually testing all three methods. And the Test-TargetResource test is duplicated also. I think this will be clearer when you change the Describe/Context/It-blocks.
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xsqlserver/156#-:-KWC5PlwE77GfegyjkTv:b-vnu4xv)*

**Comment by johlju** [comment]
Ah, you got the same error as I yesterday using Chrome. They fixed it a few hours ago. :)

I will go thru the tests one more time later today since it was a bunch of changes. Just one comment until then.

---

Reviewed 1 of 2 files at r1, 2 of 3 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[Tests/Unit/Stubs/SqlPowerShellSqlExecutionException.cs, line 9 at r3](https://reviewable.io:443/reviews/powershell/xsqlserver/156#-KWCfkLPFrH4AQdKvdKh:-KWCfkLPFrH4AQdKvdKi:b-pvy47n) ([raw file](https://github.com/powershell/xsqlserver/blob/74d435d3565475e28da33b0686a0edbd19585bf3/Tests/Unit/Stubs/SqlPowerShellSqlExecutionException.cs#L9)):*
> ```Smalltalk
>         }
>     }
> }
> ```

Could you please add a blank line at the end of the file? Seems that it is not one now.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xsqlserver/156#-:-KWCdzmuknHj2oq8qafr:b4ptt3e)*

**Comment by dcrreynolds** [comment]
Review status: 2 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[Tests/Unit/Stubs/SqlPowerShellSqlExecutionException.cs, line 9 at r3](https://reviewable.io:443/reviews/powershell/xsqlserver/156#-KWCfkLPFrH4AQdKvdKh:-KWEHAEK4_FVLm6Xat7x:b-896fix) ([raw file](https://github.com/powershell/xsqlserver/blob/74d435d3565475e28da33b0686a0edbd19585bf3/Tests/Unit/Stubs/SqlPowerShellSqlExecutionException.cs#L9)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary>
> Could you please add a blank line at the end of the file? Seems that it is not one now.
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xsqlserver/156)*

**Comment by johlju** [comment]
Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 14 unresolved discussions.

---

*[Tests/Unit/MSFT_xSQLServerScript.Tests.ps1, line 20 at r4](https://reviewable.io:443/reviews/powershell/xsqlserver/156#-KWH2hRBXjQ5Gwzq0KG2:-KWH2hRBXjQ5Gwzq0KG3:bgqjdgk) ([raw file](https://github.com/powershell/xsqlserver/blob/8e852400b820aa51a9f8e80418b4861c15627750/Tests/Unit/MSFT_xSQLServerScript.Tests.ps1#L20)):*
> ```PowerShell
> }
> 
> Import-Module (Join-Path -Path $script:moduleRoot -ChildPath 'DSCResource.Tests\TestHelper.psm1') -Force
> ```

Change to `Import-Module -Name ...` here

---

*[Tests/Unit/MSFT_xSQLServerScript.Tests.ps1, line 30 at r4](https://reviewable.io:443/reviews/powershell/xsqlserver/156#-KWH35U0vUxw5hhJX5Vi:-KWH35U0vUxw5hhJX5Vj:b-n9vy9h) ([raw file](https://github.com/powershell/xsqlserver/blob/8e852400b820aa51a9f8e80418b4861c15627750/Tests/Unit/MSFT_xSQLServerScript.Tests.ps1#L30)):*
> ```PowerShell
> 
> function Invoke-TestSetup {
>     Add-Type -Path (Join-Path -Path $script:moduleRoot -ChildPath 'Tests\Unit\Stubs\SqlPowerShellSqlExecutionException.cs')
> ```

PowerShell Team is looking for to remove all backslashes in paths. Could you change this line, and the line beneath, to use `Join-Path` to build the path instead? 

---

*[Tests/Unit/MSFT_xSQLServerScript.Tests.ps1, line 62 at r4](https://reviewable.io:443/reviews/powershell/xsqlserver/156#-KWH3WS7Oi2X_d5EQa05:-KWH3WS7Oi2X_d5EQa06:b-pim6e9) ([raw file](https://github.com/powershell/xsqlserver/blob/8e852400b820aa51a9f8e80418b4861c15627750/Tests/Unit/MSFT_xSQLServerScript.Tests.ps1#L62)):*
> ```PowerShell
>                 Mock -CommandName Import-Module -MockWith { throw $throwMessage } -ModuleName $sqlServerHelperModuleName
> 
>                 It 'Should throw an error' {
> ```

Change this to something like `'Should throw the correct error from Import-Module'`

---

*[Tests/Unit/MSFT_xSQLServerScript.Tests.ps1, line 71 at r4](https://reviewable.io:443/reviews/powershell/xsqlserver/156#-KWH4RXgmS7pWYJ8nzKX:-KWH4RXgmS7pWYJ8nzKY:beqv263) ([raw file](https://github.com/powershell/xsqlserver/blob/8e852400b820aa51a9f8e80418b4861c15627750/Tests/Unit/MSFT_xSQLServerScript.Tests.ps1#L71)):*
> ```PowerShell
>                 Mock -CommandName Invoke-Sqlcmd -MockWith { "" } -ModuleName $dscResourceName
> 
>                 $result = Get-TargetResource @testParameters
> ```

You could preferably move this into the It-block. Please also look at `Assert-MockCalled` using for example `-Context  It -Times 1` to verify your mocks are actually called.

---

*[Tests/Unit/MSFT_xSQLServerScript.Tests.ps1, line 82 at r4](https://reviewable.io:443/reviews/powershell/xsqlserver/156#-KWH5i-vqkfmI99TnRpq:-KWH5i-vqkfmI99TnRpr:b-dbixul) ([raw file](https://github.com/powershell/xsqlserver/blob/8e852400b820aa51a9f8e80418b4861c15627750/Tests/Unit/MSFT_xSQLServerScript.Tests.ps1#L82)):*
> ```PowerShell
>             }
> 
>             Context 'Get SQl script throws an error' {
> ```

You could change this to something like `'Get-TargetResource throws an error when running the script in GetFilePath parameter'`

---

*[Tests/Unit/MSFT_xSQLServerScript.Tests.ps1, line 88 at r4](https://reviewable.io:443/reviews/powershell/xsqlserver/156#-KWH50qyL2DfgqtKUujN:-KWH50qzYHkDiZI1WxR9:b-qldpuc) ([raw file](https://github.com/powershell/xsqlserver/blob/8e852400b820aa51a9f8e80418b4861c15627750/Tests/Unit/MSFT_xSQLServerScript.Tests.ps1#L88)):*
> ```PowerShell
>                 Mock -CommandName Invoke-Sqlcmd -MockWith { Throw $errorMessage } -ModuleName $script:DSCResourceName
> 
>                 It 'Should throw an error' {
> ```

Change this to something like `'Should throw the correct error from Invoke-Sqlcmd'`

---

*[Tests/Unit/MSFT_xSQLServerScript.Tests.ps1, line 101 at r4](https://reviewable.io:443/reviews/powershell/xsqlserver/156#-KWH5IQrSnVmSO3ZniCe:-KWH5IQrSnVmSO3ZniCf:b-8gtqmj) ([raw file](https://github.com/powershell/xsqlserver/blob/8e852400b820aa51a9f8e80418b4861c15627750/Tests/Unit/MSFT_xSQLServerScript.Tests.ps1#L101)):*
> ```PowerShell
>                 Mock -CommandName Import-Module -MockWith { throw $throwMessage } -ModuleName $sqlServerHelperModuleName
> 
>                 It 'Should throw an error' {
> ```

Same comment as above for the Get-method.

---

*[Tests/Unit/MSFT_xSQLServerScript.Tests.ps1, line 110 at r4](https://reviewable.io:443/reviews/powershell/xsqlserver/156#-KWH5X153AbElsQ4SbwG:-KWH5X153AbElsQ4SbwH:b-z82o2m) ([raw file](https://github.com/powershell/xsqlserver/blob/8e852400b820aa51a9f8e80418b4861c15627750/Tests/Unit/MSFT_xSQLServerScript.Tests.ps1#L110)):*
> ```PowerShell
>                 Mock -CommandName Invoke-Sqlcmd -MockWith { "" } -ModuleName $dscResourceName
> 
>                 $result = Set-TargetResource @testParameters
> ```

You could move this into the It-block

---

*[Tests/Unit/MSFT_xSQLServerScript.Tests.ps1, line 112 at r4](https://reviewable.io:443/reviews/powershell/xsqlserver/156#-KWH5aAw2ctoazarAoNL:-KWH5aAw2ctoazarAoNM:bf4s908) ([raw file](https://github.com/powershell/xsqlserver/blob/8e852400b820aa51a9f8e80418b4861c15627750/Tests/Unit/MSFT_xSQLServerScript.Tests.ps1#L112)):*
> ```PowerShell
>                 $result = Set-TargetResource @testParameters
> 
>                 It 'Should return the expected results' {
> ```

Please also look at `Assert-MockCalled` using for example `-Context  It -Times 1` to verify your mocks are actually called.

---

*[Tests/Unit/MSFT_xSQLServerScript.Tests.ps1, line 117 at r4](https://reviewable.io:443/reviews/powershell/xsqlserver/156#-KWH6pTyz20mgq9qPjon:-KWH6pTyz20mgq9qPjoo:b-69qk79) ([raw file](https://github.com/powershell/xsqlserver/blob/8e852400b820aa51a9f8e80418b4861c15627750/Tests/Unit/MSFT_xSQLServerScript.Tests.ps1#L117)):*
> ```PowerShell
>             }
> 
>             Context 'Set SQL script trhows an error' {
> ```

You could change this to something like `'Set-TargetResource throws an error when running the script in SetFilePath parameter'`

---

*[Tests/Unit/MSFT_xSQLServerScript.Tests.ps1, line 123 at r4](https://reviewable.io:443/reviews/powershell/xsqlserver/156#-KWH71XLnKPapK7zWUhV:-KWH71XLnKPapK7zWUhW:bxn08fy) ([raw file](https://github.com/powershell/xsqlserver/blob/8e852400b820aa51a9f8e80418b4861c15627750/Tests/Unit/MSFT_xSQLServerScript.Tests.ps1#L123)):*
> ```PowerShell
>                 Mock -CommandName Invoke-Sqlcmd -MockWith { Throw $errorMessage } -ModuleName $script:DSCResourceName
> 
>                 It 'Should throw an error' {
> ```

Please change to something like 'Should throw the correct error from Invoke-Sqlcmd'`

---

*[Tests/Unit/MSFT_xSQLServerScript.Tests.ps1, line 129 at r4](https://reviewable.io:443/reviews/powershell/xsqlserver/156#-KWH7lEkc2G9VopCtFew:-KWH7lEnoDFf6Ly63WDT:baskd2p) ([raw file](https://github.com/powershell/xsqlserver/blob/8e852400b820aa51a9f8e80418b4861c15627750/Tests/Unit/MSFT_xSQLServerScript.Tests.ps1#L129)):*
> ```PowerShell
>         }
>         
>         Describe "$dscResourceName\Test-TargetResource" {
> ```

Please change the phrases in this Describe-block as well depending on what/how you change above. :)

---

*[Tests/Unit/MSFT_xSQLServerScript.Tests.ps1, line 202 at r4](https://reviewable.io:443/reviews/powershell/xsqlserver/156#-KWH8Wc_8YlC7MiYwkbH:-KWH8Wc_8YlC7MiYwkbI:b5vtjik) ([raw file](https://github.com/powershell/xsqlserver/blob/8e852400b820aa51a9f8e80418b4861c15627750/Tests/Unit/MSFT_xSQLServerScript.Tests.ps1#L202)):*
> ```PowerShell
>                 $invokeScriptParameters.Add("Credential", $cred)
> 
>                 $null = Invoke-SqlScript @invokeScriptParameters
> ```

This could be moved into the It-block

---

*[Tests/Unit/MSFT_xSQLServerScript.Tests.ps1, line 205 at r4](https://reviewable.io:443/reviews/powershell/xsqlserver/156#-KWH8cedNTP-I0kZfg3u:-KWH8cedNTP-I0kZfg3v:bkrcq4u) ([raw file](https://github.com/powershell/xsqlserver/blob/8e852400b820aa51a9f8e80418b4861c15627750/Tests/Unit/MSFT_xSQLServerScript.Tests.ps1#L205)):*
> ```PowerShell
> 
>                 It 'Should call Invoke-Sqlcmd with correct parameters' {
>                     Assert-MockCalled -CommandName Invoke-Sqlcmd -Times 1 -Exactly -ParameterFilter { ($Username -eq $user) -and ($Password -eq $passwordPlain) }
> ```

If you move Invoke-SQLscript into the It block, you copuld also add `-Context It` to the assert.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xsqlserver/156)*

**Comment by dcrreynolds** [comment]
Review status: all files reviewed at latest revision, 14 unresolved discussions.

---

*[Tests/Unit/MSFT_xSQLServerScript.Tests.ps1, line 30 at r4](https://reviewable.io:443/reviews/powershell/xsqlserver/156#-KWH35U0vUxw5hhJX5Vi:-KX9IsVkN0mSahopHPR5:blmwrwh) ([raw file](https://github.com/powershell/xsqlserver/blob/8e852400b820aa51a9f8e80418b4861c15627750/Tests/Unit/MSFT_xSQLServerScript.Tests.ps1#L30)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary>
> PowerShell Team is looking for to remove all backslashes in paths. Could you change this line, and the line beneath, to use `Join-Path` to build the path instead? 
</details>
It is using Join-Path. Do you have an example of what you are wanting here? This is from the example you gave me previously. 

---

*[Tests/Unit/MSFT_xSQLServerScript.Tests.ps1, line 71 at r4](https://reviewable.io:443/reviews/powershell/xsqlserver/156#-KWH4RXgmS7pWYJ8nzKX:-KX9Jl5ULAcc4TxKbe1y:b-ze7bz9) ([raw file](https://github.com/powershell/xsqlserver/blob/8e852400b820aa51a9f8e80418b4861c15627750/Tests/Unit/MSFT_xSQLServerScript.Tests.ps1#L71)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary>
> You could preferably move this into the It-block. Please also look at `Assert-MockCalled` using for example `-Context  It -Times 1` to verify your mocks are actually called.
</details>
I can move the Get-TargetResource call within the It statement, but then adding another It statement to do the Assert-MockCalled would look strange scope wise.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xsqlserver/156)*

**Comment by johlju** [comment]
Review status: all files reviewed at latest revision, 14 unresolved discussions.

---

*[Tests/Unit/MSFT_xSQLServerScript.Tests.ps1, line 30 at r4](https://reviewable.io:443/reviews/powershell/xsqlserver/156#-KWH35U0vUxw5hhJX5Vi:-KX9mVK4eNT7q0I1xzw0:bn68f0k) ([raw file](https://github.com/powershell/xsqlserver/blob/8e852400b820aa51a9f8e80418b4861c15627750/Tests/Unit/MSFT_xSQLServerScript.Tests.ps1#L30)):*
<details><summary><i>Previously, dcrreynolds (David Reynolds) wrote…</i></summary>
> It is using Join-Path. Do you have an example of what you are wanting here? This is from the example you gave me previously. 
</details>
Yes, sorry. After I gave you that I got word that PowerShell team is looking to replace all backslashes in paths.  It is also in the Style Guideline now. You have an example here. 
https://github.com/PowerShell/DscResources/blob/master/StyleGuidelines.md#no-backslash-in-paths

---

*[Tests/Unit/MSFT_xSQLServerScript.Tests.ps1, line 71 at r4](https://reviewable.io:443/reviews/powershell/xsqlserver/156#-KWH4RXgmS7pWYJ8nzKX:-KX9nmOixyxdFGxZRqAq:b2w5t95) ([raw file](https://github.com/powershell/xsqlserver/blob/8e852400b820aa51a9f8e80418b4861c15627750/Tests/Unit/MSFT_xSQLServerScript.Tests.ps1#L71)):*
<details><summary><i>Previously, dcrreynolds (David Reynolds) wrote…</i></summary>
> I can move the Get-TargetResource call within the It statement, but then adding another It statement to do the Assert-MockCalled would look strange scope wise.
</details>
Sorry, I meant that you should move Get-TargetResource into the below It-block and do Assert-MockCalled in the same It-block. To make sure that the commands you mock actually are called.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xsqlserver/156)*

**Comment by johlju** [comment]
I'm pushing this thru even if the comments are not all done. I need this for other changes. I will fix those comments that remain in that PR.

:lgtm: 

---

Review status: all files reviewed at latest revision, 14 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xsqlserver/156#-:-K_LGqPuZdRVNREqmFAv:bmyiobk)*

**Comment by dcrreynolds** [comment]
Sorry this took so long for me to get back to. My original intention was to simply get the test running as is, then it grew in scope.

**Comment by johlju** [comment]
@dcrreynolds No worries! Glad you got things started! I was not a problem for me to resolve the last few bits. Now you have time to start on something else here instead 😉 

We have a lot of technical debt in this module so things tend to grow when changing something :/

**Pull request merged**
