### PR TITLE
Changes to xSQLServerMemory part:

### PR DESCRIPTION
**Pull request by Radamonas**
Changes to xSQLServerMemory
1. adding possibility to manager memory for multiply SQL instances. Changes were made to DSCResources/MSFT_xSQLServerMemory/MSFT_xSQLServerMemory.schema.mof file, another key value was added - SQLInstanceName;
2. adding possibility to manage memory for multiply SQL instances. Changes were made to  DSCResources/MSFT_xSQLServerMemory/MSFT_xSQLServerMemory.psm1 fileL
-  ammended change to accept 0 MB as MinMemory value, predefined value was set to -1, as 0 in all _if_ checks as _$false_;
-  SQLInstanceName value became mandatory for this xSQLServerMemory functionality.

---
This change is [Reviewable](https://reviewable.io/reviews/powershell/xsqlserver/49)

### CODE REVIEW

**Comment by kwirkykat** [comment]
Review status: 0 of 2 files reviewed at latest revision, 4 unresolved discussions.

---

*[DSCResources/MSFT_xSQLServerMemory/MSFT_xSQLServerMemory.psm1, line 70 \[r1\]](https://reviewable.io:443/reviews/powershell/xsqlserver/49#-KGODtvSXgOV0mdMfEIk:-KGODtvSXgOV0mdMfEIl:87612779) ([raw file](https://github.com/powershell/xsqlserver/blob/2684a4cec22737663cab18ba9b4832e596bb0a1f/DSCResources/MSFT_xSQLServerMemory/MSFT_xSQLServerMemory.psm1#L70)):*
Remove commented-out code
(You can add an informative comment somewhere if you think the user needs to know what the default value should be.)

---

*[DSCResources/MSFT_xSQLServerMemory/MSFT_xSQLServerMemory.psm1, line 128 \[r1\]](https://reviewable.io:443/reviews/powershell/xsqlserver/49#-KGODsF0FodLBMFt-VhC:-KGODsF0FodLBMFt-VhD:243174597) ([raw file](https://github.com/powershell/xsqlserver/blob/2684a4cec22737663cab18ba9b4832e596bb0a1f/DSCResources/MSFT_xSQLServerMemory/MSFT_xSQLServerMemory.psm1#L128)):*
Remove commented-out code

---

*[DSCResources/MSFT_xSQLServerMemory/MSFT_xSQLServerMemory.psm1, line 176 \[r1\]](https://reviewable.io:443/reviews/powershell/xsqlserver/49#-KGOD8lITuE50UH9P3re:-KGOBNT2YPFxaOAfkky0:-2022263538) ([raw file](https://github.com/powershell/xsqlserver/blob/2684a4cec22737663cab18ba9b4832e596bb0a1f/DSCResources/MSFT_xSQLServerMemory/MSFT_xSQLServerMemory.psm1#L176)):*
There needs to be a check here for $MinMemory -lt 0 to keep the same functionality. If  Ensure = 'Present' was declared without MinMemory, MaxMemory, or Dynamic Alloc declared, then the resource is being called incorrectly and the error needs to be thrown.

---

*[DSCResources/MSFT_xSQLServerMemory/MSFT_xSQLServerMemory.psm1, line 229 \[r1\]](https://reviewable.io:443/reviews/powershell/xsqlserver/49#-KGODpm-WIKBMy3toDAh:-KGODpm-WIKBMy3toDAi:243174597) ([raw file](https://github.com/powershell/xsqlserver/blob/2684a4cec22737663cab18ba9b4832e596bb0a1f/DSCResources/MSFT_xSQLServerMemory/MSFT_xSQLServerMemory.psm1#L229)):*
Remove commented-out code

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xsqlserver/49)*

**Comment by kwirkykat** [comment]
@Radamonas Please add your changes to the README per the [contributing guidelines](https://github.com/PowerShell/DscResource.Kit/blob/master/CONTRIBUTING.md).

**Comment by Radamonas** [comment]
Review status: 0 of 2 files reviewed at latest revision, 4 unresolved discussions.

---

*[DSCResources/MSFT_xSQLServerMemory/MSFT_xSQLServerMemory.psm1, line 128 \[r1\]](https://reviewable.io:443/reviews/powershell/xsqlserver/49#-KGODsF0FodLBMFt-VhC:-KGXQz3k9pprF2Y9EtEP:-499146009) ([raw file](https://github.com/powershell/xsqlserver/blob/2684a4cec22737663cab18ba9b4832e596bb0a1f/DSCResources/MSFT_xSQLServerMemory/MSFT_xSQLServerMemory.psm1#L128)):*
Done.

---

*[DSCResources/MSFT_xSQLServerMemory/MSFT_xSQLServerMemory.psm1, line 176 \[r1\]](https://reviewable.io:443/reviews/powershell/xsqlserver/49#-KGOD8lITuE50UH9P3re:-KGQV4RI0Fk_ExUQFtBc:695020551) ([raw file](https://github.com/powershell/xsqlserver/blob/2684a4cec22737663cab18ba9b4832e596bb0a1f/DSCResources/MSFT_xSQLServerMemory/MSFT_xSQLServerMemory.psm1#L176)):*
$MinMemory should not be mandatory, as according to documentation it can be shown as equal to 0 and remain as not defined and it can be equal 0 even it is recalculated as min. according to the environment (32bit or 64bit).

I'd thinking about changing the message below and validation into version below:
```
 if (!$MaxMemory -or ($MinMemory -gt $MaxMemory))
                    {
                        Throw "Dynamic Allocation is not set, Max memory was not passed or Min memory value is greater than Max memory."
                        Exit
                    } 
```

Also please note, that there is no possibility to provide negative value of $MinMemory value to set it on db as there is additional check below:
```
 if($MinMemory -ge 0)
            {
                Write-Verbose -message "MinMem will be set to $MinMemory."
                $sql.Configuration.MinServerMemory.ConfigValue = $MinMemory
            }
```

---

*[DSCResources/MSFT_xSQLServerMemory/MSFT_xSQLServerMemory.psm1, line 229 \[r1\]](https://reviewable.io:443/reviews/powershell/xsqlserver/49#-KGODpm-WIKBMy3toDAh:-KGXR0IjghMBrzVO_aEo:-499146009) ([raw file](https://github.com/powershell/xsqlserver/blob/2684a4cec22737663cab18ba9b4832e596bb0a1f/DSCResources/MSFT_xSQLServerMemory/MSFT_xSQLServerMemory.psm1#L229)):*
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xsqlserver/49)*

**Comment by Radamonas** [comment]
Review status: 0 of 3 files reviewed at latest revision, 4 unresolved discussions.

---

*[DSCResources/MSFT_xSQLServerMemory/MSFT_xSQLServerMemory.psm1, line 70 \[r1\]](https://reviewable.io:443/reviews/powershell/xsqlserver/49#-KGODtvSXgOV0mdMfEIk:-KHYl1yZk8nXfMohbrjd:-499146009) ([raw file](https://github.com/powershell/xsqlserver/blob/2684a4cec22737663cab18ba9b4832e596bb0a1f/DSCResources/MSFT_xSQLServerMemory/MSFT_xSQLServerMemory.psm1#L70)):*
<details><summary><i>Previously, kwirkykat wrote…</i></summary>
> Remove commented-out code
> (You can add an informative comment somewhere if you think the user needs to know what the default value should be.)</details>
Done.

---

*[DSCResources/MSFT_xSQLServerMemory/MSFT_xSQLServerMemory.psm1, line 128 \[r1\]](https://reviewable.io:443/reviews/powershell/xsqlserver/49#-KGODsF0FodLBMFt-VhC:-KHYl30oRJ9bpLZq_In9:-499146009) ([raw file](https://github.com/powershell/xsqlserver/blob/2684a4cec22737663cab18ba9b4832e596bb0a1f/DSCResources/MSFT_xSQLServerMemory/MSFT_xSQLServerMemory.psm1#L128)):*
<details><summary><i>Previously, Radamonas (Rapolas Dangveckas) wrote…</i></summary>
> Done.</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xsqlserver/49)*

**Comment by kwirkykat** [comment]
Reviewed 1 of 2 files at r1, 1 of 2 files at r2.
Review status: 2 of 3 files reviewed at latest revision, 3 unresolved discussions.

---

*[DSCResources/MSFT_xSQLServerMemory/MSFT_xSQLServerMemory.psm1, line 176 \[r1\]](https://reviewable.io:443/reviews/powershell/xsqlserver/49#-KGOD8lITuE50UH9P3re:-KIdmJa3w9KfF2PWNgwA:-1077633673) ([raw file](https://github.com/powershell/xsqlserver/blob/2684a4cec22737663cab18ba9b4832e596bb0a1f/DSCResources/MSFT_xSQLServerMemory/MSFT_xSQLServerMemory.psm1#L176)):*
<details><summary><i>Previously, Radamonas (Rapolas Dangveckas) wrote…</i></summary>
> $MinMemory should not be mandatory, as according to documentation it can be shown as equal to 0 and remain as not defined and it can be equal 0 even it is recalculated as min. according to the environment (32bit or 64bit).
> 
> I'd thinking about changing the message below and validation into version below:
> ```
>  if (!$MaxMemory -or ($MinMemory -gt $MaxMemory))
>                     {
>                         Throw "Dynamic Allocation is not set, Max memory was not passed or Min memory value is greater than Max memory."
>                         Exit
>                     } 
> ```
> 
> Also please note, that there is no possibility to provide negative value of $MinMemory value to set it on db as there is additional check below:
> ```
>  if($MinMemory -ge 0)
>             {
>                 Write-Verbose -message "MinMem will be set to $MinMemory."
>                 $sql.Configuration.MinServerMemory.ConfigValue = $MinMemory
>             }
> ```
> 
</details>
I don't think MinMemory should be mandatory, but previously, when DynamicAlloc was set to false and you did not supply MaxMemory but did supply a valid MinMemory (0 or greater), the resource would *not* throw an error. Now, if you supply a valid MinMemory value , but not a MaxMemory value, the resource will throw an error. 

Also to keep the error message clear, the check that MaxMemory or MinMemory is present and the check that MinMemory is not greater than MaxMemory should be separated. Like this:

```powershell
if  (-not $MaxMemory -or $MinMemory -lt 0) {
    throw "Dyanamic Allocation is not set. Valid values were not supplied for MaxMemory or MinMemory.
}

if ($MinMemory -gt $MaxMemory) {
    throw "MinMemory is greater than MaxMemory."
}
```

---

*[DSCResources/MSFT_xSQLServerMemory/MSFT_xSQLServerMemory.psm1, line 60 \[r2\]](https://reviewable.io:443/reviews/powershell/xsqlserver/49#-KIdp6GcXGpuiBAaY3j9:-KIdp6GcXGpuiBAaY3jA:652076223) ([raw file](https://github.com/powershell/xsqlserver/blob/79e99add1df5b3d177f2c31a4b0296a78f249a78/DSCResources/MSFT_xSQLServerMemory/MSFT_xSQLServerMemory.psm1#L60)):*
> ```PowerShell
> 
>         [System.Int32]
>         $MinMemory,
> ```

This should also be default to -1 to match the other TargetResource functions.

---

*[DSCResources/MSFT_xSQLServerMemory/MSFT_xSQLServerMemory.psm1, line 147 \[r2\]](https://reviewable.io:443/reviews/powershell/xsqlserver/49#-KIdfG5KowODW3MioFne:-KIdfG5KowODW3MioFnf:147130517) ([raw file](https://github.com/powershell/xsqlserver/blob/79e99add1df5b3d177f2c31a4b0296a78f249a78/DSCResources/MSFT_xSQLServerMemory/MSFT_xSQLServerMemory.psm1#L147)):*
> ```PowerShell
>                    $MaxMemory =2147483647
>                    $MinMemory = 128
>                 #} 
> ```

Please remove commented-out code.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xsqlserver/49)*

**Comment by Radamonas** [comment]
Review status: 2 of 3 files reviewed at latest revision, 3 unresolved discussions.

---

*[DSCResources/MSFT_xSQLServerMemory/MSFT_xSQLServerMemory.psm1, line 147 \[r2\]](https://reviewable.io:443/reviews/powershell/xsqlserver/49#-KIdfG5KowODW3MioFne:-KJ1Cuv1mID-Q1CIT7Bq:-499146009) ([raw file](https://github.com/powershell/xsqlserver/blob/79e99add1df5b3d177f2c31a4b0296a78f249a78/DSCResources/MSFT_xSQLServerMemory/MSFT_xSQLServerMemory.psm1#L147)):*
<details><summary><i>Previously, kwirkykat (Katie Keim) wrote…</i></summary>
> Please remove commented-out code.
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xsqlserver/49)*

**Comment by Radamonas** [comment]
Review status: 2 of 3 files reviewed at latest revision, 3 unresolved discussions.

---

*[DSCResources/MSFT_xSQLServerMemory/MSFT_xSQLServerMemory.psm1, line 176 \[r1\]](https://reviewable.io:443/reviews/powershell/xsqlserver/49#-KGOD8lITuE50UH9P3re:-KJL65JVSdAB1nsoUiIV:-499146009) ([raw file](https://github.com/powershell/xsqlserver/blob/2684a4cec22737663cab18ba9b4832e596bb0a1f/DSCResources/MSFT_xSQLServerMemory/MSFT_xSQLServerMemory.psm1#L176)):*
<details><summary><i>Previously, kwirkykat (Katie Keim) wrote…</i></summary>
> I don't think MinMemory should be mandatory, but previously, when DynamicAlloc was set to false and you did not supply MaxMemory but did supply a valid MinMemory (0 or greater), the resource would *not* throw an error. Now, if you supply a valid MinMemory value , but not a MaxMemory value, the resource will throw an error. 
> 
> Also to keep the error message clear, the check that MaxMemory or MinMemory is present and the check that MinMemory is not greater than MaxMemory should be separated. Like this:
> 
> ```powershell
> if  (-not $MaxMemory -or $MinMemory -lt 0) {
>     throw "Dyanamic Allocation is not set. Valid values were not supplied for MaxMemory or MinMemory.
> }
> 
> if ($MinMemory -gt $MaxMemory) {
>     throw "MinMemory is greater than MaxMemory."
> }
> ```
</details>
Done.

---

*[DSCResources/MSFT_xSQLServerMemory/MSFT_xSQLServerMemory.psm1, line 60 \[r2\]](https://reviewable.io:443/reviews/powershell/xsqlserver/49#-KIdp6GcXGpuiBAaY3j9:-KJL6Okl5-iFM9Q5xMVE:-499146009) ([raw file](https://github.com/powershell/xsqlserver/blob/79e99add1df5b3d177f2c31a4b0296a78f249a78/DSCResources/MSFT_xSQLServerMemory/MSFT_xSQLServerMemory.psm1#L60)):*
<details><summary><i>Previously, kwirkykat (Katie Keim) wrote…</i></summary>
> This should also be default to -1 to match the other TargetResource functions.
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xsqlserver/49)*

**Comment by Radamonas** [comment]
Review status: 2 of 3 files reviewed at latest revision, 3 unresolved discussions.

---

*[DSCResources/MSFT_xSQLServerMemory/MSFT_xSQLServerMemory.psm1, line 147 \[r2\]](https://reviewable.io:443/reviews/powershell/xsqlserver/49#-KIdfG5KowODW3MioFne:-KLLqhixaSGPh17B3kQW:-499146009) ([raw file](https://github.com/powershell/xsqlserver/blob/79e99add1df5b3d177f2c31a4b0296a78f249a78/DSCResources/MSFT_xSQLServerMemory/MSFT_xSQLServerMemory.psm1#L147)):*
<details><summary><i>Previously, Radamonas (Rapolas Dangveckas) wrote…</i></summary>
> Done.
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xsqlserver/49)*

**Comment by kwirkykat** [comment]
Review status: 2 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[DSCResources/MSFT_xSQLServerMemory/MSFT_xSQLServerMemory.psm1, line 176 \[r1\]](https://reviewable.io:443/reviews/powershell/xsqlserver/49#-KGOD8lITuE50UH9P3re:-KLM1iuxtyW2NRO9-uA9:717358040) ([raw file](https://github.com/powershell/xsqlserver/blob/2684a4cec22737663cab18ba9b4832e596bb0a1f/DSCResources/MSFT_xSQLServerMemory/MSFT_xSQLServerMemory.psm1#L176)):*
<details><summary><i>Previously, Radamonas (Rapolas Dangveckas) wrote…</i></summary>
> Done.
</details>
One last tiny change. It looks like this should be an -and rather than an -or (to avoid making $MinMemory mandatory) since it was an -xor before.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xsqlserver/49)*

**Comment by Radamonas** [comment]
Review status: 2 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[DSCResources/MSFT_xSQLServerMemory/MSFT_xSQLServerMemory.psm1, line 176 \[r1\]](https://reviewable.io:443/reviews/powershell/xsqlserver/49#-KGOD8lITuE50UH9P3re:-KM8VyDKyYTV4GPzttBp:360249279) ([raw file](https://github.com/powershell/xsqlserver/blob/2684a4cec22737663cab18ba9b4832e596bb0a1f/DSCResources/MSFT_xSQLServerMemory/MSFT_xSQLServerMemory.psm1#L176)):*
<details><summary><i>Previously, kwirkykat (Katie Keim) wrote…</i></summary>
> One last tiny change. It looks like this should be an -and rather than an -or (to avoid making $MinMemory mandatory) since it was an -xor before.
</details>
Hi, as -if we are discussing is within **-if ($DynamicAlloc) {} else {*-- here --*}** it doesn't seem reasonable to have suggested *-and*, as this part assumes that dynamic allocation was not requested and this leads to assumption that all values needed for memory setup has to be provided, so *-or* helps us to identify what one of both values were not provided when dynamic memory allocation was not chosen. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xsqlserver/49)*

**Comment by mbreakey3** [comment]
@Radamonas - Any updates on this PR?

**Comment by kwirkykat** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[DSCResources/MSFT_xSQLServerMemory/MSFT_xSQLServerMemory.psm1, line 176 \[r1\]](https://reviewable.io:443/reviews/powershell/xsqlserver/49#-KGOD8lITuE50UH9P3re:-KNmpm4Dmp7nwnDvuSon:-376232790) ([raw file](https://github.com/powershell/xsqlserver/blob/2684a4cec22737663cab18ba9b4832e596bb0a1f/DSCResources/MSFT_xSQLServerMemory/MSFT_xSQLServerMemory.psm1#L176)):*
<details><summary><i>Previously, Radamonas (Rapolas Dangveckas) wrote…</i></summary>
> Hi, as -if we are discussing is within **-if ($DynamicAlloc) {} else {*-- here --*}** it doesn't seem reasonable to have suggested *-and*, as this part assumes that dynamic allocation was not requested and this leads to assumption that all values needed for memory setup has to be provided, so *-or* helps us to identify what one of both values were not provided when dynamic memory allocation was not chosen. 
</details>
Ok. You're right

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xsqlserver/49)*

**Comment by aultt** [comment]
@kwirkykat can we merge this since all checks are good?

**Pull request merged**
