### PR TITLE
xSQLServerSetup: Allow Multiple DB Instances on One Box

### PR DESCRIPTION
**Pull request by OmarRizla**
We have updated the xSQLServerConfiguration.schema.mof file so SQLInstance is now a Key. This allows the SQLServerConfiguration resource to configure multiple instances on the same box as every schema.mof file entry will be uniquely named.

This Pull Request (PR) fixes the following issues:
n/a

- [x] Change details added to Unreleased section of CHANGELOG.md?
- [x] Added/updated documentation, comment-based help and descriptions in .schema.mof files where appropriate?
- [x] Examples appropriately updated?
- [x] New/changed code adheres to [Style Guidelines](https://github.com/PowerShell/DscResources/blob/master/StyleGuidelines.md)?
- [x] [Unit and (optional) Integration tests](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md) created/updated where possible?

---
This change is [Reviewable](https://reviewable.io/reviews/powershell/xsqlserver/348)

### CODE REVIEW

**Comment by johlju** [comment]
@OmarRizla Thansk for sending in your contribution again! 

There is a test failing. Can you please resolve that?
https://ci.appveyor.com/project/PowerShell/xsqlserver/build/5.0.794.0#L186

**Comment by OmarRizla** [comment]
No worries
I'll do that tomorrow...

Sent from my iPhone

On 26 Jan 2017, at 17:48, Johan Ljunggren <notifications@github.com<mailto:notifications@github.com>> wrote:


@OmarRizla<https://github.com/OmarRizla> Thansk for sending in your contribution again!

There is a test failing. Can you please resolve that?
https://ci.appveyor.com/project/PowerShell/xsqlserver/build/5.0.794.0#L186

-

**Comment by OmarRizla** [comment]
Hi Johan


I'll have to get to the failing unit test next week


Sorry for the delay...


Omar

________________________________

**Comment by johlju** [comment]
No worries! Get to it when you have time :)

**Pull request closed without merging**
