### PR TITLE
README.md: Changes to contributing and resource list section

### LINKED ISSUE #218: README.md: Change text in README.md to not mention System Center
> The **xSQLServer** module contains DSC resources for deployment and configuration of SQL Server in a way that is fully compliant with the requirements of System Center.

I think we should change this text to not include System Center. We are not working after any specific guidelines for just System Center. We are working to be compliant with most installations, right?

### LINKED ISSUE #222: README.md: Should list the resources in alphabetical order
**Details of the scenario you try and problem that is occurring:**
The resources listed in the README.md is not listed in alphabetical order. This change should be done to improve readability.

### PR DESCRIPTION
**Pull request by johlju**
Changes to README.md
  - Changed the contributing section to help new contributors.
  - Added links for each resource so it is easier to navigate to the parameter list for each resource.
  - Moved the list of resources in alphabetical order.
  - Moved each resource parameter list into alphabetical order.
  - Removed old text mentioning System Center.

This Pull Request (PR) fixes the following issues:
Fixes #222 
Fixes #218

- [x] Change details added to Unreleased section of CHANGELOG.md?
- [x] Added/updated documentation, comment-based help and descriptions in .schema.mof files where appropriate?
- [x] Examples appropriately updated?
- [x] New/changed code adheres to [Style Guidelines](https://github.com/PowerShell/DscResources/blob/master/StyleGuidelines.md)?
- [x] [Unit and (optional) Integration tests](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md) created/updated where possible?

---
This change is [Reviewable](https://reviewable.io/reviews/powershell/xsqlserver/281)

### CODE REVIEW

**Comment by FrokenSonja** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[README.md, line 15 at r1](https://reviewable.io:443/reviews/powershell/xsqlserver/281#-K_PLQN45kL7-6fHxjg4:-K_PLQN5CRb5j3horuPB:bborrq5) ([raw file](https://github.com/powershell/xsqlserver/blob/52e39eb8049ba55ebbed3781412b0ea2b6d5c39a/README.md#L15)):*
> And you can
You can also 

---

*[README.md, line 28 at r1](https://reviewable.io:443/reviews/powershell/xsqlserver/281#-K_PLdGj0mrwwMCCqlhY:-K_PLdGj0mrwwMCCqlhZ:blfv8y5) ([raw file](https://github.com/powershell/xsqlserver/blob/52e39eb8049ba55ebbed3781412b0ea2b6d5c39a/README.md#L28)):*
> And if 
If you 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xsqlserver/281)*

**Comment by johlju** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[README.md, line 15 at r1](https://reviewable.io:443/reviews/powershell/xsqlserver/281#-K_PLQN45kL7-6fHxjg4:-K_Z4YE1G4Sqt12D4ZBG:b-896fix) ([raw file](https://github.com/powershell/xsqlserver/blob/52e39eb8049ba55ebbed3781412b0ea2b6d5c39a/README.md#L15)):*
<details><summary><i>Previously, FrokenSonja wrote…</i></summary><blockquote>

> And you can
You can also 
</blockquote></details>

Done.

---

*[README.md, line 28 at r1](https://reviewable.io:443/reviews/powershell/xsqlserver/281#-K_PLdGj0mrwwMCCqlhY:-K_Z4YwwrFxPwwlWJ5qM:b-896fix) ([raw file](https://github.com/powershell/xsqlserver/blob/52e39eb8049ba55ebbed3781412b0ea2b6d5c39a/README.md#L28)):*
<details><summary><i>Previously, FrokenSonja wrote…</i></summary><blockquote>

> And if 
If you 
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xsqlserver/281)*

**Comment by FrokenSonja** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xsqlserver/281#-:-K_Z5O865dz7JHsW6d8f:bnfp4nl)*

**Comment by johlju** [comment]
:lgtm: 

---

Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xsqlserver/281#-:-K_Z5u9_sY1vo_U2MYBf:bg7igkv)*

**Comment by johlju** [comment]
Reviewed 1 of 2 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xsqlserver/281)*

**Pull request merged**
