### PR TITLE
xSQLServerMaxDop: Added Cluster Aware code

### LINKED ISSUE #882: xSQLServerMaxDop: Should Be Cluster Aware
**Details of the scenario you tried and the problem that is occurring:**
When the xSQLServerMaxDop resource is applied to all of the nodes in a Failover Cluster Instance (FCI), all of the nodes will connect to the instance and ensure the desired state is true even if the node is not currently hosting the instance.

**The DSC configuration that is using the resource (as detailed as possible):**
When the following configuration is applied to two or more nodes in a FCI.
```
xSQLServerLogin Add_WindowsUser
xSQLServerMaxDop Set_SQLServerMaxDop_ToAuto
{
    Ensure               = 'Present'
    DynamicAlloc         = $true
    SQLServer            = 'SQLServer'
    SQLInstanceName      = 'DSC'
    PsDscRunAsCredential = $SysAdminAccount
}
```

**Version of the Operating System, SQL Server and PowerShell the DSC Target Node is running:**
Any

**What module (SqlServer or SQLPS) and which version of the module the DSC Target Node is running:**
Any

**Version of the DSC module you're using, or 'dev' if you're using current dev branch:**
Any

### PR DESCRIPTION
**Pull request by PaulFeaser**
**Pull Request (PR) description**
Made the resource cluster aware. When ProcessOnlyOnActiveNode is specified, the resource will only determine if a change is needed if the target node is the active host of the SQL Server instance

**This Pull Request (PR) fixes the following issues:**
Fixes #882 

**Task List:**
- [x] Change details added to Unreleased section of CHANGELOG.md?
- [x] Added/updated documentation, comment-based help and descriptions in .schema.mof files where appropriate?
- [x] Examples appropriately updated?
- [x] New/changed code adheres to [Style Guidelines](https://github.com/PowerShell/DscResources/blob/master/StyleGuidelines.md)?
- [x] [Unit and (optional) Integration tests](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md) created/updated where possible?

---
This change is [Reviewable](https://reviewable.io/reviews/powershell/xsqlserver/901)

### CODE REVIEW

**Comment by johlju** [comment]
Thanks for sending this in! Great work on this one! :smile:  Just minor review comments.

---

Reviewed 6 of 6 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[DSCResources/MSFT_xSQLServerMaxDop/MSFT_xSQLServerMaxDop.psm1, line 238 at r1](https://reviewable.io:443/reviews/powershell/xsqlserver/901#-KyMmzHEawL10Zygmc4T:-KyMmzHEawL10Zygmc4U:b-dca78t) ([raw file](https://github.com/powershell/xsqlserver/blob/45bd845bfa4156650b12359398e512401dd21db6/DSCResources/MSFT_xSQLServerMaxDop/MSFT_xSQLServerMaxDop.psm1#L238)):*
> $script:localizedData.NotActiveClusterNode

This resource has not yet been localized so we can't use this method (there are no localized string file). We have to hard code the string. 

Like here:

https://github.com/PowerShell/xSQLServer/blob/1eddecbc424aec7b5c77eec70309cc8f88e10c7b/DSCResources/MSFT_xSQLServerAlwaysOnAvailabilityGroup/MSFT_xSQLServerAlwaysOnAvailabilityGroup.psm1#L625

---

*[Tests/Unit/MSFT_xSQLServerMaxDop.Tests.ps1, line 358 at r1](https://reviewable.io:443/reviews/powershell/xsqlserver/901#-KyMkOm7AWS7M68T3Eiz:-KyMkOm7AWS7M68T3Ej-:b-q7gtft) ([raw file](https://github.com/powershell/xsqlserver/blob/45bd845bfa4156650b12359398e512401dd21db6/Tests/Unit/MSFT_xSQLServerMaxDop.Tests.ps1#L358)):*
> <mockProcessOnlyOnActiveNode>

This is used with `-TestCases` parameter (Or I'm I wrong?). So maybe we need to set this the correct value if we are not using test cases? See below for example. But you could just hard code the correct value into the string if you don't want to use test cases.

https://github.com/PowerShell/xSQLServer/blob/1eddecbc424aec7b5c77eec70309cc8f88e10c7b/Tests/Unit/MSFT_xSQLServerAlwaysOnAvailabilityGroup.Tests.ps1#L1362-L1371

---

*[Tests/Unit/MSFT_xSQLServerMaxDop.Tests.ps1, line 372 at r1](https://reviewable.io:443/reviews/powershell/xsqlserver/901#-KyMmOeGvhOpgayvOuDF:-KyMmOeGvhOpgayvOuDG:b-cxfbnl) ([raw file](https://github.com/powershell/xsqlserver/blob/45bd845bfa4156650b12359398e512401dd21db6/Tests/Unit/MSFT_xSQLServerMaxDop.Tests.ps1#L372)):*
> ```PowerShell
>                 }
> 
>                 It 'Should be "true" when ProcessOnlyOnActiveNode is <mockProcessOnlyOnActiveNodeOriginal>.' {
> ```

Same as previous comment.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xsqlserver/901#-:-KyMnv8-GQ6vLOsydne8:b-q3l8sc)*

**Comment by PaulFeaser** [comment]
Review status: 4 of 6 files reviewed at latest revision, 3 unresolved discussions.

---

*[DSCResources/MSFT_xSQLServerMaxDop/MSFT_xSQLServerMaxDop.psm1, line 238 at r1](https://reviewable.io:443/reviews/powershell/xsqlserver/901#-KyMmzHEawL10Zygmc4T:-KyMzXPQLj-jiZAB8MS6:b-896fix) ([raw file](https://github.com/powershell/xsqlserver/blob/45bd845bfa4156650b12359398e512401dd21db6/DSCResources/MSFT_xSQLServerMaxDop/MSFT_xSQLServerMaxDop.psm1#L238)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

> $script:localizedData.NotActiveClusterNode

This resource has not yet been localized so we can't use this method (there are no localized string file). We have to hard code the string. 

Like here:

https://github.com/PowerShell/xSQLServer/blob/1eddecbc424aec7b5c77eec70309cc8f88e10c7b/DSCResources/MSFT_xSQLServerAlwaysOnAvailabilityGroup/MSFT_xSQLServerAlwaysOnAvailabilityGroup.psm1#L625
</blockquote></details>

Done.

---

*[Tests/Unit/MSFT_xSQLServerMaxDop.Tests.ps1, line 358 at r1](https://reviewable.io:443/reviews/powershell/xsqlserver/901#-KyMkOm7AWS7M68T3Eiz:-KyQn6yGYAKCTd__y1vr:bie77ws) ([raw file](https://github.com/powershell/xsqlserver/blob/45bd845bfa4156650b12359398e512401dd21db6/Tests/Unit/MSFT_xSQLServerMaxDop.Tests.ps1#L358)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

> <mockProcessOnlyOnActiveNode>

This is used with `-TestCases` parameter (Or I'm I wrong?). So maybe we need to set this the correct value if we are not using test cases? See below for example. But you could just hard code the correct value into the string if you don't want to use test cases.

https://github.com/PowerShell/xSQLServer/blob/1eddecbc424aec7b5c77eec70309cc8f88e10c7b/Tests/Unit/MSFT_xSQLServerAlwaysOnAvailabilityGroup.Tests.ps1#L1362-L1371
</blockquote></details>

I changed it so let me know if it is more what you were thinking.

---

*[Tests/Unit/MSFT_xSQLServerMaxDop.Tests.ps1, line 372 at r1](https://reviewable.io:443/reviews/powershell/xsqlserver/901#-KyMmOeGvhOpgayvOuDF:-KyQnI6759h2xLGSmkKE:b-qsy2qo) ([raw file](https://github.com/powershell/xsqlserver/blob/45bd845bfa4156650b12359398e512401dd21db6/Tests/Unit/MSFT_xSQLServerMaxDop.Tests.ps1#L372)):*
> I changed it so let me know if it is more what you were thinking.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xsqlserver/901)*

**Comment by johlju** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[Tests/Unit/MSFT_xSQLServerMaxDop.Tests.ps1, line 306 at r2](https://reviewable.io:443/reviews/powershell/xsqlserver/901#-KyR6TngEIojArKVDIqW:-KyR6TngEIojArKVDIqX:be6s8so) ([raw file](https://github.com/powershell/xsqlserver/blob/a6caab6e54cba65d2ef5bad097b7003d28538c36/Tests/Unit/MSFT_xSQLServerMaxDop.Tests.ps1#L306)):*
> 'When the system is not in the desired state and Ensure is set to absent and ProcessOnlyOnActiveNode is set to true'

This test actually mimics the previous test, that it should actually fail (return `$false`) because MaxDop has the wrong value (see It-block description in previous test), but because `ProcessOnlyOnActiveNode` is set to $true in this test, the test correctly returns `$true`. Maybe we should change the description here, or in the below It-block, to make that more clear?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xsqlserver/901)*

**Comment by PaulFeaser** [comment]
Review status: 5 of 6 files reviewed at latest revision, 1 unresolved discussion.

---

*[Tests/Unit/MSFT_xSQLServerMaxDop.Tests.ps1, line 306 at r2](https://reviewable.io:443/reviews/powershell/xsqlserver/901#-KyR6TngEIojArKVDIqW:-KyR_xQGdYL7u6iU8jAH:bshf6yf) ([raw file](https://github.com/powershell/xsqlserver/blob/a6caab6e54cba65d2ef5bad097b7003d28538c36/Tests/Unit/MSFT_xSQLServerMaxDop.Tests.ps1#L306)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

> 'When the system is not in the desired state and Ensure is set to absent and ProcessOnlyOnActiveNode is set to true'

This test actually mimics the previous test, that it should actually fail (return `$false`) because MaxDop has the wrong value (see It-block description in previous test), but because `ProcessOnlyOnActiveNode` is set to $true in this test, the test correctly returns `$true`. Maybe we should change the description here, or in the below It-block, to make that more clear?
</blockquote></details>

I changed the description and the It-Block verbiage

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xsqlserver/901)*

**Comment by PaulFeaser** [comment]
Review status: 5 of 6 files reviewed at latest revision, 1 unresolved discussion.

---

*[Tests/Unit/MSFT_xSQLServerMaxDop.Tests.ps1, line 306 at r2](https://reviewable.io:443/reviews/powershell/xsqlserver/901#-KyR6TngEIojArKVDIqW:-KyRaGVQTMPT6oF37M-M:b-896fix) ([raw file](https://github.com/powershell/xsqlserver/blob/a6caab6e54cba65d2ef5bad097b7003d28538c36/Tests/Unit/MSFT_xSQLServerMaxDop.Tests.ps1#L306)):*
<details><summary><i>Previously, PaulFeaser (Paul Feaser) wrote…</i></summary><blockquote>

I changed the description and the It-Block verbiage
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xsqlserver/901)*

**Comment by johlju** [comment]
:lgtm:

Tests looks good. Thanks! Awesome work! :smile: 

---

Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xsqlserver/901#-:-KyRgaG7hhdkpqSbaZY3:b-4kqj1o)*

**Pull request merged**
