### PR TITLE
Fix Ensure equal Present in xSQLServerRole resource (Fixes #151,#165)

### LINKED ISSUE #151: xSQLServerRole defaults to Ensure = Absent
xSQLServerRole defaults to Ensure = Absent because no default value is set in the resource. E.g. xSQLServerLogin is set to `[ValidateSet('Present', 'Absent')] [System.String] $Ensure = 'Present',` while xSQLServerRole is set to `[ValidateSet("Present","Absent")] [System.String] $Ensure,` causing it to default to Absent since the check in the resource is `if ($Ensure -eq "Present"){}...else{}`.

Is this by design? I would expect it to default to Present when not specified explicitly.

### PR DESCRIPTION
**Pull request by luigilink**
Fixes #151 and #165

Change xSQLServerRole Resource:
defaults to Ensure = Present

- [x] Change details added to Unreleased section of readme.md?
- [x] Added/updated documentation and descriptions in .schema.mof files where appropriate?
- [x] Examples appropriately updated?
- [x] New/changed code adheres to [Style Guidelines]?(https://github.com/PowerShell/DscResources/blob/master/StyleGuidelines.md)?
- [x] [Unit and Integration tests](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md) created/updated where possible?

This change is [Reviewable](https://reviewable.io/reviews/powershell/xsqlserver/154)

### CODE REVIEW

**Comment by mbreakey3** [comment]
It looks like you included changes to xSQLServerHelper.psm1 that you added in a different PR. So you either need to wait for that PR to be merged first or exclude those changes from this PR.

**Comment by johlju** [comment]
@luigilink since you have that new function in four PR's, should we focus on getting the PR #147 merged? I started the review on that one, and commented on this new function in the xSQLServerHelper.psm1 file.
After PR #147 is merged you should be able to rebase the other PR's to resolve the comment from @mbreakey3

**Comment by johlju** [comment]
@luigilink Seemed that PR #138 is further along with comments about this function than #147, so I added my comments to PR #138 too. So lets focus on getting #138 to merge first :)

**Comment by luigilink** [comment]
PR #138 is merged, "On hold" tag can be removed.
"Needs Review" Tag can be added.

**Comment by johlju** [comment]
Reviewed 2 of 3 files at r1, 5 of 5 files at r2.
Review status: all files reviewed at latest revision, 7 unresolved discussions.

---

*[xSQLServerHelper.psm1, line 647 at r2](https://reviewable.io:443/reviews/powershell/xsqlserver/154#-KW8t4haDyTj024b2ajy:-KW8t4haDyTj024b2ajz:b-o4mojw) ([raw file](https://github.com/powershell/xsqlserver/blob/7fc136ad2102657c8c5693356e9ab4c5e4346ab5/xSQLServerHelper.psm1#L647)):*
> ```PowerShell
> }
> 
> function Add-SqlServerRole
> ```

Could you rename this helper function to `Add-SqlServerRoleMember` and change the resource(s) accordingly?
See issue #165

---

*[xSQLServerHelper.psm1, line 688 at r2](https://reviewable.io:443/reviews/powershell/xsqlserver/154#-KW8t1gmQcL8mDJACvb6:-KW8t1gmQcL8mDJACvb7:b-tkhu65) ([raw file](https://github.com/powershell/xsqlserver/blob/7fc136ad2102657c8c5693356e9ab4c5e4346ab5/xSQLServerHelper.psm1#L688)):*
> ```PowerShell
> }
> 
> function Remove-SqlServerRole
> ```

Could you rename this helper function to `Remove-SqlServerRoleMember` and change the resource(s) accordingly?
See issue #165

---

*[xSQLServerHelper.psm1, line 729 at r2](https://reviewable.io:443/reviews/powershell/xsqlserver/154#-KW8sd7RvOn5_S3n-Zul:-KW8sd7RvOn5_S3n-Zum:b-78xlil) ([raw file](https://github.com/powershell/xsqlserver/blob/7fc136ad2102657c8c5693356e9ab4c5e4346ab5/xSQLServerHelper.psm1#L729)):*
> ```PowerShell
> }
> 
> function Confirm-SqlServerRole
> ```

Could you rename this helper function to `Confirm-SqlServerRoleMember` and change the resource(s) accordingly?
See issue #165

---

*[DSCResources/MSFT_xSQLServerRole/MSFT_xSQLServerRole.psm1, line 22 at r2](https://reviewable.io:443/reviews/powershell/xsqlserver/154#-KW8s4DEzSQpDk7SWcjt:-KW8s4DEzSQpDk7SWcju:b-9qdw3l) ([raw file](https://github.com/powershell/xsqlserver/blob/7fc136ad2102657c8c5693356e9ab4c5e4346ab5/DSCResources/MSFT_xSQLServerRole/MSFT_xSQLServerRole.psm1#L22)):*
> ```PowerShell
>         [ValidateSet("Present","Absent")]
>         [System.String]
>         $Ensure = "Present",
> ```

Please change to `Present`

---

*[DSCResources/MSFT_xSQLServerRole/MSFT_xSQLServerRole.psm1, line 79 at r2](https://reviewable.io:443/reviews/powershell/xsqlserver/154#-KW8s8vjQKAqKnLfVuqK:-KW8s8vjQKAqKnLfVuqL:b-9qdw3l) ([raw file](https://github.com/powershell/xsqlserver/blob/7fc136ad2102657c8c5693356e9ab4c5e4346ab5/DSCResources/MSFT_xSQLServerRole/MSFT_xSQLServerRole.psm1#L79)):*
> ```PowerShell
>         [ValidateSet("Present","Absent")]
>         [System.String]
>         $Ensure = "Present",
> ```

Please change to `Present`

---

*[DSCResources/MSFT_xSQLServerRole/MSFT_xSQLServerRole.psm1, line 124 at r2](https://reviewable.io:443/reviews/powershell/xsqlserver/154#-KW8sCKTcLA5uAenvpVv:-KW8sCKTcLA5uAenvpVw:b-9qdw3l) ([raw file](https://github.com/powershell/xsqlserver/blob/7fc136ad2102657c8c5693356e9ab4c5e4346ab5/DSCResources/MSFT_xSQLServerRole/MSFT_xSQLServerRole.psm1#L124)):*
> ```PowerShell
>         [ValidateSet("Present","Absent")]
>         [System.String]
>         $Ensure = "Present",
> ```

Please change to `Present`

---

*[DSCResources/MSFT_xSQLServerRole/MSFT_xSQLServerRole.schema.mof, line 6 at r2](https://reviewable.io:443/reviews/powershell/xsqlserver/154#-KW8u-vN1FxKUda7Vz1W:-KW8u-vOuRFrhQoySLu_:b399avb) ([raw file](https://github.com/powershell/xsqlserver/blob/7fc136ad2102657c8c5693356e9ab4c5e4346ab5/DSCResources/MSFT_xSQLServerRole/MSFT_xSQLServerRole.schema.mof#L6)):*
> ```
> {
>     [Key, Description("The name of the SQL login.  If LoginType='WindowsUser' or 'WindowsGroup', this is also the name of the user or group in format DOMAIN\name.")] String Name;
>     [Write, Description("Present to ensure that the login has the defined roles, or absent to ensure that these roles are not defined for the login. Default value is 'Present'"), ValueMap{"Present","Absent"}, Values{"Present","Absent"}] String Ensure;
> ```

Please add this parameter to the resources parameter list in the README.md. It is missing there. Please use the same description as here.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xsqlserver/154)*

**Comment by johlju** [comment]
Review status: all files reviewed at latest revision, 7 unresolved discussions.

---

*[DSCResources/MSFT_xSQLServerRole/MSFT_xSQLServerRole.psm1, line 22 at r2](https://reviewable.io:443/reviews/powershell/xsqlserver/154#-KW8s4DEzSQpDk7SWcjt:-KW8ucUOMXKNvtd_c1Ih:bryfyeh) ([raw file](https://github.com/powershell/xsqlserver/blob/7fc136ad2102657c8c5693356e9ab4c5e4346ab5/DSCResources/MSFT_xSQLServerRole/MSFT_xSQLServerRole.psm1#L22)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary>
> Please change to `Present`
</details>
I meant, please change to `'Present'`

---

*[DSCResources/MSFT_xSQLServerRole/MSFT_xSQLServerRole.psm1, line 79 at r2](https://reviewable.io:443/reviews/powershell/xsqlserver/154#-KW8s8vjQKAqKnLfVuqK:-KW8ugq-HU7HCdJhJSA1:bryfyeh) ([raw file](https://github.com/powershell/xsqlserver/blob/7fc136ad2102657c8c5693356e9ab4c5e4346ab5/DSCResources/MSFT_xSQLServerRole/MSFT_xSQLServerRole.psm1#L79)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary>
> Please change to `Present`
</details>
I meant, please change to `'Present'`

---

*[DSCResources/MSFT_xSQLServerRole/MSFT_xSQLServerRole.psm1, line 124 at r2](https://reviewable.io:443/reviews/powershell/xsqlserver/154#-KW8sCKTcLA5uAenvpVv:-KW8uhJ7as2qlLuhlLz1:bryfyeh) ([raw file](https://github.com/powershell/xsqlserver/blob/7fc136ad2102657c8c5693356e9ab4c5e4346ab5/DSCResources/MSFT_xSQLServerRole/MSFT_xSQLServerRole.psm1#L124)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary>
> Please change to `Present`
</details>
I meant, please change to `'Present'`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xsqlserver/154)*

**Comment by mgreenegit** [comment]
Reviewed 2 of 3 files at r1, 5 of 5 files at r2.
Review status: all files reviewed at latest revision, 7 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xsqlserver/154)*

**Comment by luigilink** [comment]
Reviewed 3 of 7 files at r3.
Review status: all files reviewed at latest revision, 7 unresolved discussions.

---

*[xSQLServerHelper.psm1, line 647 at r2](https://reviewable.io:443/reviews/powershell/xsqlserver/154#-KW8t4haDyTj024b2ajy:-KWEPH4Ufe6cPxcpYQJh:b-896fix) ([raw file](https://github.com/powershell/xsqlserver/blob/7fc136ad2102657c8c5693356e9ab4c5e4346ab5/xSQLServerHelper.psm1#L647)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary>
> Could you rename this helper function to `Add-SqlServerRoleMember` and change the resource(s) accordingly?
> See issue #165
</details>
Done.

---

*[xSQLServerHelper.psm1, line 688 at r2](https://reviewable.io:443/reviews/powershell/xsqlserver/154#-KW8t1gmQcL8mDJACvb6:-KWEPHhTcRlDzarC1Aem:b-896fix) ([raw file](https://github.com/powershell/xsqlserver/blob/7fc136ad2102657c8c5693356e9ab4c5e4346ab5/xSQLServerHelper.psm1#L688)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary>
> Could you rename this helper function to `Remove-SqlServerRoleMember` and change the resource(s) accordingly?
> See issue #165
</details>
Done.

---

*[xSQLServerHelper.psm1, line 729 at r2](https://reviewable.io:443/reviews/powershell/xsqlserver/154#-KW8sd7RvOn5_S3n-Zul:-KWEPIdlaRaSjqHH4ohB:b-896fix) ([raw file](https://github.com/powershell/xsqlserver/blob/7fc136ad2102657c8c5693356e9ab4c5e4346ab5/xSQLServerHelper.psm1#L729)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary>
> Could you rename this helper function to `Confirm-SqlServerRoleMember` and change the resource(s) accordingly?
> See issue #165
</details>
Done.

---

*[DSCResources/MSFT_xSQLServerRole/MSFT_xSQLServerRole.psm1, line 22 at r2](https://reviewable.io:443/reviews/powershell/xsqlserver/154#-KW8s4DEzSQpDk7SWcjt:-KWEPKqihFbIOREq6DAR:b-896fix) ([raw file](https://github.com/powershell/xsqlserver/blob/7fc136ad2102657c8c5693356e9ab4c5e4346ab5/DSCResources/MSFT_xSQLServerRole/MSFT_xSQLServerRole.psm1#L22)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary>
> I meant, please change to `'Present'`
</details>
Done.

---

*[DSCResources/MSFT_xSQLServerRole/MSFT_xSQLServerRole.psm1, line 79 at r2](https://reviewable.io:443/reviews/powershell/xsqlserver/154#-KW8s8vjQKAqKnLfVuqK:-KWEPLOUenH0zVCq2HqA:b-896fix) ([raw file](https://github.com/powershell/xsqlserver/blob/7fc136ad2102657c8c5693356e9ab4c5e4346ab5/DSCResources/MSFT_xSQLServerRole/MSFT_xSQLServerRole.psm1#L79)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary>
> I meant, please change to `'Present'`
</details>
Done.

---

*[DSCResources/MSFT_xSQLServerRole/MSFT_xSQLServerRole.psm1, line 124 at r2](https://reviewable.io:443/reviews/powershell/xsqlserver/154#-KW8sCKTcLA5uAenvpVv:-KWEPLtNX-qrBAWWwRZZ:b-896fix) ([raw file](https://github.com/powershell/xsqlserver/blob/7fc136ad2102657c8c5693356e9ab4c5e4346ab5/DSCResources/MSFT_xSQLServerRole/MSFT_xSQLServerRole.psm1#L124)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary>
> I meant, please change to `'Present'`
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xsqlserver/154)*

**Comment by luigilink** [comment]
Review status: all files reviewed at latest revision, 7 unresolved discussions.

---

*[DSCResources/MSFT_xSQLServerRole/MSFT_xSQLServerRole.schema.mof, line 6 at r2](https://reviewable.io:443/reviews/powershell/xsqlserver/154#-KW8u-vN1FxKUda7Vz1W:-KWEQAEnqIoD61QpSXp8:b-outit9) ([raw file](https://github.com/powershell/xsqlserver/blob/7fc136ad2102657c8c5693356e9ab4c5e4346ab5/DSCResources/MSFT_xSQLServerRole/MSFT_xSQLServerRole.schema.mof#L6)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary>
> Please add this parameter to the resources parameter list in the README.md. It is missing there. Please use the same description as here.
</details>
I don't see what is missing :cry: 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xsqlserver/154)*

**Comment by johlju** [comment]
Review status: all files reviewed at latest revision, 7 unresolved discussions.

---

*[DSCResources/MSFT_xSQLServerRole/MSFT_xSQLServerRole.schema.mof, line 6 at r2](https://reviewable.io:443/reviews/powershell/xsqlserver/154#-KW8u-vN1FxKUda7Vz1W:-KWEUPPZiPjEczTcLJDf:btw515z) ([raw file](https://github.com/powershell/xsqlserver/blob/7fc136ad2102657c8c5693356e9ab4c5e4346ab5/DSCResources/MSFT_xSQLServerRole/MSFT_xSQLServerRole.schema.mof#L6)):*
<details><summary><i>Previously, luigilink (Jean-Cyril Drouhin) wrote…</i></summary>
> I don't see what is missing :cry: 
</details>
In the README.md there are only four parameters
```
xSQLServerRole

Name: (Key) Name of the SQL Login to create
ServerRole: Type of SQL role to add.(bulkadmin, dbcreator, diskadmin, processadmin , public, securityadmin, serveradmin , setupadmin, sysadmin)
SQLServer: SQL Server where login should be created
SQLInstance: SQL Instance for the login
```

In the Schema there five parameters. Ensure is missing above in the README.md. :smile: 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xsqlserver/154)*

**Comment by johlju** [comment]
Reviewed 3 of 7 files at r3.
Review status: all files reviewed at latest revision, 8 unresolved discussions.

---

*[DSCResources/MSFT_xSQLServerRole/MSFT_xSQLServerRole.psm1, line 4 at r3](https://reviewable.io:443/reviews/powershell/xsqlserver/154#-KWEVPdZGI3WZRAB0_9e:-KWEVPdZGI3WZRAB0_9f:bv9b5kj) ([raw file](https://github.com/powershell/xsqlserver/blob/4862e93f282326de8ce21dda52af7056b61172a0/DSCResources/MSFT_xSQLServerRole/MSFT_xSQLServerRole.psm1#L4)):*
> ```PowerShell
> Write-Debug -Message "CurrentPath: $currentPath"
> 
> Import-Module -Name $currentPath\..\..\xSQLServerHelper.psm1 -Verbose:$false -ErrorAction Stop
> ```

Please change to this instead.
```
Import-Module -Name (Join-Path -Path (Split-Path (Split-Path $PSScriptRoot -Parent) -Parent) -ChildPath 'xSQLServerHelper.psm1') -Force
```
This is not in any guideline yet I believe, but PowerShell Team is looking to remove hard-coded '\' in paths.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xsqlserver/154)*

**Comment by johlju** [comment]
@luigilink Could you add `Fixes #165` to the "description" (first comment) of the PR? You know at the top, were you initially wrote 
```
Change xSQLServerRole Resource:

defaults to Ensure = Present
```
to 
```
Fixes #165

Change xSQLServerRole Resource:
defaults to Ensure = Present
```
I'm hoping that will auto-close issue #165 on merge. I'm not sure it will, but let's try :) You can only have on in the PR title I believe, haven't gotten it to work with several there.

**Comment by luigilink** [comment]
Need help 😢 
Why Pester Failed on files that was not commit by me ? oO

**Comment by johlju** [comment]
@luigilink I will look into the failing tests.

**Comment by johlju** [comment]
@luigilink The tests are fixed. You can do a rebase and push and tests should pass.

**Comment by johlju** [comment]
@luigilink Don't seem that you rebased? Got a lot of files that shouldn't be in this PR. :/ Also I see a commit that should not have appeared if you did rebase, the 'Rebase branch 'Fix-xSQLServerRole' commit. 
Did you use the command `git rebase`?

See guidance here
https://github.com/PowerShell/DscResources/blob/master/GettingStartedWithGitHub.md#resolve-merge-conflicts

**Comment by luigilink** [comment]
That's what I did 😞 
Can I did it again ? I think I made a mistake at the last step.

**Comment by johlju** [comment]
Yes you can do rebase as many times as you like, it just replays your changes again :)

**Comment by johlju** [comment]
On the other hand, since you added the last commit, you might need to do interactive rebase so you can skip the last commit you made `git rebase -i‘. Or rollback using reset.

If you need to test the steps, just copy the entire cloned folder on your hard drive so you have a backup if something goes wrong. I think that should work :)

**Comment by luigilink** [comment]
@johlju Thanks again for your help !!

The rebase works perfectly this time 😄

**Comment by luigilink** [comment]
Reviewed 1 of 1 files at r4, 2 of 2 files at r5.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[DSCResources/MSFT_xSQLServerRole/MSFT_xSQLServerRole.psm1, line 4 at r3](https://reviewable.io:443/reviews/powershell/xsqlserver/154#-KWEVPdZGI3WZRAB0_9e:-KX2K0JMxD0DXGlOxsww:b-896fix) ([raw file](https://github.com/powershell/xsqlserver/blob/4862e93f282326de8ce21dda52af7056b61172a0/DSCResources/MSFT_xSQLServerRole/MSFT_xSQLServerRole.psm1#L4)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary>
> Please change to this instead.
> ```
> Import-Module -Name (Join-Path -Path (Split-Path (Split-Path $PSScriptRoot -Parent) -Parent) -ChildPath 'xSQLServerHelper.psm1') -Force
> ```
> This is not in any guideline yet I believe, but PowerShell Team is looking to remove hard-coded '\' in paths.
</details>
Done.

---

*[DSCResources/MSFT_xSQLServerRole/MSFT_xSQLServerRole.schema.mof, line 6 at r2](https://reviewable.io:443/reviews/powershell/xsqlserver/154#-KW8u-vN1FxKUda7Vz1W:-KX2Jy8EnvKYWwp1bxLh:b-896fix) ([raw file](https://github.com/powershell/xsqlserver/blob/7fc136ad2102657c8c5693356e9ab4c5e4346ab5/DSCResources/MSFT_xSQLServerRole/MSFT_xSQLServerRole.schema.mof#L6)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary>
> In the README.md there are only four parameters
> ```
> xSQLServerRole
> 
> Name: (Key) Name of the SQL Login to create
> ServerRole: Type of SQL role to add.(bulkadmin, dbcreator, diskadmin, processadmin , public, securityadmin, serveradmin , setupadmin, sysadmin)
> SQLServer: SQL Server where login should be created
> SQLInstance: SQL Instance for the login
> ```
> 
> In the Schema there five parameters. Ensure is missing above in the README.md. :smile: 
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xsqlserver/154)*

**Comment by luigilink** [comment]
Reviewed 2 of 2 files at r7.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[DSCResources/MSFT_xSQLServerRole/MSFT_xSQLServerRole.psm1, line 4 at r3](https://reviewable.io:443/reviews/powershell/xsqlserver/154#-KWEVPdZGI3WZRAB0_9e:-KX5EDJeWToOyLLeXnPr:b-896fix) ([raw file](https://github.com/powershell/xsqlserver/blob/4862e93f282326de8ce21dda52af7056b61172a0/DSCResources/MSFT_xSQLServerRole/MSFT_xSQLServerRole.psm1#L4)):*
<details><summary><i>Previously, luigilink (Jean-Cyril Drouhin) wrote…</i></summary>
> Done.
</details>
Done.

---

*[DSCResources/MSFT_xSQLServerRole/MSFT_xSQLServerRole.schema.mof, line 6 at r2](https://reviewable.io:443/reviews/powershell/xsqlserver/154#-KW8u-vN1FxKUda7Vz1W:-KX5EENP5c1HIYITPyAv:b-896fix) ([raw file](https://github.com/powershell/xsqlserver/blob/7fc136ad2102657c8c5693356e9ab4c5e4346ab5/DSCResources/MSFT_xSQLServerRole/MSFT_xSQLServerRole.schema.mof#L6)):*
<details><summary><i>Previously, luigilink (Jean-Cyril Drouhin) wrote…</i></summary>
> Done.
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xsqlserver/154)*

**Comment by johlju** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r4, 2 of 2 files at r7.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xsqlserver/154#-:-KX6jjcL-2v9dp56SikT:bnfp4nl)*

**Pull request merged**
