### PR TITLE
xSQLServerConfiguration: Replace WMI with CIM

### PR DESCRIPTION
**Pull request by nabrond**
This PR makes the following changes:

- All usage of *-WMIObject have been replaced by CIM cmdlets (Issue #203)
- Updated unit tests to validate CIM changes
- Removed unnecessary logic in Get-TargetResource and Set-TargetResource
- Updated README to reflect changes

---
This change is [Reviewable](https://reviewable.io/reviews/powershell/xsqlserver/214)

### CODE REVIEW

**Comment by johlju** [comment]
Reviewed 1 of 3 files at r1.
Review status: 1 of 3 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[DSCResources/MSFT_xSQLServerConfiguration/MSFT_xSQLServerConfiguration.psm1, line 256 at r1](https://reviewable.io:443/reviews/powershell/xsqlserver/214#-KX6pU2AqTVmb6BeUKBr:-KX6pU2BBfQQ49THm761:bt7eqzn) ([raw file](https://github.com/powershell/xsqlserver/blob/a796b283c36149df768be7eefd04a3f188c48935/DSCResources/MSFT_xSQLServerConfiguration/MSFT_xSQLServerConfiguration.psm1#L256)):*
> ```PowerShell
>         ## Get the cluster resources
>         New-VerboseMessage -Message 'Getting cluster resource for SQL Server' 
>         $sqlService = Get-CimInstance -Namespace root/MSCluster -ClassName MSCluster_Resource -Filter "Type = 'SQL Server'" | 
> ```

When I try this 
```
$sqlService = Get-CimInstance -Namespace root/MSCluster -ClassName MSCluster_Resource -Filter "Type = 'SQL Server'"
```
I get error
```
Get-CimInstance : Invalid property 
At line:1 char:15
+ $sqlService = Get-CimInstance -Namespace root/MSCluster -ClassName MSCluster_Res ...
```

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xsqlserver/214)*

**Comment by nabrond** [comment]
*[DSCResources/MSFT_xSQLServerConfiguration/MSFT_xSQLServerConfiguration.psm1, line 256 at r1](https://reviewable.io:443/reviews/powershell/xsqlserver/214#-KX6pU2AqTVmb6BeUKBr:-KX774boyfgwZ-ZMU4CO:bwajnlu) ([raw file](https://github.com/powershell/xsqlserver/blob/a796b283c36149df768be7eefd04a3f188c48935/DSCResources/MSFT_xSQLServerConfiguration/MSFT_xSQLServerConfiguration.psm1#L256)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary>
> When I try this 
> ```
> $sqlService = Get-CimInstance -Namespace root/MSCluster -ClassName MSCluster_Resource -Filter "Type = 'SQL Server'"
> ```
> I get error
> ```
> Get-CimInstance : Invalid property 
> At line:1 char:15
> + $sqlService = Get-CimInstance -Namespace root/MSCluster -ClassName MSCluster_Res ...
> ```
</details>
What is your environment? I can run this code with PowerShell 5 on Windows 2012 R2 without error.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xsqlserver/214)*

**Comment by johlju** [comment]
Review status: 0 of 12 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[README.md, line 358 at r3](https://reviewable.io:443/reviews/powershell/xsqlserver/214#-KX9w4ZkUwBwXlm1e3PV:-KX9w4ZkUwBwXlm1e3PW:b3i54kl) ([raw file](https://github.com/powershell/xsqlserver/blob/5678372bc4e860bfe624c0b506b2b68ca541bb35/README.md#L358)):*
> ```Markdown
>   - BREAKING CHANGE: Updated parameters to align with other resources (SQLServer / SQLInstanceName)
>   - Added pester tests
>   - Change Get-WmiObject to Get-CimInstance and Get-CimAssociatedInstance in Resource and associated pester file.
> ```

The Unreleased section has been moved to the CHANGELOG.md. Please move your entries to the Unreleased section in the new CHANGELOG.md when you do `git rebase`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xsqlserver/214)*

**Comment by johlju** [comment]
@nabrond I would appreciate if you do a rebase against upstream. Now there are a lot of changes already merged that show up as changes in this PR also. Here is how to rebase
https://github.com/PowerShell/DscResources/blob/master/GettingStartedWithGitHub.md#resolve-merge-conflicts

---

Reviewed 2 of 10 files at r2.
Review status: 2 of 12 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xsqlserver/214#-:-KXA-ZA3I20WXbyVby8F:b3ywyoe)*

**Comment by nabrond** [comment]
Review status: 0 of 4 files reviewed at latest revision, 2 unresolved discussions.

---

*[README.md, line 358 at r3](https://reviewable.io:443/reviews/powershell/xsqlserver/214#-KX9w4ZkUwBwXlm1e3PV:-KXBW8NZyPadBjt-lBa4:b-896fix) ([raw file](https://github.com/powershell/xsqlserver/blob/5678372bc4e860bfe624c0b506b2b68ca541bb35/README.md#L358)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary>
> The Unreleased section has been moved to the CHANGELOG.md. Please move your entries to the Unreleased section in the new CHANGELOG.md when you do `git rebase`.
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xsqlserver/214)*

**Comment by nabrond** [comment]
@johlju I rebased this branch. The change list looks much better now!

**Comment by johlju** [comment]
:lgtm:

---

Reviewed 1 of 3 files at r1, 3 of 3 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xsqlserver/214#-:-KXBz3z8fBi8upR5G_2Q:bnfp4nl)*

**Pull request merged**
