### PR TITLE
xSQLServerAlwaysOnAvailabilityGroup : add Database Level Health Detection and Per Database DTC support / improve BasicAvailabilityGroup (Fixes #721)

### LINKED ISSUE #721: xSQLServerAlwaysOnAvailabilityGroup : add Database Level Health Detection and Per Database DTC support
**Details of the scenario you tried and the problem that is occurring:**

I work on the DSC configurations for an upgrade to SQL 2016. The environment uses an Always-On Cluster and we would like to use the option Database Level Health Detection.

I had a look at the resource and I can implement that. If you agree with this implementation, I will submit it to you. I also want to add the option Per Database DTC support in the resource at the same time.

Please share your thoughts.

**The DSC configuration that is using the resource (as detailed as possible):**

**Version of the Operating System, SQL Server and PowerShell the DSC Target Node is running:**
Windows Server 2016
SQL Server 2016 SP1 CU3
Powershell 5.1

**What module (SqlServer or SQLPS) and which version of the module the DSC Target Node is running:**
xSQLServer 8.0.0.0

**Version of the DSC module you're using, or 'dev' if you're using current dev branch:**

### PR DESCRIPTION
**Pull request by mdaniou**
**Pull Request (PR) description**

This PR is to implement the two new features in SQL Server 2016 :

**DatabaseHealthTrigger** : It is a boolean parameter. The resource will enable or disable it depending on its value
**DtcSupportEnabled** :	It is a boolean parameter. The resource will enable it only as this feature can be configured at the creation of the Availability Group.

I have also figured that there was an issue with the feature :
	
**BasicAvailabilityGroup** :
This feature is compatible with Standard Edition only. I have then added a check to ignore the feature depending on the Edition
The resource didn't allow us to disable the feature if we wanted because the check didn't take in account the fact that the parameter is a boolean.
	

**This Pull Request (PR) fixes the following issues:**

Fixes #721 

**Task list:**

- [x] Change details added to Unreleased section of CHANGELOG.md?
- [x] Added/updated documentation, comment-based help and descriptions in .schema.mof files where appropriate?
- [x] Examples appropriately updated?
- [x] New/changed code adheres to [Style Guidelines](https://github.com/PowerShell/DscResources/blob/master/StyleGuidelines.md)?
- [x] [Unit and (optional) Integration tests](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md) created/updated where possible?

---
This change is [Reviewable](https://reviewable.io/reviews/powershell/xsqlserver/722)

### CODE REVIEW

**Comment by johlju** [comment]
Can you look at the failing tests here See https://ci.appveyor.com/project/PowerShell/xsqlserver/build/6.0.1464.0

**Comment by johlju** [comment]
Please also update the parameters for the resource in the README.md.

When the tests are passing and README.md is updated I will start the review. I guess when tests are passing it will get coverage of the last nine rows it misses now?

Thanks for sending in this PR! 😄

**Comment by mdaniou** [comment]
It should be fine now, could you pls confirm ?

- [x] Remove tabs from .psm1
- [x] Update Readme
- [x] Add new example script

**Comment by johlju** [comment]
Getting there. :smile: There are still a few lint errors in the CHANGELOG.md
https://ci.appveyor.com/project/PowerShell/xsqlserver/build/6.0.1470.0#L1373

**Comment by johlju** [comment]
And the tests are failing for the resource here https://ci.appveyor.com/project/PowerShell/xsqlserver/build/6.0.1470.0#L1635

**Comment by mdaniou** [comment]
thanks, it seems like I need to spend some time understand the test mechanism :)

**Comment by johlju** [comment]
@mdaniou No worries. Take your time. :) If you have a problem with the Pester tests, let me know.

**Comment by mdaniou** [comment]
How can I run this test without having to commit my changes?

**Comment by johlju** [comment]
Make sure you have Pester PowerShell module installed. 

```
Install-Module Pester -Force - SkipPublisherCheck
```
Force is to install the newest version when another version exist. And SkipPublisherCheck is  ended it the old version exist and is signed by Microsoft.
You need latest version of Pester. 

After that you can just start the test you are working on. 

```
Invoke-Pester MSFT_xSQLServerAlwaysOnAvailibilityGroup.Tests.ps1
```

Just running `Invoke-Pester` will run all tests recursively in the current folder.

**Comment by johlju** [comment]
If you add the parameter `-CodeCoverage` and set it to the path of the resource module file, you will also get any rows that does not get hit by the test.

**Comment by mdaniou** [comment]
ok, thanks

**Comment by mdaniou** [comment]
I keep getting this error when I run that and I don't find the solution :

```
$mockNtServiceClusSvcName = ( New-Object -TypeName Microsoft.SqlServer.Management.Smo.Login($mockSqlServer,$mockNtServiceClusSvcName) )
New-Object : Exception calling ".ctor" with "2" argument(s): "SetParent failed for Login 'NTSERVICE\ClusSvc'. "
At line:2 char:47
+ ... SvcName = ( New-Object -TypeName Microsoft.SqlServer.Management.Smo.L ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [New-Object], MethodInvocationException
    + FullyQualifiedErrorId : ConstructorInvokedThrowException,Microsoft.PowerShell.Commands.NewObjectCommand
```

**Pull request closed without merging**
