### PR TITLE
Add module xSQLServer.Helper.psm1 in xSQLServer.psd1

### LINKED ISSUE #199: Instead of import helper module in each resource, can we add in psd1 file
Add module xSQLServer.Helper.psm1 in xSQLServer.psd1
Thanks to that, no need to import this module in each resource.

Suggested PR #198

### PR DESCRIPTION
**Pull request by luigilink**
Fixes #199 

Add module xSQLServer.Helper.psm1 in xSQLServer.psd1
Thanks to that, no need to import this module in each resource.

---
This change is [Reviewable](https://reviewable.io/reviews/powershell/xsqlserver/198)

### CODE REVIEW

**Comment by luigilink** [comment]
Bad idea with xPDT module, revert commit.

**Comment by johlju** [comment]
@luigilink I will fix the tests tomorrow.

**Comment by johlju** [comment]
I put this PR on-hold until you have fixed the PR according to issue #199

**Comment by luigilink** [comment]
@johlju When can we work on this PR ?
Maybe we have to focus on the remove of xPDT.psm1 first ?

**Comment by johlju** [comment]
I really would like to have unit testing on all resources first.
And yes, xPDT.psm1 would be good to remove as well. I'm hoping that is close though. As soon as xSQLServerSetup is working with installing SSAS into a cluster, then we can remove xSQLServerFailoverClusterSetup  When that is removed, we can change the way xSQLServerSetup is starting setup process (currently in PR). When all that is done we can remove all code in xPDT.psm1. And code coverage should increase significantly then as well.

I'm planning on testing SSAS functionality this weekend.

**Comment by johlju** [comment]
We need to https://github.com/PowerShell/xStorage/issues/93 into account. So we do not create the same issue with this one.

**Comment by johlju** [comment]
Closing this as per comment in issue https://github.com/PowerShell/xSQLServer/issues/199.

**Pull request closed without merging**
