### PR TITLE
xSQLServerRole: Fix for Issue #790

### LINKED ISSUE #790: xSQLServerRole: Returns an error when calling Get-DscConfiguration
xSQLServerRole DscRessource returns an error when running Get-DscConfiguration

Get-DscConfiguration : GetConfiguration did not succeed.

Event Log give some more details

Message Unable to cast object of type 'System.String' to type 'System.Collections.IList'.
Parameter name: value

Implicitly casting Return Value to a String Array fixes this issue, but there's probably a better way to do this.

    $returnValue = @{
        Ensure           = $ensure
        Members          = [System.String[]]$membersInRole
        MembersToInclude = [System.String[]]$MembersToInclude
        MembersToExclude = [System.String[]]$MembersToExclude
        ServerRoleName   = $ServerRoleName
        SQLServer        = $SQLServer
        SQLInstanceName  = $SQLInstanceName
    }

### PR DESCRIPTION
**Pull request by seizste**
**Pull Request (PR) description**
Explicit Casting to System.String[] for $membersInRole

**This Pull Request (PR) fixes the following issues:**
Fixes #790

**Task list:**
- [x] Change details added to Unreleased section of CHANGELOG.md?
- [x] Added/updated documentation, comment-based help and descriptions in .schema.mof files where appropriate?
- [x] Examples appropriately updated?
- [x] New/changed code adheres to [Style Guidelines](https://github.com/PowerShell/DscResources/blob/master/StyleGuidelines.md)?
- [x] [Unit and (optional) Integration tests](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md) created/updated where possible?

---
This change is [Reviewable](https://reviewable.io/reviews/powershell/xsqlserver/791)

### CODE REVIEW

**Comment by johlju** [comment]
First, thanks for sending this fix in! 😄 

Could you please 
* Add this change to the Unreleased section of the CHANGELOG.md.
* Add a regression test (that fails for the old code, and passes for the new code) in [MSFT_xSQLServerRole.Tests.ps1](https://github.com/PowerShell/xSQLServer/blob/dev/Tests/Unit/MSFT_xSQLServerRole.Tests.ps1).

**Comment by johlju** [comment]
If you need help with anything, let me know! 😄

**Comment by johlju** [comment]
I updated the PR description to use the template. You removed that by mistake when entering you PR description, when you sent in the PR.  It's easier for me to have the PR's use the template. But no worries. It was easy fixed. :)

**Comment by seizste** [comment]
Added entry to changelog.md and "Should return the members as string array"

**Comment by johlju** [comment]
Just minor review comments! Great work! :smile: 

---

Reviewed 1 of 1 files at r3, 2 of 2 files at r4.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[CHANGELOG.md, line 17 at r4](https://reviewable.io:443/reviews/powershell/xsqlserver/791#-KtMxycqntCvPVt70ZAz:-KtMxycqntCvPVt70ZB-:bbziyy2) ([raw file](https://github.com/powershell/xsqlserver/blob/d2bbb66a38d14737e5ec613a1392215fe27fc4a9/CHANGELOG.md#L17)):*
> Fixed Error due to Return Variable Type

Please change to something more descriptive. Like "When running Get-DscConfiguration it longer throws an error saying that the property Members is not an array ([Issue #790](https://github.com/PowerShell/xSQLServer/issues/790))."

---

*[DSCResources/MSFT_xSQLServerRole/MSFT_xSQLServerRole.psm1, line 70 at r4](https://reviewable.io:443/reviews/powershell/xsqlserver/791#-KtMynHsVdfveY-lxo-K:-KtMynHsVdfveY-lxo-L:b-inqcne) ([raw file](https://github.com/powershell/xsqlserver/blob/d2bbb66a38d14737e5ec613a1392215fe27fc4a9/DSCResources/MSFT_xSQLServerRole/MSFT_xSQLServerRole.psm1#L70)):*
> ```PowerShell
>             try
>             {
>                 [System.String[]]$membersInRole = $sqlServerRoleObject.EnumMemberNames()
> ```

Please add a space between the type and the variable name

```
[System.String[]] $membersInRole = ...
```

---

*[Tests/Unit/MSFT_xSQLServerRole.Tests.ps1, line 215 at r4](https://reviewable.io:443/reviews/powershell/xsqlserver/791#-KtMzlQgMHONXcaGgAh5:-KtMzlQgMHONXcaGgAh6:b-86ndm2) ([raw file](https://github.com/powershell/xsqlserver/blob/d2bbb66a38d14737e5ec613a1392215fe27fc4a9/Tests/Unit/MSFT_xSQLServerRole.Tests.ps1#L215)):*
> ```PowerShell
>                 }
> 
>                 It 'Should return the members as string array' {
> ```

Could you please add a comment saying that this is a regression test?

```
# Regression test for issue #790 
```

Please do this for each of these new tests

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xsqlserver/791#-:-KtN-5Tu-bS1CtyCsy2M:bepnu1k)*

**Comment by seizste** [comment]
Did the changes you mentioned in the review

**Comment by seizste** [comment]
i'm new to "code-review/reviewable", how can I acknowledge the changes you mentioned in the discussion ?

**Comment by johlju** [comment]
Could you please go into Reviewable and write 'Done' (or click the Done-button) on each review comment you solved (or comment if it needs to be discussed). After you replied on all review comments, then you press the big publish-button at the top of the Reviewable page and all your comments will be sent back here. 
When you do this I can acknowledge the comments which will resolve the reviews comments. 

You find the link to Reviewable in the big purple button in the PR description.

**Comment by seizste** [comment]
*[CHANGELOG.md, line 17 at r4](https://reviewable.io:443/reviews/powershell/xsqlserver/791#-KtMxycqntCvPVt70ZAz:-KtNaBHtIry2UKqHvZQU:b-896fix) ([raw file](https://github.com/powershell/xsqlserver/blob/d2bbb66a38d14737e5ec613a1392215fe27fc4a9/CHANGELOG.md#L17)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

> Fixed Error due to Return Variable Type

Please change to something more descriptive. Like "When running Get-DscConfiguration it longer throws an error saying that the property Members is not an array ([Issue #790](https://github.com/PowerShell/xSQLServer/issues/790))."
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xsqlserver/791)*

**Comment by seizste** [comment]
*[DSCResources/MSFT_xSQLServerRole/MSFT_xSQLServerRole.psm1, line 70 at r4](https://reviewable.io:443/reviews/powershell/xsqlserver/791#-KtMynHsVdfveY-lxo-K:-KtNaKaess-eFLv3Liah:b-896fix) ([raw file](https://github.com/powershell/xsqlserver/blob/d2bbb66a38d14737e5ec613a1392215fe27fc4a9/DSCResources/MSFT_xSQLServerRole/MSFT_xSQLServerRole.psm1#L70)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

Please add a space between the type and the variable name

```
[System.String[]] $membersInRole = ...
```
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xsqlserver/791)*

**Comment by seizste** [comment]
*[Tests/Unit/MSFT_xSQLServerRole.Tests.ps1, line 215 at r4](https://reviewable.io:443/reviews/powershell/xsqlserver/791#-KtMzlQgMHONXcaGgAh5:-KtNaLjj0ScwIqpno1JF:bvr4ce) ([raw file](https://github.com/powershell/xsqlserver/blob/d2bbb66a38d14737e5ec613a1392215fe27fc4a9/Tests/Unit/MSFT_xSQLServerRole.Tests.ps1#L215)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

Could you please add a comment saying that this is a regression test?

```
# Regression test for issue #790 
```

Please do this for each of these new tests
</blockquote></details>

Done, Added comment in front of Regression Test

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xsqlserver/791)*

**Comment by seizste** [comment]
Reviewed 1 of 1 files at r3, 2 of 2 files at r4, 3 of 3 files at r5.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xsqlserver/791)*

**Comment by johlju** [comment]
:lgtm:

---

Reviewed 3 of 3 files at r5.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xsqlserver/791#-:-KtS1jLiyJPpEYNrSokm:bnfp4nl)*

**Comment by johlju** [comment]
@seizste Awesome work! Thanks for this! 😄

**Comment by seizste** [comment]
@johlju Thanks for your help and guidance

**Pull request merged**
