### PR TITLE
xSQLServerDatabasePermission: Increase code coverage

### LINKED ISSUE #454: xSQLServerDatabasePermission: Unable to revoke permissions
**Details of the scenario you try and problem that is occurring:**
Attempt to revoke the Connect and Update permissions from COMPANY\John fails in an error.

```
PowerShell DSC resource MSFT_xSQLServerDatabasePermission  failed to execute Set-TargetResource functionality with error message: Failed to set permission for login named COMPANY\John of the database named MyDatabase1 on sqltest.company.local\
SQL2012.
    + CategoryInfo          : InvalidOperation: (:) [], CimException
    + FullyQualifiedErrorId : ProviderOperationExecutionFailure
```

**The DSC configuration that is using the resource (as detailed as possible):**
```
xSQLServerDatabasePermission 'RevokePermissionForJohnInMyDatabase1'
{
    Ensure = 'Absent'
    Name = 'COMPANY\John'
    Database = 'MyDatabase1'
    PermissionState = 'Grant'
    Permissions = 'Connect','Update'
    SQLServer = $Node.NodeName
    SQLInstanceName = $Node."$($currentSqlInstance)InstanceName"
    PsDscRunAsCredential = $SysAdminAccount
}
```
**Version of the Operating System, SQL Server and PowerShell the DSC Target Node is running:**
Windows Server 2012 R2, SQL Server 2012, WMF 5.0

**Version of the DSC module you're using, or 'dev' if you're using current dev branch:**
Dev (actually using the code in PR #440)

### LINKED ISSUE #589: Test-SQLDscParameterState: Helper function is referencing a helper function that does not exist
**Details of the scenario you tried and the problem that is occurring:**
The helper function `Test-SQLDscParameterState` is referencing another helper function that does not exist; `Test-SPDSCObjectHasProperty`.

This helper function is originally from the module SharePointDsc. So we should make sure this is updated with the missing helper function.

**The DSC configuration that is using the resource (as detailed as possible):**
n/a

**Version of the Operating System, SQL Server and PowerShell the DSC Target Node is running:**
n/a

**What module (SqlServer or SQLPS) and which version of the module the DSC Target Node is running:**
n/a

**Version of the DSC module you're using, or 'dev' if you're using current dev branch:**
n/a

### PR DESCRIPTION
**Pull request by luigilink**
xSQLServerDatabasePermission: Increase code coverage

- [x] Change details added to Unreleased section of CHANGELOG.md?
- [x] Added/updated documentation, comment-based help and descriptions in .schema.mof files where appropriate?
- [ ] Examples appropriately updated?
- [x] New/changed code adheres to [Style Guidelines](https://github.com/PowerShell/DscResources/blob/master/StyleGuidelines.md)?
- [x] [Unit and (optional) Integration tests](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md) created/updated where possible?

Fixes #454 
Fixes #589 

---
This change is [Reviewable](https://reviewable.io/reviews/powershell/xsqlserver/440)

### CODE REVIEW

**Comment by johlju** [comment]
:lgtm:

---

Reviewed 5 of 5 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xsqlserver/440#-:-KfRQh2pH7qfoLjwRXd0:bnfp4nl)*

**Comment by johlju** [comment]
The changes so far looks good. Although the tests are mocking the helper functions so they are never tested. Could you change the test so the helper functions are tested as well?
https://github.com/PowerShell/xSQLServer/blob/dev/Tests/Unit/MSFT_xSQLServerDatabasePermission.Tests.ps1

**Comment by luigilink** [comment]
@johlju I made a lot of changes. Good review 😄

**Comment by johlju** [comment]
Reviewed 3 of 3 files at r2, 3 of 3 files at r3.
Review status: all files reviewed at latest revision, 6 unresolved discussions, some commit checks failed.

---

*[DSCResources/MSFT_xSQLServerDatabasePermission/MSFT_xSQLServerDatabasePermission.psm1, line 43 at r3](https://reviewable.io:443/reviews/powershell/xsqlserver/440#-Kg51XQW4DwayGE7qsOU:-Kg51XQW4DwayGE7qsOV:b-9b0oj5) ([raw file](https://github.com/powershell/xsqlserver/blob/46f99a5dad8e34e9858ddb7c45e36c922575de72/DSCResources/MSFT_xSQLServerDatabasePermission/MSFT_xSQLServerDatabasePermission.psm1#L43)):*
> ```PowerShell
> 
>         [Parameter(Mandatory = $true)]
>         [ValidateNotNullOrEmpty()]
> ```

I don't think this is necessary. It already has a ValidateSet. 

---

*[DSCResources/MSFT_xSQLServerDatabasePermission/MSFT_xSQLServerDatabasePermission.psm1, line 190 at r3](https://reviewable.io:443/reviews/powershell/xsqlserver/440#-Kg51xPp4_MVQ_v-lhI-:-Kg51xPp4_MVQ_v-lhI0:b-9b0oj5) ([raw file](https://github.com/powershell/xsqlserver/blob/46f99a5dad8e34e9858ddb7c45e36c922575de72/DSCResources/MSFT_xSQLServerDatabasePermission/MSFT_xSQLServerDatabasePermission.psm1#L190)):*
> ```PowerShell
> 
>         [Parameter(Mandatory = $true)]
>         [ValidateNotNullOrEmpty()]
> ```

I don't think this is necessary. It already has a ValidateSet. 

---

*[DSCResources/MSFT_xSQLServerDatabasePermission/MSFT_xSQLServerDatabasePermission.psm1, line 350 at r3](https://reviewable.io:443/reviews/powershell/xsqlserver/440#-Kg52L3uXg8qoN_AL2VI:-Kg52L3uXg8qoN_AL2VJ:b-9b0oj5) ([raw file](https://github.com/powershell/xsqlserver/blob/46f99a5dad8e34e9858ddb7c45e36c922575de72/DSCResources/MSFT_xSQLServerDatabasePermission/MSFT_xSQLServerDatabasePermission.psm1#L350)):*
> ```PowerShell
> 
>         [Parameter(Mandatory = $true)]
>         [ValidateNotNullOrEmpty()]
> ```

I don't think this is necessary. It already has a ValidateSet. 

---

*[Tests/Unit/MSFT_xSQLServerDatabasePermission.Tests.ps1, line 132 at r3](https://reviewable.io:443/reviews/powershell/xsqlserver/440#-Kg55QRr5-epRDkFqtvf:-Kg55QRsVZUKbxlcklSj:b-ggvz21) ([raw file](https://github.com/powershell/xsqlserver/blob/46f99a5dad8e34e9858ddb7c45e36c922575de72/Tests/Unit/MSFT_xSQLServerDatabasePermission.Tests.ps1#L132)):*
> ```PowerShell
>                                             if ( $mockSqlServerLogin -ne $mockExpectedSqlServerLogin )
>                                             {
>                                                 throw "Called mocked Grant() method without setting the right login name. Expected '{0}'. But was '{1}'." `
> ```

Could you add a test to test this mock?

---

*[Tests/Unit/MSFT_xSQLServerDatabasePermission.Tests.ps1, line 150 at r3](https://reviewable.io:443/reviews/powershell/xsqlserver/440#-Kg55WxBkH2Maeq40pBx:-Kg55WxBkH2Maeq40pBy:b-ggvz21) ([raw file](https://github.com/powershell/xsqlserver/blob/46f99a5dad8e34e9858ddb7c45e36c922575de72/Tests/Unit/MSFT_xSQLServerDatabasePermission.Tests.ps1#L150)):*
> ```PowerShell
>                                             if ( $mockSqlServerLogin -ne $mockExpectedSqlServerLogin )
>                                             {
>                                                 throw "Called mocked Deny() method without setting the right login name. Expected '{0}'. But was '{1}'." `
> ```

Could you add a test to test this mock?

---

*[Tests/Unit/MSFT_xSQLServerDatabasePermission.Tests.ps1, line 186 at r3](https://reviewable.io:443/reviews/powershell/xsqlserver/440#-Kg55cYH87a5JgkE2ryT:-Kg55cYH87a5JgkE2ryU:b-ggvz21) ([raw file](https://github.com/powershell/xsqlserver/blob/46f99a5dad8e34e9858ddb7c45e36c922575de72/Tests/Unit/MSFT_xSQLServerDatabasePermission.Tests.ps1#L186)):*
> ```PowerShell
>                             if ( $this.Name -ne $mockExpectedForCreateMethod )
>                             {
>                                 throw "Called mocked Create() method without adding the right user. Expected '{0}'. But was '{1}'." `
> ```

Could you add a test to test this mock?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xsqlserver/440)*

**Comment by johlju** [comment]
@luigilink Could you check out issue #454? I ran your PR code in my lab just to verify. And get an error when trying to revoke permissions.

**Comment by luigilink** [comment]
@johlju You're right when Ensure is set to absent, I have an exception when I use the grant() method.

**Comment by johlju** [comment]
@luigilink I think you must use the Revoke() method to revoke permission. See the Revoke() method for a database here https://msdn.microsoft.com/en-us/library/ms205795.aspx.

**Comment by johlju** [comment]
@luigilink Do you need help with this one? Do you want me to run with this? If so please make sure maintainers may edit the PR. 😄

**Comment by luigilink** [comment]
Sorry for this long silence, now I have time to continue working on this PR.
I have also check "Allow edits from maintainers" option so you can edit if it's necessary.

**Comment by johlju** [comment]
No worries. I guessed you were busy working at the regular job :smile:

Let me know if you want me to do something to help :smile: Otherwise I wait for your updates to this PR and I will continue the review. 

Welcome back my friend! :smile:

**Comment by johlju** [comment]
@luigilink I have fixed the Revoke() and fixed the tests. I will review this one again tomorrow.

**Comment by johlju** [comment]
Review status: 0 of 8 files reviewed at latest revision, 1 unresolved discussion.

---

*[DSCResources/MSFT_xSQLServerDatabasePermission/MSFT_xSQLServerDatabasePermission.psm1, line 400 at r6](https://reviewable.io:443/reviews/powershell/xsqlserver/440#-KlAGbjxK8yw2XmcJljO:-KlAGbjxK8yw2XmcJljP:b-i8fymt) ([raw file](https://github.com/powershell/xsqlserver/blob/3402c85a74a9833e38bf41f55ca1b570c4c09c68/DSCResources/MSFT_xSQLServerDatabasePermission/MSFT_xSQLServerDatabasePermission.psm1#L400)):*
> ```PowerShell
>     return Test-SQLDscParameterState -CurrentValues $getTargetResourceResult `
>                                      -DesiredValues $PSBoundParameters `
>                                      -ValuesToCheck @('Name', 'Ensure', 'PermissionState')
> ```

Will this validate if the permissions are not correct? For example if desired state should be granted permissions for 'Connect','Update' and 'Alter'. But only the permissions 'Connect' and 'Update' is set for the user.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xsqlserver/440)*

**Comment by johlju** [comment]
Review status: 0 of 8 files reviewed at latest revision, 1 unresolved discussion.

---

*[DSCResources/MSFT_xSQLServerDatabasePermission/MSFT_xSQLServerDatabasePermission.psm1, line 400 at r6](https://reviewable.io:443/reviews/powershell/xsqlserver/440#-KlAGbjxK8yw2XmcJljO:-KlDGqgTl1tofh0F-_KD:bb6un1j) ([raw file](https://github.com/powershell/xsqlserver/blob/3402c85a74a9833e38bf41f55ca1b570c4c09c68/DSCResources/MSFT_xSQLServerDatabasePermission/MSFT_xSQLServerDatabasePermission.psm1#L400)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

Will this validate if the permissions are not correct? For example if desired state should be granted permissions for 'Connect','Update' and 'Alter'. But only the permissions 'Connect' and 'Update' is set for the user.
</blockquote></details>

Done

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xsqlserver/440)*

**Comment by johlju** [comment]
Reviewed 3 of 5 files at r4, 3 of 5 files at r6, 3 of 3 files at r7.
Review status: 7 of 8 files reviewed at latest revision, 2 unresolved discussions.

---

*[Tests/Unit/MSFT_xSQLServerDatabasePermission.Tests.ps1, line 41 at r7](https://reviewable.io:443/reviews/powershell/xsqlserver/440#-KlDkMq722iHcQdPI2p5:-KlDkMq722iHcQdPI2p6:b8atry0) ([raw file](https://github.com/powershell/xsqlserver/blob/390fc67ffbf7cab513513034a0c49ef115df1c02/Tests/Unit/MSFT_xSQLServerDatabasePermission.Tests.ps1#L41)):*
> $mockLogin

Rename this back to $mockSqlServerLogin

---

*[Tests/Unit/MSFT_xSQLServerDatabasePermission.Tests.ps1, line 42 at r7](https://reviewable.io:443/reviews/powershell/xsqlserver/440#-KlDkS45HzlniIKspF8l:-KlDkS45HzlniIKspF8m:b8nccp0) ([raw file](https://github.com/powershell/xsqlserver/blob/390fc67ffbf7cab513513034a0c49ef115df1c02/Tests/Unit/MSFT_xSQLServerDatabasePermission.Tests.ps1#L42)):*
> ```PowerShell
>         $mockSqlDatabaseName                          = 'AdventureWorks'
>         $mockLogin                                    = 'Zebes\SamusAran'
>         $mockLoginUnknown                             = 'Elysia\Chozo'
> ```

Rename this to $mockSqlServerLoginUnknown

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xsqlserver/440)*

**Comment by johlju** [comment]
Review status: 7 of 8 files reviewed at latest revision, 2 unresolved discussions.

---

*[Tests/Unit/MSFT_xSQLServerDatabasePermission.Tests.ps1, line 41 at r7](https://reviewable.io:443/reviews/powershell/xsqlserver/440#-KlDkMq722iHcQdPI2p5:-KlDopOe78ZLaHjCKVBd:bb6un1j) ([raw file](https://github.com/powershell/xsqlserver/blob/390fc67ffbf7cab513513034a0c49ef115df1c02/Tests/Unit/MSFT_xSQLServerDatabasePermission.Tests.ps1#L41)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

> $mockLogin

Rename this back to $mockSqlServerLogin
</blockquote></details>

Done

---

*[Tests/Unit/MSFT_xSQLServerDatabasePermission.Tests.ps1, line 42 at r7](https://reviewable.io:443/reviews/powershell/xsqlserver/440#-KlDkS45HzlniIKspF8l:-KlDoqWfufy8uOxEio_a:bb6un1j) ([raw file](https://github.com/powershell/xsqlserver/blob/390fc67ffbf7cab513513034a0c49ef115df1c02/Tests/Unit/MSFT_xSQLServerDatabasePermission.Tests.ps1#L42)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

Rename this to $mockSqlServerLoginUnknown
</blockquote></details>

Done

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xsqlserver/440)*

**Comment by johlju** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r8.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xsqlserver/440#-:-KlDp3CdfxXwA6tPJ67s:bnfp4nl)*

**Comment by johlju** [comment]
@luigilink I took this one to the finish line. Merged now. 😄

**Comment by luigilink** [comment]
@johlju Thank you so much to finish this one. Hope to have more time next week for contribute.

**Comment by johlju** [comment]
No problem. Happy to do it. Looking forward to more contributions.

**Pull request merged**
