### PR TITLE
Enable Codecov.io reporting

### LINKED ISSUE #387: Enable CodeCov.io code coverage reporting
Enable CodeCov.io code coverage reporting

### PR DESCRIPTION
**Pull request by TravisEz13**
Enable Codecov.io reporting

This Pull Request (PR) fixes the following issues:
fixes #387 

- [x] Change details added to Unreleased section of CHANGELOG.md?
- [x] Added/updated documentation, comment-based help and descriptions in .schema.mof files where appropriate?
- [x] Examples appropriately updated?
- [x] New/changed code adheres to [Style Guidelines](https://github.com/PowerShell/DscResources/blob/master/StyleGuidelines.md)?
- [x] [Unit and (optional) Integration tests](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md) created/updated where possible?

---
This change is [Reviewable](https://reviewable.io/reviews/powershell/xsqlserver/386)

### CODE REVIEW

**Comment by TravisEz13** [comment]
I can change the target down to 63% if you like.  @kwirkykat  and I discussed it.  We would rather have the project goal stay at 70% just as a reminder of this being the goal.

**Comment by johlju** [comment]
@TravisEz13 I think it is better for new contributors if the checks are green until we can actually hit the target of 70%. Otherwise I can imagine that they could get confused if they did something wrong. So If you don't mind I would rather set this to 63% now, and I will raise it now and again when we get more coverage. My goal is 95% coverage.

**Comment by TravisEz13** [comment]
done

**Comment by johlju** [comment]
:lgtm:

---

Reviewed 2 of 3 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xsqlserver/386#-:-Kd21uVcDntkRg1FM9yb:bnfp4nl)*

**Pull request merged**
