### PR TITLE
xSQLServerDatabaseOwner: Increase code coverage

### LINKED ISSUE #365: xSQLServerDatabaseOwner: Helper function Get-SqlDatabaseOwner is missing localization key 'FailedToGetOwnerDatabase'
**Details of the scenario you try and problem that is occurring:**
Helper function Get-SqlDatabaseOwner is referencing localization key 'FailedToGetOwnerDatabase' but it does not exist in xSQLServer.strings.psd1.
Localization key needs to be added with a correct descriptive error message.

**The DSC configuration that is using the resource (as detailed as possible):**
n/a

**Version of the Operating System, SQL Server and PowerShell the DSC Target Node is running:**
n/a

**Version of the DSC module you're using, or 'dev' if you're using current dev branch:**
Dev

### PR DESCRIPTION
**Pull request by luigilink**
xSQLServerDatabaseOwner: Increase code coverage

This Pull Request (PR) fixes the following issues:
Fixes #365

- [x] Change details added to Unreleased section of CHANGELOG.md?
- [x] Added/updated documentation, comment-based help and descriptions in .schema.mof files where appropriate?
- [x] Examples appropriately updated?
- [x] New/changed code adheres to [Style Guidelines](https://github.com/PowerShell/DscResources/blob/master/StyleGuidelines.md)?
- [x] [Unit and (optional) Integration tests](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md) created/updated where possible?

---
This change is [Reviewable](https://reviewable.io/reviews/powershell/xsqlserver/409)

### CODE REVIEW

**Comment by johlju** [comment]
It is hard keeping up with you pace, my friend 😉 

Thanks for sending in yet another one. 😄

**Comment by luigilink** [comment]
And it's not over yet 😋

**Comment by johlju** [comment]
I review the test tomorrow. Time for bed now. :)

---

Reviewed 6 of 7 files at r1.
Review status: 6 of 7 files reviewed at latest revision, 9 unresolved discussions.

---

*[DSCResources/MSFT_xSQLServerDatabaseOwner/MSFT_xSQLServerDatabaseOwner.psm1, line 27 at r1](https://reviewable.io:443/reviews/powershell/xsqlserver/409#-Ke0cPeickijhoPJ6yUP:-Ke0cPeickijhoPJ6yUQ:b-jqsml0) ([raw file](https://github.com/powershell/xsqlserver/blob/694e35b33a07f68520d8ce7fd74052bfcf06224b/DSCResources/MSFT_xSQLServerDatabaseOwner/MSFT_xSQLServerDatabaseOwner.psm1#L27)):*
> ```PowerShell
>     (
>         [Parameter(Mandatory = $true)]
>         [System.String]
> ```

ValidateNullOrEmpty here to?

---

*[DSCResources/MSFT_xSQLServerDatabaseOwner/MSFT_xSQLServerDatabaseOwner.psm1, line 52 at r1](https://reviewable.io:443/reviews/powershell/xsqlserver/409#-Ke0beYBWeNasugtHZwU:-Ke0beYBWeNasugtHZwV:b-jtkyxw) ([raw file](https://github.com/powershell/xsqlserver/blob/694e35b33a07f68520d8ce7fd74052bfcf06224b/DSCResources/MSFT_xSQLServerDatabaseOwner/MSFT_xSQLServerDatabaseOwner.psm1#L52)):*
> ```PowerShell
>     {
>         # Check database exists
>         if ( -NOT($getSqlDatabase = $sqlServerObject.Databases[$Database]) )
> ```

`-not (` -lower case letters, and space before '('

---

*[DSCResources/MSFT_xSQLServerDatabaseOwner/MSFT_xSQLServerDatabaseOwner.psm1, line 52 at r1](https://reviewable.io:443/reviews/powershell/xsqlserver/409#-Ke0c-nUj4hnzB06SUzt:-Ke0c-nUj4hnzB06SUzu:b-dvtq55) ([raw file](https://github.com/powershell/xsqlserver/blob/694e35b33a07f68520d8ce7fd74052bfcf06224b/DSCResources/MSFT_xSQLServerDatabaseOwner/MSFT_xSQLServerDatabaseOwner.psm1#L52)):*
> ```PowerShell
>     {
>         # Check database exists
>         if ( -NOT($getSqlDatabase = $sqlServerObject.Databases[$Database]) )
> ```

$getSqlDatabase change to $sqlDatabaseObject

---

*[DSCResources/MSFT_xSQLServerDatabaseOwner/MSFT_xSQLServerDatabaseOwner.psm1, line 61 at r1](https://reviewable.io:443/reviews/powershell/xsqlserver/409#-Ke0cB6zFWfVJrPCeQSY:-Ke0cB6zFWfVJrPCeQSZ:b-bf62i4) ([raw file](https://github.com/powershell/xsqlserver/blob/694e35b33a07f68520d8ce7fd74052bfcf06224b/DSCResources/MSFT_xSQLServerDatabaseOwner/MSFT_xSQLServerDatabaseOwner.psm1#L61)):*
> ```PowerShell
>         try
>         {
>             $getSqlDatabaseOwner = $getSqlDatabase.Owner
> ```

change to $sqlDatabaseOwner

---

*[DSCResources/MSFT_xSQLServerDatabaseOwner/MSFT_xSQLServerDatabaseOwner.psm1, line 105 at r1](https://reviewable.io:443/reviews/powershell/xsqlserver/409#-Ke0cTKCXEH7s4MEYOmA:-Ke0cTKCXEH7s4MEYOmB:b9dubsp) ([raw file](https://github.com/powershell/xsqlserver/blob/694e35b33a07f68520d8ce7fd74052bfcf06224b/DSCResources/MSFT_xSQLServerDatabaseOwner/MSFT_xSQLServerDatabaseOwner.psm1#L105)):*
> ```PowerShell
>         [Parameter(Mandatory = $true)]
>         [System.String]
>         $Database,
> ```

Validate NullOrempty here too?

---

*[DSCResources/MSFT_xSQLServerDatabaseOwner/MSFT_xSQLServerDatabaseOwner.psm1, line 129 at r1](https://reviewable.io:443/reviews/powershell/xsqlserver/409#-Ke0cY60Qd_G77DHzDS6:-Ke0cY60Qd_G77DHzDS7:b-jtkyxw) ([raw file](https://github.com/powershell/xsqlserver/blob/694e35b33a07f68520d8ce7fd74052bfcf06224b/DSCResources/MSFT_xSQLServerDatabaseOwner/MSFT_xSQLServerDatabaseOwner.psm1#L129)):*
> ```PowerShell
>     {
>         # Check database exists
>         if ( -NOT($getSqlDatabase = $sqlServerObject.Databases[$Database]) )
> ```

`-not (` -lower case letters, and space before '('

---

*[DSCResources/MSFT_xSQLServerDatabaseOwner/MSFT_xSQLServerDatabaseOwner.psm1, line 129 at r1](https://reviewable.io:443/reviews/powershell/xsqlserver/409#-Ke0cZ3_33PlQdLicfAf:-Ke0cZ3_33PlQdLicfAg:b-7bk085) ([raw file](https://github.com/powershell/xsqlserver/blob/694e35b33a07f68520d8ce7fd74052bfcf06224b/DSCResources/MSFT_xSQLServerDatabaseOwner/MSFT_xSQLServerDatabaseOwner.psm1#L129)):*
> ```PowerShell
>     {
>         # Check database exists
>         if ( -NOT($getSqlDatabase = $sqlServerObject.Databases[$Database]) )
> ```

Chnage $getSqlDatabase to $sqlDatabaseObject

---

*[DSCResources/MSFT_xSQLServerDatabaseOwner/MSFT_xSQLServerDatabaseOwner.psm1, line 135 at r1](https://reviewable.io:443/reviews/powershell/xsqlserver/409#-Ke0cdrKcKXHIdi-U6U_:-Ke0cdrKcKXHIdi-U6Ua:b-jtkyxw) ([raw file](https://github.com/powershell/xsqlserver/blob/694e35b33a07f68520d8ce7fd74052bfcf06224b/DSCResources/MSFT_xSQLServerDatabaseOwner/MSFT_xSQLServerDatabaseOwner.psm1#L135)):*
> ```PowerShell
> 
>         # Check login exists
>         if ( -NOT($sqlServerObject.Logins[$Name]) )
> ```

`-not (` -lower case letters, and space before '('

---

*[DSCResources/MSFT_xSQLServerDatabaseOwner/MSFT_xSQLServerDatabaseOwner.psm1, line 179 at r1](https://reviewable.io:443/reviews/powershell/xsqlserver/409#-Ke0cnHNAX5CUOMPw9IG:-Ke0cnHNAX5CUOMPw9IH:br7d2w3) ([raw file](https://github.com/powershell/xsqlserver/blob/694e35b33a07f68520d8ce7fd74052bfcf06224b/DSCResources/MSFT_xSQLServerDatabaseOwner/MSFT_xSQLServerDatabaseOwner.psm1#L179)):*
> ```PowerShell
>         [Parameter(Mandatory = $true)]
>         [System.String]
>         $Database,
> ```

ValidateNullOrEmpty here too?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xsqlserver/409#-:-Ke0cy1atJ6ozLMSBmRi:b93cuqg)*

**Comment by luigilink** [comment]
Reviewed 1 of 1 files at r2.
Review status: 6 of 7 files reviewed at latest revision, 9 unresolved discussions.

---

*[DSCResources/MSFT_xSQLServerDatabaseOwner/MSFT_xSQLServerDatabaseOwner.psm1, line 27 at r1](https://reviewable.io:443/reviews/powershell/xsqlserver/409#-Ke0cPeickijhoPJ6yUP:-Ke38adfZgNeleKLHjVD:b-896fix) ([raw file](https://github.com/powershell/xsqlserver/blob/694e35b33a07f68520d8ce7fd74052bfcf06224b/DSCResources/MSFT_xSQLServerDatabaseOwner/MSFT_xSQLServerDatabaseOwner.psm1#L27)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

ValidateNullOrEmpty here to?
</blockquote></details>

Done.

---

*[DSCResources/MSFT_xSQLServerDatabaseOwner/MSFT_xSQLServerDatabaseOwner.psm1, line 52 at r1](https://reviewable.io:443/reviews/powershell/xsqlserver/409#-Ke0beYBWeNasugtHZwU:-Ke38bfItbRvZyF-_iiy:b-896fix) ([raw file](https://github.com/powershell/xsqlserver/blob/694e35b33a07f68520d8ce7fd74052bfcf06224b/DSCResources/MSFT_xSQLServerDatabaseOwner/MSFT_xSQLServerDatabaseOwner.psm1#L52)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

`-not (` -lower case letters, and space before '('
</blockquote></details>

Done.

---

*[DSCResources/MSFT_xSQLServerDatabaseOwner/MSFT_xSQLServerDatabaseOwner.psm1, line 52 at r1](https://reviewable.io:443/reviews/powershell/xsqlserver/409#-Ke0c-nUj4hnzB06SUzt:-Ke38cWMc3k0eTTAzdix:b-896fix) ([raw file](https://github.com/powershell/xsqlserver/blob/694e35b33a07f68520d8ce7fd74052bfcf06224b/DSCResources/MSFT_xSQLServerDatabaseOwner/MSFT_xSQLServerDatabaseOwner.psm1#L52)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

$getSqlDatabase change to $sqlDatabaseObject
</blockquote></details>

Done.

---

*[DSCResources/MSFT_xSQLServerDatabaseOwner/MSFT_xSQLServerDatabaseOwner.psm1, line 61 at r1](https://reviewable.io:443/reviews/powershell/xsqlserver/409#-Ke0cB6zFWfVJrPCeQSY:-Ke38dIRXeV22nMEYiS7:b-896fix) ([raw file](https://github.com/powershell/xsqlserver/blob/694e35b33a07f68520d8ce7fd74052bfcf06224b/DSCResources/MSFT_xSQLServerDatabaseOwner/MSFT_xSQLServerDatabaseOwner.psm1#L61)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

change to $sqlDatabaseOwner
</blockquote></details>

Done.

---

*[DSCResources/MSFT_xSQLServerDatabaseOwner/MSFT_xSQLServerDatabaseOwner.psm1, line 105 at r1](https://reviewable.io:443/reviews/powershell/xsqlserver/409#-Ke0cTKCXEH7s4MEYOmA:-Ke38eNDLRkcYkVaifew:b-896fix) ([raw file](https://github.com/powershell/xsqlserver/blob/694e35b33a07f68520d8ce7fd74052bfcf06224b/DSCResources/MSFT_xSQLServerDatabaseOwner/MSFT_xSQLServerDatabaseOwner.psm1#L105)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

Validate NullOrempty here too?
</blockquote></details>

Done.

---

*[DSCResources/MSFT_xSQLServerDatabaseOwner/MSFT_xSQLServerDatabaseOwner.psm1, line 129 at r1](https://reviewable.io:443/reviews/powershell/xsqlserver/409#-Ke0cY60Qd_G77DHzDS6:-Ke38fBK_-4PT-PKa2sG:b-896fix) ([raw file](https://github.com/powershell/xsqlserver/blob/694e35b33a07f68520d8ce7fd74052bfcf06224b/DSCResources/MSFT_xSQLServerDatabaseOwner/MSFT_xSQLServerDatabaseOwner.psm1#L129)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

`-not (` -lower case letters, and space before '('
</blockquote></details>

Done.

---

*[DSCResources/MSFT_xSQLServerDatabaseOwner/MSFT_xSQLServerDatabaseOwner.psm1, line 129 at r1](https://reviewable.io:443/reviews/powershell/xsqlserver/409#-Ke0cZ3_33PlQdLicfAf:-Ke38fp0sySydkVUgCDW:b-896fix) ([raw file](https://github.com/powershell/xsqlserver/blob/694e35b33a07f68520d8ce7fd74052bfcf06224b/DSCResources/MSFT_xSQLServerDatabaseOwner/MSFT_xSQLServerDatabaseOwner.psm1#L129)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

Chnage $getSqlDatabase to $sqlDatabaseObject
</blockquote></details>

Done.

---

*[DSCResources/MSFT_xSQLServerDatabaseOwner/MSFT_xSQLServerDatabaseOwner.psm1, line 135 at r1](https://reviewable.io:443/reviews/powershell/xsqlserver/409#-Ke0cdrKcKXHIdi-U6U_:-Ke38gTmH-XdQBS_y2hi:b-896fix) ([raw file](https://github.com/powershell/xsqlserver/blob/694e35b33a07f68520d8ce7fd74052bfcf06224b/DSCResources/MSFT_xSQLServerDatabaseOwner/MSFT_xSQLServerDatabaseOwner.psm1#L135)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

`-not (` -lower case letters, and space before '('
</blockquote></details>

Done.

---

*[DSCResources/MSFT_xSQLServerDatabaseOwner/MSFT_xSQLServerDatabaseOwner.psm1, line 179 at r1](https://reviewable.io:443/reviews/powershell/xsqlserver/409#-Ke0cnHNAX5CUOMPw9IG:-Ke38hFpjFPqrrPQStjU:b-896fix) ([raw file](https://github.com/powershell/xsqlserver/blob/694e35b33a07f68520d8ce7fd74052bfcf06224b/DSCResources/MSFT_xSQLServerDatabaseOwner/MSFT_xSQLServerDatabaseOwner.psm1#L179)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

ValidateNullOrEmpty here too?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xsqlserver/409)*

**Comment by johlju** [comment]
Reviewed 1 of 7 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 8 unresolved discussions.

---

*[Tests/Unit/MSFT_xSQLServerDatabaseOwner.Tests.ps1, line 41 at r2](https://reviewable.io:443/reviews/powershell/xsqlserver/409#-Ke59QIuZOFHAqXeM08c:-Ke59QIuZOFHAqXeM08d:bat73rm) ([raw file](https://github.com/powershell/xsqlserver/blob/e3f9e44ed6af63716ee664823cc51a7abd0e5472/Tests/Unit/MSFT_xSQLServerDatabaseOwner.Tests.ps1#L41)):*
> ```PowerShell
>         $mockSqlServerLogin                     = 'Zebes\SamusAran'
>         $mockSqlServerLoginType                 = 'WindowsUser'
>         $mockForSetOwnerProperty                = 'Elysia\Chozo'
> ```

Maybe $mockDatabaseOwner is enough?

---

*[Tests/Unit/MSFT_xSQLServerDatabaseOwner.Tests.ps1, line 43 at r2](https://reviewable.io:443/reviews/powershell/xsqlserver/409#-Ke59d9NsfH7j9YuYLwK:-Ke59d9NsfH7j9YuYLwL:b-e4fgz0) ([raw file](https://github.com/powershell/xsqlserver/blob/e3f9e44ed6af63716ee664823cc51a7abd0e5472/Tests/Unit/MSFT_xSQLServerDatabaseOwner.Tests.ps1#L43)):*
> ```PowerShell
>         $mockForSetOwnerProperty                = 'Elysia\Chozo'
>         $mockInvalidOperationForSetOwnerMethod  = $false
>         $mockExpectedForSetOwnerMethod          = 'Elysia\Chozo'
> ```

Maybe $mockExpectedDatabaseOwner is enough? So it could be used for other methods in the future (if there are any)

---

*[Tests/Unit/MSFT_xSQLServerDatabaseOwner.Tests.ps1, line 43 at r2](https://reviewable.io:443/reviews/powershell/xsqlserver/409#-Ke5FCYeY2S_YYu5YVfV:-Ke5FCYf_IPb1omUvEVO:b-em9fkr) ([raw file](https://github.com/powershell/xsqlserver/blob/e3f9e44ed6af63716ee664823cc51a7abd0e5472/Tests/Unit/MSFT_xSQLServerDatabaseOwner.Tests.ps1#L43)):*
> ```PowerShell
>         $mockForSetOwnerProperty                = 'Elysia\Chozo'
>         $mockInvalidOperationForSetOwnerMethod  = $false
>         $mockExpectedForSetOwnerMethod          = 'Elysia\Chozo'
> ```

Tip 1: By the way, if you think you need to initalize the "dynamic variables" here, then I can tell you that you don't need to. :) You can assign the "dynamic variable" just before the It-block where it should be used. If you do that, then it easy to see what values you set for the parameter, and what value you expect (see Tip 2 comment).  That said, it is totally okay to assign it here.

No need to change anything! Just a knowledge transfer :wink: 

---

*[Tests/Unit/MSFT_xSQLServerDatabaseOwner.Tests.ps1, line 67 at r2](https://reviewable.io:443/reviews/powershell/xsqlserver/409#-Ke58AV2ZL0pHtnauIlI:-Ke58AV2ZL0pHtnauIlJ:b-daqqeh) ([raw file](https://github.com/powershell/xsqlserver/blob/e3f9e44ed6af63716ee664823cc51a7abd0e5472/Tests/Unit/MSFT_xSQLServerDatabaseOwner.Tests.ps1#L67)):*
> ```PowerShell
>                                             if ($mockInvalidOperationForSetOwnerMethod)
>                                             {
>                                                 throw 'Mock SetOwner Method was called with invalid operation.'
> ```

'Mock SetOwner Method was...' change to 'Mock of method SetOwner() was....

---

*[Tests/Unit/MSFT_xSQLServerDatabaseOwner.Tests.ps1, line 70 at r2](https://reviewable.io:443/reviews/powershell/xsqlserver/409#-Ke5CeoP1XnM9TGNWK_G:-Ke5951b4Rwn48mQPwCx:b-itpr2k) ([raw file](https://github.com/powershell/xsqlserver/blob/e3f9e44ed6af63716ee664823cc51a7abd0e5472/Tests/Unit/MSFT_xSQLServerDatabaseOwner.Tests.ps1#L70)):*
> $mockExpectedSetOwner

Should this not be `$this.Owner -ne $mockExpectedDatabaseOwner` (after changing it in a previous comment)?

---

*[Tests/Unit/MSFT_xSQLServerDatabaseOwner.Tests.ps1, line 72 at r2](https://reviewable.io:443/reviews/powershell/xsqlserver/409#-Ke57z9bTmhrkO1nwzcC:-Ke57z9c4s5tBDYYXS9n:bnfebhq) ([raw file](https://github.com/powershell/xsqlserver/blob/e3f9e44ed6af63716ee664823cc51a7abd0e5472/Tests/Unit/MSFT_xSQLServerDatabaseOwner.Tests.ps1#L72)):*
> ```PowerShell
>                                             if ( $this.Owner -ne $mockForSetOwnerProperty )
>                                             {
>                                                 throw "Called mocked Drop() method without dropping the right database. Expected '{0}'. But was '{1}'." `
> ```

Drop() should be SetOwner(). Please revise the entire error message.

---

*[Tests/Unit/MSFT_xSQLServerDatabaseOwner.Tests.ps1, line 72 at r2](https://reviewable.io:443/reviews/powershell/xsqlserver/409#-Ke5Dp10VU63d9_IwZnP:-Ke5Dp10VU63d9_IwZnQ:b-qjni34) ([raw file](https://github.com/powershell/xsqlserver/blob/e3f9e44ed6af63716ee664823cc51a7abd0e5472/Tests/Unit/MSFT_xSQLServerDatabaseOwner.Tests.ps1#L72)):*
> ```PowerShell
>                                             if ( $this.Owner -ne $mockForSetOwnerProperty )
>                                             {
>                                                 throw "Called mocked Drop() method without dropping the right database. Expected '{0}'. But was '{1}'." `
> ```

Hmm.. maybe we should add a test to test the test ;) Thought about that yesterday. Just call the Set-method with wrong expected variable and make sure it throws the correct error message. What do you think? If you think it is a good idea I could start to enforce that.

---

*[Tests/Unit/MSFT_xSQLServerDatabaseOwner.Tests.ps1, line 233 at r2](https://reviewable.io:443/reviews/powershell/xsqlserver/409#-Ke5C5NfeLqkNTDkjN_N:-Ke5C5NgDaxMR6z4MkTD:b-oqap5w) ([raw file](https://github.com/powershell/xsqlserver/blob/e3f9e44ed6af63716ee664823cc51a7abd0e5472/Tests/Unit/MSFT_xSQLServerDatabaseOwner.Tests.ps1#L233)):*
> ```PowerShell
>             }
> 
>             $mockInvalidOperationForSetOwnerMethod  = $false
> ```

Tip 2: This is what I meant by assigning the "dynamic variable" values just before the It-block (in this case the context block).

No need to change anything! Just a knowledge transfer :wink: 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xsqlserver/409)*

**Comment by luigilink** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 8 unresolved discussions.

---

*[Tests/Unit/MSFT_xSQLServerDatabaseOwner.Tests.ps1, line 41 at r2](https://reviewable.io:443/reviews/powershell/xsqlserver/409#-Ke59QIuZOFHAqXeM08c:-Ke9VNsqyeUXDtxdVlE8:b-896fix) ([raw file](https://github.com/powershell/xsqlserver/blob/e3f9e44ed6af63716ee664823cc51a7abd0e5472/Tests/Unit/MSFT_xSQLServerDatabaseOwner.Tests.ps1#L41)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

Maybe $mockDatabaseOwner is enough?
</blockquote></details>

Done.

---

*[Tests/Unit/MSFT_xSQLServerDatabaseOwner.Tests.ps1, line 43 at r2](https://reviewable.io:443/reviews/powershell/xsqlserver/409#-Ke59d9NsfH7j9YuYLwK:-Ke9VOibxO6TQtsouePk:b-896fix) ([raw file](https://github.com/powershell/xsqlserver/blob/e3f9e44ed6af63716ee664823cc51a7abd0e5472/Tests/Unit/MSFT_xSQLServerDatabaseOwner.Tests.ps1#L43)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

Maybe $mockExpectedDatabaseOwner is enough? So it could be used for other methods in the future (if there are any)
</blockquote></details>

Done.

---

*[Tests/Unit/MSFT_xSQLServerDatabaseOwner.Tests.ps1, line 43 at r2](https://reviewable.io:443/reviews/powershell/xsqlserver/409#-Ke5FCYeY2S_YYu5YVfV:-Ke9VQk2zyPKFy7Kfu7o:bmoo0zc) ([raw file](https://github.com/powershell/xsqlserver/blob/e3f9e44ed6af63716ee664823cc51a7abd0e5472/Tests/Unit/MSFT_xSQLServerDatabaseOwner.Tests.ps1#L43)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

Tip 1: By the way, if you think you need to initalize the "dynamic variables" here, then I can tell you that you don't need to. :) You can assign the "dynamic variable" just before the It-block where it should be used. If you do that, then it easy to see what values you set for the parameter, and what value you expect (see Tip 2 comment).  That said, it is totally okay to assign it here.

No need to change anything! Just a knowledge transfer :wink: 
</blockquote></details>

Good to know :+1: 

---

*[Tests/Unit/MSFT_xSQLServerDatabaseOwner.Tests.ps1, line 67 at r2](https://reviewable.io:443/reviews/powershell/xsqlserver/409#-Ke58AV2ZL0pHtnauIlI:-Ke9VV6MVmB8qYd7FgBS:b-896fix) ([raw file](https://github.com/powershell/xsqlserver/blob/e3f9e44ed6af63716ee664823cc51a7abd0e5472/Tests/Unit/MSFT_xSQLServerDatabaseOwner.Tests.ps1#L67)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

'Mock SetOwner Method was...' change to 'Mock of method SetOwner() was....
</blockquote></details>

Done.

---

*[Tests/Unit/MSFT_xSQLServerDatabaseOwner.Tests.ps1, line 72 at r2](https://reviewable.io:443/reviews/powershell/xsqlserver/409#-Ke57z9bTmhrkO1nwzcC:-Ke9XRdmEJaEZSkETcM0:b-896fix) ([raw file](https://github.com/powershell/xsqlserver/blob/e3f9e44ed6af63716ee664823cc51a7abd0e5472/Tests/Unit/MSFT_xSQLServerDatabaseOwner.Tests.ps1#L72)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

Drop() should be SetOwner(). Please revise the entire error message.
</blockquote></details>

Done.

---

*[Tests/Unit/MSFT_xSQLServerDatabaseOwner.Tests.ps1, line 72 at r2](https://reviewable.io:443/reviews/powershell/xsqlserver/409#-Ke5Dp10VU63d9_IwZnP:-Ke9XSQ2V_ALxkKDgfxO:bi6bsdc) ([raw file](https://github.com/powershell/xsqlserver/blob/e3f9e44ed6af63716ee664823cc51a7abd0e5472/Tests/Unit/MSFT_xSQLServerDatabaseOwner.Tests.ps1#L72)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

Hmm.. maybe we should add a test to test the test ;) Thought about that yesterday. Just call the Set-method with wrong expected variable and make sure it throws the correct error message. What do you think? If you think it is a good idea I could start to enforce that.
</blockquote></details>

Very Good idea. I will add it in the next commit

---

*[Tests/Unit/MSFT_xSQLServerDatabaseOwner.Tests.ps1, line 233 at r2](https://reviewable.io:443/reviews/powershell/xsqlserver/409#-Ke5C5NfeLqkNTDkjN_N:-Ke9XYeXnrwtqex39jbA:btvj6wo) ([raw file](https://github.com/powershell/xsqlserver/blob/e3f9e44ed6af63716ee664823cc51a7abd0e5472/Tests/Unit/MSFT_xSQLServerDatabaseOwner.Tests.ps1#L233)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

Tip 2: This is what I meant by assigning the "dynamic variable" values just before the It-block (in this case the context block).

No need to change anything! Just a knowledge transfer :wink: 
</blockquote></details>

Good to know again :+1: 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xsqlserver/409)*

**Comment by luigilink** [comment]
Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 8 unresolved discussions.

---

*[Tests/Unit/MSFT_xSQLServerDatabaseOwner.Tests.ps1, line 70 at r2](https://reviewable.io:443/reviews/powershell/xsqlserver/409#-Ke5CeoP1XnM9TGNWK_G:-Ke9XqdmEOoheoZ2SKbN:b-896fix) ([raw file](https://github.com/powershell/xsqlserver/blob/e3f9e44ed6af63716ee664823cc51a7abd0e5472/Tests/Unit/MSFT_xSQLServerDatabaseOwner.Tests.ps1#L70)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

> $mockExpectedSetOwner

Should this not be `$this.Owner -ne $mockExpectedDatabaseOwner` (after changing it in a previous comment)?
</blockquote></details>

Done.

---

*[Tests/Unit/MSFT_xSQLServerDatabaseOwner.Tests.ps1, line 72 at r2](https://reviewable.io:443/reviews/powershell/xsqlserver/409#-Ke5Dp10VU63d9_IwZnP:-Ke9XrRuchVd5xuD0-w6:b-gcjiot) ([raw file](https://github.com/powershell/xsqlserver/blob/e3f9e44ed6af63716ee664823cc51a7abd0e5472/Tests/Unit/MSFT_xSQLServerDatabaseOwner.Tests.ps1#L72)):*
<details><summary><i>Previously, luigilink (Jean-Cyril Drouhin) wrote…</i></summary><blockquote>

Very Good idea. I will add it in the next commit
</blockquote></details>

Done. Test added.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xsqlserver/409)*

**Comment by luigilink** [comment]
@johlju "Waiting for the author" tag can be removed.

**Comment by johlju** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xsqlserver/409#-:-KeFVTjey7IGtc7iLjMt:bnfp4nl)*

**Pull request merged**
