### PR TITLE
xSQLServerAlwaysOnAvailabilityGroup: Added missing read-only properties

### LINKED ISSUE #787: xSQLServerAlwaysOnAvailabilityGroup: Get-TargetResource returns a property Version that is missing in the schema.mof
**Details of the scenario you tried and the problem that is occurring:**
The function `Get-TargetResource` returns a property `Version` that is missing in the schema.mof. It should be added as a read-only parameter.

**The DSC configuration that is using the resource (as detailed as possible):**
n/a

**Version of the Operating System, SQL Server and PowerShell the DSC Target Node is running:**
n/a

**What module (SqlServer or SQLPS) and which version of the module the DSC Target Node is running:**
n/a

**Version of the DSC module you're using, or 'dev' if you're using current dev branch:**
Dev

### PR DESCRIPTION
**Pull request by randomnote1**
**Pull Request (PR) description**
Added missing read-only properties to the xSQLServerAlwaysOnAvailabilityGroup schema.

**This Pull Request (PR) fixes the following issues:**
Fixes #787 

**Task list:**
- [ ] Change details added to Unreleased section of CHANGELOG.md?
- [ ] Added/updated documentation, comment-based help and descriptions in .schema.mof files where appropriate?
- [ ] Examples appropriately updated?
- [X] New/changed code adheres to [Style Guidelines](https://github.com/PowerShell/DscResources/blob/master/StyleGuidelines.md)?
- [ ] [Unit and (optional) Integration tests](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md) created/updated where possible?

---
This change is [Reviewable](https://reviewable.io/reviews/powershell/xsqlserver/838)

### CODE REVIEW

**Comment by johlju** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[DSCResources/MSFT_xSQLServerAlwaysOnAvailabilityGroup/MSFT_xSQLServerAlwaysOnAvailabilityGroup.schema.mof, line 20 at r1](https://reviewable.io:443/reviews/powershell/xsqlserver/838#-Ku_SvAjZyJFOQBt6oLp:-Ku_SvAjZyJFOQBt6oLq:bpma06c) ([raw file](https://github.com/powershell/xsqlserver/blob/7943c7fc08c7f1a05e6991de72e85b9f168cef8c/DSCResources/MSFT_xSQLServerAlwaysOnAvailabilityGroup/MSFT_xSQLServerAlwaysOnAvailabilityGroup.schema.mof#L20)):*
> ```
>     [Write, Description("Specifies the failover mode. Default is 'Manual'."), ValueMap{"Automatic","Manual"}, Values{"Automatic","Manual"}] String FailoverMode;
>     [Write, Description("Specifies the length of time, in milliseconds, after which AlwaysOn availability groups declare an unresponsive server to be unhealthy. Default is 30000.")] UInt32 HealthCheckTimeout;
>     [Read, Description("Gets the Endpoint URL of the availability group replica endpoint.")] String EndpointUrl;
> ```

Please add these to the README.md as well. Please see other resource with read parameters for example.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xsqlserver/838)*

**Comment by randomnote1** [comment]
Review status: 2 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[DSCResources/MSFT_xSQLServerAlwaysOnAvailabilityGroup/MSFT_xSQLServerAlwaysOnAvailabilityGroup.schema.mof, line 20 at r1](https://reviewable.io:443/reviews/powershell/xsqlserver/838#-Ku_SvAjZyJFOQBt6oLp:-Ku_X1Ct8gBrImXNtX-g:bu8efyt) ([raw file](https://github.com/powershell/xsqlserver/blob/7943c7fc08c7f1a05e6991de72e85b9f168cef8c/DSCResources/MSFT_xSQLServerAlwaysOnAvailabilityGroup/MSFT_xSQLServerAlwaysOnAvailabilityGroup.schema.mof#L20)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

Please add these to the README.md as well. Please see other resource with read parameters for example.
</blockquote></details>

Wow....totally forgot about that!
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xsqlserver/838)*

**Comment by johlju** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---

*[README.md, line 246 at r2](https://reviewable.io:443/reviews/powershell/xsqlserver/838#-Ku_XzG87fU44n-rX4P7:-Ku_XzG87fU44n-rX4P8:b-s8xf9w) ([raw file](https://github.com/powershell/xsqlserver/blob/5b0c13de7f71f6bd185591918ebc9ee808d2b5c8/README.md#L246)):*
> ```Markdown
>   milliseconds, after which AlwaysOn availability groups declare an unresponsive
>   server to be unhealthy. Default is 30000.
> * **`[String]` EndpointUrl** _(Read)_: Gets the Endpoint URL of the
> ```

Please see line 181 (for the section) and add that here as well. :)

---

*[README.md, line 251 at r2](https://reviewable.io:443/reviews/powershell/xsqlserver/838#-Ku_YVsCIcqhbpR8Lrzu:-Ku_YVsCIcqhbpR8Lrzv:b-hlgfoz) ([raw file](https://github.com/powershell/xsqlserver/blob/5b0c13de7f71f6bd185591918ebc9ee808d2b5c8/README.md#L251)):*
> Instance

'instance' lower case 'i'

---

*[README.md, line 253 at r2](https://reviewable.io:443/reviews/powershell/xsqlserver/838#-Ku_YWkQpSz0IXzDQpV9:-Ku_YWkQpSz0IXzDQpVA:b-hlgfoz) ([raw file](https://github.com/powershell/xsqlserver/blob/5b0c13de7f71f6bd185591918ebc9ee808d2b5c8/README.md#L253)):*
> Instance

'instance' lower case 'i'

---

*[DSCResources/MSFT_xSQLServerAlwaysOnAvailabilityGroup/MSFT_xSQLServerAlwaysOnAvailabilityGroup.schema.mof, line 20 at r1](https://reviewable.io:443/reviews/powershell/xsqlserver/838#-Ku_SvAjZyJFOQBt6oLp:-Ku_YL4XnwQcACRJuwaB:b-15tjsg) ([raw file](https://github.com/powershell/xsqlserver/blob/7943c7fc08c7f1a05e6991de72e85b9f168cef8c/DSCResources/MSFT_xSQLServerAlwaysOnAvailabilityGroup/MSFT_xSQLServerAlwaysOnAvailabilityGroup.schema.mof#L20)):*
<details><summary><i>Previously, randomnote1 (Dan Reist) wrote…</i></summary><blockquote>

Wow....totally forgot about that!
Done.
</blockquote></details>

That's why it's good to have someone else review :smile: 

---

*[DSCResources/MSFT_xSQLServerAlwaysOnAvailabilityGroup/MSFT_xSQLServerAlwaysOnAvailabilityGroup.schema.mof, line 22 at r2](https://reviewable.io:443/reviews/powershell/xsqlserver/838#-Ku_YFfo4psgfN4GwcgU:-Ku_YFfo4psgfN4GwcgV:b-hlgfoz) ([raw file](https://github.com/powershell/xsqlserver/blob/5b0c13de7f71f6bd185591918ebc9ee808d2b5c8/DSCResources/MSFT_xSQLServerAlwaysOnAvailabilityGroup/MSFT_xSQLServerAlwaysOnAvailabilityGroup.schema.mof#L22)):*
> Instance

'instance' lower case 'i'

---

*[DSCResources/MSFT_xSQLServerAlwaysOnAvailabilityGroup/MSFT_xSQLServerAlwaysOnAvailabilityGroup.schema.mof, line 23 at r2](https://reviewable.io:443/reviews/powershell/xsqlserver/838#-Ku_YK0BAQS2gxw6D5tm:-Ku_YK0BAQS2gxw6D5tn:b-hlgfoz) ([raw file](https://github.com/powershell/xsqlserver/blob/5b0c13de7f71f6bd185591918ebc9ee808d2b5c8/DSCResources/MSFT_xSQLServerAlwaysOnAvailabilityGroup/MSFT_xSQLServerAlwaysOnAvailabilityGroup.schema.mof#L23)):*
> Instance

'instance' lower case 'i'

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xsqlserver/838)*

**Comment by randomnote1** [comment]
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[README.md, line 246 at r2](https://reviewable.io:443/reviews/powershell/xsqlserver/838#-Ku_XzG87fU44n-rX4P7:-Ku__Ks0BVdiKIoHFk2W:b-896fix) ([raw file](https://github.com/powershell/xsqlserver/blob/5b0c13de7f71f6bd185591918ebc9ee808d2b5c8/README.md#L246)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

Please see line 181 (for the section) and add that here as well. :)
</blockquote></details>

Done.

---

*[README.md, line 251 at r2](https://reviewable.io:443/reviews/powershell/xsqlserver/838#-Ku_YVsCIcqhbpR8Lrzu:-Ku__Ac4YSQaoQ32L994:b-896fix) ([raw file](https://github.com/powershell/xsqlserver/blob/5b0c13de7f71f6bd185591918ebc9ee808d2b5c8/README.md#L251)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

> Instance

'instance' lower case 'i'
</blockquote></details>

Done.

---

*[README.md, line 253 at r2](https://reviewable.io:443/reviews/powershell/xsqlserver/838#-Ku_YWkQpSz0IXzDQpV9:-Ku__AHtHF3EnmSDeDUm:b-896fix) ([raw file](https://github.com/powershell/xsqlserver/blob/5b0c13de7f71f6bd185591918ebc9ee808d2b5c8/README.md#L253)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

> Instance

'instance' lower case 'i'
</blockquote></details>

Done.

---

*[DSCResources/MSFT_xSQLServerAlwaysOnAvailabilityGroup/MSFT_xSQLServerAlwaysOnAvailabilityGroup.schema.mof, line 22 at r2](https://reviewable.io:443/reviews/powershell/xsqlserver/838#-Ku_YFfo4psgfN4GwcgU:-Ku__9FcQzN_IevHq4gp:b-896fix) ([raw file](https://github.com/powershell/xsqlserver/blob/5b0c13de7f71f6bd185591918ebc9ee808d2b5c8/DSCResources/MSFT_xSQLServerAlwaysOnAvailabilityGroup/MSFT_xSQLServerAlwaysOnAvailabilityGroup.schema.mof#L22)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

> Instance

'instance' lower case 'i'
</blockquote></details>

Done.

---

*[DSCResources/MSFT_xSQLServerAlwaysOnAvailabilityGroup/MSFT_xSQLServerAlwaysOnAvailabilityGroup.schema.mof, line 23 at r2](https://reviewable.io:443/reviews/powershell/xsqlserver/838#-Ku_YK0BAQS2gxw6D5tm:-Ku__91T-bK3s9Mcfb_u:b-896fix) ([raw file](https://github.com/powershell/xsqlserver/blob/5b0c13de7f71f6bd185591918ebc9ee808d2b5c8/DSCResources/MSFT_xSQLServerAlwaysOnAvailabilityGroup/MSFT_xSQLServerAlwaysOnAvailabilityGroup.schema.mof#L23)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

> Instance

'instance' lower case 'i'
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xsqlserver/838)*

**Comment by johlju** [comment]
:lgtm:

Will merge as soon as the tests passes.

---

Reviewed 1 of 2 files at r3, 1 of 1 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xsqlserver/838#-:-Ku_a7TgjplWtH1FlxUK:b28epyn)*

**Comment by randomnote1** [comment]
Thanks! The easy PRs are always the ones I make silly mistakes on 😄

**Comment by johlju** [comment]
It's not easy to remember everything all the time 😄

**Pull request merged**
