### PR TITLE
Add support for SQL Features "CONN" & "BC" (fixes #159)

### LINKED ISSUE #159: Request for Advice on Adding Functionality for new Feature support
I am going to try to add the ability to add more SQL Features during the installation process as they are required for my installation requirements.

These are the features I require:
SqlInstallFeatures = 'SQLENGINE,FULLTEXT,SSMS,ADV_SSMS,IS,CONN,BC'

It appears that 'CONN,BC ' are not support in the module as they throw errors.

While my skillset is still at the novice end, I am willing to try and add this into the module. Is anyone able to give me a little guidance on how to start?

Thanks!!

### PR DESCRIPTION
**Pull request by joshan1120**
-Add test cases to allow "Client Connectivity Tools" & "Client Connectivity Backwards Compatibility" to install successfully
- Added support for all SQL version support by xSqlServerSetup

---

This change is [Reviewable](https://reviewable.io/reviews/powershell/xsqlserver/163)

### CODE REVIEW

**Comment by johlju** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 12 unresolved discussions.

---

*[DSCResources/MSFT_xSQLServerSetup/MSFT_xSQLServerSetup.psm1, line 194 at r1](https://reviewable.io:443/reviews/powershell/xsqlserver/163#-KW8z5Gjs1E0A0JR9gA4:-KW8z5GkAFzIVWxazyQC:b-167cyb) ([raw file](https://github.com/powershell/xsqlserver/blob/03c304a9a3d8b73a3e07772ee08950a5b175a1d4/DSCResources/MSFT_xSQLServerSetup/MSFT_xSQLServerSetup.psm1#L194)):*
> ```PowerShell
>             $Features += "REPLICATION,"
>         }
>         $FeaturesVersion = $SqlVersion + "0"
> ```

Could you please add a new line before this line?

---

*[DSCResources/MSFT_xSQLServerSetup/MSFT_xSQLServerSetup.psm1, line 195 at r1](https://reviewable.io:443/reviews/powershell/xsqlserver/163#-KW8xa9FlluxZOIbMNg9:-KW8xa9FlluxZOIbMNgA:bnw8jzk) ([raw file](https://github.com/powershell/xsqlserver/blob/03c304a9a3d8b73a3e07772ee08950a5b175a1d4/DSCResources/MSFT_xSQLServerSetup/MSFT_xSQLServerSetup.psm1#L195)):*
> ```PowerShell
>         }
>         $FeaturesVersion = $SqlVersion + "0"
>         Write-Verbose "Detecting Client Connectivity Tools feature"
> ```

Change this to use the helper function
```
New-VerboseMessage -Message 'Detecting Client Connectivity Tools feature'
``` 

---

*[DSCResources/MSFT_xSQLServerSetup/MSFT_xSQLServerSetup.psm1, line 196 at r1](https://reviewable.io:443/reviews/powershell/xsqlserver/163#-KW8x3giOGELFU3nx0_m:-KW8x3giOGELFU3nx0_n:b8g1c7i) ([raw file](https://github.com/powershell/xsqlserver/blob/03c304a9a3d8b73a3e07772ee08950a5b175a1d4/DSCResources/MSFT_xSQLServerSetup/MSFT_xSQLServerSetup.psm1#L196)):*
> ```PowerShell
>         $FeaturesVersion = $SqlVersion + "0"
>         Write-Verbose "Detecting Client Connectivity Tools feature"
>         Write-Verbose "Reading registry key HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Microsoft SQL Server\$FeaturesVersion\Tools\Setup\Client_Components_Full"
> ```

I don't think this needs to be a Verbose message, since the previous one feels enough. My thought is, if you want to keep this row then change it to `Write-Debug -Message ...` instead?

---

*[DSCResources/MSFT_xSQLServerSetup/MSFT_xSQLServerSetup.psm1, line 198 at r1](https://reviewable.io:443/reviews/powershell/xsqlserver/163#-KW8y5OBkw1U8j2CgP4V:-KW8y5OBkw1U8j2CgP4W:b6mgyru) ([raw file](https://github.com/powershell/xsqlserver/blob/03c304a9a3d8b73a3e07772ee08950a5b175a1d4/DSCResources/MSFT_xSQLServerSetup/MSFT_xSQLServerSetup.psm1#L198)):*
> ```PowerShell
>         Write-Verbose "Reading registry key HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Microsoft SQL Server\$FeaturesVersion\Tools\Setup\Client_Components_Full"
>         $isCONNInstalled = (Get-ItemProperty -Path "HKLM:\SOFTWARE\Microsoft\Microsoft SQL Server\$FeaturesVersion\Tools\Setup\Client_Components_Full").FeatureList
>         Write-Verbose "SQL_Client_Connectivity_Tools = $isCONNInstalled"
> ```

Please change to `New-VerboseMessage -Message ...`.

---

*[DSCResources/MSFT_xSQLServerSetup/MSFT_xSQLServerSetup.psm1, line 199 at r1](https://reviewable.io:443/reviews/powershell/xsqlserver/163#-KW8yTmPLI8GeptSgY6G:-KW8yTmPLI8GeptSgY6H:b-ni3afv) ([raw file](https://github.com/powershell/xsqlserver/blob/03c304a9a3d8b73a3e07772ee08950a5b175a1d4/DSCResources/MSFT_xSQLServerSetup/MSFT_xSQLServerSetup.psm1#L199)):*
> ```PowerShell
>         $isCONNInstalled = (Get-ItemProperty -Path "HKLM:\SOFTWARE\Microsoft\Microsoft SQL Server\$FeaturesVersion\Tools\Setup\Client_Components_Full").FeatureList
>         Write-Verbose "SQL_Client_Connectivity_Tools = $isCONNInstalled"
>         if ($isCONNInstalled -like '*Connectivity_FNS=3*')
> ```

Just want to make sure. Is this always the same regardless of SQL Server major version (2008 R2, 2012, 2014, 2016)?

---

*[DSCResources/MSFT_xSQLServerSetup/MSFT_xSQLServerSetup.psm1, line 201 at r1](https://reviewable.io:443/reviews/powershell/xsqlserver/163#-KW8y8t1pHNEGTHyGGqu:-KW8y8t1pHNEGTHyGGqv:b-kep0m4) ([raw file](https://github.com/powershell/xsqlserver/blob/03c304a9a3d8b73a3e07772ee08950a5b175a1d4/DSCResources/MSFT_xSQLServerSetup/MSFT_xSQLServerSetup.psm1#L201)):*
> ```PowerShell
>         if ($isCONNInstalled -like '*Connectivity_FNS=3*')
>         {
>             Write-Verbose "Client Connectivity Tools feature detected"
> ```

Please change to `New-VerboseMessage -Message ...`

---

*[DSCResources/MSFT_xSQLServerSetup/MSFT_xSQLServerSetup.psm1, line 204 at r1](https://reviewable.io:443/reviews/powershell/xsqlserver/163#-KW8yghzIDN4TtEeMi-p:-KW8yghzIDN4TtEeMi-q:bwrc96n) ([raw file](https://github.com/powershell/xsqlserver/blob/03c304a9a3d8b73a3e07772ee08950a5b175a1d4/DSCResources/MSFT_xSQLServerSetup/MSFT_xSQLServerSetup.psm1#L204)):*
> ```PowerShell
>             $Features += "CONN,"
>         }
>         Write-Verbose "Detecting Client Connectivity Backwards Compatibility Tools feature"
> ```

Please change to `New-VerboseMessage -Message ...`
Also Could you please add a new line before this line?

---

*[DSCResources/MSFT_xSQLServerSetup/MSFT_xSQLServerSetup.psm1, line 205 at r1](https://reviewable.io:443/reviews/powershell/xsqlserver/163#-KW8yj2sQlPBPnKpZW1K:-KW8yj2sQlPBPnKpZW1L:b8g1c7i) ([raw file](https://github.com/powershell/xsqlserver/blob/03c304a9a3d8b73a3e07772ee08950a5b175a1d4/DSCResources/MSFT_xSQLServerSetup/MSFT_xSQLServerSetup.psm1#L205)):*
> ```PowerShell
>         }
>         Write-Verbose "Detecting Client Connectivity Backwards Compatibility Tools feature"
>         Write-Verbose "Reading registry key HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Microsoft SQL Server\$FeaturesVersion\Tools\Setup\Client_Components_Full"
> ```

I don't think this needs to be a Verbose message, since the previous one feels enough. My thought is, if you want to keep this row then change it to `Write-Debug -Message ...` instead?

---

*[DSCResources/MSFT_xSQLServerSetup/MSFT_xSQLServerSetup.psm1, line 207 at r1](https://reviewable.io:443/reviews/powershell/xsqlserver/163#-KW8ylCENUpktyqMBDqD:-KW8ylCENUpktyqMBDqE:b-kep0m4) ([raw file](https://github.com/powershell/xsqlserver/blob/03c304a9a3d8b73a3e07772ee08950a5b175a1d4/DSCResources/MSFT_xSQLServerSetup/MSFT_xSQLServerSetup.psm1#L207)):*
> ```PowerShell
>         Write-Verbose "Reading registry key HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Microsoft SQL Server\$FeaturesVersion\Tools\Setup\Client_Components_Full"
>         $isBCInstalled = (Get-ItemProperty -Path "HKLM:\SOFTWARE\Microsoft\Microsoft SQL Server\$FeaturesVersion\Tools\Setup\Client_Components_Full").FeatureList
>         Write-Verbose "SQL_Client_Connectivity_Tools_Backwards_Compatibility = $isBCInstalled"
> ```

Please change to `New-VerboseMessage -Message ...`

---

*[DSCResources/MSFT_xSQLServerSetup/MSFT_xSQLServerSetup.psm1, line 208 at r1](https://reviewable.io:443/reviews/powershell/xsqlserver/163#-KW8yp_KGSR3B_boLmkJ:-KW8yp_KGSR3B_boLmkK:b-ni3afv) ([raw file](https://github.com/powershell/xsqlserver/blob/03c304a9a3d8b73a3e07772ee08950a5b175a1d4/DSCResources/MSFT_xSQLServerSetup/MSFT_xSQLServerSetup.psm1#L208)):*
> ```PowerShell
>         $isBCInstalled = (Get-ItemProperty -Path "HKLM:\SOFTWARE\Microsoft\Microsoft SQL Server\$FeaturesVersion\Tools\Setup\Client_Components_Full").FeatureList
>         Write-Verbose "SQL_Client_Connectivity_Tools_Backwards_Compatibility = $isBCInstalled"
>         if ($isBCInstalled -like '*Tools_Legacy_FNS=3*')
> ```

Just want to make sure. Is this always the same regardless of SQL Server major version (2008 R2, 2012, 2014, 2016)?

---

*[DSCResources/MSFT_xSQLServerSetup/MSFT_xSQLServerSetup.psm1, line 210 at r1](https://reviewable.io:443/reviews/powershell/xsqlserver/163#-KW8ylrpCZL_oJ5Ph3Wj:-KW8ylrpCZL_oJ5Ph3Wk:b-kep0m4) ([raw file](https://github.com/powershell/xsqlserver/blob/03c304a9a3d8b73a3e07772ee08950a5b175a1d4/DSCResources/MSFT_xSQLServerSetup/MSFT_xSQLServerSetup.psm1#L210)):*
> ```PowerShell
>         if ($isBCInstalled -like '*Tools_Legacy_FNS=3*')
>         {
>             Write-Verbose "Client Connectivity Tools Backwards Compatibility feature detected"
> ```

Please change to `New-VerboseMessage -Message ...`

---

*[DSCResources/MSFT_xSQLServerSetup/MSFT_xSQLServerSetup.psm1, line 213 at r1](https://reviewable.io:443/reviews/powershell/xsqlserver/163#-KW8zITr0sDTdvUd3m6w:-KW8zITr0sDTdvUd3m6x:b-167cyb) ([raw file](https://github.com/powershell/xsqlserver/blob/03c304a9a3d8b73a3e07772ee08950a5b175a1d4/DSCResources/MSFT_xSQLServerSetup/MSFT_xSQLServerSetup.psm1#L213)):*
> ```PowerShell
>             $Features += "BC,"
>             }
>         $InstanceID = $FullInstanceID.Split(".")[1]
> ```

Could you please add a new line before this line?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xsqlserver/163)*

**Comment by joshan1120** [comment]
Thanks, I will get these changes in.

**Comment by johlju** [comment]
Thanks for contributing @joshan1120! :smile: 

I forgot one thing. Also, in the README.md, under the unreleased section, please add what this change does, something like
* Added the ability for xSQLServerSetup to detect if the features Client Connectivity Tools or Client Connectivity Backwards Compatibility Tools are installed.

I will review again when you made these changes.

**Comment by johlju** [comment]
And yet another thing... :wink: 

Could you please change the PR title to `Add support for SQL Features "CONN" & "BC" (fixes #159)`.
This will auto-close the issue once PR is merged.

**Comment by johlju** [comment]
@joshan1120 If you want me to help you resolve the comments, then could you make sure that "Allow edits from maintainers" is turned on?

**Comment by johlju** [comment]
@joshan1120 I saw that your branch was to far long after, so it was very difficult to rebase it. So if you don't mind, I will send in a new PR with your changes and fix the review comments on it, and also fix test for this.

**Comment by johlju** [comment]
@joshan1120 Closing this. I sent in a new PR #383.

**Pull request closed without merging**
