### PR TITLE
xSQLServerRSConfig: Adding examples

### LINKED ISSUE #844: xSQLServerRSConfig: Add examples for the new parameters in this resource
**Details of the scenario you tried and the problem that is occurring:**
This resource should have examples updated to reflect the new parameters in this resource (that was merged with PR #638).

These should also be added to the integration tests.
 
**The DSC configuration that is using the resource (as detailed as possible):**
n/a

**Version of the Operating System, SQL Server and PowerShell the DSC Target Node is running:**
n/a

**What module (SqlServer or SQLPS) and which version of the module the DSC Target Node is running:**
n/a

**Version of the DSC module you're using, or 'dev' if you're using current dev branch:**
Dev

### PR DESCRIPTION
**Pull request by bozho**
**Pull Request (PR) description**
Added examples for xSQLServerRSConfig resource.

**This Pull Request (PR) fixes the following issues:**
Fixes #844

**Task list:**

- [x] Change details added to Unreleased section of CHANGELOG.md?
- [ ] Added/updated documentation, comment-based help and descriptions in .schema.mof files where appropriate?
- [x] Examples appropriately updated?
- [x] New/changed code adheres to [Style Guidelines](https://github.com/PowerShell/DscResources/blob/master/StyleGuidelines.md)?
- [ ] [Unit and (optional) Integration tests](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md) created/updated where possible?

---
This change is [Reviewable](https://reviewable.io/reviews/powershell/xsqlserver/852)

### CODE REVIEW

**Comment by johlju** [comment]
Please resolve the failing tests 
https://ci.appveyor.com/project/PowerShell/xsqlserver/build/6.0.1654.0#L63
and 
https://ci.appveyor.com/project/PowerShell/xsqlserver/build/6.0.1654.0#L1528

**Comment by johlju** [comment]
Please also add an entry to the CHANGELOG.md.

**Comment by johlju** [comment]
Please also add these examples to the README.md. See others resources examples for the correct layout.

**Comment by johlju** [comment]
@bozho Do you have time to resolve the comments above?

* Resolve the failing tests.
* Add an entry to the CHANGELOG.md
* Add these examples to the README.md. See others resources examples for the correct layout.

Also. Please rebase this PR, and make sure to move the entries in the CHANGELOG.md back to the Unreleased section after rebase. This is due to the recent release of the module.

**Comment by bozho** [comment]
@johlju Sorry for the delay, life interfered :)

**Comment by johlju** [comment]
@bozho No worries :) Glad you are back.

**Comment by johlju** [comment]
:lgtm:

---

Reviewed 1 of 2 files at r1, 3 of 3 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xsqlserver/852#-:-Kwp23YkWbKMZArd8Lw3:bnfp4nl)*

**Pull request merged**
