### PR TITLE
xSQLServerSetup: Allow Multiple DB Instances on One Box

### PR DESCRIPTION
**Pull request by OmarRizla**
Allow Multiple DB Instances on One Box - Updated xSQLServerConfiguration.schema.mof so SQLInstance is now a Key.

This Pull Request (PR) fixes the following issues:
n/a

- [x] Change details added to Unreleased section of CHANGELOG.md?
- [x] Added/updated documentation, comment-based help and descriptions in .schema.mof files where appropriate?
- [x] Examples appropriately updated?
- [x] New/changed code adheres to [Style Guidelines](https://github.com/PowerShell/DscResources/blob/master/StyleGuidelines.md)?
- [x] [Unit and (optional) Integration tests](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md) created/updated where possible?

---
This change is [Reviewable](https://reviewable.io/reviews/powershell/xsqlserver/341)

### CODE REVIEW

**Comment by msftgits** [comment]
Hi, I am closing and re-opening this PR to bump the CLA bot. Sorry for the inconvenience!

**Comment by johlju** [comment]
@OmarRizla First of all, thank you for your contribution! 

You have opened your PR against master. New pull requests can only be done (allowed) against the PowerShell:Dev branch. I would need you to submit a pull request again, and this time point it to Dev instead. :)

I will close this PR now, but I will be waiting for you to open the new PR againts Dev. 

Looking forward to review and merge your contribution. Thank you! 😄

**Comment by OmarRizla** [comment]
Hi Johan


I will submit the new pull request tomorrow


Regards

Omar

________________________________

**Comment by johlju** [comment]
@OmarRizla Looking forward to it! Thank you! :)

**Pull request closed without merging**
