### PR TITLE
xSQLServerAlwaysOnService: Fix PSSA rules

### LINKED ISSUE #724: xSQLServerAlwaysOnService: PSScriptAnalyzer errors need to be fixed
**Details of the scenario you tried and the problem that is occurring:**
The following PSScriptAnalyzer errors need to be fixed:
MSFT_xSQLServerAlwaysOnService.psm1 (Line 59): $null should be on the left side of equality comparisons.

**The DSC configuration that is using the resource (as detailed as possible):**
n/a

**Version of the Operating System, SQL Server and PowerShell the DSC Target Node is running:**
n/a

**What module (SqlServer or SQLPS) and which version of the module the DSC Target Node is running:**
n/a

**Version of the DSC module you're using, or 'dev' if you're using current dev branch:**
Dev

### PR DESCRIPTION
**Pull request by ChrisLGardner**
**Pull Request (PR) description**
As raised in #724 there are PSSA errors caused by $null comparison being the wrong way round.

**This Pull Request (PR) fixes the following issues:**
Fixes #724

**Task list:**
- [x] Change details added to Unreleased section of CHANGELOG.md?
- [ ] Added/updated documentation, comment-based help and descriptions in .schema.mof files where appropriate?
- [ ] Examples appropriately updated?
- [ ] New/changed code adheres to [Style Guidelines](https://github.com/PowerShell/DscResources/blob/master/StyleGuidelines.md)?
- [ ] [Unit and (optional) Integration tests](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md) created/updated where possible?

---
This change is [Reviewable](https://reviewable.io/reviews/powershell/xsqlserver/765)

### CODE REVIEW

**Comment by johlju** [comment]
@ChrisLGardner Please add this change to the CHANGELOG.md.

**Comment by ChrisLGardner** [comment]
Done.

**Comment by johlju** [comment]
Reviewed 1 of 1 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[CHANGELOG.md, line 54 at r2](https://reviewable.io:443/reviews/powershell/xsqlserver/765#-Krdxy1Wtkg9s7hPltBg:-Krdxy1Wtkg9s7hPltBh:b-44i7nc) ([raw file](https://github.com/powershell/xsqlserver/blob/81e08a889b00401cadc0b515f4e6093e498a9b4c/CHANGELOG.md#L54)):*
> Analyser

Change to 'Analyzer' here asx well. Please change the other PR's as well. :smile: 

---

*[DSCResources/MSFT_xSQLServerAlwaysOnService/MSFT_xSQLServerAlwaysOnService.psm1, line 211 at r2](https://reviewable.io:443/reviews/powershell/xsqlserver/765#-KrdxYewVc8wmcsqDfPr:-KrdxYewVc8wmcsqDfPs:b-bc1s9z) ([raw file](https://github.com/powershell/xsqlserver/blob/dc22c91176ec46deabf28bf01365a45af06a0689/DSCResources/MSFT_xSQLServerAlwaysOnService/MSFT_xSQLServerAlwaysOnService.psm1#L211)):*
> ```PowerShell
>     # Determine the current state of Always On
>     $getTargetResourceParameters = @{
>         Ensure          = $Ensure
> ```

```
Ensure          = $Ensure
SQLServer       = $SQLServer
SQLInstanceName = $SQLInstanceName
```

Please keep the indentation here, because VS Code auto-format align these this way ( using Alt-Shift-F).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xsqlserver/765)*

**Comment by ChrisLGardner** [comment]
Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions.

---

*[CHANGELOG.md, line 54 at r2](https://reviewable.io:443/reviews/powershell/xsqlserver/765#-Krdxy1Wtkg9s7hPltBg:-KrdzB-WQ9h9s2sRkRCE:b-896fix) ([raw file](https://github.com/powershell/xsqlserver/blob/81e08a889b00401cadc0b515f4e6093e498a9b4c/CHANGELOG.md#L54)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

> Analyser

Change to 'Analyzer' here asx well. Please change the other PR's as well. :smile: 
</blockquote></details>

Done.

---

*[DSCResources/MSFT_xSQLServerAlwaysOnService/MSFT_xSQLServerAlwaysOnService.psm1, line 211 at r2](https://reviewable.io:443/reviews/powershell/xsqlserver/765#-KrdxYewVc8wmcsqDfPr:-KrdzBh_h-L0xXR6rEU_:b-896fix) ([raw file](https://github.com/powershell/xsqlserver/blob/dc22c91176ec46deabf28bf01365a45af06a0689/DSCResources/MSFT_xSQLServerAlwaysOnService/MSFT_xSQLServerAlwaysOnService.psm1#L211)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

```
Ensure          = $Ensure
SQLServer       = $SQLServer
SQLInstanceName = $SQLInstanceName
```

Please keep the indentation here, because VS Code auto-format align these this way ( using Alt-Shift-F).


</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xsqlserver/765)*

**Comment by johlju** [comment]
@ChrisLGardner Please rebase this PR. Please use git rebase (not git merge or git pull).
Help is here; https://github.com/PowerShell/DscResources/blob/master/GettingStartedWithGitHub.md#resolve-merge-conflicts

**Comment by ChrisLGardner** [comment]
Rebased as requested. I might need to rebase one of these again once it's merged.

**Comment by johlju** [comment]
Reviewed 1 of 2 files at r4, 1 of 1 files at r5.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[CHANGELOG.md, line 54 at r2](https://reviewable.io:443/reviews/powershell/xsqlserver/765#-Krdxy1Wtkg9s7hPltBg:-KrgL2Z09odbOp_JkonL:bb61xtk) ([raw file](https://github.com/powershell/xsqlserver/blob/81e08a889b00401cadc0b515f4e6093e498a9b4c/CHANGELOG.md#L54)):*
<details><summary><i>Previously, ChrisLGardner wrote…</i></summary><blockquote>

Done.
</blockquote></details>

You missed this one, it still 'Analyser' :)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xsqlserver/765)*

**Comment by ChrisLGardner** [comment]
Rebased now.

**Comment by ChrisLGardner** [comment]
Review status: 1 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[CHANGELOG.md, line 54 at r2](https://reviewable.io:443/reviews/powershell/xsqlserver/765#-Krdxy1Wtkg9s7hPltBg:-KrglQ9zfii-pu6BXMns:b-896fix) ([raw file](https://github.com/powershell/xsqlserver/blob/81e08a889b00401cadc0b515f4e6093e498a9b4c/CHANGELOG.md#L54)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

You missed this one, it still 'Analyser' :)
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xsqlserver/765)*

**Comment by johlju** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r6.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xsqlserver/765#-:-KrkFSBYvuyWs0p_8qOJ:bnfp4nl)*

**Pull request merged**
