### PR TITLE
xSQLServerDatabase: Changed SQLInstance to SQLInstanceName

### PR DESCRIPTION
**Pull request by Blankf**
Changed the documenation for the xSQLServerDatabase, there was an error in there because the sqlinstance should be sqlinstancename.

checked the code for this.

---
This change is [Reviewable](https://reviewable.io/reviews/powershell/xsqlserver/579)

### CODE REVIEW

**Comment by johlju** [comment]
@Blankf Thank you for this PR! 

Even if this is an small change, could you please update the Unreleased section of the file CHANGELOG.md what changed?

**Comment by johlju** [comment]
Thanks for updating the CHANGELOG.md. Although since I merged another PR you need to rebase this PR so those new merged changes get into this PR.
Normally I can do this from GitHub directly, but don't get that option this time for some reason.

So could you rebase your PR? You an read how that is done here https://github.com/PowerShell/DscResources/blob/master/GettingStartedWithGitHub.md#resolve-merge-conflicts
Let me know if you have any problems, and I try to help! 

Or the other alternative is to check "Allow edit from maintainers" for this PR, to the right here, under Notifications. Then I can help you rebase it and push it directly into your branch, which will update this PR.

**Comment by Blankf** [comment]
i've did a rebase, that went fine but it still gives an error here. i've ticket 'Allow edits from maintainers'
so if you could help me out, thnx!

**Comment by johlju** [comment]
Seems that you got a lot of old commits into this one now. So something went wrong. Might be because you working in the dev branch, so the steps is a little different then. 
If you want to try again, here is what I would do

I assume 'origin' below is the remote name to PowerShell repository, if not, appropriately (you can list remote names with `git remote -v`).
And I assume 'my' is the remote name that points to your fork of xSQLServer. 

```
git checkout dev # your working branch
git fetch origin dev # fetch changes from PowerShell/xSQLServer/dev
git rebase origin/dev
# resolve any conflicts (if any); save any changed files, 'add file' for each file to stage (or just click the + sign in VSCode when file has been changed and saved), then run 'git rebase --continue'. 
git push my dev --force
```

If you haven't had the time I am happy to help you resolve this, when I get home later tonight. :)

**Comment by johlju** [comment]
Seems the rebase went fine, but the conflicts were not resolve correctly, but instead ended up with the conflicts in the change log. But that can be fixed.

See here https://github.com/PowerShell/xSQLServer/pull/579/commits/68b86c5ff604aaf96c4a674dc65c84cc319c74a7

You see this headers
```
<<<<<<< HEAD
Some text
=======
some text
>>>>>>> added information to the changelog
```

This block needs to be manually resolved, saved and then staged before running `git rebase --continue`.

To fix, you need to rebase again, and resolve the conflict (you must edit the file manually at the step `# resolve any conflicts`).

To make matters a bit more complicated, we just release a new version which means when rebasing, git does not understand that we move the change history (unreleased section) to a new version section. So you need to move your lines back up to the unreleased section. 

Do you want to give this another try? Otherwise I will help you as soon as I have time, probaby after the weekend (been more busy lately than I thought I would be).

**Comment by johlju** [comment]
@Blankf I rebased this one, and pushed a new commit to solve the change log (it could not be done in rebase).

**Comment by johlju** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r1, 1 of 1 files at r3, 1 of 1 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xsqlserver/579#-:-KlnwOLKwbK_LzC1jQXN:bnfp4nl)*

**Comment by johlju** [comment]
@Blankf Again, thank your for sending in this fix! 😄  I will merge this one as soon as the tests complete.

**Pull request merged**
