### PR TITLE
Changes to tests in xSQLServer module

### PR DESCRIPTION
**Pull request by johlju**
Changes to tests in xSQLServer module

- Added common test xSQLServerCommon.Tests for xSQLServer module
  - Now all markdown files will be style checked when tests are running in AppVeyor after sending in a pull request.
  - Now all [Examples](/Examples/Resources) will be tested by compiling to a .mof file after sending in a pull request.
- Changes to xSQLServerDatabaseOwner
  - The example 'SetDatabaseOwner' can now compile, it wrongly had a `DependsOn` in the example.
- Changes to SQLServerRole
  - The examples 'AddServerRole' and 'RemoveServerRole' can now compile, it wrongly had a `DependsOn` in the example.
- Changes to xSQLServerScript
  - The examples 'AddServerRole' and 'RemoveServerRole' can now compile correctly.
- Changes to CONTRIBUTING.md
  - Added section 'Tests for examples files'
  - Added section 'Tests for style check of Markdown files'
  - Added section 'Documentation with Markdown'
  - Added texts to section 'Tests'
- Added default rules to .markdownlint.json

This Pull Request (PR) fixes the following issues:
n/a

- [x] Change details added to Unreleased section of CHANGELOG.md?
- [x] Added/updated documentation, comment-based help and descriptions in .schema.mof files where appropriate?
- [x] Examples appropriately updated?
- [x] New/changed code adheres to [Style Guidelines](https://github.com/PowerShell/DscResources/blob/master/StyleGuidelines.md)?
- [x] [Unit and (optional) Integration tests](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md) created/updated where possible?

---
This change is [Reviewable](https://reviewable.io/reviews/powershell/xsqlserver/300)

### CODE REVIEW

**Comment by johlju** [comment]
Reviewed 13 of 13 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[Tests/xSQLServerCommon.Tests.ps1, line 39 at r1](https://reviewable.io:443/reviews/powershell/xsqlserver/300#-Ka838miX2RKOGgDFvGx:-Ka838miX2RKOGgDFvGy:b-ovf2h7) ([raw file](https://github.com/powershell/xsqlserver/blob/268d648f1bb3b8fc874b02455fad6cbb18dfdce6/Tests/xSQLServerCommon.Tests.ps1#L39)):*
> ```PowerShell
>                 It "Should compile MOFs for example '$exampleDescriptiveName' correctly" {
>                     {
>                         #Start-Job -ScriptBlock {
> ```

Commented code. Remove?

---

*[Tests/xSQLServerCommon.Tests.ps1, line 77 at r1](https://reviewable.io:443/reviews/powershell/xsqlserver/300#-Ka83OSLCTLqxE50TTWb:-Ka83OSLCTLqxE50TTWc:b-ukui3) ([raw file](https://github.com/powershell/xsqlserver/blob/268d648f1bb3b8fc874b02455fad6cbb18dfdce6/Tests/xSQLServerCommon.Tests.ps1#L77)):*
> ```PowerShell
>     }
> 
>     Context -Name 'Validate Markdown files' {
> ```


"When there are Markdown files in the module"

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xsqlserver/300)*

**Comment by johlju** [comment]
:lgtm: 

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xsqlserver/300#-:-Ka84ZrrDhsbHeV_L7Nb:bg7igkv)*

**Comment by johlju** [comment]
@frokensonja Would you be so kind to proof read CHANGELOG.md and CONTRIBUTING.md? 

Review here: https://reviewable.io/reviews/powershell/xsqlserver/300

**Comment by FrokenSonja** [comment]
Reviewed 2 of 13 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 4 unresolved discussions, all commit checks successful.

---

*[CONTRIBUTING.md, line 88 at r2](https://reviewable.io:443/reviews/powershell/xsqlserver/300#-Ka86IPSajqIY0Jts2xz:-Ka86IPSajqIY0Jts2y-:b-z2d8io) ([raw file](https://github.com/powershell/xsqlserver/blob/e6f73401cf4afdcf00540e7fec019f0406cd127a/CONTRIBUTING.md#L88)):*
>  style
a style

---

*[CONTRIBUTING.md, line 96 at r2](https://reviewable.io:443/reviews/powershell/xsqlserver/300#-Ka86VNV8V-pZ7AmWfVA:-Ka86VNV8V-pZ7AmWfVB:b-ky55po) ([raw file](https://github.com/powershell/xsqlserver/blob/e6f73401cf4afdcf00540e7fec019f0406cd127a/CONTRIBUTING.md#L96)):*
> error
errors

---

*[Tests/xSQLServerCommon.Tests.ps1, line 2 at r2](https://reviewable.io:443/reviews/powershell/xsqlserver/300#-Ka87Ft9MIjutoPyGfRc:-Ka87Ft9MIjutoPyGfRd:b825qyx) ([raw file](https://github.com/powershell/xsqlserver/blob/e6f73401cf4afdcf00540e7fec019f0406cd127a/Tests/xSQLServerCommon.Tests.ps1#L2)):*
> mocked credential to pass examples that need in in the tests
mocked credentials that will be passed along to the examples that are needed in the tests

---

*[Tests/xSQLServerCommon.Tests.ps1, line 127 at r2](https://reviewable.io:443/reviews/powershell/xsqlserver/300#-Ka87jC1cubGB8be1XPZ:-Ka87jC1cubGB8be1XP_:br3bjjc) ([raw file](https://github.com/powershell/xsqlserver/blob/e6f73401cf4afdcf00540e7fec019f0406cd127a/Tests/xSQLServerCommon.Tests.ps1#L127)):*
>  second 
seconds

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xsqlserver/300)*

**Comment by johlju** [comment]
Reviewed 2 of 2 files at r3.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[CONTRIBUTING.md, line 88 at r2](https://reviewable.io:443/reviews/powershell/xsqlserver/300#-Ka86IPSajqIY0Jts2xz:-Ka89XL46d3VUcpNE5ao:b-896fix) ([raw file](https://github.com/powershell/xsqlserver/blob/e6f73401cf4afdcf00540e7fec019f0406cd127a/CONTRIBUTING.md#L88)):*
<details><summary><i>Previously, FrokenSonja wrote…</i></summary><blockquote>

>  style
a style
</blockquote></details>

Done.

---

*[CONTRIBUTING.md, line 96 at r2](https://reviewable.io:443/reviews/powershell/xsqlserver/300#-Ka86VNV8V-pZ7AmWfVA:-Ka89Y6vHsv2_OOwT34E:b-896fix) ([raw file](https://github.com/powershell/xsqlserver/blob/e6f73401cf4afdcf00540e7fec019f0406cd127a/CONTRIBUTING.md#L96)):*
<details><summary><i>Previously, FrokenSonja wrote…</i></summary><blockquote>

> error
errors
</blockquote></details>

Done.

---

*[Tests/xSQLServerCommon.Tests.ps1, line 2 at r2](https://reviewable.io:443/reviews/powershell/xsqlserver/300#-Ka87Ft9MIjutoPyGfRc:-Ka89ZKrPBXsmCBA6pDW:b-896fix) ([raw file](https://github.com/powershell/xsqlserver/blob/e6f73401cf4afdcf00540e7fec019f0406cd127a/Tests/xSQLServerCommon.Tests.ps1#L2)):*
<details><summary><i>Previously, FrokenSonja wrote…</i></summary><blockquote>

> mocked credential to pass examples that need in in the tests
mocked credentials that will be passed along to the examples that are needed in the tests
</blockquote></details>

Done.

---

*[Tests/xSQLServerCommon.Tests.ps1, line 127 at r2](https://reviewable.io:443/reviews/powershell/xsqlserver/300#-Ka87jC1cubGB8be1XPZ:-Ka89SUWgHWc5LTTw5YZ:b-896fix) ([raw file](https://github.com/powershell/xsqlserver/blob/e6f73401cf4afdcf00540e7fec019f0406cd127a/Tests/xSQLServerCommon.Tests.ps1#L127)):*
<details><summary><i>Previously, FrokenSonja wrote…</i></summary><blockquote>

>  second 
seconds
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xsqlserver/300)*

**Comment by FrokenSonja** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 4 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xsqlserver/300#-:-Ka8AFDt5dwlO2nlB4ih:bnfp4nl)*

**Pull request merged**
