### PR TITLE
New resource xSQLServerConfiguration

### PR DESCRIPTION
**Pull request by Arturas-K**
Hi,

I have create new resource that allows to configure any SQL Server configuration option listed in: https://msdn.microsoft.com/en-us/library/ms189631.aspx

I have also provided a very simple example on how to use this resource.

Updated readme file accordingly.

---
This change is [Reviewable](https://reviewable.io/reviews/powershell/xsqlserver/50)

### CODE REVIEW

**Comment by kwirkykat** [comment]
Review status: 0 of 4 files reviewed at latest revision, 5 unresolved discussions.

---

*[README.md, line 264 \[r1\]](https://reviewable.io:443/reviews/powershell/xsqlserver/50#-KGNynd0H_gRprjugh8h:-KGNynd0H_gRprjugh8i:-684451345) ([raw file](https://github.com/powershell/xsqlserver/blob/84c66902aa47ff8f223b0354a1eb72bbe335a293/README.md#L264)):*
Typo (nave --> name)

---

*[README.md, line 267 \[r1\]](https://reviewable.io:443/reviews/powershell/xsqlserver/50#-KGO1xbBXa2_vxBjK54Y:-KGO1xbBXa2_vxBjK54Z:1617011459) ([raw file](https://github.com/powershell/xsqlserver/blob/84c66902aa47ff8f223b0354a1eb72bbe335a293/README.md#L267)):*
I don't see the point of the 'Ensure' property if it does not affect Set-TargetResource. I would suggest removing it and returning the actual value of the option in Get-TargetResource instead.

---

*[DSCResources/xSQLServerConfiguration/xSQLServerConfiguration.psm1, line 23 \[r1\]](https://reviewable.io:443/reviews/powershell/xsqlserver/50#-KGO7hP9XIEWLuMsn9QC:-KGO7hP9XIEWLuMsn9QD:1054696882) ([raw file](https://github.com/powershell/xsqlserver/blob/84c66902aa47ff8f223b0354a1eb72bbe335a293/DSCResources/xSQLServerConfiguration/xSQLServerConfiguration.psm1#L23)):*
This 'Ensure' property isn't needed when you could just call Test-TargetResource. I would move some of your code from Test-TargetResource up here to your Get to return the actual value of the option. Then your Test method can call your Get to check that the option is set properly.

---

*[DSCResources/xSQLServerConfiguration/xSQLServerConfiguration.psm1, line 80 \[r1\]](https://reviewable.io:443/reviews/powershell/xsqlserver/50#-KGO-HVieqxsT0vj3Tdi:-KGO-HVieqxsT0vj3Tdj:211813136) ([raw file](https://github.com/powershell/xsqlserver/blob/84c66902aa47ff8f223b0354a1eb72bbe335a293/DSCResources/xSQLServerConfiguration/xSQLServerConfiguration.psm1#L80)):*
Why not trigger a reboot here if it's needed for the resource to work? If another resource in a configuration depends on this one, it may not work properly if the restart hasn't happened yet.

---

*[Examples/xSQLServerConfiguration.ps1, line 1 \[r1\]](https://reviewable.io:443/reviews/powershell/xsqlserver/50#-KGO8kvrEtb1yD1TewLk:-KGO8kvrEtb1yD1TewLl:-1691633303) ([raw file](https://github.com/powershell/xsqlserver/blob/84c66902aa47ff8f223b0354a1eb72bbe335a293/Examples/xSQLServerConfiguration.ps1#L1)):*
Can you put quotes around 'show advanced options' in the comment? Just for readability.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xsqlserver/50)*

**Comment by kwirkykat** [comment]
@aultt Would you mind looking at this?

**Comment by Arturas-K** [comment]
Review status: 0 of 4 files reviewed at latest revision, 5 unresolved discussions.

---

*[README.md, line 264 \[r1\]](https://reviewable.io:443/reviews/powershell/xsqlserver/50#-KGNynd0H_gRprjugh8h:-KGQq99DswAXIb-aEs0w:974235462) ([raw file](https://github.com/powershell/xsqlserver/blob/84c66902aa47ff8f223b0354a1eb72bbe335a293/README.md#L264)):*
ups, my Visual Studio spellchecker missed this one, will fix.

---

*[README.md, line 267 \[r1\]](https://reviewable.io:443/reviews/powershell/xsqlserver/50#-KGO1xbBXa2_vxBjK54Y:-KGQnnDBS1EDNtqyKysb:-1990558939) ([raw file](https://github.com/powershell/xsqlserver/blob/84c66902aa47ff8f223b0354a1eb72bbe335a293/README.md#L267)):*
This was i minimal viable version that got me over to solve.
I was hoping that in the future, myself or someone else could improve the resource so that Ensure = 'Absent' would retur the value to its default value.

Maybe we could keep this in but record an enhancement issue, unless you think that Absent would not be beneficial and is not worth the effort. 

I'm fine either way, but let me know what you think.

---

*[DSCResources/xSQLServerConfiguration/xSQLServerConfiguration.psm1, line 23 \[r1\]](https://reviewable.io:443/reviews/powershell/xsqlserver/50#-KGO7hP9XIEWLuMsn9QC:-KGQosUqezLlvh9Ebv0Y:779058434) ([raw file](https://github.com/powershell/xsqlserver/blob/84c66902aa47ff8f223b0354a1eb72bbe335a293/DSCResources/xSQLServerConfiguration/xSQLServerConfiguration.psm1#L23)):*
I wasn't sure what is the best way of implementing Get and Test methods.
I'll move the code as per your suggestion and will submit updated version in couple of days.

---

*[DSCResources/xSQLServerConfiguration/xSQLServerConfiguration.psm1, line 80 \[r1\]](https://reviewable.io:443/reviews/powershell/xsqlserver/50#-KGO-HVieqxsT0vj3Tdi:-KGQpFh04Q8zmniM6lFL:-563213046) ([raw file](https://github.com/powershell/xsqlserver/blob/84c66902aa47ff8f223b0354a1eb72bbe335a293/DSCResources/xSQLServerConfiguration/xSQLServerConfiguration.psm1#L80)):*
As with ensure, was only doing minimal viable product first, and was hoping to leave this for future enhancements.
I have looked that there are only a small number of options that need restarting, and they are quite rare to change.

Would it be OK to leave this as it is now and create Enhancement Issue?

If not then i can port some code from my other resource xSQLServerNetwork that has restart capability.
In that case would you recommend moving restart to a helper module?

---

*[Examples/xSQLServerConfiguration.ps1, line 1 \[r1\]](https://reviewable.io:443/reviews/powershell/xsqlserver/50#-KGO8kvrEtb1yD1TewLk:-KGQq2WpAEWpHLEjlHvr:1029041776) ([raw file](https://github.com/powershell/xsqlserver/blob/84c66902aa47ff8f223b0354a1eb72bbe335a293/Examples/xSQLServerConfiguration.ps1#L1)):*
NP will fix this.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xsqlserver/50)*

**Comment by Arturas-K** [comment]
Review status: 0 of 4 files reviewed at latest revision, 5 unresolved discussions.

---

*[README.md, line 264 \[r1\]](https://reviewable.io:443/reviews/powershell/xsqlserver/50#-KGNynd0H_gRprjugh8h:-KGU8cXA-OIyvyvYngoB:-499146009) ([raw file](https://github.com/powershell/xsqlserver/blob/84c66902aa47ff8f223b0354a1eb72bbe335a293/README.md#L264)):*
Done.

---

*[README.md, line 267 \[r1\]](https://reviewable.io:443/reviews/powershell/xsqlserver/50#-KGO1xbBXa2_vxBjK54Y:-KGU8eEyKmzbWPn_bNtk:-986248107) ([raw file](https://github.com/powershell/xsqlserver/blob/84c66902aa47ff8f223b0354a1eb72bbe335a293/README.md#L267)):*
Removed in latest version

---

*[DSCResources/xSQLServerConfiguration/xSQLServerConfiguration.psm1, line 23 \[r1\]](https://reviewable.io:443/reviews/powershell/xsqlserver/50#-KGO7hP9XIEWLuMsn9QC:-KGU8jkqVb4Ysh4RppgB:-499146009) ([raw file](https://github.com/powershell/xsqlserver/blob/84c66902aa47ff8f223b0354a1eb72bbe335a293/DSCResources/xSQLServerConfiguration/xSQLServerConfiguration.psm1#L23)):*
Done.

---

*[DSCResources/xSQLServerConfiguration/xSQLServerConfiguration.psm1, line 80 \[r1\]](https://reviewable.io:443/reviews/powershell/xsqlserver/50#-KGO-HVieqxsT0vj3Tdi:-KGU8mu9K3I-DCk2clWo:1481857776) ([raw file](https://github.com/powershell/xsqlserver/blob/84c66902aa47ff8f223b0354a1eb72bbe335a293/DSCResources/xSQLServerConfiguration/xSQLServerConfiguration.psm1#L80)):*
Added restart logic in last commit.

---

*[Examples/xSQLServerConfiguration.ps1, line 1 \[r1\]](https://reviewable.io:443/reviews/powershell/xsqlserver/50#-KGO8kvrEtb1yD1TewLk:-KGU8v6ayUuAioHCEH8X:-499146009) ([raw file](https://github.com/powershell/xsqlserver/blob/84c66902aa47ff8f223b0354a1eb72bbe335a293/Examples/xSQLServerConfiguration.ps1#L1)):*
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xsqlserver/50)*

**Comment by Arturas-K** [comment]
@kwirkykat @aultt in last commit i have fixed all the issue highlight in review.
Please have a look if and let me know if you have any more suggestions.

**Comment by johlju** [comment]
Just a thought. Why have the resource restart the service when the user can do it with built in DSC resource (below)? I think using built-in gives the user more control of the restart, maybe the user wants to do more before starting the service again. I'm also thinking that the user know the setting they change will need a restart (also seeing a warning about it might confuse other team members if the configuration handle it itself).
But if the resource do it with more control this is a good thing, but then I would love to see that restart in an own resource like `xSqlServerServiceState`, and being able to handle all SQL services.

```
Service SQLServerServiceStopped
{
    Name = "MSSQLSERVER"
    State = "Stopped"
}

Service SQLServerServiceStarted
{
    Name = "MSSQLSERVER"
    State = "Running"

    DependsOn = "[Service]SQLServerServiceStopped"
}
```

**Comment by Arturas-K** [comment]
@johlju thank you for your comment
I'll try and explain reasons for having restart capability in resource.

* Convenience - it is optional, but useful if you are setting up from clean machine and just want configuration setting to take affect immediately.
* There is no other way to restart service using DSC, you would have to use PowerShell script outside DSC.
 * If you move restart to separate resource, this would result in service restart regardless if it is needed or not, DSC configuration supports drift detection, so which particular resources are run depends on current state.

Your proposed example wouldn't work because **service** resource key is **name**, so you can not have two resources defined in the same configuration for the same service name.
If you try this example:
```PowerShell
configuration ServiceTest
{
    Import-DscResource -ModuleName 'PSDesiredStateConfiguration'

    Node 'localhost'
    {
        Service mssql
        {
            Name = 'MSSQLSERVER'
            State = 'Stopped'
        }

        Service mssql2
        {
            Name = 'MSSQLSERVER'
            State = 'Running'
        }
    }
}

ServiceTest
Start-DscConfiguration .\ServiceTest -Wait -Force -Verbose
```
You will get this error
```
Test-ConflictingResources : A conflict was detected between resources '[Service]mssql (C:\temp\service.test.ps1::7::9::Service)' and '[Service]mssql2 (C:\temp\service.test.ps1::13::9::Service)' in node 'localhost'. Resources have identical key properties bu
t there are differences in the following non-key properties: 'State'. Values 'Stopped' don't match values 'Running'. Please update these property values so that they are identical in both cases.
```

Also even if we had a resource that could force restart, this would be problematic in practice.
DSC is state management and it supports pull mode with auto correct, if you could make above example work this would mean that on each configuration check DSC Manager would detect drift (first resource expects stopped but would find service running) and would try to correct it by re applying configuration, this would result in service restart on each pull.

Hope this helps.

**Comment by johlju** [comment]
@Arturas-K I see you point with the unnecessary restart on each pull, that is not something a user want. I didn't think this thru entirely but I learned something new today. :) Thank you for your detailed explanation! 

Then would it be a good thing to move the restart function to the xSqlServerHelper module maybe? So other resources can use the same method of restart.

**Comment by Matticusau** [comment]
Just on the restart issue. It is an interesting thought because the setting wont actually take effect till you restart (depending on the setting). Some DBA's use this as part of change process, like set the change and just schedule the restart to occur during the outage window. The problem if you don't restart soon after making the change with DSC is that if someone configures the LCM to check frequently and the restart hasn't happened yet then it will detect "drift" because the setting is not yet effective and then try and change the setting again. Of cause the resource could check the effective and the configured values as part of the drift? 

Just another thought could we not use the Reboot If Needed configuration of the LCM if we are to restart the service as needed, or throw a warning that the service needs to be restarted before it take effect the same way we would if say installing a windows feature?

**Comment by aultt** [comment]
I would say tell DSC a reboot is needed and let it manage that piece.  In most cases when we are talking about this should be on a new server and not on running SQL Server.  On a production server I would want to manage any service restarts outside of DSC.

Troy Ault | Premier Field Engineering
SQL Server PFE
Office: (917) 388-1040  | Email: troyault@microsoft.com<mailto:troyault@microsoft.com>

Premier Support: 1.800.936.3100 | Premier Online https://premier.microsoft.com<https://premier.microsoft.com/>
If you have any feedback about my work, please email either me or my  Manager: Brad Vernier | bradve@microsoft.com<mailto:bradve@microsoft.com>

**Comment by Arturas-K** [comment]
@Matticusau i have actually thought of that, this is why i have implemented Get method to report ConfigValue not RunValue. So in your scenario when you delay restart even on pull mode this would not be detected as drift.

**Comment by Arturas-K** [comment]
@kwirkykat @aultt  can i get an update on this PR please.
Do i need to do anything else before you can accept this?

**Comment by kwirkykat** [comment]
@Arturas-K Why didn't you want to use $global:DSCMachineStatus = 1 to have DSC restart the machine based on the user-input value of RebootIfNeeded? Is it because you really only want to restart a service and not the whole machine here?

<details><summary><i>Previously, Arturas-K (Arturas Kuznecovas) wrote…</i></summary>
> @kwirkykat @aultt  can i get an update on this PR please.
> 
> Do i need to do anything else before you can accept this?
</details>


---

Reviewed 3 of 4 files at r3.
Review status: 3 of 4 files reviewed at latest revision, 2 unresolved discussions.

---

*[DSCResources/xSQLServerConfiguration/xSQLServerConfiguration.psm1, line 215 \[r4\]](https://reviewable.io:443/reviews/powershell/xsqlserver/50#-KIdZj4kuSfODNzJy8xn:-KIdZj4kuSfODNzJy8xo:-850265950) ([raw file](https://github.com/powershell/xsqlserver/blob/c974e410c33494d3e5bed61f205de36bc5440e70/DSCResources/xSQLServerConfiguration/xSQLServerConfiguration.psm1#L215)):*
> ```PowerShell
>         $sqlService.Refresh()
>     }
>     Write-Verbose "[$dbServiceName] service stopped"
> ```

This code block {while (someService -eq State), wait, refresh, Write-Verbose} is repeated a few times so it should probably be pulled out into a separate function. All of these "Wait for state" instances also need a timeout so that they don't run forever if something weird goes wrong.

---

*[DSCResources/xSQLServerConfiguration/xSQLServerConfiguration.psm1, line 229 \[r4\]](https://reviewable.io:443/reviews/powershell/xsqlserver/50#-KIdZfMd6MUkNRb3soR_:-KIdZfMe4ZyAqA15VOap:677121513) ([raw file](https://github.com/powershell/xsqlserver/blob/c974e410c33494d3e5bed61f205de36bc5440e70/DSCResources/xSQLServerConfiguration/xSQLServerConfiguration.psm1#L229)):*
> ```PowerShell
>     if ($startAgent)
>     {
>         Write-Verbose "Staring [$agtServiceName] service ..."
> ```

Typo

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xsqlserver/50#-:-KIdb3x40lRdbzi4YMgO:1989913252)*

**Comment by Arturas-K** [comment]
@kwirkykat thank you for your comments.
To your question, yes I think it is better to just restart the service if needed and not whole machine.

Also i have fixed the typo and refactored Restart-SqlServer function to use new extracted function Wait-SqlServiceState as per your suggestions.

<details><summary><i>Previously, kwirkykat (Katie Keim) wrote…</i></summary>
> @Arturas-K Why didn't you want to use $global:DSCMachineStatus = 1 to have DSC restart the machine based on the user-input value of RebootIfNeeded? Is it because you really only want to restart a service and not the whole machine here?
</details>


---

Review status: 3 of 4 files reviewed at latest revision, 2 unresolved discussions.

---

*[DSCResources/xSQLServerConfiguration/xSQLServerConfiguration.psm1, line 215 \[r4\]](https://reviewable.io:443/reviews/powershell/xsqlserver/50#-KIdZj4kuSfODNzJy8xn:-KJ4ybejYk2jMHLeniEE:2086959141) ([raw file](https://github.com/powershell/xsqlserver/blob/c974e410c33494d3e5bed61f205de36bc5440e70/DSCResources/xSQLServerConfiguration/xSQLServerConfiguration.psm1#L215)):*
<details><summary><i>Previously, kwirkykat (Katie Keim) wrote…</i></summary>
> This code block {while (someService -eq State), wait, refresh, Write-Verbose} is repeated a few times so it should probably be pulled out into a separate function. All of these "Wait for state" instances also need a timeout so that they don't run forever if something weird goes wrong.
</details>
Extracted new function Wait-SqlServceState, and refactored code to use this.
Also added timeout logic.
Please have a look.

---

*[DSCResources/xSQLServerConfiguration/xSQLServerConfiguration.psm1, line 229 \[r4\]](https://reviewable.io:443/reviews/powershell/xsqlserver/50#-KIdZfMd6MUkNRb3soR_:-KJ4xmFijKsZSkph1u6s:-499146009) ([raw file](https://github.com/powershell/xsqlserver/blob/c974e410c33494d3e5bed61f205de36bc5440e70/DSCResources/xSQLServerConfiguration/xSQLServerConfiguration.psm1#L229)):*
<details><summary><i>Previously, kwirkykat (Katie Keim) wrote…</i></summary>
> Typo
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xsqlserver/50#-:-KJ4xq6WWw2k6AZJ3ct5:1625180681)*

**Comment by kwirkykat** [comment]
Review status: 3 of 4 files reviewed at latest revision, 1 unresolved discussion.

---

*[DSCResources/xSQLServerConfiguration/xSQLServerConfiguration.psm1, line 243 \[r5\]](https://reviewable.io:443/reviews/powershell/xsqlserver/50#-KJ8DgVPVJINbfG023yg:-KJ8DgVPVJINbfG023yh:1720124562) ([raw file](https://github.com/powershell/xsqlserver/blob/835d7df304eeadd523488e30fad2b1bd505e318f/DSCResources/xSQLServerConfiguration/xSQLServerConfiguration.psm1#L243)):*
> ```PowerShell
>     while($Service.ServiceState -ne $State)
>     {
>         if((New-TimeSpan -Start $startTime -End (Get-Date)).TotalSeconds -gt 6)
> ```

I think you meant to put $TimeOut here instead of 6

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xsqlserver/50)*

**Comment by Arturas-K** [comment]
Review status: 3 of 4 files reviewed at latest revision, 1 unresolved discussion.

---

*[DSCResources/xSQLServerConfiguration/xSQLServerConfiguration.psm1, line 243 \[r5\]](https://reviewable.io:443/reviews/powershell/xsqlserver/50#-KJ8DgVPVJINbfG023yg:-KJ9jbTlidGxpRKEL2LL:-815734623) ([raw file](https://github.com/powershell/xsqlserver/blob/835d7df304eeadd523488e30fad2b1bd505e318f/DSCResources/xSQLServerConfiguration/xSQLServerConfiguration.psm1#L243)):*
<details><summary><i>Previously, kwirkykat (Katie Keim) wrote…</i></summary>
> I think you meant to put $TimeOut here instead of 6
</details>
Ups, fixed.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xsqlserver/50)*

**Comment by kwirkykat** [comment]
:lgtm:

<details><summary><i>Previously, Arturas-K (Arturas Kuznecovas) wrote…</i></summary>
> @kwirkykat thank you for your comments.
> To your question, yes I think it is better to just restart the service if needed and not whole machine.
> 
> Also i have fixed the typo and refactored Restart-SqlServer function to use new extracted function Wait-SqlServiceState as per your suggestions.
</details>


---

Review status: 3 of 4 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xsqlserver/50#-:-KJD3vb1TT727duAwoBR:1417088721)*

**Comment by kwirkykat** [comment]
Reviewed 1 of 1 files at r6.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xsqlserver/50)*

**Comment by Arturas-K** [comment]
@kwirkykat thank you for your effort.

**Pull request merged**
